Auto sign in after sign up
aws-amplify/amplify-js pull request #10064
Opened 2022-07-06 17:43 UTC by helgabalashova

#### Description of changes
Changes add confirm sign up listener to initiate auto sign in once account is confirmed. It happens if autoSignIn is set to true in params for SignUp function.
Since customers can choose either code, link, or autoConfirm, the solution use three different ways to auto sign in. autoConfirm implementation immediately calls on confirmSignUp function. Link implementation uses polling to sign user in since there is no explicit way to know if user clicked the link. Polling is done within 3 minutes (time verification link is valid) every 5 seconds. Code implementation is using hub listening event. Once user confirms account with code, it dispatches listening event. SignUp function is listening for this event to initiate SignIn process.

#### Issue #, if available
https://github.com/aws-amplify/amplify-js/issues/6320
https://github.com/aws-amplify/amplify-js/issues/3882
https://github.com/aws-amplify/amplify-js/issues/3631
https://github.com/aws-amplify/amplify-js/issues/6018

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-06 22:35 UTC, jamesaucode requested changes
Looks good 😄 Left a few comments

2022-07-06 22:35 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +			const pollingInitiated = this._storage.getItem('pollingStarted') || false;
should we check `this._storage.getItem('pollingStarted') === 'true'` instead? The value here could be `'true'` or `'false'` (the string, not the boolean), which is still going to be a truthy value

2022-07-06 22:35 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +							this._storage.setItem('pollingStarted', false);
Make sure we are checking if `this._storage.getItem('pollingStarted') === 'true'` since boolean will be stored as string in `localStorage`. Since this could be `'false'`, if we don't check it's `=== 'true'` a `'false'` still gives us a truthy value.

2022-07-06 22:35 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +			const pollingInitiated = this._storage.getItem('pollingStarted') || false;
nit: I would define this key as a `const` somewhere 😄

2022-07-06 22:35 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +		autoSignInPolling?: NodeJS.Timer
a NodeJS type here seems a bit out of place. I would use `ReturnType<typeof setTimeout>` instead to make Typescript happy.

2022-07-07 20:06 UTC, nickarocho reviewed
Great work, Olya! Left one high-level comment and a clarifying TS question. Also wanted to ask before approving - what is the plan with adding unit/integ tests to this feature?

2022-07-07 20:06 UTC, nickarocho commented on packages/auth/src/types/Auth.ts
> +	verificationMethod?: string;
Should this be an `enum` if there are only three possible values?

2022-07-07 21:03 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			autoSignIn = params['autoSignIn'] || false;
```suggestion
			autoSignIn = params.autoSignIn ?? false;
```

2022-07-07 21:04 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +								}, 5000);
I agree with @nickarocho can look cleaner by exporting this into a function

2022-07-07 21:05 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +								}, 5000);
Also split the logic for link and code separately

2022-07-07 21:09 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +									this.onConfirmSignUp(authDetails, null, autoSignInPolling);
Would you need to `return` on the `if` or make it an `else` statement for `this.onConfirmSignUp`

2022-07-07 21:11 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +							this._storage.setItem('pollingStarted', false);
Why not delete?

2022-07-07 21:14 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +						if (autoSignIn === 'true' && !this.autoSignInInitiated) {
Should this be `true` instead, serializing data to boolean from storage seem a little hacky, maybe having a helper function that allows to treat this better? What do you think?

2022-07-07 21:15 UTC, elorzafe commented on packages/auth/src/types/Auth.ts
> +	verificationMethod?: string;
or `'code'` | `'link'`

2022-07-09 00:31 UTC, elorzafe reviewed
Just minor comments,

Have a callout related to `clientMetadata` and `validationData` because what happens if the customer wants to use that for `autoSignIn`?

2022-07-09 00:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +const MAX_AUTOSIGNIN_POLLING_TIME = 180000;
I would add the unit like `MAX_AUTOSIGNIN_POLLING_MS`, and split into minutes like this `3 * 60 * 1000`

2022-07-09 00:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +		const autoSignInPolling = setInterval(() => {
Could be more clear `autoSignInPollingIntervalId`?

2022-07-09 00:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +		const autoSignInPolling = setInterval(() => {
or `pollingIntervalId`

2022-07-09 00:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	private isTrueStorageValue(value: any) {
what if instead of passing the value you pass the key of the storage or rename the function because it seems that is getting the value from Storage which isnt

2022-07-21 09:07 UTC, oemer-sellwerk commented
When can we expect this to be merged?

2022-07-26 00:42 UTC, elorzafe requested changes
It looks very good, just some adjustments need to be made, we can chat more offline.

Thanks @helgabalashova !

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const signInSpyon = jest.spyOn(CognitoUser.prototype, 'authenticateUser');
I would add a mock for `authenticateUser` in order to not make the network request inside of the test (it wont impact the test now but maybe it will impact the whole suite)

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const signInSpyon = jest.spyOn(CognitoUser.prototype, 'authenticateUser');
I would add a mock for this to avoid network request

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const spyon = jest.spyOn(CognitoUserPool.prototype, 'signUp');
I think this might need a mock Implementation. Maybe is using another mock that responds with `userConfirmed: false`?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const confirmSpyon = jest.spyOn(
You might need a mock for this, or is using a global mock?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const signInSpyon = jest.spyOn(CognitoUser.prototype, 'authenticateUser');
Maybe you need mocks for this or is using a global mock?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const spyon = jest.spyOn(CognitoUserPool.prototype, 'signUp');
Is this using a global mock?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			jest.useRealTimers();
Why is this needed?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +					'Please use your credentials to sign in.'
You can add this on the `AuthError.ts` file

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			if (pollingInitiated) {
I think you need to clear `pollingStarted`

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +		const autoSignInValidationData: CognitoUserAttribute[] = null;
Are you sure that is the right type?

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +								'Please use your credentials to sign in.'
I would reuse the same constant from `AuthErrors.ts`

2022-07-26 00:42 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +				this._storage.setItem('autoSignIn', true);
We are not removing this. Can you check where this should be removed?

2022-07-26 17:11 UTC, helgabalashova commented on packages/auth/__tests__/auth-unit-test.ts
> +			const confirmSpyon = jest.spyOn(
it is a global mock

2022-07-26 17:11 UTC, helgabalashova commented on packages/auth/__tests__/auth-unit-test.ts
> +			const signInSpyon = jest.spyOn(CognitoUser.prototype, 'authenticateUser');
This one is also a global mock

2022-07-26 17:11 UTC, helgabalashova commented on packages/auth/__tests__/auth-unit-test.ts
> +			const spyon = jest.spyOn(CognitoUserPool.prototype, 'signUp');
yes

2022-07-26 17:12 UTC, helgabalashova commented on packages/auth/__tests__/auth-unit-test.ts
> +			jest.useRealTimers();
it breaks all other tests that rely on time to pass

2022-07-26 21:29 UTC, elorzafe requested changes
It looks very good and is super close, can you also add `amplify-` as a prefix for all the items persisted on localStorage?
Thanks @helgabalashova !

2022-07-26 21:29 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			}
This could be a bug, if this is true it should return otherwise it could throw the error and also try to signIn

2022-07-26 21:29 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	private async onConfirmSignUp(
` signInAfterUserConfirmed` ?

seems odd using `this.onConfirmSignUp` from polling use case, what do you think?

2022-07-26 22:04 UTC, jamesaucode reviewed
Looks good to me for the most part, good job @helgabalashova  😄  For the unit tests, can we also test that the flag inside storage is cleared properly, and also the `Hub` event is removed?

2022-07-26 22:04 UTC, jamesaucode commented on packages/auth/__tests__/auth-unit-test.ts
> +			expect(signInSpyon).toHaveBeenCalledTimes(1);
Can we also test that the storage is clearing the flag properly, and `Hub` is removing the callback function?

2022-07-26 22:04 UTC, jamesaucode commented on packages/auth/__tests__/auth-unit-test.ts
> +			expect(signInSpyon).toHaveBeenCalledTimes(1);
Same as above

2022-07-26 22:04 UTC, jamesaucode commented on packages/auth/__tests__/auth-unit-test.ts
> +			expect(signInSpyon).toHaveBeenCalledTimes(2);
same as above

2022-07-26 22:04 UTC, jamesaucode commented on packages/auth/__tests__/auth-unit-test.ts
> +			expect(signInSpyon).toHaveBeenCalledTimes(0);
same as above

2022-07-27 14:15 UTC, elorzafe approved these changes
Looks great! Thanks @helgabalashova 🏅 🌮

2022-07-27 14:15 UTC, merged