GH-9824 - PubSub Connection state tracking for AppSyncRealtime
aws-amplify/amplify-js pull request #10063
Opened 2022-07-06 17:38 UTC by stocaaro

#### Description of changes

This change includes all behavior and testing to implement tracking connection state changes for AppSync/API subscriptions as Hub events for all connection conditions discussed.

This has been extended to cover missed keep alive messages, which demonstrates how a health check could be implemented in the future.

Changes:
- Add `ConnectionStateMonitor` to track connection health (derivative from DataStoreConnectivity)
- Add tests to cover all states/transitions of `ConnectionStateMonitor`.
- Augment `AWSAppSyncRealTimeProvider` with `ConnectionStateMonitor` dispatching `Hub` events on connection state changes.
- Use `Hub` connection states instead of timeouts in AppSyncRealtimeProvider testing (17.6s => 5.4s)
- Add missed keep alive state tracking on a 65s delay.

Areas of interest/concern:
- Are the the `ConnectionHealthState` names the right ones?
- Should `ConnectionHealthState` be a string literal or an enum?
- Once accessed both `Reachability().networkMonitor()` and `this.connectionStateMonitor.connectionHealthStateObservable` subscriptions are never disposed of as even when all subscriptions are closed, the listen should still be in place to track the "Disconnected" state. I couldn't come up with a case where these should be unsubscribed, so this code doesn't capture the subscriptions.

```
Hub.listen('api', (data: any) => {
	const { payload } = data;
	if (payload.event === CONNECTION_HEALTH_CHANGE) {
		const healthState = payload.message as ConnectionHealthState;
		console.log(healthState);
	}
});
```

#### Issue #, if available
#9824

#### Description of how you validated changes
- Unit tests added
- All state behavior manually tested in custom example app

#### Checklist

- [ x ] PR description included
- [ x ] `yarn test` passes
- [ x ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-08 23:50 UTC, elorzafe commented
Thanks @stocaaro this is great!

Is it possible to add here a screenshot or a written diagram, to understand more the transitions? Maybe that help clarify the names a little bit more.

2022-07-09 00:20 UTC, elorzafe reviewed
I couldnt finish reviewing but I gave partial comments

Thank you so much for doing this @stocaaro 🌮 🥇

2022-07-09 00:20 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +			this.connectionStateMonitor.disconnecting();
I am not sure about sending two events so close together, in that case if there are no more subscriptions I would send the `disconnecting` event but not just before calling `disconnected`

2022-07-09 00:20 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +			this.connectionStateMonitor.disconnected();
Would make more sense `closed` instead of `disconnected`?

2022-07-09 00:20 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
>  			// TODO: emit event on hub but it requires to store the id first
Maybe we can remove this comment!

2022-07-11 21:05 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +			this.connectionStateMonitor.disconnecting();
Good catch. In the current implementation, `closing` (formerly `disconnection` updates the intended state when the connection is closed on purpose. `closed` (formerly `disconnect`) only updates the connection state, so when it appears separate from `disconnecting` it signals a `ConnectionDisrupted` state instead of the final `Disconnected` state.

Without reconnection, this is a distinction without a difference, where when reconnection logic gets mixed into this, it will be common to see connection `ConnectionDisrupted` transition back to `Connecting` => `Connected`.

For this comment, I am recognizing that I want to move `closing` out of the buffer wait, which may meet your comment. If you do not think we should have both state changes here, then the fix would be to have a new call that can change both the intended and connection state to disconnected at the same time to avoid the extra event.

2022-07-11 21:13 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +import { CONNECTION_HEALTH_CHANGE, CONTROL_MSG } from '../../index';
Yeah. I was too lazy here.  Had used ConnectionState in the internal implementation of the ConnectionStateMonitor and was using ConnectionHealth as an alt name for the string literal in the public interface. This is bad and wrong and I've gone back to do some internal renaming to reclaim this name for use in the constant, external interface such that...

Watching for `CONNECTION_STATE_CHANGE` Hub events will receive `ConnectionState` typed values generated internally by the `ConnectionStateMonitor` interface.

2022-07-11 21:15 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/constants.ts
> +export const KEEP_ALIVE_ALERT_TIMEOUT = 65 * 1000;
Sure. Had considered this, but rejected using DEFAULT as this will not be overridden. Will change it as I suppose we could add an override in the future.

2022-07-11 21:27 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
>  			// TODO: emit event on hub but it requires to store the id first
Removed

2022-07-15 22:41 UTC, svidgen reviewed
Happy to chat offline about my comments. I don't think I have super strong opinions on any of my nits. Just a question or two I think should be answered mostly, and then a bunch of knee-jerk reactions!

2022-07-15 22:41 UTC, svidgen commented on packages/pubsub/__tests__/ConnectionStateMonitor.tests.ts
> +			monitor.keepAlive();
*Just hanging this comment here because a good number of these monitor methods are gathered here ...*

This may also be too nit-picky for an internal interface. But, did you consider any alternative naming schemes for these methods? 😅  I'm a little distracted by the non-verb method naming. I feel like I should be seeing `set`, `record`, `emit`, or `push` or something here. (And throughout the implementation, of course.)

```js
monitor.recordConnectionOpening();
monitor.recordConnectionEstablished();
monitor.recordKeepAliveMissed();
monitor.recordKeepAliveMissed();
monitor.recordKeepAliveReceived();
```

I could also get behind a single verb that accepts a state event, which could even contain the newly intended connection/network/* field values.

```js
monitor.record(CONNECTION.OPENING);
monitor.record(CONNECTION.ESTABLISHED);
monitor.record(CONNECTION.KEEP_ALIVE_MISSED);
monitor.record(CONNECTION.KEEP_ALIVE_MISSED);
monitor.record(CONNECTION.KEEP_ALIVE_RECEIVED);
```

🤷 

@elorzafe does this contradict opinions you've given?

2022-07-15 22:41 UTC, svidgen commented on packages/pubsub/__tests__/helpers.ts
> +	}
Even though this is test code, docstrings would be help here for tooltips when reading the tests to help me quickly distinguish between the behavior of these two.

Also, unless I'm misreading, these look like they could be helpful to customers *in some form or another*. I wonder if there's opportunity to generalize these into a lite design / addition to Hub...

2022-07-15 22:41 UTC, svidgen commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return 'ConnectedPendingNetwork';
Loosely related to a comment above, it may be helpful to us to put these values into an enum with docstrings:

```js
enum CONNECTION_STATES {
  /*
   * Indicates that the physical network has been disconnected. A socket
   * disconnect will follow shortly unless network connectivity is restored.
   */
   ConnectionPendingNetwork = "ConnectionPendingNetwork"
}
```

These will show as tooltips in VS Code.

Alternatively, and much more related to a prior comment, would it make sense to return a structure here that has the short string *and a description* that can be included in the hub events?

2022-07-18 22:01 UTC, ashika01 commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return 'ConnectedPendingNetwork';
+1

2022-07-18 22:03 UTC, ashika01 commented
> > Should ConnectionState be a string literal or an enum?
> 
> Unless we have bundle size concern for PubSub. The pros for a string union I see here is the string union is strictly on the Typescript level so it won't bloat the bundle size. But overall I'm in favor of `enum` as it _usually_ gives a better editor experience. (types `ConnectionState.` and see a list of all the possible connection state).

+1. Not just editor experience, removes a lot of mistyping issues for development and makes things more readable and less distracting.

2022-07-19 16:55 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		this._connectionStateObserver.next({ ...this._connectionState });
Yep. You're right. Updating.

2022-07-19 17:03 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		// Translate from connection states to ConnectionStates, then remove any duplicates
Good question. This object aggregates state changes to any of the network, connection, intendedConnection, keepAliveHealth states. Some states will change these independent states without changing the overall connection state, such as keep alive misses during a network outage, both of with translate to `ConnectedPendingNetwork` while the connection hasn't been disrupted.

In other cases, it might happen that a connection becomes disrupted in a way that causes two async events that both update the state with the same value.  I had originally had these deduplicated in the `updateConnectionState` function, but refactored deuplication to only happen in this one place.

2022-07-19 18:34 UTC, stocaaro commented on packages/pubsub/__tests__/ConnectionStateMonitor.tests.ts
> +			monitor.keepAlive();
I really like this suggestion. Verbs are good. Going with `monitor.record(CONNECTION_CHANGE.CLOSED)`

2022-07-19 20:12 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return 'ConnectedPendingNetwork';
Updated

2022-07-19 20:56 UTC, stocaaro commented on packages/pubsub/__tests__/helpers.ts
> +	}
Docstring added. I've got a revision of this extracting the Hub specific stuff. I think I would prefer to not expose it cross package until there's a specific need for that, but could be persuaded.  Either way, lets hold off for the refector.

2022-07-19 21:19 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +					`Connection state is ${ConnectionState}`
Parts of this discussion happened in the Design/API documents/reviews. I haven't prepared document updates related to this change yet. For the purpose of this conversation here are 3 use-cases customers have discussed.

**Connection Status**
Lets assume a customer wants to display an icon to their users reflecting the connection health, they might do so like this:
```ts
const brokenStates = [ConnectionState.ConnectionDisrupted, ConnectionState.ConnectionDisruptedPendingNetwork, ConnectionState.Disconnected]
const unhealthyStates = [ConnectionState.ConnectedPendingDisconnect, ConnectionState.ConnectedPendingKeepAlive, ConnectionState.ConnectedPendingNetwork]

...

Hub.listen('api', (data: any) => {
	const { payload } = data;
	if (payload.event === CONNECTION_STATE_CHANGE) {
		const connectionState = payload.data.connectionState as ConnectionState;
		if (brokenStates.includes(connectionState)) {
			setConnectionHealth('broken');
		} else if (unhealthyStates.includes(connectionState)) {
			setConnectionHealth('unhealthy');
		} else {
			setConnectionHealth('healthy');
		}
	}
});
```
**Run an action whenever the connection becomes connected**
1. Emit user active status
2. Get most recent content (ensure all content is current)

In some cases this customer may track the prior state and only action on specific state transitions.

```ts
Hub.listen('api', (data: any) => {
	const { payload } = data;
	if (payload.event === CONNECTION_STATE_CHANGE) {
		const connectionState = payload.data.connectionState as ConnectionState;
		if (connectionState === ConnectionState.Connected) {
			// Take action
                }
	}
});
```

**Self managed reconnection**
Since reconnection will follow this, I wouldn't recommend we robustly document this use-case.

2022-07-20 18:55 UTC, stocaaro commented on packages/pubsub/__tests__/helpers.ts
> +	}
Like that thought. There's work out there to get better typing for Hub that might make a good opportunity to look at adding some helper infrastructure/interfaces around Hub.

2022-07-22 01:06 UTC, elorzafe commented
@stocaaro 

The diagram is great!! We could implement AppSync real time using state machine and following the same diagram!

2022-07-22 01:25 UTC, elorzafe reviewed
@stocaaro pr looks great, I would spend a little time to try xstate. It could be so much easy to understand the state. You already have the diagram ready, is just convert it to xstate. Let me know what you think

2022-07-22 01:25 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +					`Connection state is ${ConnectionState}`
Maybe we could add a helper function that converts the enum into health status so the customer doesnt need to implement that logic?

2022-07-22 01:25 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
could be an issue that never unsubscribes?

2022-07-22 01:25 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +		this.connectionStateMonitor.record(CONNECTION_CHANGE.CLOSING);
This might be recorded multiple times if the buffer is not empty

2022-07-22 01:25 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	private linkedConnectionStatesToConnectionState({
I think we should use xstate, it would be so much better to visualize and maintain when we implement the provider using that machine. I dont see as a blocker but maybe if is worth the investment.

2022-07-22 15:14 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +		this.connectionStateMonitor.record(CONNECTION_CHANGE.CLOSING);
Agreed. This should be fine as the resulting observable is deduplicated. Made it intentionally to avoid needing to protect against duplicate protection complicating usage.

2022-07-22 15:17 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
Good catch/call. I originally had a subscription instance var, but this object is never disposed of / cleaned up, so when I went about testing that the subscription was cleaned up, I was considering adding a surface to allow this when I couldn't come up with a realworld usecase.

Even when all subscriptions are removed and the connection is closed, the Disconnected state is still relevant and there's nothing stopping this same provider from being used again, forming a new connection, right?

2022-07-22 15:38 UTC, stocaaro commented
@elorzafe Responding to comments here that didn't have the reply option

> Maybe we could add a helper function that converts the enum into health status so the customer doesn't need to implement that logic?

In an upcoming reconnect PR, I have a private variable that retains this for our use managing reconnection. We could make that public/add it to the provider interface, which would help in the MQTT use-case, but for AppSync, the provider isn't easy for the developer to access, right?  Are you thinking that we would plumb that out into the API or datastore surface somehow? I'm not clear on what developer experience you're proposing, would appreciate a bit more detail to make sure I'm thinking in the right direction.

>  I would spend a little time to try xstate. It could be so much easy to understand the state. You already have the diagram ready, is just convert it to xstate. Let me know what you think

I had looked briefly at state machines to model this, but they seemed like a poor fit / something that would add fragility and complexity. The named states are more of a developer experience normalization of the underlying states. From an internal implementation standpoint, it seemed more intuitive to manage the different state types independently and translate them together into a named state as late as possible in the process.

Are there good examples of where we've used xstate to accomplish things like this elsewhere in our code that I might model this after?  On its face, as a single layer of state, I imagine when the connection is lost, we might need to condition on the network condition to pick the right state transition to match the behavior (or capture this in a layer of abstraction). Either way, moving this logic to the head of the state transition process seems more complicated than leaving denormalizing the states to a single name late in the process as it is now.

I think @svidgen made a run at migrating this to xstate while reviewing it earlier and may have other thoughts in response.

2022-07-22 15:40 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +					`Connection state is ${ConnectionState}`
Yeah. I could see adding helper logic like this, but would prefer to get a round of customer feedback first to validate this is a need/requirement.

One thought that would make this a now vs later type thing might be to replace the enum with objects and add health state to those objects.

2022-07-22 15:42 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	private linkedConnectionStatesToConnectionState({
I've made a run at this and it seemed like a poor fit. Do you have an xstate example or the time to put together a playground example that models out what your thinking? Interested to know if I've missed something here.

2022-07-22 17:09 UTC, svidgen commented
> I think @svidgen made a run at migrating this to xstate while reviewing it earlier and may have other thoughts in response.

It wasn't me... At least that I remember! 😅

2022-07-25 16:03 UTC, stocaaro commented
I've made a [run at rewriting the ConnectionStateMonitor behavior in xState](https://gist.github.com/stocaaro/69274ab0d7e4e83f34606f2f85487527).

Benefits of this approach:
- It's shorter (although the prototype is missing types)
- Each transition is very clear

This code was written to be a bit flexible/permissive such that odd or out of order state transitions work just fine, which I have attempted to capture in this state machine. 

I considered modeling this is one parent machine that contains 4 child machines as this code captures the logic, but couldn't find any examples about how this would work and doing this the parent machine loses visibility into the behavior of the child machines, so I dropped it.

This prototype probably has unintended bugs for my not being able to think through all the cases clearly enough. If we where to go this direction, I think I would try to generate the state transitions from the existing code. In the existing code, there are cases of hidden transition (such as missed keep alive messages) where `ConnectedPendingNetwork` can transition to either `Connected` or `ConnectedPendingKeepAlive` depending on whether a KA message has been missed. I rejected making a special `ConnectedPendingNetoworkAndKeepAlive` type state to represent this difference to the customer.

My conclusion is that this code models 4 very simple states that are then being denormalized into a single meta-state. Modeling this as a single state-machine adds complexity and room for bugs that are avoided in the current implementation. Modeling the problem as many very small state machines could be done, but adds complexity while serving no apparent value.

2022-07-26 16:40 UTC, elorzafe requested changes
Thanks @stocaaro 🥇 

I think this is very close, my only blocking comment would be initializing the observables on the constructor, the others I leave it to you.

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	networkState: LinkedConnectionState;
Why do we need `networkState`, the problem with this is that `connected` can have false positives. I think the most important is `keepAliveState` because is testing the connection. Do you think this is very important to have?

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		| 'CLOSING'
Why not `CLOSING_CONNECTION` just to be consistent with `OPENING_CONNECTION` or viceversa

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	KEEP_ALIVE: { keepAliveState: 'healthy' },
Would this also mean `connectionState` is `connected`?

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			keepAliveState: 'healthy',
I would prefer to start as everything is `disconnected` and `unhealthy` unless I can prove otherwise

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		});
I would initialize this after someone is subscribed (that means you might need to count the subscribers)

I usually see this for Observable pattern so this can be cleaned up and is not adding stuff in memory that no one is using

What do you think?

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			...this._linkedConnectionState,
Cool, so is overwritting only the changes 👍. Can happen you end up on some inconsistent state? Maybe it would be nice to define an invariant that could be type safe? What do you think?

For example `networkState: 'disconnected', keepAliveState: 'healthy'` shouldn't be possible

2022-07-26 16:40 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return ConnectionState.ConnectedPendingKeepAlive;
Would it read more easily if instead of the flat `if` structure make it nested? It could read like a decision tree instead.

2022-07-26 17:00 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			...this._linkedConnectionState,
These states are independent, so I would expect `networkState: 'disconnected', keepAliveState: 'healthy'` to be quite common where keepAlive will then timeout to unhealthy after 65 seconds, but because ka is ignored for disconnected states it won't add an event.

2022-07-26 17:08 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return ConnectionState.ConnectedPendingKeepAlive;
I started down that path initially and refactored it into this for readability, aligning with the school of thought that flat conditionals / guard clauses are easier to read and reason about than nested conditionals. If there's a contrary philosophy at play here, I'd be happy to refactor this to fall in line with a different pattern. Do you have an article or code sample I can use to ensure I'm aligned with what you're going for?

2022-07-26 17:13 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	KEEP_ALIVE: { keepAliveState: 'healthy' },
Not necessarily. If we received a ka message while the connection was PendingDisconnect or Disconnected, that could hypothetically be async callbacks catching up, so flipping the connection state on a ka or a missed ka might cause bugginess (I think). My bias has been to try to keep state updates as independent as possible to avoid odd use-cases.

2022-07-26 17:13 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			keepAliveState: 'healthy',
I like this a lot. I'm going to see what I can do to adopt it.

2022-07-26 17:15 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		});
I think you're right from a cleanliness standpoint. In code, creating and disposing of this with connectivity adds a layer of interaction that could easily be buggy/error prone. I'll give it a 1-2 hour go today and update with further thoughts.

2022-07-26 17:16 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		| 'CLOSING'
Sure. That makes sense. Will make the update.

2022-07-26 17:19 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	networkState: LinkedConnectionState;
Network state is very important to reconnection as it is usually the signal of when we should attempt to reconnect.

Eg. If the network is down and we fail ka after 60 seconds, then close the connection at 5 minutes, neither of these mark when we should attempt reconnect. Only once the network recovers is it valuable to attempt to reconnect again.

This pattern has been adopted from directly from the datastore implementation and has some decent production attletesting in that code.

2022-07-26 19:56 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			keepAliveState: 'healthy',
Running into two problems.
1. I'd like to start the networkState as whatever `Reachability` would tell me the current network state is. `Reachability` only fires when the state changes. For web, it is reading the value out of the global object, which I can expose.  RN doesn't have this same readable value. For RN we could setup some sort of global observer to track this state, but that seems worse than assuming the app is online at the time it is loaded.
2. Since KeepAlive arrives after a connection is formed, defaulting KA to unhealthy means that we get an extra `PendingKeepAlive` event after each new `Connection`. Since `PendingKeepAlive` is really only valuable after a 60 second timeout, I would not recommend injecting all these extra events or adding complexity to suppress them.

I think either of these could be worked around by adding complexity / fragility and in the case of reachability adding surface to core, but I don't think there is much value gained in being rigidly correct in these cases.

2022-07-26 20:02 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		});
I think I found a pattern of starting network monitoring with the first subscription and disabling it after the connection closes that works and I can live with. Interested to get your thoughts.

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
I would check the lifecycle of this when using API graphql without subscriptions just to check if this constructor gets called (I think it does).

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +					`Connection state is ${ConnectionState}`
I am good with that

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	networkState: LinkedConnectionState;
That makes sense, thanks!

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	KEEP_ALIVE: { keepAliveState: 'healthy' },
Makes sense, thanks for clarifying!

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			keepAliveState: 'healthy',
If is that problematic I am fine with this, we can revisit this logic in the future.

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			...this._linkedConnectionState,
Makes sense, thanks for clarifying

2022-07-27 16:24 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return ConnectionState.ConnectedPendingKeepAlive;
Is more like a personal preference tbh, when I see the same statement multiple times I tend to only have it once. Could also be more readable if is spread into smaller functions. would the function name be more readable if is `connectionStatesReducer`or `connectionStatesTranslator` what do you think?

2022-07-27 16:50 UTC, stocaaro commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +			return ConnectionState.ConnectedPendingKeepAlive;
Name changed.

I get that. We're all aiming for code that looks like code we've had a good experience maintaining before.

I just did 2 more short experiments.
1. Building a translation object to wrap the connectedStates. My translation methods ended up with the same names as my `ConnectedState` enum, which made me think of a map.
2. Since this is order of operation guard clauses, a map is the wrong structure and its more of an array of tuples. I started down the path of code that looks like the following, however, I think this trades clarity for brevity, which seems like the wrong direction.
```ts
const CONNECT_STATE_TRANSLATION_MAPPINGS = [
	[
		ConnectionState.ConnectedPendingNetwork,
		{ connectionState: 'connected', networkState: 'disconnected' },
	],
        ...
];
```

Based on this further exploration, I've left it the way it was again.

2022-07-27 16:59 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +		});
Yes! I totally good with doing that

2022-07-27 17:38 UTC, jamesaucode commented
> > I think @svidgen made a run at migrating this to xstate while reviewing it earlier and may have other thoughts in response.
> 
> It wasn't me... At least that I remember! 😅

That was me ... 😄

2022-07-28 15:49 UTC, elorzafe requested changes
@stocaaro I think the logic of enableNetworkMonitor should be inside of the observable. We can chat more offline if you want.

2022-07-28 15:49 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +
I dont like to have this logic outside of the `connectionStateMonitor` I would do it inside of the observable

2022-07-28 15:49 UTC, elorzafe commented on packages/pubsub/src/utils/ConnectionStateMonitor.ts
> +	public enableNetworkMonitoring() {
I would have this logic inside of `_linkedConnectionStateObservable` to initialize the network monitor and on the `return` I would  unsubscribe the network monitor if there is no more subscribers.

2022-07-28 16:06 UTC, svidgen approved these changes

2022-07-29 15:56 UTC, elorzafe approved these changes
Great work @stocaaro 🚢 🌮 🏅 🎉

2022-07-29 18:43 UTC, merged