Datastore/feat user agent suffix
aws-amplify/amplify-js pull request #10086
Opened 2022-07-15 19:16 UTC by erinleigh90

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-15 20:03 UTC, stocaaro reviewed
Good stuff. I think I can follow this all the way through. Have a couple minor comments below.

2022-07-15 20:06 UTC, erinleigh90 commented on packages/datastore/src/util.ts
> +export enum NAMESPACES {
I moved them up because it seemed like a good idea to have constants at the top (i couldn't find constants until later and realized they were hidden at the bottom) I suppose I should have called that out in a commit message.

2022-07-15 20:11 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +export const getAmplifyUserAgent = (content?: string | null) => {
I found that i needed to be able to actively pass null at some point, potentially because I was thinking I couldn't set to undefined. I will look into where I thought this was necessary and verify.

2022-07-15 20:12 UTC, erinleigh90 commented on packages/datastore/__tests__/mutation.test.ts
> +			};
That is what that looks like. Removing. Thank you for catching that!

2022-07-18 17:31 UTC, dpilch approved these changes

2022-07-18 18:50 UTC, ashika01 requested changes

2022-07-18 18:50 UTC, ashika01 commented on packages/core/__tests__/Platform-test.ts
> +import { getAmplifyUserAgent } from '../lib-esm';
Change this import from `src/core/platform` shouldnt be `lib-esm`

2022-07-18 18:50 UTC, ashika01 commented on packages/datastore/__tests__/mutation.test.ts
> +const mockRestPost = jest.fn();
nit: i would adjust these order to have `imports` at top. Should have been a lint config no?

2022-07-18 18:50 UTC, ashika01 commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +		test('happy-case-query with userAgentSuffix', async () => {
nit: change description to not say happy-case instead maybe say `userAgent on request`

2022-07-18 18:50 UTC, ashika01 commented on packages/datastore/__tests__/subscription.test.ts
> +let mockObservable = new Observable(() => {});
same nit as above imports followed by variable declarations

2022-07-18 18:50 UTC, ashika01 commented on packages/datastore/__tests__/subscription.test.ts
> +import { USER_AGENT_SUFFIX_DATASTORE } from '../lib-esm/util';
no lib-esm imports

2022-07-18 18:50 UTC, ashika01 commented on packages/datastore/__tests__/sync.test.ts
> +				expect.objectContaining({ userAgentSuffix: '/DataStore' })
nit: u can use ur `const` created

2022-07-18 19:26 UTC, erinleigh90 commented on packages/datastore/__tests__/mutation.test.ts
> +const mockRestPost = jest.fn();
Since jest hoists mock calls, I had to put the constant at the top of the file for it to be in scope. I attempted to put below the imports and the constant was not recognized.

2022-07-18 19:33 UTC, erinleigh90 commented on packages/datastore/__tests__/subscription.test.ts
> +import { USER_AGENT_SUFFIX_DATASTORE } from '../lib-esm/util';
Fixed

2022-07-18 19:34 UTC, erinleigh90 commented on packages/datastore/__tests__/sync.test.ts
> +				expect.objectContaining({ userAgentSuffix: '/DataStore' })
Fixed

2022-07-18 19:34 UTC, david-mcafee requested changes
Left a few minor comments - overall looks good!! :)

2022-07-18 19:45 UTC, erinleigh90 commented on packages/datastore/__tests__/sync.test.ts
> +let mockGraphQl;
Actually I tested to verify in this file and it appeared to work either way. In the above files pointed out by Ashika, when I tested with them previously the tests did not recognize the variable unless it was at the very top. I wonder if that is related to the number or size of imports? I will validate in other files as well, but will change in this file.

2022-07-18 19:48 UTC, erinleigh90 commented on packages/datastore/__tests__/mutation.test.ts
> +const mockRestPost = jest.fn();
Validated that the test fails when const is moved directly under imports.

2022-07-18 20:19 UTC, erinleigh90 commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +		test('happy-case-query with userAgentSuffix', async () => {
done

2022-07-18 20:52 UTC, ashika01 approved these changes
Great work @erinleigh90 I am good with this PR 👍

2022-07-18 20:53 UTC, ashika01 commented on packages/datastore/__tests__/sync.test.ts
> +let mockGraphQl;
Yup i think the error is happening when the mock needs to run through the imported module. Something along those lines :)

2022-07-18 22:11 UTC, david-mcafee reviewed
Quick follow-up comment

2022-07-18 22:11 UTC, david-mcafee commented on packages/core/src/Platform/index.ts
> +export const getAmplifyUserAgent = (content?: string) => {
I could have sworn I put a comment on this before - but could `content` here, ever be empty? And if so, when?

2022-07-18 22:13 UTC, david-mcafee approved these changes
LGTM! 🎉

2022-07-18 22:13 UTC, david-mcafee commented on packages/core/src/Platform/index.ts
> +export const getAmplifyUserAgent = (content?: string) => {
Discussed offline

2022-07-18 22:18 UTC, merged