feat(@aws-amplify/storage): Access all files from S3 with List API
aws-amplify/amplify-js pull request #10095
Opened 2022-07-19 23:53 UTC by kvramyasri7

#### Description of changes

In storage list api, users can pass 'ALL' as maxKeys in configuration. This change enables users to access all files from S3.

#### Issue #, if available

#7133 
#6838

#### Description of how you validated changes

- Unit test added for the change
- Tested change in the sample app

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-20 02:13 UTC, jamesaucode requested changes
Looks pretty good. Left a few suggestions 😄

2022-07-20 02:13 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3Provider.ts
> +					listResult.contents.map(ele => {
Looks like we are not using the return of `.map`, we can probably use `.forEach` instead.
Or we can simplify it to 

```js
list.push(...listResult)
```

2022-07-20 21:06 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +type S3ProviderListOutputWithToken = {
Fixed

2022-07-20 21:06 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +		params: any,
Fixed

2022-07-20 21:06 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +					listResult.contents.map(ele => {
Fixed

2022-07-20 22:43 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3Provider.ts
> +					list = [...listResult.contents];
wouldn't this override the `list` every time it calls `this._list` ? We should be concatenating all the listResults we gathered.

2022-07-20 22:43 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3Provider.ts
> +				maxKeys < 1000 || typeof maxKeys === 'string'
Did we discuss in API review what happens if someone put maxKeys > 1000 ? I think at least having a `logger.warn` telling the user `.list` only list at most 1000 keys or they will need to use 'ALL' will be helpful here.

2022-07-21 00:36 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +				maxKeys < 1000 || typeof maxKeys === 'string'
Fixed

2022-07-21 00:36 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +					list = [...listResult.contents];
Fixed

2022-07-22 17:44 UTC, stocaaro commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +			});
Can we add a test that receives multiple requests so that we observe a continuation token being used? Mocking a sequence of things is a bit of a pain, but it will be less fragile if we have this usecase covered.  Also, will be valuable for testing the token passing version later.

2022-07-26 17:58 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +			});
Thank you for the suggestion.Done adding this test.

2022-07-26 21:51 UTC, jamesaucode reviewed
LGTM for the most part, just have a few minor comments 😄

2022-07-26 21:51 UTC, jamesaucode commented on packages/storage/src/types/AWSS3Provider.ts
> +export type NewS3ClientOptions = StorageOptions & {
It's a little unclear what this type means. What does `NewS3ClientOptions` here mean?

2022-07-26 22:18 UTC, stocaaro commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +			let continuationToken = 'token';
Can this be "TEST_TOKEN" or something like that?

2022-07-26 23:52 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +			let continuationToken = 'token';
Thanks for the suggestion. Done.

2022-07-26 23:57 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +			let methodCalls = 1;
Yeah. Good Catch. Changed it.

2022-07-27 15:29 UTC, stocaaro approved these changes
Like that the test is one long narrative piece now.  No hidden logic. There's probably room to improve/clarify the test a bit, but it works and that can wait for the next change where we'll have more complexity to test against.

2022-07-27 16:24 UTC, jamesaucode approved these changes
LGTM 🎉

2022-07-28 14:23 UTC, merged