Khareview
aws-amplify/amplify-js pull request #10114
Opened 2022-07-25 19:05 UTC by khatruong2009

#### Description of changes

Adding fetchSession API with authorization state machine. 

#### Issue #, if available

N/A

#### Description of how you validated changes
I tested the changes manually using a sample app and a few unit changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-25 22:28 UTC, jamesaucode requested changes
Didn't finish the review yet 😄 will have more comments later

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
> +					src: async (_context, _event) => {
we use the `_` to signal a variable is not used. In this case your `context` should just be `context` instead of `_context`

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const getIdRes = await cognitoIdentityClient.send(
I think we can just use `this.cognitoIdentityPoolClient` here instead of `cognitoIdentityClient` ?

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const getCredentialsRes = await cognitoIdentityClient.send(
same as above

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
> +					identityID: (context: any, event: any) => context.identityID,
we should probably type the `context` here. `event` is not used so we can leave it untyped and use `_event`

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAwsCredentialsStateMachine.ts
> +// Fetch AWS Credentials State Machine
Remove this file

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/fetchIdentityStateMachine.ts
> +const fetchIdentityStateMachine: MachineConfig<any, any, any> = {
Remove this file

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/fetchUserPoolTokensStateMachine.ts
> +const fetchUserPoolTokensStateMachine: MachineConfig<any, any, any> = {
Remove this file

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
> -import { CognitoIdentityProviderClientConfig } from '@aws-sdk/client-cognito-identity-provider';
Is there any reason we are changing this file ? We should keep the sign up state machine

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const getIdRes = await cognitoIdentityClient.send(
why not use `this.cognitoIdentityPoolClient` here?

2022-07-25 22:28 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> -/**
Why are we removing the docString here?

2022-07-25 23:55 UTC, khatruong2009 commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		if (!this._authService.state.matches('signedIn')) {
Correct

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/__tests__/providers/machines/authorizationMachine.ts
> +		expect(_authzService).toBeTruthy();
nit: I think this is redundant, if it's defined it should be truthy

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/__tests__/providers/machines/authorizationMachine.ts
> +				console.log('skip test');
we can probably remove this line

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +import { Session } from 'inspector';
looks like it's not used, lets remove this

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +
we can remove these as they are only for debugging/demo

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		return signUpRes;
We should keep using the state machine for this part as well

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> -	}
we shouldn't remove this part

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		this._authzService.send(authzMachineEvents.signInRequested());
why do we send this on `signOut`?

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/authenticationMachine.ts
> -	spawnSignUpActor: authenticationMachineModel.assign(
why are all the sign up machine stuff removed?

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
> +	fetchAuthSessionEvent,
Can we use title case for the type names?

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
> +	beginningSessionEvent,
same as above

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
> -import { CognitoIdentityProviderClientConfig } from '@aws-sdk/client-cognito-identity-provider';
It's still not showing up in this iteration

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +	private cognitoIdentityClient: CognitoIdentityClient;
why did we remove `readonly` from these? Are we going to change them in anywhere?

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +	private cognitoClient: CognitoIdentityProviderClient;
same as above

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const cognitoClient = this.createCognitoClient();
we can remove this, and just use `this.cognitoIdentityClient`

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const client = this.createCognitoClient();
I think we can just use `this.cognitoIdentityClient` here

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const client = this.createCognitoClient();
same as above

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const client = this.createCognitoClient();
same as above

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const client = this.createCognitoClient();
same as above

2022-07-26 22:24 UTC, jamesaucode commented on packages/auth/src/Providers/CognitoProvider/types/machines/fetchAuthSessionStateMachine.ts
> +export type fetchAuthSessionReturnContext = {
use title case for type names

2022-08-03 19:00 UTC, haverchuck commented on packages/auth/__tests__/providers/machines/authorizationMachine.ts
> +import { interpret } from 'xstate';
Do we need to be including license headers in each file?

2022-08-04 22:33 UTC, Ashish-Nanda commented on packages/auth/__tests__/providers/machines/authorizationMachine.ts
> +	// });
We should delete the commented out code if its not needed.

2022-08-04 22:34 UTC, Ashish-Nanda commented on packages/auth/__tests__/providers/machines/authorizationMachine.ts
> +		// console.log(state);
Remove commented out log statements

2022-08-04 22:51 UTC, elorzafe requested changes
Remove comment code before merging and also fix James feedback.

2022-08-04 22:51 UTC, elorzafe commented on packages/amplify-ui-components/src/components/amplify-sign-up/readme.md
> +| `usernameAlias`         | `username-alias`     | Username Alias is used to setup authentication with `username`, `email` or `phone_number`
Please revert this file change

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		const client = this.createCognitoClient();
I think you can change that @khatruong2009

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/types/machines/refreshSessionMachine.ts
> +	// actorRef?: FetchAuthSessionActorRef;
If this is not used you can delete it

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/types/machines/fetchAuthSessionStateMachine.ts
> +	// actorRef?: FetchAuthSessionActorRef;
If you dont need this you can remove it

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/types/AuthPluggable.ts
> +	isSignedIn?: boolean;
I think this can be required

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/types/AuthPluggable.ts
> +	confirmationCode?: string;
Why is this optional?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +		// console.log({ getUserRes });
remove this line

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/serviceClass.ts
> +			// @ts-ignore
Why do you need these?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +	// @ts-ignore
Why you needs these?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +		// @ts-ignore
why you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +	  }
I would create a type for this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +		// @ts-ignore
why you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +		// @ts-ignore
why you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/service.ts
> +			// @ts-ignore
why you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
>  						// TODO: ask James about this
What did you James said about this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/signInMachine.ts
> +					// @ts-ignore
why you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/refreshSessionMachine.ts
> +			// ...fetchAuthSessionStateMachine,
Why do you need this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/refreshSessionMachine.ts
> +			// },
I would remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
> +				// ],
I would remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
> +				// ],
I would remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
> +		// fetchedAWSCredentials: () => ({}),
I would remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
> +		// },
I will remove this?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
> +	// }),
I will remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +			console.log(res);
I would remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +			// console.log(state);
Remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +// inspect();
remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		// inspect();
remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		// inspect();
remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
> +		// this._authzService.send(authzMachineEvents.signInRequested());
remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/authenticationMachine.ts
> +			initiateSignUp: () => ({}),
What happen here?

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
> +			// refreshed: () => ({}),
remove this

2022-08-04 22:51 UTC, elorzafe commented on packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
>  						console.log('signUpMachine 97!!!', { res });
remove this

2022-08-04 23:30 UTC, khatruong2009 commented on packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
>  						// TODO: ask James about this
I think this was Nick. I didn't do any work on the signUpMachine. I can delete this comment and the commented code underneath it

2022-08-06 00:10 UTC, elorzafe approved these changes
Thanks @khatruong2009 🎉

2022-08-10 20:12 UTC, haverchuck approved these changes

2022-08-10 20:13 UTC, merged