feat(@aws-amplify/auth): Auto sign in after sign up
aws-amplify/amplify-js pull request #10126
Opened 2022-07-28 16:47 UTC by helgabalashova

#### Description of changes
Changes add confirm sign up listener to initiate auto sign in once account is confirmed. It happens if autoSignIn is set to true in params for SignUp function.
Since customers can choose either code, link, or autoConfirm, the solution use three different ways to auto sign in. autoConfirm implementation immediately calls on confirmSignUp function. Link implementation uses polling to sign user in since there is no explicit way to know if user clicked the link. Polling is done within 3 minutes (time verification link is valid) every 5 seconds. Code implementation is using hub listening event. Once user confirms account with code, it dispatches listening event. SignUp function is listening for this event to initiate SignIn process.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/6320
https://github.com/aws-amplify/amplify-js/issues/3882
https://github.com/aws-amplify/amplify-js/issues/3631
https://github.com/aws-amplify/amplify-js/issues/6018

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-28 17:43 UTC, elorzafe requested changes
There might be a bug when autoSignIn fails is not clearing storage flag for `amplify-auto-sign`

2022-07-28 17:43 UTC, elorzafe commented on package.json
> +		"publish:auto-sign-in-main-branch": "lerna publish --canary --force-publish \"*\" --yes --dist-tag=auto-sign-in --preid=auto-sign-in --exact --no-verify-access",
We will remove that in a following PR

2022-07-28 17:43 UTC, elorzafe commented on .circleci/config.yml
> +      - auto-sign-in-main-branch
We will remove this in a following PR

2022-07-28 17:43 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +						logger.error(error);
Maybe we need to remove `amplify-auto-sign-in` here as well

2022-07-28 18:00 UTC, elorzafe commented on .circleci/config.yml
> +      - auto-sign-in-main-branch
We can remove this line too

2022-07-28 18:01 UTC, elorzafe approved these changes
Great work @helgabalashova 🎉 🏅 🌮

2022-07-28 18:07 UTC, stocaaro approved these changes
This change doesn't document the validation process observed to ensure that the unit/integ/manual testing has taken place to give us the confidence to roll this out to our customers.  Would appreciate getting a bit more detail of that into this description for posterity, but see no reason not to go ahead and merge.

Have noted a number of things that caught my eye going through the code, but nothing that qualifies as a "must fix" before merge.

2022-07-28 18:07 UTC, stocaaro commented on packages/auth/src/Auth.ts
> +		}, 5000);
How do we know that 5 seconds is the right interval?

2022-07-28 18:07 UTC, stocaaro commented on packages/auth/src/Auth.ts
> +		}
Checking my own understanding. These timeout because we're polling for state, right, were user confirmation doesn't timeout because it's a received event?

2022-07-28 18:07 UTC, stocaaro commented on packages/auth/__tests__/auth-unit-test.ts
> +	describe('autoSignInAfterSignUp', () => {
Big fan of how self contained and succinct these tests came through. Have we done the step of confirming that they fail without the change?

2022-07-28 19:26 UTC, elorzafe commented on package.json
> +		"publish:auto-sign-in-main-branch": "lerna publish --canary --force-publish \"*\" --yes --dist-tag=auto-sign-in --preid=auto-sign-in --exact --no-verify-access",
We could but it will take another round of tests, I can deleted after the launch is made

2022-07-28 19:27 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +		}, 5000);
We made discussions about this during API reviews, I agree we could that as a quick follow up

2022-07-28 19:28 UTC, jamesaucode approved these changes
Non-blocking, but I think we can have more unit tests around making sure localStorage flags & Hub events are cleared properly. But overall LGTM 🎉

2022-07-28 19:43 UTC, helgabalashova commented on packages/auth/__tests__/auth-unit-test.ts
> +	describe('autoSignInAfterSignUp', () => {
they fail without the change

2022-07-28 19:48 UTC, helgabalashova commented on packages/auth/src/Auth.ts
> +		}
yes

2022-07-28 19:50 UTC, merged

2022-07-29 19:24 UTC, alxsavard commented
👋 Hi,

What coincidence that I needed this feature today and it litteraly got released hours ago! Thanks for doing that! 

I do want to point out that I'm getting an Unhandled promise rejection now. It doesn't seem to be breaking anything, but I just thought you might want to know! 

```
Error: Invalid value for entry - must be a string. Got entry: (
    "@MemoryStorage:amplify-auto-sign-in",
    1
)
    at convertError (http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:151207:15)
    at http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:151215:14
    at Array.map (<anonymous>)
    at convertErrors (http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:151214:28)
    at http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:150955:51
    at MessageQueue.__invokeCallback (http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:23519:18)
    at http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:23217:18
    at MessageQueue.__guard (http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:23432:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://192.168.1.231:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:23216:14)
    at http://localhost:19000/debugger-ui/debuggerWorker.aca173c4.js:4:902
    
```

2022-07-29 21:45 UTC, elorzafe commented
@alxsavard thanks for reporting this, we will take a look.

2022-07-29 22:48 UTC, elorzafe commented
@alxsavard are you using a custom Storage adapter? how are you configuring the library? We couldnt reproduce the issue here. Also in which browser/env did you run it?

2022-08-01 14:15 UTC, alxsavard commented
I'm not using any custom storage and I have nothing in my library configuration. Just the barebone region & userPoolIds.

I'm using React Native (with expo) on iOS!

2022-08-01 14:47 UTC, alxsavard commented
I didn't look into it too much, but maybe it's be because iOS local storage expects a string and not a bool?

Here you set a boolean
https://github.com/aws-amplify/amplify-js/pull/10126/files#diff-d7133ba15216009e91d0c1632f34aa2279f4e6a03873e701c4abf582e011ed5fR377
```
(Line 377) this._storage.setItem('amplify-auto-sign-in', true);
```

But elsewhere in the code you set a string 
https://github.com/aws-amplify/amplify-js/pull/10126/files#diff-d7133ba15216009e91d0c1632f34aa2279f4e6a03873e701c4abf582e011ed5fR131
```
(Line 131) this._storage.setItem('amplify-signin-with-hostedUI', 'false');
```

2022-08-01 18:48 UTC, alxsavard commented
@elorzafe Sorry for the spam, I'm just tagging you because since this PR is closed I assumed it is not tracked anymore. I should probably open an issue instead of adding stuff here 😰.

2022-08-01 23:31 UTC, elorzafe commented
@alxsavard can you check with the latest version of the library, it was published a few mins ago.

Thanks!

2022-08-02 15:13 UTC, alxsavard commented
@elorzafe Yep, that seems to have done the trick! Thanks for the quick fix!