GH-9824 - feat: PubSub Connection state tracking for MQTT and IoT providers
aws-amplify/amplify-js pull request #10136
Opened 2022-07-29 20:17 UTC by stocaaro

#### Description of changes
Add Hub events for MQTT connection state changes. Building on the work to [add connection states for AppSync](https://github.com/aws-amplify/amplify-js/pull/10063), this applies the same events to the MQTT interface, which will include the IoT provider.

Changes:
- Add ConnectionStateMonitor and events to the MQTT provider
- Refactor the test helper to expose the hub event tracking for use with the MQTT tests
- Add MQTT tests to cover the new behavior

#### Issue #, if available
#9824

#### Description of how you validated changes
- Unit tests where added
- Manually tested against a sample app

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-06 01:09 UTC, elorzafe requested changes
It seems we could add more events on the monitor, we can chat more offline

I think is very close
Thanks @stocaaro 🌮

2022-08-06 01:09 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(CONNECTION_CHANGE.OPENING_CONNECTION);
on L196 is missing `record`

2022-08-06 01:09 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(CONNECTION_CHANGE.OPENING_CONNECTION);
on L188 could be something similar to the `ka` messages?

2022-08-10 22:27 UTC, stocaaro commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(CONNECTION_CHANGE.OPENING_CONNECTION);
Alright. The onDisconnect record event is added.

Re: Keep alive. The only place in the [paho public surface](https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/paho-mqtt.js) that keep alive appears to be logged is in the `trace` behavior.  It looks like this is available in the public interface if you receive it through the `traceFunction` callback. This isn't offered the the TS interface, but I made a run at using it and couldn't make it respond with the expected callback events.

I'm pretty sure I could turn this into something in another hour or two, but I'm off the end of my timebox and I think the better path would be to settle for not offering KA input for MQTT at this time.

2022-08-11 22:00 UTC, elorzafe requested changes
Sorry I didn't see this before. It seems `connectionStateMonitor` should be unsubscribe after the las subscription is unsubscribed

2022-08-11 22:00 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
What happens if the connection is closed, is this going to be emitting events right?

Shouldn't in that case this be only when there is a subscription open ?

2022-08-11 22:00 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +						);
This should also remove the subscription for `connectionStateMonitor` right?

2022-08-12 23:12 UTC, stocaaro commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
Good news. When [CONNECTION_FAILED or CLOSING_CONNECTION changes](https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/utils/ConnectionStateMonitor.ts#L44-L48) are recorded, the monitor automatically [turns off the Reachability subscription](https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/utils/ConnectionStateMonitor.ts#L136-L140).

2022-08-12 23:13 UTC, stocaaro commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +						);
Yep, since `CLOSING_CONNECTION` turns the `intended _connection_state` to disconnected, this will automatically turn off the Reachability sub.

2022-08-16 17:08 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.connectionStateObservable.subscribe(
oh nice, ok cool

2022-08-16 17:08 UTC, elorzafe commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +						);
Cool!

2022-08-16 17:09 UTC, elorzafe approved these changes
Great work

Thanks @stocaaro 🌮 🎉 🏅

2022-08-17 20:30 UTC, Samaritan1011001 commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(
Should this be inside the onSuccess block of the connect call? Does it not make a difference?

2022-08-17 20:33 UTC, Samaritan1011001 approved these changes
Looking good. Just two clarification, non-actionable questions. 
Thank you.

2022-08-17 20:33 UTC, Samaritan1011001 commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(
Should this be inside the onSuccess block of the connect call? Does it not make a difference?

2022-08-17 20:33 UTC, Samaritan1011001 commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +				const sub = pubsub.subscribe('topic', { clientId: '123' }).subscribe({
Curious why the subscribe calls are chained here.

2022-08-17 20:54 UTC, stocaaro commented on packages/pubsub/src/Providers/MqttOverWSProvider.ts
> +		this.connectionStateMonitor.record(
We want this to fire as soon as the connection is available for use. In the above `.connect`, we could add this in the `onSuccess` handler.  Since this resolves the outer promise that is being awaited, having the state recorded right after the await keeps this in the right place without burying it down in a callback, but you're right to call out that the code doesn't immediately tell you that this is the moment where the connection has finally been established.

2022-08-17 20:54 UTC, stocaaro commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +				const sub = pubsub.subscribe('topic', { clientId: '123' }).subscribe({
The PubSub API uses the `.subscribe` keyword to setup an `Observable` where these `zen-observable` objects also have a `.subscribe` method that allows you to setup independent callback for `next` events, `complete` and `error` events. Both `error` and `complete` events close the observable, so will only ever be called once.

2022-08-17 20:55 UTC, merged

2022-08-17 21:00 UTC, Samaritan1011001 commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +				const sub = pubsub.subscribe('topic', { clientId: '123' }).subscribe({
Nice! thanks for both the explanations.