async adapter bug fixes; observeQuery bug fix
aws-amplify/amplify-js pull request #10140
Opened 2022-07-31 01:42 UTC by david-mcafee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-01 19:02 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +				// observeQuery does not accept OL, okay to remove, Manuel?
Discussed with Manuel offline, will remove

2022-08-01 19:13 UTC, iartemiev requested changes
Looks good! Just a couple tiny call outs

2022-08-01 19:13 UTC, iartemiev commented on packages/datastore/src/util.ts
> +	idEmptyString: 'Field of type `ID` cannot be an empty string',
This should read: "An index field cannot contain an empty string value". 

The field's type is not important, we can have an optional field with type `ID`. But any field (regardless of type) that's part of a primary key or other index cannot be empty.

2022-08-01 20:31 UTC, david-mcafee commented on packages/datastore/src/util.ts
> +	idEmptyString: 'Field of type `ID` cannot be an empty string',
Updated!

2022-08-01 23:52 UTC, iartemiev approved these changes
LGTM! 👍🏻

2022-08-02 15:05 UTC, dpilch approved these changes
LGTM, just one non-blocking style nit

2022-08-02 15:07 UTC, dpilch commented on packages/datastore/src/datastore/datastore.ts
> +		for (const key of extractPrimaryKeyFieldNames(modelDefinition)) {
nvm, looks like this has changed since I started the review.

2022-08-02 17:45 UTC, merged