feat(@aws-amplify/storage): pagination for storage list api using Token
aws-amplify/amplify-js pull request #10161
Opened 2022-08-05 00:59 UTC by kvramyasri7

#### Description of changes
To enable users to paginate through storage using List api. Enabled users to pass a pageToken to the list Api so that they can get a next set of files.

#### Issue #, if available

#7133 
#6838 

#### Description of how you validated changes

- Unit test added for the change
- Tested change in the sample app

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-05 18:26 UTC, stocaaro commented on packages/storage/src/providers/AWSS3Provider.ts
>  					: (params.MaxKeys = 1000);
My brain wants this block of code structured differently. Saying I don't like the aesthetic of it isn't helpful, so let me see if I can step into what I might propose as better and why.

```js
params.maxKeys = 1000
if (typeof pageSize === 'number') {
  params.maxKeys = Math.min(params.maxKeys, pageSize);
}
```

Now, what do I like about this, better than what you've got here?
- Ternaries shouldn't span multiple lines, ideally, but with multiple conditions this would be too much for one line.
- Guarding for `number` as opposed to against `string` seems more inline with what is happening here.
- I like using 1000 as the default value and only overriding it when we find an applicable override.

2022-08-05 18:26 UTC, stocaaro commented on packages/storage/src/providers/AWSS3Provider.ts
> +					params.ContinuationToken = continuationToken;
can we get away with not having a different `continuationToken` variable? Instead, just referring to `listResult?nextPageToken`?

2022-08-05 18:26 UTC, stocaaro commented on packages/storage/src/providers/AWSS3Provider.ts
>  					params.MaxKeys = 1000;
This never changes, right?  Do we need to reset it to 1000 each loop?

2022-08-05 18:26 UTC, stocaaro commented on packages/core/src/Signer.ts
> +		if (request.body && !request.data) {
This signer stuff must have gotten mixed up in our next merge stuff.  Can you see if this was removed and we're adding it back vs the next branch was missing this diff?

2022-08-05 18:26 UTC, stocaaro commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +		for (let i = 0; i < pages; i++) listResult.push(resultObj);
This testing stuff looks a bit odd, loops in open describe blocks. Long-ish tests with lots of layered behavior. There's got to be a better way, but its hard for me to think of exactly which direction to explore for improvement. Can we pair on this some today or Monday?

2022-08-05 18:29 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +						"makeys can be from 0 - 1000 or 'ALL'. To list all files you can set maxKeys to 'ALL'."
This is a good catch. Thank you.

2022-08-05 19:20 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
>  					params.MaxKeys = 1000;
Yeah, we can place it out side of the loop. Thanks for the suggestion.

2022-08-08 18:16 UTC, elorzafe requested changes
it seems `ALL` vs list page is a little unclear on the type level. We can discuss that more offline

2022-08-08 18:16 UTC, elorzafe commented on packages/core/__tests__/Signer-test.ts
> +				region: 'aregion',
I think this change is because the other branch needs rebasing right?

2022-08-08 18:16 UTC, elorzafe commented on packages/storage/src/providers/AWSS3Provider.ts
> +			console.log('Helloo  from list');
Need to remove this

2022-08-08 18:16 UTC, elorzafe commented on packages/storage/src/types/AWSS3Provider.ts
> +	pageSize?: number | 'ALL';
What happens if `pageSize` has changed after first `list` operation? Is that possible?

2022-08-08 18:16 UTC, elorzafe commented on packages/storage/src/types/AWSS3Provider.ts
> +	pageSize?: number | 'ALL';
I would have a type with `pageSize` (the first list), then another with `pageToken`.

I would also remove `ALL` it seems to be the default anyway. And also feels odd that a page is `ALL`.

2022-08-08 18:26 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +			console.log('Helloo  from list');
Thanks. Done.

2022-08-08 22:09 UTC, stocaaro commented on packages/storage/src/types/AWSS3Provider.ts
> +	pageSize?: number | 'ALL';
Agree that we can drop ALL if this is the default behavior.

For `pageSize` I think we have tested that it is possible to change the pageSize after the first operation, given a token.  Since without having an explicit page size, we would need to retain it somewhere, are you thinking that we would include this as part of the nextPageToken so that we know the pagesize to keep things consistent moving forward? I can see customer usecases where the end user might change the pagesize mid-pagination and expect not to be reset. Presumably if the developer doesn't want to enable this, they will be able to keep the pagesize static. Are you sure about removing the pageSize input when there is a token?

2022-08-08 23:56 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
> +					params.ContinuationToken = continuationToken;
Yeah we can do that. Thanks for the suggestion.

2022-08-08 23:57 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3Provider.ts
>  					: (params.MaxKeys = 1000);
Removing string or number as we are removing 'ALL' in total. Thanks for the suggestion.

2022-08-10 00:07 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
> +		for (let i = 0; i < pages; i++) listResult.push(resultObj);
Done. Thanks for the suggestion.

2022-08-10 00:08 UTC, kvramyasri7 commented on packages/core/src/Signer.ts
> +		if (request.body && !request.data) {
Done. Thanks

2022-08-10 20:24 UTC, kvramyasri7 commented on packages/core/__tests__/Signer-test.ts
> +				region: 'aregion',
Removed the Changes. Done. Thanks.

2022-08-10 21:14 UTC, closed without merging

2022-08-10 21:15 UTC, kvramyasri7 commented
Closing this PR and opened a new PR with the pagination changes.