fix(aws-amplify/auth): debouncing get user session calls
aws-amplify/amplify-js pull request #10195
Opened 2022-08-11 21:24 UTC by Samaritan1011001

#### Description of changes

Rebasing the fix/auth-debouncing branch to main. 
Worked on by James.
Changes allow for debouncing getSession API calls 

#### Issue #, if available

#### Description of how you validated changes
yarn test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-11 22:21 UTC, elorzafe approved these changes
Looks good,

Thanks @Samaritan1011001 🌮

2022-08-12 17:28 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +			return await this.inflightSessionPromise;
Have you tested that invocations which return the pre-existing `inflightSessionPromise` here are resolved correctly and get the expected value?

2022-08-12 17:29 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			return await this.inflightSessionPromise;
Great question, yeah we should add tests for this

2022-08-16 15:24 UTC, stocaaro requested changes
Are we removing a method from the public library surface here?

Either way, let's get some unit tests added to cover the updated behavior.

2022-08-16 15:24 UTC, stocaaro commented on packages/auth/src/Auth.ts
> +						const bypassCache = params ? params.bypassCache : false;
nit: bools in ternaries can be a bit of a code smell; essentially using a bool to get to a bool. Also, in this case it could end up undefined if params exists, but doesn't have bypassCache set, right? Mighty be slightly clearer as:
```ts
const bypassCache = params?.bypassCache ?? false;
```

2022-08-16 15:24 UTC, stocaaro commented on packages/auth/src/Auth.ts
> +						const bypassCache = params ? params.bypassCache : false;
Leaving this, but just noticed it's whitespace change, not added code...  Feel free to ignore.

2022-08-16 15:24 UTC, stocaaro commented on packages/auth/src/Auth.ts
> -	public userSession(user): Promise<CognitoUserSession> {
Is this dropping the public `userSession` method?

2022-08-16 17:05 UTC, elorzafe requested changes
I will approve this after adding some testing

2022-08-16 18:19 UTC, Samaritan1011001 commented on packages/auth/src/Auth.ts
> +			return await this.inflightSessionPromise;
Thanks! Yeah, they all get resolved and only one network is made as intended.

2022-08-16 18:22 UTC, Samaritan1011001 commented on packages/auth/src/Auth.ts
> -	public userSession(user): Promise<CognitoUserSession> {
No, it's just the GitHub diff showing it that way because of how it was edited maybe. `userSession` is just moved to the bottom of the page and existing internal `_userSession` has added code.

2022-08-17 18:30 UTC, stocaaro approved these changes
LGTM

2022-08-17 19:25 UTC, Samaritan1011001 commented on packages/auth/src/Auth.ts
> +						const bypassCache = params ? params.bypassCache : false;
Nice catch and that's right, it's existing code.

2022-10-27 19:30 UTC, AllanZhengYP commented
Replaced by https://github.com/aws-amplify/amplify-js/pull/10553

2022-10-27 19:30 UTC, closed without merging