bug(analytics): change timestamp to camelCase
aws-amplify/amplify-js pull request #10329
Opened 2022-09-15 18:24 UTC by katiegoines

#### Description of changes
Changed the case styling of `timestamp` to `timeStamp` [per documentation](https://docs.aws.amazon.com/personalize/latest/dg/API_UBS_Event.html#:~:text=The%20keys%20use%20camel%20case%20names%20that%20match%20the%20fields%20in%20the%20Interactions%20schema.%20In%20the%20above%20example%2C%20the%20numberOfRatings%20would%20match%20the%20%27NUMBER_OF_RATINGS%27%20field%20defined%20in%20the%20Interactions%20schema). 

#### Issue #, if available
https://github.com/aws-amplify/amplify-js/issues/6906

#### Description of how you validated changes
Manual testing.

#### Checklist

- [ x] PR description included
- [ x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-15 18:55 UTC, AllanZhengYP approved these changes

2022-09-15 20:18 UTC, jimblanc reviewed
Could this be considered a breaking change? It looks like the existing naming has been in place for a few years (even though it disagrees with the docs).

2022-09-21 15:16 UTC, stocaaro commented
Timestamp can be one word or two. The error from the related issue is what matters. I just tried to trace out the API interface that needs this to be camelcase and couldn't find how this buffer is cleared. I could repro, but I suspect that this is what you mean by "manual testing". Can you add more detail about what you did to test this and the behavior you observed?

In this case, unless there's an API definition we can use to test inputs against, unit testing this would be brittle and not especially helpful, so I wouldn't advocate for that at this time, unless there is an interface for this that I missed.

2023-01-24 21:10 UTC, jimblanc approved these changes

2023-01-30 16:27 UTC, jimblanc requested changes
Ran into some issues while testing this PR, blocking merge until I can update.

2023-02-07 19:08 UTC, closed without merging