feat: add bundle_size job in CCI flow
aws-amplify/amplify-js pull request #10416
Opened 2022-10-04 15:01 UTC by israx

#### Description of changes

-adds bundle_size job in CCI flow
-upgrades node version in build executor

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-04 15:50 UTC, jimblanc approved these changes
Nice, good first step! Could you confirm that you got a clean integ test run (pretty big cypress upgrade)? Also we should hold off on merging to main until we discuss this afternoon

2022-10-04 16:00 UTC, israx commented
> Could you confirm that you got a clean integ test run (pretty big cypress upgrade)? I think the integration tests are running on another executor that has a different node version.

2022-10-04 16:17 UTC, haverchuck commented on .circleci/config.yml
> +      - image: cypress/base:14.15.0
Have we verified that all other tests run successfully with this version bump?

2022-10-04 16:25 UTC, haverchuck commented on packages/auth/package.json
> +        "path": "dist/aws-amplify-auth.min.js"
This is testing the size of the minified file only.  If that's what we are going to do for now, maybe we should change the command names to "size-test" or something, and not use the term "bundle".

Have you looked into testing the actual impact of the auth/core modules on a web app bundled with webpack?

2022-10-04 16:26 UTC, haverchuck commented on package.json
> +		"size-limit": "^8.1.0",
This is a CLI tool, yeah? Have other teams looked at this and vetted it with security?

2022-10-04 16:27 UTC, haverchuck requested changes
See inline comments.

2022-10-04 16:33 UTC, israx commented on package.json
> +		"size-limit": "^8.1.0",
The UI is using the same dev dependency

2022-10-04 16:42 UTC, israx commented on .circleci/config.yml
> +      - image: cypress/base:14.15.0
Unit tests run and work but need to verify if integration tests are using this version bump

2022-10-04 16:43 UTC, iartemiev commented on .circleci/config.yml
> +      - image: cypress/base:14.15.0
Integ tests use different executors altogether, so they won't be affected

2022-10-04 16:46 UTC, iartemiev commented on packages/auth/package.json
> +        "path": "dist/aws-amplify-auth.min.js"
+1

2023-01-10 21:19 UTC, abdallahshaban557 commented
Closing this - confirmed with @jimblanc

2023-01-10 21:19 UTC, closed without merging