Fix: awaited globalSignOut in cognitoSignOut
aws-amplify/amplify-js pull request #10458
Opened 2022-10-11 14:24 UTC by MatthewChon

#### Description of changes

Added the `async` keyword when calling `user.globalSignOut` in `cognitoIdentitySignOut`

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-12 19:17 UTC, AllanZhengYP approved these changes

2022-10-12 19:34 UTC, chrisbonifacio approved these changes

2022-10-13 16:06 UTC, chrisbonifacio requested changes
Hey Matthew, could you explain how you validated or tested that the await here is ensuring that the `Auth.signIn` call is no longer resulting in `access token has been revoked`? 

Were you able to reproduce the issue before adding this line?
Did you try this in different network conditions? 
Logging into multiple devices/browsers to test scenarios where there are more tokens to revoke?

2022-10-14 18:21 UTC, closed without merging

2022-10-14 18:24 UTC, MatthewChon commented
The issue was not resolved with this change.