Revert "Revert "fix(@aws-amplify/datastore): introduce "settlement" guarantees to stop() and clear()""
aws-amplify/amplify-js pull request #10450
Opened 2022-10-10 21:00 UTC by svidgen

Reverts aws-amplify/amplify-js#10449

2022-10-17 16:19 UTC, dpilch commented on packages/datastore/__tests__/DataStore.ts
> -	test('multiple DataStore imports are identical', async () => {
Why is this removed?

2022-10-17 16:19 UTC, dpilch commented on packages/datastore/src/datastore/datastore.ts
> +								// console.log('sync sub message', { type, data });
Stray comment

2022-10-17 19:21 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +				console.log(this.runningProcesses);
ack.

2022-10-17 19:40 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +			// return this.runningProcesses.addCleaner(async () => {
Digging on this a little more. I removed this while troubleshooting, but the fact that it's not causing a test to fail means it was possibly an inconsequential cleanup to start with.

2022-10-17 19:50 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> -	test('multiple DataStore imports are identical', async () => {
Simulating connect/disconnect and/or `isNode` required the `getDataStore()` call to do this:

```
	jest.clearAllMocks();
	jest.resetModules();
```

So, this sanity check just no longer holds. Tests that require the same instance of DataStore will need to create DataStore at the `describe` level or higher.

I'll reintroduce the test but with a `not.toBe` assertion instead, along with a brief explanation.

2022-10-17 20:35 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +								// console.log('sync sub message', { type, data });
ack.

2022-10-17 20:54 UTC, david-mcafee requested changes
Left some comments and suggestions

2022-10-17 20:54 UTC, david-mcafee commented on packages/core/__tests__/Retry-test.ts
> +	// TODO: test expontential backoff ...
Do we have an item in our backlog for this?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore-storage-adapter/package.json
>  						"dom"
```suggestion
```

Remove duplicate

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/CHANGELOG.md
Can we remove these changes?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/DataStore.ts
> +	 * TODO: Investigate.
Do we have a backlog item to investigate this?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/helpers.ts
> +		// });
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/helpers.ts
> +		// console.log('API request', { query, variables, authMode, authToken });
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/helpers.ts
> +				// Simluate update using the default (AUTO_MERGE) for now.
```suggestion
				// Simulate update using the default (AUTO_MERGE) for now.
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/helpers.ts
> +			// console.log('observers', { observers, all: this.observers });
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/__tests__/helpers.ts
> +				// console.log('sending mutation', observerMessageName, message);
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/not-tsconfig.json
> +//WARNING: If you are manually specifying files to compile then the tsconfig.json is completely ignored, you must use command line flags
What is this file?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +	 * Accumulator for backgrouns things that can **and MUST** be called when
```suggestion
	 * Accumulator for background things that can **and MUST** be called when
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +		// });
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +	async clear() {
Why do we no longer check if the schema has been initialized?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> -		}
What was the expectation here, previously?

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/sync/index.ts
> +										// } & Record<string, any>>]>
```suggestion
										ctlSubsObservable,
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/sync/processors/mutation.ts
> +						// });
```suggestion
```

2022-10-17 20:54 UTC, david-mcafee commented on packages/datastore/src/sync/processors/sync.ts
> +					// TODO: onTerminate.then(() => API.cancel(...))
Is this a fast-follow, or long-term item?

2022-10-17 21:12 UTC, svidgen commented on packages/datastore/not-tsconfig.json
> +//WARNING: If you are manually specifying files to compile then the tsconfig.json is completely ignored, you must use command line flags
🤦 ... TLDR, I thought I needed a BAK of my `tsconfig.json`, thinking it wasn't committed in the lazy loading branch. And I guess I accidentally added it.

2022-10-17 22:12 UTC, svidgen commented on packages/datastore/__tests__/helpers.ts
> +				}),
Darnit. This is wrong. I'm not sure at what point I broke this, but I'm seeing errors in an app now that my tests aren't catching, and I believe this explains why.

WIP.

2022-10-17 22:46 UTC, svidgen commented on packages/datastore/__tests__/helpers.ts
> +				}),
OK. This is actually half-right. (And still therefore half wrong.) I goofed it up because I saw it being exported at the not level and thought I originally goofed it up, so I changed it. But, it looks like it's exported *and consumed* from both places.

Still a WIP.

2022-10-19 21:55 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +			// return this.runningProcesses.addCleaner(async () => {
Yes. I've updated all the processors to use the open/close pattern instead of unsetting the `runningProcesses`. I've also revisited some of these cleaners in the process &mdash; some of them were just superfluous vestiges of an earlier iteration.

2022-10-19 21:58 UTC, svidgen commented on packages/core/__tests__/Retry-test.ts
> +	// TODO: test expontential backoff ...
No. The test coverage around this functionality was lacking prior to this PR. I think we need to discuss a small handful of PR's to address test coverage and refactors &mdash; not necessarily targeted at this LOC just yet. What do you think?

2022-10-19 21:59 UTC, svidgen commented on packages/datastore/CHANGELOG.md
🤦

2022-10-19 22:07 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +					// TODO: onTerminate.then(() => API.cancel(...))
I've added a task to the backlog. I'm not sure this is high value, but I wanted to leave a TODO here to highlight the fact that the API requests themselves are not actually being canceled on `onTerminate` today.

2022-10-19 22:10 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> +	 * TODO: Investigate.
I think I can add this back in with a comment. It's here to let customers know when things are bad and that multiple instances of datastore are probably running together.

2022-10-19 22:11 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	async clear() {
Re-added.

2022-10-19 22:30 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> -		}
As far as I can tell, this was always unnecessary &mdash; the result of a copy/paste from elsewhere. IIRC, I asked @iartemiev about it and he suggested that was probably the case.

2022-10-19 22:58 UTC, david-mcafee approved these changes
LGTM! Just one minor nit that isn't a blocker

2022-10-19 22:58 UTC, david-mcafee commented on packages/core/__tests__/Retry-test.ts
> +	// TODO: test expontential backoff ...
Agree with you completely!

2022-10-19 22:58 UTC, david-mcafee commented on packages/datastore/CHANGELOG.md
> -# [3.14.0](https://github.com/aws-amplify/amplify-js/compare/@aws-amplify/datastore@3.13.0...@aws-amplify/datastore@3.14.0) (2022-10-14)
nit: remove?

2022-10-20 02:21 UTC, svidgen commented on packages/datastore/CHANGELOG.md
> -# [3.14.0](https://github.com/aws-amplify/amplify-js/compare/@aws-amplify/datastore@3.13.0...@aws-amplify/datastore@3.14.0) (2022-10-14)
That's odd, I thought I removed this change. Let me try this again ...

2022-10-20 15:07 UTC, dpilch approved these changes

2022-10-20 16:32 UTC, david-mcafee approved these changes
LGTM!

2022-10-21 18:34 UTC, stocaaro approved these changes
Hand full of nits / questions. Overall, I have no objections to merging this.  I don't have enough of the DS internals in my brain to consider my review of that packages larger changes good enough, but others have made a deep review of this.

2022-10-21 18:55 UTC, svidgen commented on packages/core/__tests__/Util-test.ts
> +			expect(true).toBe(false);
Yeah, this one got a bit awkward &mdash; I'm not 100% sure I like jest's assertion counting as a mechanism. But, I ran into crazy issues in this test IIRC, trying to sort out what was actually failing in my red-green case. So, as a nit, I'm letting this one go for now. 😓

2022-10-21 19:04 UTC, svidgen commented on packages/core/__tests__/BackgroundProcessManager-test.ts
> +		expect(manager.isClosed).toBe(false);
I think I agree. As discussed offline, we're we can iterate since the class is `@private`, so we'll favor shipping.

2022-10-21 21:44 UTC, svidgen commented on packages/core/__tests__/BackgroundProcessManager-test.ts
> +				resolve(); // always remember to resolve/reject!
As-is, `close()` won't resolve while promises under its management are unresolved. I had considered adding a variant of `close()` that accepts a timeout, but didn't have a need for it yet, so I applied YAGNI. But, down the line, if the timeout is exceeded, we could have the manager throw an exception and enumerate the "stuck" work.

2022-10-21 21:52 UTC, svidgen commented on packages/core/__tests__/BackgroundProcessManager-test.ts
> +			const { resolve, onTerminate } = manager.add();
I had a few specific cases in mind to refactor to look more like this, but didn't get that far into tinkering with a refactor. We can iterate on this down the line too. I'd be happy to chat about better patterns.

2022-10-21 22:53 UTC, merged