feat(data): update Circle CI config to use new CPK integ tests / samples
aws-amplify/amplify-js pull request #10466
Opened 2022-10-12 18:14 UTC by david-mcafee

#### Description of changes

The current CPK integ tests can take a long time to execute (15 min or so). I've split the integ tests / samples to allow for concurrent test execution.
[Samples PR](https://github.com/aws-amplify/amplify-js-samples-staging/pull/428)

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-12 19:05 UTC, iartemiev requested changes

2022-10-12 19:05 UTC, iartemiev commented on .circleci/config.yml
> +          spec: custom-pk
We need to pass in the new spec filenames here and for the other 2. 
```suggestion
          spec: custom-pk-unconnected-models
```

2022-10-12 20:12 UTC, iartemiev approved these changes
LGTM 👍🏻

2022-10-13 14:35 UTC, dpilch submitted a review, later dismissed

2022-10-13 20:37 UTC, dpilch approved these changes

2022-10-13 20:45 UTC, iartemiev approved these changes

2022-10-14 04:43 UTC, merged