feature(@aws-amplify/datastore): lazy loading and nested/related-model predicates
aws-amplify/amplify-js pull request #10477
Opened 2022-10-14 17:38 UTC by svidgen

#### Description of changes

Expands functionality of has-one, has-many, and belongs-to model property handling in DataStore.

**Adds lazy loadings.**

1. Required has-one and belongs-to properties will now return a `Promise<RelatedModel>`.
2. Optional has-one and belongs-to properties will now return a `Promise<RelatedModel | undefined>`.
3. Has-many properties will return an `AsyncCollection<RelatedModel>`.

Model initialization is unchanged.

Previously, has-only and belongs-to related properties were eagerly loaded *partially*. This will not occur at all anymore. Only the lazy-loaded promises for those properties will work going forwarded.

**Refactors the predicates interface, adding support for "nested"/related-model queries.**

⚠️ V4 predicate grammar will no longer work! ⚠️ 

`p => p.field('eq', 'value')` style predicates are obsolete as this PR / aws-amplify V5. 

1. Predicate grammar redesigned across the board per #8901 (Option A)
2. All local query-type operations support fully nested predicates
3. Mutation operations and sync expression support new grammar, but without nesting

#### Example

Given a simple schema:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  body: String!
  blog: Blog! @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model {
  id: ID!
  message: String!
  post: Post! @belongsTo
}
```

As of this PR, assuming a populated database, you will be able to navigate the data like so:

```js
// basic property traversal
const blog = await DataStore.query(Blog, myBlogId);
const posts = await blog.posts.toArray();
const commentsOfFirstHit = await posts[0].comments.toArray();

// using nested predicates
const blogsWithSpammyComments = await DataStore.query(Blog,
  blog => blog.posts.comments.message.contains('ACT NOW!')
);
```

#### Description of how you validated changes

1. Manuel testing with test apps
2. @dpilch Updated integ tests: https://github.com/aws-amplify/amplify-js-samples-staging/pull/435
3. @dpilch Added integ tests: https://github.com/aws-amplify/amplify-js-samples-staging/pull/439
4. Significantly expanded test coverage, hitting all known model relationship types; predicate tests on all operators, etc.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-25 21:49 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> +	test.skip('error on schema not initialized on clear', async () => {
TODO: Re-include this. I'm pretty sure this requirement is supposed to remain.

2022-10-25 21:50 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> +			// buuut, it looks like we have been allowing `null`s in. and so we must continue ... ?
Or rather, JS customers might explicitly set to `null`?

2022-10-25 21:51 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> -			);
Not a changed requirement; just a duplicate test.

2022-10-25 21:52 UTC, svidgen commented on packages/datastore/__tests__/IndexedDBAdapter.test.ts
> +			 */
I think this was me testing the types. 😅 To remove.

2022-10-25 21:53 UTC, svidgen commented on packages/datastore/__tests__/IndexedDBAdapter.test.ts
> +			 */
I think this was me testing the types. 😅 To remove.

2022-10-25 21:58 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +		it.skip('should produce a mutation for a nested BELONGS_TO insert', async () => {
TODO: Circle back, this is not supported. Update test to expect an error instead.

2022-10-25 21:59 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +					// }
Cruft.

2022-10-25 21:59 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +		for (const modelName of Object.keys(schema.models)) {
TODO: Add a high level note about what's going on here.

2022-10-25 22:02 UTC, svidgen commented on packages/datastore/__tests__/connectivityHandling.test.ts
> +		test('sends conditional model deletes to the cloud with valid conditions', async () => {
Woops! This was used to see and visually confirm the fix for gql conditions; but the conditions aren't actually implemented yet in the fake appsync client.

TODO: Implement the behavior or add a note and skip the test for now. Else, the test does nothing. Worst case here, the integ tests that caught the bug originally will catch it again. Suboptimal DX for us, but base level of safety exists.

2022-10-25 22:12 UTC, svidgen commented on packages/datastore/__tests__/helpers.ts
> +	}
TODO: Yup. Implement or add a note for now.

2022-10-25 22:14 UTC, svidgen commented on packages/datastore/__tests__/helpers.ts
> +			LegacyJSONBlog: {
TODO: Add a note on Legacy schema JSON to **not** overwrite with updated codegen!!!

2022-10-25 22:24 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +const getModelPKFieldName = (
TODO: Revisit. Import helper method from CPK utils that provide the right canonical result.

2022-10-25 22:25 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	}
TODO: Re-condense. I think this was expanded to inject logging lines for troubleshooting.

2022-10-25 22:25 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +const buildSeedPredicate = <T extends PersistentModel>(
TODO: Docstring.

2022-10-25 22:32 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	for (const field in modelDefinition.fields) {
Add comment/docstring to explain the block that follows and/or break off into a function.

2022-10-25 22:35 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	 * Accumulator for backgrouns things that can **and MUST** be called when
😕

2022-10-25 22:36 UTC, svidgen commented on packages/datastore/src/predicates/index.ts
> +	static createGroupFromExisting<T extends PersistentModel>(
TODO: Docstring.

2022-10-25 22:37 UTC, svidgen commented on packages/datastore/src/predicates/index.ts
> +	static transformGraphQLtoPredicateAST(gql: any) {
TODO: Docstring.

2022-10-25 22:37 UTC, svidgen commented on packages/datastore/src/predicates/index.ts
> +	static createFromAST(
TODO: Docstring.

2022-10-25 22:38 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +	__query: GroupCondition;
Here and throughout, these `__*` properties are marked `@private` for now; but as soon as time allows, these should just be stuffed in a `WeakMap` or something.

2022-10-25 22:39 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +	private matchingIndex(
Docstring.

Also: Note sure this is accurately picking up indexes as of CPK. Revisit.

2022-10-25 22:52 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +						// TODO: custom PK
TODO: Gotta revisit this. Clearly not being hit since CPK changed indexing patterns, or this wouldn't work.

2022-10-25 22:54 UTC, svidgen commented on packages/datastore/CHANGELOG.md
> -
Remove file from diff.

2022-10-25 22:55 UTC, svidgen commented on packages/datastore/.gitignore
> +tsconfig.json
Wait what? Nope. I'm pretty sure we want this included now. In fact, the file is in the diff.

What are you doing, git?!

2022-10-25 22:55 UTC, svidgen commented on packages/datastore/__tests__/AsyncStorage.ts
> +	// jest.resetModules();
TODO: 👀

2022-10-26 02:02 UTC, david-mcafee requested changes
Not done reviewing, but figured I'd provide some preliminary feedback.

2022-10-26 03:06 UTC, svidgen commented on packages/datastore/__tests__/AsyncStorage.ts
> +	// jest.resetModules();
Adding a comment for this. I think the tests in this file have gone a little stale. But, there's good coverage for AsyncStorageAdapter in `AsyncStorageAdapter.test`, so I'm not diving on this right now.

2022-10-26 19:29 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +			)(buildSeedPredicate(modelConstructor) as any).__query;
Yeah. So, I'm happy to look for opportunities to clean up the `as any`'s. But, in general, a lot of them are the downstream result of a quick pass of bumping up the TS strictness so that our exported typemaps are correct.

Same with all the new `!`'s and `?`'s all over. The intent of the strictification bump is not to comprehensively fix all of our types, but just to make our exported `d.ts` correct. Happy to chat about this if needed.

2022-10-26 19:45 UTC, svidgen commented on packages/datastore/__tests__/AsyncStorage.ts
> +	// skipping in this PR. will re-enable as part of cascading deletes work
Oh, yes. It should. The previous tests also check delete behavior. I'll take a look at this.

2022-10-26 19:48 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	 * Accumulator for backgrouns things that can **and MUST** be called when
```suggestion
	 * Accumulator for background things that can **and MUST** be called when
```

2022-10-26 19:49 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +									pkField: extractPrimaryKeyFieldNames(modelDefinition),
Yep. Will need to change throughout.

2022-10-26 19:52 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
>  		relations: RelationType[],
To continue supporting cascading delete. No change to the requirements/expected behavior here.

2022-10-26 20:11 UTC, svidgen commented on packages/datastore/__tests__/AsyncStorage.ts
> +	// skipping in this PR. will re-enable as part of cascading deletes work
It looks like this test, along with its counterpart in `indexeddb.test.ts`, each work in isolation. But, they conflicting in ways that aren't immediately obvious to me with the other tests the their respective suites. (Other than the obvious manner in which these adapter test files are all initialized with common instances.)

Delete behavior appears to be covered in various places. So, what I think I'll do is bolster deletion tests in `commonAdapterTests.ts` to cover all adapters &mdash; and where the test isolation and mocking is a little more mature.

2022-10-27 17:21 UTC, svidgen commented on packages/datastore/__tests__/AsyncStorage.ts
> -	test('delete cascade', async () => {
Conflicts with other tests after rejiggering. Adding cascading delete tests to common adapter tests to compensate.

2022-10-27 17:22 UTC, svidgen commented on packages/datastore/__tests__/connectivityHandling.test.ts
> +		test('sends conditional model deletes to the cloud with valid conditions', async () => {
Addressed.

2022-10-27 17:23 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +		}
@david-mcafee In theory, we can remove this filter once SQLiteAdapter supports CPK.

2022-10-27 17:27 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +							// skip for now. needs to look like BELONGS_TO, but inverted save orders i think.
Will revisit prior to seeking final approval. But, the error here is unrelated to the actual lazy loading or nested predicate behavior. This was removed because the structure of the tests began violating the new integrity checks. Specifically, the tests were trying to add parent/child entities in the wrong order for some HAS_ONE relationships based on the model crawl.

2022-10-27 17:30 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +			Object.values(model.fields).forEach(field => {
This is ancient, as far as this feature is concerned. This may actually be redundant at this point. But, I'll dig and either add a comment or remove it.

2022-10-27 17:37 UTC, svidgen commented on packages/datastore/__tests__/commonAdapterTests.ts
> +							// skip for now. needs to look like BELONGS_TO, but inverted save orders i think.
It looks like I actually fixed this in my FK fields filtering update. Crawled HAS_ONE tests are passing when re-enabled.

2022-10-27 19:02 UTC, david-mcafee approved these changes
Discussed offline - TODOs, comments, and refactoring will happen in subsequent PRs.

2022-10-27 20:59 UTC, stocaaro reviewed
Have a meeting break. Posting notes so far, will be resuming from `pridcates/next.ts` when my meetings are over.

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/__tests__/indexeddb.test.ts
> +	test.skip('delete 1:1 function', async () => {
?

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/__tests__/subscription.test.ts
> +	test.only('error handler once after all retires have failed', done => {
Re: https://jestjs.io/docs/api#testonlyname-fn-timeout

> Usually you wouldn't check code using test.only 

?

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/src/datastore/datastore.ts
> +	// construction.
Super hate this in library code. As noted in chat, this is making promises into the future that your code isn't structured to keep. There should be a TODO here to come back through to clean this up at minimum.

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/src/datastore/datastore.ts
> +						).__query.toStoragePredicate<T>(pkPredicate);
What does the `__` signal here?

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/src/datastore/datastore.ts
> +			)(buildSeedPredicate(modelConstructor) as any).__query;
Sure. Making an implicit `any` explicit. Is there backlog work to circle back to improve upon this?

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/src/predicates/index.ts
> +]);
I think this is duplicated in the tests. Might be worth capturing as something exported to the tests to share the list / ensure changes are auto-hydrated. (Not now, just a thing this makes me think).

2022-10-27 20:59 UTC, stocaaro commented on packages/datastore/src/predicates/next.ts
> +];
Repeat of the set above?

2022-10-27 21:14 UTC, svidgen commented on packages/datastore/__tests__/subscription.test.ts
> +	test.only('error handler once after all retires have failed', done => {
An oversight, thank-you for catching it! I didn't see my test numbers numbers go down b/c it's the only test in the scope, so it had no effect.

2022-10-27 21:14 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +						).__query.toStoragePredicate<T>(pkPredicate);
Internal. This properties are marked `@private`. TODO's in the backlog to hide then properly.

2022-10-27 21:17 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +];
It would seem so!

2022-10-27 21:28 UTC, svidgen commented on packages/datastore/__tests__/indexeddb.test.ts
> +	test.skip('delete 1:1 function', async () => {
I'll get a good rejiggering of this in shortly. As-written, it was somehow conflicting with the other tests in the file. But, I think I see the intent and will ensure the relationship cascade deletion is respected, with no collateral deletions.

2022-10-27 21:30 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +	// construction.
Ack. I'll also be adding an internal task for a bunch of refactoring that was out of scope of LL.

2022-10-27 21:39 UTC, stocaaro commented on packages/pubsub/__tests__/AWSAppSyncRealTimeProvider.ts
> +});
This  duplicates two of the tests now captures in `AWSAppSyncRealTimeProvider.test.ts`. Seems like it can go.

2022-10-27 21:42 UTC, stocaaro approved these changes
Kill the PS test file and I'm good to go. Most of the confidence I lack is something all the good test work covers or will only be caught with manual verification which will be made easier by getting this onto the next tag.

2022-10-27 21:42 UTC, svidgen commented on packages/datastore/src/predicates/index.ts
> +]);
I'll have to think about this one. There are times when I want lists in lib and test code to remain in sync automatically. Other times I want the explicit redundancy, so mutations to the list are flagged and acknowledged.

2022-10-28 20:09 UTC, merged