Updated misconfigured dispatch
aws-amplify/amplify-js pull request #10511
Opened 2022-10-20 20:25 UTC by MatthewChon

#### Description of changes

Change verifytotptoken() to emit an 'verify' event instead of 'signIn'.
Added the case 'verify' to the listener.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/9750

#### Description of how you validated changes
i reproduced the issue and from there, I reran the application with the modified changes.
The hub now console logs 'verify' instead of 'signIn'.

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-16 20:48 UTC, AllanZhengYP reviewed
This change looks good to me. But I'm not sure whether stop emitting `signIn` is a breaking change for those expecting this event. I'd defer to other approvers.

2022-11-29 18:17 UTC, MatthewChon commented
Ok, that sounds good!

2022-12-15 17:35 UTC, elorzafe approved these changes
LGTM thanks @MatthewChon 🎖️

2022-12-15 17:42 UTC, AllanZhengYP submitted a review, later dismissed

2022-12-15 17:55 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +					dispatchAuthEvent('signIn', user, ``);
@MatthewChon Thanks for this PR. Why would we not continue to log the message `A user ${user.getUsername()} has been signed in` when emitting the signIn event?

2022-12-15 17:56 UTC, haverchuck requested changes
@MatthewChon Please see inline [comment](https://github.com/aws-amplify/amplify-js/pull/10511/files#r1049975351).

2022-12-15 19:44 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +					dispatchAuthEvent('signIn', user, ``);
```suggestion
					dispatchAuthEvent('signIn', user, `A user ${user.getUsername()} has been signed in`);
```

2022-12-15 19:45 UTC, haverchuck approved these changes

2022-12-15 20:17 UTC, elorzafe approved these changes

2022-12-15 20:18 UTC, merged

2023-07-02 12:28 UTC, cnorthfield commented
Could really do with the signin event _not_ being emitted 🙈