ci(datastore): add integ tests for lazy loading
aws-amplify/amplify-js pull request #10529
Opened 2022-10-25 17:19 UTC by dpilch

#### Description of changes

Add integration tests for lazy loading.

#### Issue #, if available

N/A

#### Description of how you validated changes

Run integ tests

#### Checklist

- [x] PR description included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-28 20:55 UTC, svidgen requested changes

2022-10-28 20:55 UTC, svidgen commented on .circleci/config.yml
> +  integ_react_datastore_related_models:
I think this is missing from workflow jobs and deploy requirements as well. Expected to see an edit around lines 1702 and 1751.

2022-10-28 21:59 UTC, svidgen approved these changes

2022-10-31 16:40 UTC, elorzafe approved these changes
Looks good

Thanks @dpilch 👍

2022-10-31 16:42 UTC, jimblanc approved these changes

2022-10-31 17:05 UTC, merged