feat(auth): Signup function rewrite, adds new types for auth
aws-amplify/amplify-js pull request #10606
Opened 2022-11-03 17:35 UTC by helgabalashova

#### Description of changes
`Auth.signUp` function rewrite. Adds new types for Auth and HubEvents. Work in progress.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-09 19:17 UTC, AllanZhengYP reviewed
This is a solid start! Thank you for putting this together!

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			this.signInAfterUserConfirmed(initiateAuthCommand, username);
Missing `await`? Same as other 2 branches.

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private handleAutoSignIn<UserAttributeKey extends AuthUserAttributeKey>(
This should an async function.

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		autoSignInPollingIntervalId?: ReturnType<typeof setInterval>
This function should not include logics specific to `handleLinkAutoSignIn` or `handleCodeAutoSignIn`. I'd remove them and move the individual code for cleaning resources back to the 2 functions.

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			}
These can be done outside of this function.

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +}
Need to confirm but I think we use `Record<string, string>` type in other places in codebase(newer part). Same as the other places in this file.

2022-11-09 19:17 UTC, AllanZhengYP commented on packages/auth/src/types/hubEvents.ts
> +import { AuthError } from "../Errors";
Not sure why this file is using double quotes and lint is not complain about it.

2022-11-10 18:42 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		autoSignInPollingIntervalId?: ReturnType<typeof setInterval>
I removed code logic from here, but I don't see how link logic can be removed. We only remove listener if sign in succeeded. With link verification, I can't know if sign in succeeded within handle function. That's why it is being removed within this function once we know user signed in.

2022-11-10 23:25 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			return error;
Throw error?

2022-11-10 23:25 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			}
I don't think I can find where `'amplify_polling_started'` is set. This if block can be moved below line 277. 

Also a super nit: I notice `'amplify-auto-sign-in'` is using the kabab casing whereas this is snake casing.

2022-11-10 23:25 UTC, AllanZhengYP commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			logger.error(error);
Is it intended to swallow the error?

2022-11-11 20:49 UTC, haverchuck commented on package.json
> +		"@aws-sdk/client-cognito-identity-provider": "^3.198.0"
Yes, we are using the signup command.

2022-11-11 20:50 UTC, haverchuck commented on packages/auth/src/Errors.ts
> +	underlyingException?: Error;
These will probably be changed a bit based on current API proposal. No need to modify this PR right now, though.

2022-11-11 21:02 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private autoSignInInitiated = false;
`autoSignInInitiated` will most likely be moved to a state machine. It's ok to have this here for now.

2022-11-11 21:05 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		const clientId = this._config.userPoolId ?? '';
Can we create service for userpool SDK calls? We can then make the client id part of the service constructor, and don't have to handle it in each individual API.

2022-11-11 21:05 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			this.rejectAuthError(authErrorMessages.emptyUsername);
These will change when error handling proposal is ironed out.

2022-11-11 21:06 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		};
Creating the command input can be moved to a service file.

2022-11-11 21:07 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput = await this.client.send(signUpCommand);
Creating the command and sending to the client can be part of the userpool service.

2022-11-11 21:08 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private async handleAutoSignIn<UserAttributeKey extends AuthUserAttributeKey>(
All of this autoSignIn stuff can be moved to the state machine once it's ready, but it's fine to have it here for now.

2022-11-11 21:10 UTC, haverchuck commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export type AuthPluginOptions = Record<string, any>;
Can create another types  file at the category level? So things like AuthPluginOptions would exist there, but Cognito-specific types would remain here.

2022-11-11 21:12 UTC, haverchuck requested changes
Left some comments, with three over-arching themes:
1. We can create a UserPoolService that is called from the API to make SDK calls. That way we leave the door open for better tree shaking opportunities, cleaner separation of concerns, and the ability to do things like set the clientId only once.
2. Take a look at the error handling proposal in the API doc.
3. We can create a separate types file for category-level types (I think maybe we talked about this but I don't remember the outcome).

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Auth.ts
> +	signUp<PluginOptions extends AuthPluginOptions = CognitoSignUpOptions>(req: SignUpRequest<CognitoUserAttributeKey,PluginOptions>):Promise<AuthSignUpResult<CognitoUserAttributeKey>> {
I think this API goes to the Cognito Provider

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			this.rejectAuthError(authErrorMessages.emptyUsername);
Yes, the error handling is still being worked on

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private async handleAutoSignIn<UserAttributeKey extends AuthUserAttributeKey>(
I think it's not necessary using a generic function here, we can pass directly the **CognitoUserAttributeKey** instead 

```
AuthSignUpResult<CognitoUserAttributeKey>
```

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private async signInAfterUserConfirmed<UserAttributeKey extends AuthUserAttributeKey>(
same as above

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private mapChallengeNames(challengeName: string): AuthSignInStep {
I think this method should be part of utils, as it can used by other APIs as well

2022-11-11 21:35 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private mapChallengeNames(challengeName: string): AuthSignInStep {
And also maybe changing the **challengeName** param type  to **ChallengeNameType**

2022-11-11 21:35 UTC, israx commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export type AuthPluginOptions = Record<string, any>;
I think we need to follow a similar folder structure for types as the other libraries, iOS is a good point of reference

2022-11-11 21:35 UTC, israx commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export enum AuthProvider {
This AuthProvider got updated

2022-11-11 21:35 UTC, israx commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export type SignOutResult = {
Now the the SignOut result has a better type definition

2022-11-11 21:35 UTC, israx commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export type ResetPasswordResult = {
same as above

2022-11-11 21:35 UTC, israx commented on packages/auth/src/types/hubEvents.ts
> +export const enum AuthHubEvent {
Not sure exactly were this should be located at. @haverchuck Do you think it should be part of the category or cognito specific ?

2022-11-11 21:37 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		if (!this._config?.userPoolId) {
I think here's a good place to define a generic assertion guard to check for plugin options

2022-11-14 19:29 UTC, AllanZhengYP commented on package.json
> +		"@aws-sdk/client-cognito-identity-provider": "^3.198.0"
Should this be in the auth package's package.json?

2022-12-21 22:16 UTC, closed without merging