fix(datastore): disconnected has one
aws-amplify/amplify-js pull request #10608
Opened 2022-11-03 20:08 UTC by iartemiev

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-03 20:10 UTC, dpilch approved these changes

2022-11-03 20:27 UTC, svidgen requested changes
Add tests please!

2022-11-03 20:44 UTC, david-mcafee commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> -							);
Assuming this also will need to be fixed in the async storage adapter?

2022-11-04 13:30 UTC, iartemiev commented
Added tests and migrated changes to a PR against v5: https://github.com/aws-amplify/amplify-js/pull/10613

Closing

2022-11-04 13:30 UTC, closed without merging