docs: V5 breaking change README guidance
aws-amplify/amplify-js pull request #10649
Opened 2022-11-09 16:36 UTC by stocaaro

#### Description of changes
docs: V5 breaking change README guidance

Look at [the commit on my branch](https://github.com/stocaaro/amplify-js/tree/readme-update#notice) to see the markdown rendered.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-09 16:54 UTC, jimblanc reviewed
Looks good! Few random call-outs:

- JS class export has been removed: https://github.com/aws-amplify/amplify-js/pull/10528
- `Amplify.Auth`, `Amplify.Cache`, and `Amplify.ServiceWorker` instances have been removed: https://github.com/aws-amplify/amplify-js/pull/10562
- Should we mention the legacy UI packages (v1.x) have all been removed and point customers to the UI docs?

2022-11-09 22:51 UTC, stocaaro commented
From Jim's comment, I caught up with Francisco and made updates.

2022-11-09 22:57 UTC, jimblanc submitted a review, later dismissed
Looks good!

2022-11-09 23:42 UTC, AllanZhengYP commented on README.md
> +  - ```diff
Nit: Remove the bulletpoints before the diff? Same to all the other new diffs in this change

2022-11-09 23:57 UTC, stocaaro commented on README.md
> +  - ```diff
Good call. Removed

2022-11-10 18:12 UTC, abdallahshaban557 requested changes
left comments

2022-11-10 18:12 UTC, abdallahshaban557 commented on README.md
> +  + import { Analytics } from '@aws-amplify/analytics';
Is this using the scoped packages rather than the singleton package? if so - should we recommend using the singleton package?

2022-11-10 18:12 UTC, abdallahshaban557 commented on README.md
> +To get started pick your platform from our [**Getting Started** home page](https://docs.amplify.aws/start/?sc_icampaign=start&sc_ichannel=docs-home)
On the getting started section - can we just have 1 url shown, and then mention that we have getting started guides for all of our currently available frameworks in the docs site.

2022-11-10 18:12 UTC, abdallahshaban557 commented on README.md
>  AWS Amplify provides a declarative and easy-to-use interface across different categories of cloud operations. AWS Amplify goes well with any JavaScript based frontend workflow and React Native for mo
Can we change this to:

AWS Amplify Javascript provides a declarative and easy-to-use interface across different use cases and cloud operations. Amplify Javascript is supported for common Javascript web libraries and frameworks, in addition to React Native. 

With Amplify Javascript you can build Authentication experiences, Data integrations with backend database, Storing and retrieving Media, and more!

2022-11-10 18:25 UTC, stocaaro commented on README.md
> +  + import { Analytics } from '@aws-amplify/analytics';
Since our existing customers may have direct package imports, we want to demonstrate the direct upgrade path.  I'm adding `// or better` alt lines to direct customer to prefer using the root package.

2022-11-10 18:25 UTC, stocaaro commented on README.md
>  AWS Amplify provides a declarative and easy-to-use interface across different categories of cloud operations. AWS Amplify goes well with any JavaScript based frontend workflow and React Native for mo
The recommended change seems fine, but unrelated the the v5 upgrade notes. Can you tackle this in a separate PR?

2022-11-10 18:30 UTC, abdallahshaban557 commented on README.md
>  AWS Amplify provides a declarative and easy-to-use interface across different categories of cloud operations. AWS Amplify goes well with any JavaScript based frontend workflow and React Native for mo
Yes, I can!

2022-11-10 19:45 UTC, abdallahshaban557 commented on README.md
> +  + import { Analytics } from '@aws-amplify/analytics';
got it - thank you!

2022-11-10 22:22 UTC, abdallahshaban557 approved these changes
LGTM!

2022-11-11 00:47 UTC, jimblanc approved these changes

2022-11-11 22:42 UTC, AllanZhengYP approved these changes

2022-11-14 17:09 UTC, merged