fix(aws-amplify/auth): debouncing get user session calls
aws-amplify/amplify-js pull request #10654
Opened 2022-11-09 20:45 UTC by AllanZhengYP

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-14 17:26 UTC, jimblanc reviewed
Looks good, small question about de-bounce logic. Appreciate the detailed PR write-up!

2022-11-14 17:26 UTC, jimblanc commented on packages/auth/src/Auth.ts
> +		// This solution asumes users will always call this function with the same CognitoUser instance.
I realize original PR had this also, but is this a safe assumption to make? E.g. if `user.getSession` takes longer than normal and in the mean time a different user logs in, would this method return the session from the original user?

Also, small typo `asumes`

2022-11-14 18:38 UTC, AllanZhengYP commented on packages/auth/src/Auth.ts
> +		// This solution asumes users will always call this function with the same CognitoUser instance.
Confirmed with @elorzafe this is low risk, but I'd like him to chime-in.

2022-11-14 18:51 UTC, jimblanc approved these changes

2022-11-15 17:58 UTC, elorzafe requested changes
Just minor comments on tests but overall looks good!

Thanks @AllanZhengYP 🌮

2022-11-15 17:58 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +				fail('expect promsie to reject');
nit
```suggestion
				fail('expect promise to reject');
```

2022-11-15 17:58 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			// expect.assertions(2);
Should we enable this?

2022-11-15 17:58 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			const auth = new Auth(authOptions);
Is would add here `expect.assertions`

2022-11-15 17:58 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +		test('debouncer happy case', async () => {
I would add `expect.assertions`

2022-11-15 17:58 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +		// This solution asumes users will always call this function with the same CognitoUser instance.
is a good concern @jimblanc this class could potenially have a RC on this, do you think we could add in a separate PR a mechanism to use this debouncer for other operations as well?

2022-11-15 21:08 UTC, elorzafe approved these changes
Looks good to me

Thanks @AllanZhengYP 🚢

2022-11-15 21:22 UTC, jimblanc approved these changes

2022-11-16 00:39 UTC, merged