feat(auth): Adds new types for new Auth API definition
aws-amplify/amplify-js pull request #10690
Opened 2022-11-18 22:08 UTC by helgabalashova

#### Description of changes
PR adds new types required for SignUp and Reset Password functions rewrite.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-19 00:55 UTC, elorzafe commented
Maybe we can add tests for the types to validate those are not changing, on other categories like DataStore they are doing something like [this](https://github.com/aws-amplify/amplify-js/blob/a85171384db4bca202bb5cb5f832a8e319ec89d4/packages/datastore/__tests__/custom-pk-typings/model-init-mutable-model-typings/custom-identifier.test.tsx)

@helgabalashova Can you take a look? I think is good to have tests on the types so we don't break it 

What do you think @israx

2022-11-21 17:06 UTC, israx commented
> Maybe we can add tests for the types to validate those are not changing, on other categories like DataStore they are doing something like [this](https://github.com/aws-amplify/amplify-js/blob/a85171384db4bca202bb5cb5f832a8e319ec89d4/packages/datastore/__tests__/custom-pk-typings/model-init-mutable-model-typings/custom-identifier.test.tsx)
> 
> @helgabalashova Can you take a look? I think is good to have tests on the types so we don't break it
> 
> What do you think @israx

I think type tests are a good idea. We can implement them for sure

2022-11-21 17:09 UTC, israx commented
I think is a good time to start defining a folder structure for types, we could go for one of these [two](https://master.d1b62s5gslus8x.amplifyapp.com/) options or any other suggestions ?

2022-11-22 21:56 UTC, israx requested changes

2022-11-22 21:56 UTC, israx commented on packages/auth/src/types/models/authCodeDeliveryDetails.ts
> +export enum DeliveryMedium {
should be `const `enum

2022-11-22 21:56 UTC, israx commented on packages/auth/src/types/models/authUserAttributeKey.ts
> +type AuthStandardAttributeKey =
this should be exported as well, to be used for the `CognitoUserAttributeKey`

2022-11-22 22:50 UTC, helgabalashova commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export enum DeliveryMedium {
this file doesn't exists anymore

2022-11-22 22:50 UTC, helgabalashova commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +	pluginOptions?: PluginOptions;
you looked at outdated file. it is not there anymore and in the new file, it is fixed

2022-11-22 22:51 UTC, helgabalashova commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +	additionalInfo?: { [key: string]: string };
same thing as above

2022-11-22 22:51 UTC, helgabalashova commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export enum AuthSignInStep {
same thing as above

2022-11-22 22:52 UTC, helgabalashova commented on packages/auth/src/types/AmazonCognitoProvider.ts
> +export type SignOutResult = {
outdated file. this PR doesn't contain this type at all

2022-11-23 17:10 UTC, jimblanc reviewed
Some small comments below, but looking good!

2022-11-23 17:10 UTC, jimblanc commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts
> +	oauth?: any;
Okay for now, but possible to define a type for this?

2022-11-23 17:10 UTC, jimblanc commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts
> +	clientMetaData?: any;
Should this be typed as `ClientMetadata`?

2022-11-23 17:10 UTC, jimblanc commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/index.ts
> +
Nit: Extra new-line

2022-11-23 17:10 UTC, jimblanc commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authFlowType.ts
> +export type AuthFlowType =
I think we need to add the new copyright header to all of these files. Also each file should end in a newline to play nicely with the terminal.

2022-11-23 17:10 UTC, jimblanc commented on packages/auth/src/types/models/authCodeDeliveryDetails.ts
> +
Nit: Extra newline

2022-11-23 17:53 UTC, helgabalashova commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts
> +	oauth?: any;
@israx Do we have a type for this?

2022-11-23 18:24 UTC, jimblanc approved these changes

2022-11-23 18:43 UTC, AllanZhengYP reviewed
Are we settled exactly 1 interface per file? Some files are really small, like those in `types/aws-plugins/cognito-plugin/types/options/index.ts`. IMO put them together can make it easier to navigate.

2022-11-23 18:43 UTC, AllanZhengYP commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/index.ts
> +	ICognitoStorage,
I'm not a big fan of `I` prefix for interface. Other interfaces doesn't have this prefix either. Should we drop this prefix?

2022-11-23 20:01 UTC, haverchuck commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts
> +	oauth?: any;
If we don't have a type defined for oauth in our current repo, then I believe it would be something like this:

```
type OAuth = {
  domain: string,
  scope: string[],
  redirectSignIn: string,
  redirectSignOut: string,
  responseType: OAuthResponseType
}

enum OAuthResponseType {
  Code = "code",
  Implicit = "implicit"
}

2022-11-23 20:02 UTC, haverchuck commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts
> +	oauth?: any;
redirects can actually have multiple values, but I think they are concatenated strings in the CLI due to how they are sent to cognito cloudformation...

2022-11-23 20:04 UTC, haverchuck requested changes
See inline comment about OAuth type.

2022-11-28 18:44 UTC, merged