test(integ): test UMD artifacts
aws-amplify/amplify-js pull request #10704
Opened 2022-11-22 22:41 UTC by AllanZhengYP

#### Description of changes

Amplify JS publishes UMD artifacts to CDN distributions. However, these artifacts lack integration tests. This change add spot integration test to `auth` and `geo` categories.

#### Issue #, if available

Associated with: https://github.com/aws-amplify/amplify-js-samples-staging/pull/477

#### Description of how you validated changes
[Integ test run](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/16925/workflows/6731c7da-879c-4797-8591-d5f9e548a2df)

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-23 20:52 UTC, stocaaro submitted a review, later dismissed

2022-11-23 22:40 UTC, elorzafe requested changes
I would not block the pipeline for now until we release the UMD artifacts from here.

2022-11-23 22:40 UTC, elorzafe commented on .circleci/config.yml
> +            - integ_javascript_auth
I will not block the pipeline in case is failing, I would like to run this on a separate job so we can add it as part of `releases` branch, what do you think?

2022-11-23 22:40 UTC, elorzafe commented on .circleci/config.yml
> +            - integ_javascript_geo
I would not block the pipeline in this case. Specially since we are not launching it from this branch for now

2022-11-23 23:52 UTC, elorzafe commented on .circleci/config.yml
> +            # - integ_javascript_auth
you can add a comment for enabling this when is automated cdn deployment

2022-11-29 00:03 UTC, AllanZhengYP commented
Confirmed failed new CDN test won't block the release: [CircleCI execution example](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/16976/workflows/a239d070-1c24-4ef7-b905-fa4726ea47f8)

2022-11-29 00:06 UTC, elorzafe approved these changes
Looks good

Thanks @AllanZhengYP 🎖️

2022-11-29 00:40 UTC, Samaritan1011001 approved these changes

2022-11-29 00:46 UTC, merged