fix(amazon-cognito-identity-js): specify the right userAgent/deviceName when remembering devices (React Native)
aws-amplify/amplify-js pull request #10724
Opened 2022-11-29 20:52 UTC by Samaritan1011001

#### Description of changes

API: `Auth.rememberDevice` & `Auth.listDevices`
Existing code only depended on the `navigator !== undefined` to check if it's the target device is a browser or not. 
React Native [initializes](https://github.com/facebook/react-native/blob/main/Libraries/Core/setUpNavigator.js#L15-L18) this `navigator` object leaving the above check invalid and inaccurate. 
Here we make use of [polyfilled](https://github.com/facebook/react-native/blob/main/Libraries/Core/setUpNavigator.js#L21) `navigator.product` to determine if it's ReactNative and update the device name accordingly

#### Issue #, if available

#### Description of how you validated changes
Ran a sample React Native app containing the remember and list devices feature turned on. List Devices API returned the device with the name 'react-native'

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-29 22:37 UTC, elorzafe commented on packages/amazon-cognito-identity-js/src/CognitoUser.js
> +const userAgent = isNavigatorAvailable ? specificUserAgent : 'nodejs';
Why not use `Platform` instead.

2022-11-29 22:39 UTC, elorzafe requested changes

2022-11-29 22:39 UTC, elorzafe commented on packages/amazon-cognito-identity-js/src/CognitoUser.js
> +const userAgent = isNavigatorAvailable ? specificUserAgent : 'nodejs';
And we might to refactor a little bit to use native file to make it safer? what do you think?

2022-11-30 21:38 UTC, elorzafe requested changes
Thanks @Samaritan1011001 

Need to add a check that `navigator` is not `undefined`

2022-11-30 21:38 UTC, elorzafe commented on packages/amazon-cognito-identity-js/src/CognitoUser.js
> +	: navigator.userAgent;
This could be a bug in case navigator is `undefined`

2022-11-30 22:27 UTC, Samaritan1011001 commented on packages/amazon-cognito-identity-js/src/CognitoUser.js
> +	: navigator.userAgent;
Thanks for catching that. I corrected it.

2022-11-30 23:27 UTC, elorzafe submitted a review, later dismissed
Looks good!

Thanks @Samaritan1011001 🎖️

2022-12-01 00:09 UTC, jimblanc approved these changes
Looks good!

2022-12-15 22:02 UTC, AllanZhengYP submitted a review, later dismissed

2022-12-15 22:22 UTC, elorzafe commented on .circleci/config.yml
> +  integ_rn_ios_device_tracking:
You need to add this also on the workflow section https://github.com/aws-amplify/amplify-js/blob/8a50266c97ecded674df5e6cf4004ba8e6a733fc/.circleci/config.yml#L1473 and also required for deploy on https://github.com/aws-amplify/amplify-js/blob/8a50266c97ecded674df5e6cf4004ba8e6a733fc/.circleci/config.yml#L1972

2022-12-15 22:28 UTC, elorzafe approved these changes

2022-12-15 22:38 UTC, AllanZhengYP approved these changes

2022-12-15 22:53 UTC, wlee221 approved these changes

2022-12-15 22:56 UTC, merged