feat(auth): adds hub events to updateUserAttributes api
aws-amplify/amplify-js pull request #10731
Opened 2022-12-01 23:10 UTC by helgabalashova

#### Description of changes
adds hub event to `Auth.updateUserAttributes` to determine if verification of the attribute is required

#### Issue #, if available
#9134 

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-02 14:54 UTC, israx requested changes

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +		attributes: object,
`object` is a JS type that can be either an `array` , `function` and `map`. I think is better to use a more constrained type like `Record<string, string>`

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +	): object {
same above

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +		Object.keys(attributes).map(key => {
I think using `forEach` is the best option as `map` will return a new array

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +				const codeDeliveryDetails = this.findCodeDeliveryDetails(key, codeDeliveryDetailsList);
I thinks there's no need to create another function, using `find` will do the job. 

```
const codeDeliveryDetails = codeDeliveryDetailsList.find(codeDeliveryDetails.AttributeName === key)
```

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +	private createUpdateAttributesResultList(
I think this function should return a `Promise` as it could be expensive due to the nested `array` methods

2022-12-02 14:54 UTC, israx commented on packages/auth/src/Auth.ts
> +							const attrs = this.createUpdateAttributesResultList(attributes, result.CodeDeliveryDetailsList);
it should `await` as the comment bellow

2022-12-02 16:45 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +	private createUpdateAttributesResultList(
@israx How exactly does returning a promise help with the expensiveness of this function?

2022-12-02 17:01 UTC, helgabalashova commented on packages/auth/src/Auth.ts
> +	private createUpdateAttributesResultList(
I personally don't think it is expensive. even if they update 100 attributes (which I doubt), it will still be super fast

2022-12-02 17:10 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +	private createUpdateAttributesResultList(
@israx Running it async doesn't make it any less expensive - it is still all running on a single thread. So what is the real benefit of making this a Promise?

2022-12-02 17:29 UTC, haverchuck requested changes
Can we create and/or update tests?

2022-12-05 19:45 UTC, AllanZhengYP submitted a review, later dismissed
Looks good to me! ⛴

2022-12-05 21:03 UTC, haverchuck commented on packages/amazon-cognito-identity-js/src/CognitoUser.js
> -				return this.getUserData(() => callback(null, 'SUCCESS'), {
What is in the result object? If it is anything other than 'SUCCESS', this would actually be breaking change for anyone using `amazon-cognito-identity-js`, right?

Could we just continue to return the same thing here?

2022-12-06 01:32 UTC, elorzafe requested changes
Can you add the change on the `d.ts` file because is a public facing API, I also have a nit comment.

Overall looks good.
Thanks @helgabalashova

2022-12-06 01:32 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	private createUpdateAttributesResultList(
This is a good discussion, I don't have the right response but just to add more data here.

The code is running async because is inside of a callback, the callback will run on the event loop when the `user.updateAttributes` invoke that.  If I understand correctly at some point that would be taking the single thread and in case there is a huge object I would expect to use something that split this in chunks and release the thread, otherwise even if you wrap that with a `Promise` will still take the thread until is completed.

I think that would be a very advance scenario which in that case I would solve it if a customer has a really huge attribute list which I think Cognito service doesn't support right now.

2022-12-06 01:32 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +				const codeDeliveryDetails = codeDeliveryDetailsList.find(value => value.AttributeName === key);
This could be shorter if using optional chaining instead?

`if (codeDeliveryDetails?.find(....)) {`

2022-12-06 19:09 UTC, elorzafe requested changes
Check the `d.ts` file, I would create another type for `updateUserAttribute` callback

2022-12-06 19:09 UTC, elorzafe commented on packages/amazon-cognito-identity-js/index.d.ts
> +			callback: NodeCallback<Error, string, any>,
I think we only needed the update for the this one, not for the others

2022-12-06 19:09 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +				attrs[key].codeDeliveryDetails = codeDeliveryDetails;
👍

2022-12-06 19:48 UTC, jimblanc approved these changes

2022-12-07 01:20 UTC, haverchuck submitted a review, later dismissed

2022-12-07 16:34 UTC, israx submitted a review, later dismissed
lgtm

2022-12-07 17:05 UTC, elorzafe commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +				callback(null, 'SUCCESS', codeDeliverDetailsResult);
This mock is not testing anything in particular, is just testing the mock. What you should do here is mock the cognito client instead. Like this https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js#L384

2022-12-07 17:05 UTC, elorzafe commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +				callback(null, 'SUCCESS', codeDeliverDetailsResult);
Same as the other, this is testing the mock not the actual code look on this one 
https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js#L384

2022-12-07 17:06 UTC, elorzafe commented on packages/amazon-cognito-identity-js/index.d.ts
> +	export type UpdateAttributesNodeCallback<E, T, K> = (err?: E, result?: T, details?: K) => void;
nice

2022-12-07 17:28 UTC, elorzafe commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +				callback(null, 'SUCCESS', codeDeliverDetailsResult);
For testing there are no regressions for the version that has two arguments we need to have a TypeScript test that validates is not introducing a regression. I will approve the PR but before launching to `latest` we need the integ test in place

2022-12-07 17:28 UTC, elorzafe submitted a review, later dismissed
Add the integ test to validate the 2 and 3 version arguments before launching this to `latest`

2022-12-07 17:32 UTC, elorzafe commented
The commit message should be 

feat(@aws-amplify/auth,amazon-cognito-identity-js): return code delivery details for updateUserAttributes on Hub event

2022-12-07 18:08 UTC, israx approved these changes

2022-12-07 18:11 UTC, merged