Benchmarking v5
aws-amplify/amplify-js pull request #10734
Opened 2022-12-02 17:26 UTC by svidgen

## Not ready for review.

Just putting this out so I can keep preview while I work.

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-19 17:17 UTC, david-mcafee requested changes

2022-12-19 17:17 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +	optimized(preserve = true): UntypedCondition {
Considering if `preserve` could have a slightly more explicit name? `preserveNode`, for instance. On the fence.

2022-12-19 17:17 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +			o instanceof GroupCondition ? o.optimized(this.operator === 'not') : o
There are a several places where you check against `not`, `and`, and `or`, and wondering if helper functions make sense here to 1) make the condition a little more explicit, and 2) to make the checks reusable (and future updates to the check would only need to be updated in one place).

2022-12-19 17:17 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +					const allJoinConditions: any = [];
Is a better type possible here? Same for line 529.

2022-12-19 17:17 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +								[relationship.localJoinFields[i]]: {
Is there a reason we're not updating the `FieldCondition` constructor instead, here?

2022-12-19 17:17 UTC, david-mcafee commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +			const keypath = Array.isArray(idx.keyPath) ? idx.keyPath : [idx.keyPath];
Why is it sometimes an array, and other times not? That seems potentially smelly.

2023-01-05 20:21 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +			o instanceof GroupCondition ? o.optimized(this.operator === 'not') : o
I could see some value in creating semantically named functions, especially if it allows me to strike comments like the one on the conditional below. But, I'm not sure what that looks like yet. I'm a little concerned that addressing this would result in either zero added clarity at the call sites and no LOC saved **or** lots of added clarity at the call sites, but lots of similar/redundant methods.

I've created a task on the backlog internally to revisit this one. If you have a more concrete suggestion in the meantime, let's discuss!

2023-01-05 20:25 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +					const allJoinConditions: any = [];
Whoops. I was lazy in the moment and failed to circle back. I'll see what I can do!

2023-01-06 22:36 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +								[relationship.localJoinFields[i]]: {
I may be having a dense moment. What do you mean? What do you want to see?

2023-01-06 22:38 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
>  		return keyValues.length === keyPath.length ? keyValues : undefined;
It might be worth putting a story in the backlog. But, my impression when I did the *original* optimization was that AsyncAdapter was on the way out. And since the SQLiteAdapter will handle these optimizations in the SQL engine layer, they're not needed there. So, IndexedDB was the only one I assumed we needed at the time.

Happy to revisit it separately.

2023-01-06 22:40 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +			const keypath = Array.isArray(idx.keyPath) ? idx.keyPath : [idx.keyPath];
I might have traced through things incorrectly to arrive at this point, but IIRC this accounts for the Safari implementation discrepancy that we had to fix urgently a few months back. See [this method](https://github.com/aws-amplify/amplify-js/blob/a85171384db4bca202bb5cb5f832a8e319ec89d4/packages/datastore/src/storage/adapter/IndexedDBAdapter.ts#L1072-L1086).

2023-01-06 22:46 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +	const baseQueryInternals = registerPredicateInternals(baseCondition, link);
Oh, correct! I think I'd started down a refactor path that I failed to fully abandon. Cleaning it up...

2023-01-06 22:48 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +		// and these containers
Your guess is as good as mine here at this point. I'll revert this bit. 😅

2023-01-11 16:05 UTC, dpilch approved these changes

2023-01-11 16:05 UTC, dpilch commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +					indexedQueries: fieldPredicates.reduce((agg, p) => {
nit: flatMap may be a little more clear here

2023-01-13 02:27 UTC, david-mcafee commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
>  		return keyValues.length === keyPath.length ? keyValues : undefined;
Could we get an item in the backlog, in the event the Async Adapter sticks around?

2023-01-13 19:03 UTC, david-mcafee commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +			const keypath = Array.isArray(idx.keyPath) ? idx.keyPath : [idx.keyPath];
Tell me if this is overkill, but is that worth calling out, here? I think DataStore in general has been prone to a lot of these kinds of historical, unexplainable, spaghetti situations. Ideally, when / if the Safari implementation is fixed, we could remove this.

2023-01-13 19:48 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +					indexedQueries: fieldPredicates.reduce((agg, p) => {
I'm digging on this a little more. Now that I'm looking at it again, this actually looks like a test coverage gap I'll want to fill before changing (and merging).

2023-01-13 21:31 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +								[relationship.localJoinFields[i]]: {
Previously, we had:

```ts
individualRowJoinConditions.push(
    new FieldCondition(relationship.localJoinFields[i], 'eq', [
	    relative[relationship.remoteJoinFields[i]],
    ])
);
```

which was, with this PR, replaced with:

```ts
relativeConditions.push({
    [relationship.localJoinFields[i]]: {
        eq: relative[relationship.remoteJoinFields[i]],
    },
});
```

So we've removed the call to [the `FieldCondition` constructor](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/predicates/next.ts#L141). By not using the constructor, we miss out on [the validation step](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/predicates/next.ts#L213). 

It's also possible I may be having a dense moment?

2023-01-13 23:00 UTC, svidgen commented on packages/datastore/src/predicates/next.ts
> +								[relationship.localJoinFields[i]]: {
Oh I see. Good question!

The `FieldCondition` validation is intended primarily to validate customer predicate construction at runtime (mainly JS contexts) and provide meaningful guidance if they supply something like this:

```
await DataStore.query(Model, m => m.name.eq('a', 'b', 'c'))
```

In this example, we don't have a defined interpretation of what `eq` does when given multiple operands. So, the `FieldCondition` validator will issue an error intended to tell the customer what to fix.

In our case, we're building the query in a predictable fashion from existing data + metadata, so I wasn't concerned about losing this validation. And it therefore seemed simpler to skip the object construction.

But, I don't think there's any reason I couldn't drop the constructor back in as an intermediary:

```
	relativeConditions.push(new FieldCondition(
		relationship.localJoinFields[i],
		'eq',
		relative[relationship.remoteJoinFields[i]]
	).toAST());
```

I'm happy to make that change, unless I'm forgetting something!

2023-01-13 23:18 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +					indexedQueries: fieldPredicates.reduce((agg, p) => {
This is actually a little more involved than I realized. As it's pretty much EOD here, this will take me into next week to keep digging. But, here's where I'm at so far:

Join conditions are coming through with additional levels of nesting that I failed to account for. This may just be a CPK thing -- TBD on that -- I haven't actually probed into that yet. But, I'm going to try to make this branch a little smarter and unpack those join conditions one level deeper next week. I got a small start there, but am out of time for today.

I'll also timebox the effort to my "free" time this sprint. The changes in this branch reduce the number of table scans needed and execution times overall. But, but `or` branch isn't adding the intended value. So, I may end up having to trash the branch if I can't shim it in before the end of the sprint.

2023-01-13 23:30 UTC, david-mcafee commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +			// if we have a matchind predicate field for each component of this index,
nit:
```suggestion
			// if we have a matching predicate field for each component of this index,
```

2023-01-13 23:32 UTC, david-mcafee submitted a review, later dismissed
Left a question re: using the `FieldCondition` constructor, and a minor spelling suggestion, otherwise LGTM.

2023-01-13 23:38 UTC, david-mcafee commented on packages/datastore/src/predicates/next.ts
> +								[relationship.localJoinFields[i]]: {
Thanks for clarifying, Jon! In that case, seems there isn't any value in adding it back in :)

2023-01-13 23:57 UTC, iartemiev approved these changes
LGTM pending responses to the questions David raised in his review.

2023-01-13 23:57 UTC, iartemiev commented on packages/datastore/__tests__/IndexedDBAdapter.test.ts
> +		const end = new Date();
Nit: can use [peformance.now()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#examples) for improved benchmark accuracy

2023-01-13 23:57 UTC, iartemiev commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +			const keypath = Array.isArray(idx.keyPath) ? idx.keyPath : [idx.keyPath];
FWIW even when Safari fixes the IDB keypath bug, we'll have to keep our workarounds in place for a couple of years to ensure compatibility with older versions of Safari. I think adding a comment here should suffice for now, but if we have a chance to refactor this later, we should try to abstract any repeated workarounds out into single method like the one Jon linked above.

2023-01-18 16:59 UTC, svidgen commented on packages/datastore/__tests__/IndexedDBAdapter.test.ts
> +		const end = new Date();
👍

2023-01-18 17:11 UTC, svidgen commented on packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
> +					indexedQueries: fieldPredicates.reduce((agg, p) => {
OK. I've added tests that stress this branch, which I reworked a bit to successfully trigger on CPK join conditions. In doing so, this particular line is replaced by a handful of maps and filters above.

2023-01-18 20:41 UTC, david-mcafee approved these changes
LGTM! 🎉

2023-01-18 21:14 UTC, merged