fix(core): add cache-control header to cognito identity client
aws-amplify/amplify-js pull request #10753
Opened 2022-12-08 02:05 UTC by haverchuck

#### Description of changes
Adds the cache-control 'no-store' header via middleware to the various instantiations of the Cognito Identity Pool Client.

#### Description of how you validated changes
Manual testing.

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-08 03:24 UTC, palpatim commented on packages/core/src/Credentials.ts
> +		cognitoClient.middlewareStack.add(
Is there ever a case when we would not want the cache control header to be added? If not, could we just bake this into the CognitoClient constructor?

2022-12-08 14:45 UTC, jimblanc commented on packages/core/src/Credentials.ts
> +				args.request.headers['cache-control'] = 'no-store';
Nit: Might want to do this immutably to keep the middleware side-effect free.

```
const updatedArgs = {
  ...args,
  request: {
    ...args.request,
    headers: { 
      ...args.request.headers,
      'cache-control': 'no-store'
    }
  }
};
```

Also might be worth breaking into a utility function to improve re-usability & test-ability?

2022-12-09 21:29 UTC, haverchuck commented on packages/amazon-cognito-identity-js/src/Client.js
Changes to this file were made by Prettier when I made a change. I reverted the change, but the prettification remains.

2022-12-09 21:50 UTC, AllanZhengYP submitted a review, later dismissed

2022-12-09 22:11 UTC, stocaaro commented on packages/amazon-cognito-identity-js/src/Client.js
Missed that you made no changes. Might recommend checking out the original file to simplify your commit.

eg `git co origin/main packages/amazon-cognito-identity-js/src/Client.js && git commit -am 'chore: Revert prettier changes'`

2022-12-09 22:21 UTC, stocaaro approved these changes

2022-12-09 22:33 UTC, cshfang approved these changes
Minor comments otherwise lgtm

2022-12-09 22:33 UTC, cshfang commented on packages/amazon-cognito-identity-js/src/Client.js
+1

2022-12-09 22:33 UTC, cshfang commented on packages/core/src/Util/CognitoIdentityClient.ts
> +	region: string | Provider<string> | undefined
Nit: Use the type provided by SDK
```js
import { CognitoIdentityClient, CognitoIdentityClientConfig } from '@aws-sdk/client-cognito-identity';

...

region: CognitoIdentityClientConfig["region"]
```

2022-12-10 00:25 UTC, elorzafe requested changes
What do you think of having an E2E for checking the headers instead of doing it on the unit tests? I would try to test the logic on unit tests but test the actual requests headers I would do it on cypress on a real app.

Thanks @haverchuck 🎖️

2022-12-10 00:25 UTC, elorzafe commented on packages/core/__tests__/Util-test.ts
> +		test('headers should be added by middleware on GetIdCommand', async () => {
I would add `expect.assertions` and also use `done` in case the tests ends before doing the assertions

2022-12-10 00:25 UTC, elorzafe commented on packages/core/__tests__/Util-test.ts
> +		test('headers should be added by middleware on GetCredentialsForIdentityCommand', async () => {
Same as the other just for been careful the test is not finishing before doing the assertions I would add `expect.assertions` and use `done` callback

2022-12-10 00:25 UTC, elorzafe commented on packages/core/src/Util/CognitoIdentityClient.ts
> +function middlewareArgs(args: { request: { headers: any }; input: any }) {
I would add a test for this function

2022-12-10 00:38 UTC, haverchuck commented on packages/core/__tests__/Util-test.ts
> +		test('headers should be added by middleware on GetIdCommand', async () => {
Yeah we should have both.

2022-12-12 15:43 UTC, haverchuck commented on packages/core/src/Credentials.ts
> +		cognitoClient.middlewareStack.add(
The answer to your question is 'no'; and while we don't control the client constructor itself (it's an sdk construct) we've moved instantiation up into a separate utility that bakes in this middleware.

2022-12-12 18:53 UTC, haverchuck commented on packages/core/__tests__/Util-test.ts
> +		test('headers should be added by middleware on GetIdCommand', async () => {
I don't think the `done` is necessary if you are using async callback and awaiting, but I added the expect.assertions. Could callout, thanks.

2022-12-12 19:00 UTC, cshfang approved these changes

2022-12-12 19:03 UTC, AllanZhengYP submitted a review, later dismissed

2022-12-12 19:03 UTC, jimblanc submitted a review, later dismissed

2022-12-12 19:06 UTC, stocaaro submitted a review, later dismissed

2022-12-12 21:34 UTC, elorzafe approved these changes

2022-12-12 21:54 UTC, cshfang approved these changes

2022-12-12 21:54 UTC, stocaaro approved these changes

2022-12-12 21:55 UTC, AllanZhengYP approved these changes

2022-12-12 21:55 UTC, merged