Sign up function
aws-amplify/amplify-js pull request #10774
Opened 2022-12-13 18:09 UTC by helgabalashova

#### Description of changes
Implements sign up function (without auto sign in, hub, and errors implementations; TODOs are in place).

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-13 21:36 UTC, jimblanc reviewed
Some comments below. Also in the interest of keeping PRs smaller okay with leaving unit tests out for now, but we should make sure to get those included.

2022-12-13 21:36 UTC, jimblanc commented on package.json
> +		"@aws-sdk/client-cognito-identity-provider": "^3.198.0"
Would prefer to peg this to a specific version of the SDK while we try to get our bundle size ironed out. Also does this align with our other SDK dependencies? I see 3.6.1 in a lot of packages.

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Auth.ts
> +	signUp<PluginOptions extends AuthPluginOptions>(req:SignUpRequest<CognitoUserAttributeKey, PluginOptions>):Promise<AuthSignUpResult<CognitoUserAttributeKey>>
Nit: Missing some white-space in the params here, e.g. `req:SignUpRequest` & `:Promise`)

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +import { AttributeType, CognitoIdentityProviderClient, SignUpCommand } from '@aws-sdk/client-cognito-identity-provider';
Nit: Generally I think we should try to put non-relative imports before the relative ones, although I realize we should have a linter rule for this instead.

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const pluginOptions = req.options.pluginOptions;
Nit: Could we re-order this to reduce duplication, e.g.

```
const pluginOptions = req.options?.pluginOptions;
if (pluginOptions) {
```

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			userAttr = req.options.userAttributes.map(obj => ({
Ditto here about reducing duplication

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput: any = await sendCommand(this._client, signUpCommand);
Any way to properly type this output?

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +							attributeName: signUpCommandOutput.CodeDeliveryDetails?.AttributeName as CognitoUserAttributeKey
Should we avoid optional chaining here? If the next step is `CONFIRM_SIGN_UP`, would it ever be valid for `CodeDeliveryDetails` to be undefined? Also nit-pick but we could extract `signUpCommandOutput.CodeDeliveryDetails` into a const to reduce duplication.

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/types/index.ts
> +export * from './aws-plugins/cognito-plugin/types/options';
Nit-pick but I think I'd prefer to export all types for a given plugin from that plugin's index file, and then re-export from that here (just to keep the organization cleaner)

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +	clientMetadata?
Should this be typed?

2022-12-13 21:36 UTC, jimblanc commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +		return commandOutput;
Should be able to just return the promise directly: `return client.send(command);`

2022-12-13 22:23 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput: any = await sendCommand(this._client, signUpCommand);
I think the only way to type this output would be to create a separate function for each send command and the only difference between them would be the command input type and return type.

2022-12-13 22:27 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +							attributeName: signUpCommandOutput.CodeDeliveryDetails?.AttributeName as CognitoUserAttributeKey
by optional chaining you mean to make codeDeliveryDetails required part of the result object? If so, it is not an option because we don't return codeDeliveryDetails if next step is DONE

2022-12-13 22:42 UTC, israx requested changes

2022-12-13 22:42 UTC, israx commented on packages/auth/src/types/aws-plugins/cognito-plugin/types/models/cognitoUserAttributeKey.ts
> +	| `custom:${string}`
please also double check the type of `AuthUserAttributeKey` as well

2022-12-13 22:42 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput: any = await sendCommand(this._client, signUpCommand);
I checked the util `sendCommand` function. I think it's not needed, it's redundant to have a double `try and catch` clause

2022-12-13 22:42 UTC, israx commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +export const sendCommand = async (client:CognitoIdentityProviderClient, command) => {
this function shouldn't be needed, there's no reusability benefits

2022-12-13 22:42 UTC, israx commented on packages/auth/src/utils/assertPluginAvailable.ts
> +import { AuthProvider } from '../types';
`AuthProvider` name should be change as it would conflict with other type name

2022-12-13 22:53 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput: any = await sendCommand(this._client, signUpCommand);
it has a SignUpCommandOutput but we need to decide if we want to have a separate function for each send command or just one general? If we choose to proceed with general then we won't be able to define type here

2022-12-13 22:57 UTC, helgabalashova commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +export const sendCommand = async (client:CognitoIdentityProviderClient, command) => {
this is what @huverchuck asked me to do. We are going to have all sdk calls as functions in this file. And in case of reusability, if we keep it this way, it can be used for all other send calls (i.e. send confirmSignUpCommand)

2022-12-13 22:59 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const signUpCommandOutput: any = await sendCommand(this._client, signUpCommand);
and having sendCommand was Dustin's decision to move all aws-sdk commands to utils files (that's why it is there) and in case of keeping it general, it will be reused for other function. We will use it from each Auth function

2022-12-13 23:15 UTC, helgabalashova commented on packages/auth/src/Auth.ts
> +	signUp<PluginOptions extends AuthPluginOptions>(req: SignUpRequest<string, PluginOptions>): Promise<AuthSignUpResult<string>>;
discussed offline. SignUpRequest is in tact with current version of approved API

2022-12-13 23:19 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +import { AttributeType, CognitoIdentityProviderClient, SignUpCommand } from '@aws-sdk/client-cognito-identity-provider';
I think it is usually in alphabetical order (at least when you let VS Code add imports for you).

2022-12-13 23:20 UTC, helgabalashova commented on packages/auth/src/types/models/AuthProvider.ts
>  	// return the name of you provider
let's see what @haverchuck has to say and then I will change it if needed.

2022-12-14 01:17 UTC, elorzafe requested changes
Overall looking good, I would try to create smaller functions so the code can be easier to test.

Are you creating Unit tests in a follow up PR?

Can you fix the `export *`?

Thanks!

2022-12-14 01:17 UTC, elorzafe commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			if (validationDataObject) {
What if we create a separate function for this kinds of things?

2022-12-14 12:13 UTC, israx commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			const validationDataObject: ValidationData = pluginOptions['ValidationData'];
I think the reason is that `pluginOptions` variable doesn't have a type yet. So something to add later is an **assertion guard** for plugin options, so then `pluginOptions` will show a type

2022-12-14 12:26 UTC, israx commented on packages/auth/src/types/index.ts
> +export * from './aws-plugins/cognito-plugin/types/options';
@elorzafe I think that wouldn't be a problem as this are just types. At build time types will be lost anyways

2022-12-14 12:26 UTC, israx commented on packages/auth/src/types/models/AuthProvider.ts
>  	// return the name of you provider
yeah the thing is that the convention with the other libraries is `AuthProvider`

2022-12-14 12:26 UTC, israx commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +		// case ChallengeNameType.PASSWORD_VERIFIER:
I'm wondering if the AWS SDK has a type for `ChallengeName` that can be imported, could you check that @helgabalashova  ?

2022-12-14 12:26 UTC, israx commented on packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts
> +export const sendCommand = async (client:CognitoIdentityProviderClient, command) => {
If we are keeping this function then I think we can make it generic, for various output commands

2022-12-14 19:21 UTC, helgabalashova commented on packages/auth/src/types/models/AuthProvider.ts
>  	// return the name of you provider
it just makes more sense to keep it as `AuthProvider` and change what you suggest to `oAuthProvider` or something like that.

2022-12-14 23:52 UTC, elorzafe reviewed
A few nit pick comments and one concern with camelCase vs PascalCase value

2022-12-14 23:52 UTC, elorzafe commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			clientMetadata = pluginOptions['clientMetadata'];
Is it PascalCase or camelCase? (`validationData` or `ValidationData`)

2022-12-14 23:52 UTC, elorzafe commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	private mapValidationDataObject(
nit: is it `map` the right description, it looks more convert object to array

2022-12-14 23:58 UTC, helgabalashova commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +			clientMetadata = pluginOptions['clientMetadata'];
it is `validationData` according to [API definition](https://quip-amazon.com/rfNLAS8ns64b/Amplify-JS-Auth-API-Definition-2022#temp:C:IeK0ddcb020529e4579a56dffdb1)

2022-12-15 00:20 UTC, elorzafe approved these changes

2022-12-15 00:35 UTC, elorzafe approved these changes

2022-12-15 18:01 UTC, haverchuck commented on packages/auth/src/Auth.ts
> +	signUp<PluginOptions extends AuthPluginOptions>(
We need to decide how we are going to document category-level API methods and plugin implementation methods. Could you work with @israx on that? For now, please include documentation for both following TS best practices.

2022-12-15 18:02 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +	async signUp<PluginOptions extends AuthPluginOptions = CognitoSignUpOptions>(
See above comment about documentation.

2022-12-15 18:05 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		const clientId: string = getUserPoolId(this._config);
Couldn't the CognitoIdentityProviderClient add this  internally?

2022-12-15 18:13 UTC, haverchuck commented on packages/auth/src/Providers/AmazonCognitoProvider.ts
> +		const signUpCommand: SignUpCommand = createSignUpCommand(
I'm not entirely sure exporting these command constructors is the cleanest way to go, but I think it's ok for now.

2022-12-15 18:23 UTC, haverchuck commented on packages/auth/src/types/models/AuthProvider.ts
>  	// return the name of you provider
We are trying to match the APIs in other libraries as closely as possible, so we should probably change this file name to `AuthPluginProvider` or something similar, since we will want to reserve this name for classes/types/enums that are exposed in the APIs.

2022-12-15 18:24 UTC, haverchuck requested changes
Left a couple of minor suggestions, but otherwise looks great.

2022-12-21 19:10 UTC, haverchuck approved these changes

2022-12-21 19:43 UTC, merged