feature: Enable bundle size checks in CircleCI
aws-amplify/amplify-js pull request #10876
Opened 2023-01-18 16:28 UTC by jimblanc

#### Description of changes

This change enables the new bundle size checks in CircleCI and requires them for new PRs. It also upgrades our test executors to use Node 16 (a requirement of `size-limit`) and fixes a few errors in our tests that were exposed by the upgrade.

Other changes:
- Added info to `CONTRIBUTING` on debugging bundle size regressions

#### Issue #, if available

#### Description of how you validated changes
Clean `build_test_deploy` execution in CircleCI. Verified that unit tests pass in both Node 14 & 16.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-18 19:15 UTC, svidgen submitted a review, later dismissed

2023-01-18 20:44 UTC, iartemiev submitted a review, later dismissed

2023-01-18 22:35 UTC, elorzafe requested changes
Prefer to remove the graphql change and a minor question

2023-01-18 22:35 UTC, elorzafe commented on packages/api-graphql/src/GraphQLAPI.ts
> +				headers = {
Can we do this change in a another PR?

2023-01-18 23:09 UTC, jimblanc commented on packages/api-graphql/src/GraphQLAPI.ts
> +				headers = {
Unfortunately no, `size-limit` requires Node 16 to run, and upgrading our test executor to use node 16 (as well as building locally in node 16) revealed some issues with this code.

2023-01-18 23:33 UTC, jimblanc commented on .circleci/config.yml
> -            npm install sqlite3 --build-from-source
Discussed offline, this doesn't appear to be needed any more as after upgrading all unit & integ tests pass in node 14 & node 16 using the pre-compiled binaries.

2023-01-18 23:38 UTC, elorzafe commented on packages/api-graphql/src/GraphQLAPI.ts
> +					throw new Error(GraphQLAuthError.NO_FEDERATED_JWT);
It seems this should be `throw new Error(GraphQLAuthError.NO_CURRENT_USER);` because previously that error was catched and throw that one. What do you think?

2023-01-19 15:06 UTC, jimblanc commented on packages/api-graphql/src/GraphQLAPI.ts
> +				headers = {
Discussed offline and did some more testing, removed this in favor of test changes to reflect the actual error thrown in apps.

2023-01-19 16:51 UTC, elorzafe approved these changes
Looks good to me!

Thanks @jimblanc 🔥

2023-01-19 17:21 UTC, AllanZhengYP commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +			).rejects.toThrowError('No current user');
Nit: why is this needed?

2023-01-19 17:21 UTC, AllanZhengYP submitted a review, later dismissed

2023-01-19 17:30 UTC, jimblanc commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +			).rejects.toThrowError('No current user');
Yeah this ended up being an issue with our tests. From looking at the code & confirmation in a sample app (for both node 14 & node 16), this API will fail with `No current user` in all cases due to nested try-catch blocks. For some reason in node 14 + Jest (not observed in test app), it would fail with `No federated jwt`. This change updates the test to reflect what was observed in the test app.

2023-01-19 17:32 UTC, svidgen submitted a review, later dismissed

2023-01-19 17:52 UTC, dpilch commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +			).rejects.toThrowError('No current user');
I have the fix here: https://github.com/aws-amplify/amplify-js/pull/10470

2023-01-19 20:03 UTC, jimblanc commented on packages/api-graphql/__tests__/GraphQLAPI-test.ts
> +			).rejects.toThrowError('No current user');
Thanks for the reference! In the interest of not changing the customer-facing error surface with this change, I removed the GraphQL refactor I originally had which was similar to yours. I went through and added the `awaits` though to fix test behavior.

2023-01-19 20:04 UTC, dpilch approved these changes

2023-01-19 20:19 UTC, AllanZhengYP approved these changes
Looks good to me! Re-approve

2023-01-19 23:32 UTC, merged