feat(data): add Microsoft Edge testing
aws-amplify/amplify-js pull request #10917
Opened 2023-02-01 21:36 UTC by david-mcafee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-03 22:52 UTC, svidgen requested changes
Should this be in draft form until the samples PR is merged and TODO's + testing cruft are cleaned up here?

2023-02-03 22:52 UTC, svidgen commented on packages/geo/package.json
> +			"limit": "65 kB"
FYI, there's are more bundle size failures out there. But, I _think_ @jimblanc is working on a PR for them.

2023-02-09 21:58 UTC, david-mcafee commented
> Should this be in draft form until the samples PR is merged and TODO's + testing cruft are cleaned up here?

I explain more in the description, but the TODOs are _not_ to be addressed in this PR - I've added an item to the JS backlog for them. As far as marking as a draft, I figured I'd have folks review this PR alongside the samples repo PR as a whole. If you think that going forward we should not do this, happy to discuss :)

2023-02-09 22:06 UTC, svidgen requested changes

2023-02-09 22:06 UTC, svidgen commented on .circleci/config.yml
>  test_browsers: &test_browsers
Since there is not longer a single list of test browsers, and this isn't "all" test browsers, what is it?

2023-02-09 22:06 UTC, svidgen commented on .circleci/config.yml
> +            # yarn publish:$CIRCLE_BRANCH
Not publishing?

2023-02-09 22:06 UTC, svidgen commented on .circleci/config.yml
> +            git checkout edge-testing-2
This should be removed, correct?

2023-02-09 22:08 UTC, svidgen commented
> > Should this be in draft form until the samples PR is merged and TODO's + testing cruft are cleaned up here?
> 
> I explain more in the description, but the TODOs are _not_ to be addressed in this PR - I've added an item to the JS backlog for them. As far as marking as a draft, I figured I'd have folks review this PR alongside the samples repo PR as a whole. If you think that going forward we should not do this, happy to discuss :)

Gotcha. The one that always catches my eye is the `git checkout <some-samples-branch>`. And in this one, a publish command has been commented out. I assume those are testing artifacts that should be undone? Or, am I missing something? 😅

2023-02-09 22:09 UTC, david-mcafee commented
> > > Should this be in draft form until the samples PR is merged and TODO's + testing cruft are cleaned up here?
> > 
> > 
> > I explain more in the description, but the TODOs are _not_ to be addressed in this PR - I've added an item to the JS backlog for them. As far as marking as a draft, I figured I'd have folks review this PR alongside the samples repo PR as a whole. If you think that going forward we should not do this, happy to discuss :)
> 
> Gotcha. The one that always catches my eye is the `git checkout <some-samples-branch>`. And in this one, a publish command has been commented out. I assume those are testing artifacts that should be undone? Or, am I missing something? 😅

No, you're correct, I somehow forgot to remove this. Sorry for the confusion!

2023-02-09 22:18 UTC, erinleigh90 submitted a review, later dismissed

2023-02-10 03:48 UTC, david-mcafee commented on .circleci/config.yml
>  test_browsers: &test_browsers
Currently discussing naming with the JS team offline. I've updated this with better documentation, as well as a better naming convention. However, I'm open to suggestions :)

2023-02-10 03:48 UTC, david-mcafee commented on .circleci/config.yml
> +            # yarn publish:$CIRCLE_BRANCH
Removed

2023-02-10 03:48 UTC, david-mcafee commented on .circleci/config.yml
> +            git checkout edge-testing-2
Removed

2023-02-10 14:54 UTC, jimblanc approved these changes

2023-02-10 15:30 UTC, dpilch approved these changes

2023-02-10 15:35 UTC, svidgen approved these changes
Thanks for the changes!

2023-02-10 17:41 UTC, merged