Fix AWSS3ProviderManagedUpload.ts Type Mis-Match
aws-amplify/amplify-js pull request #10988
Opened 2023-02-16 22:11 UTC by joesilveira

Params should be of type PutObjectCommandInput

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-21 18:59 UTC, kvramyasri7 requested changes
I have tested and confirmed this removes the error without introducing any other errors. There is one unused import that needs to clean up after which this should get merged.

2023-02-21 18:59 UTC, kvramyasri7 commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
>  	PutObjectRequest,
This import is no longer in use. Please remove it.

2023-02-23 01:25 UTC, AllanZhengYP approved these changes

2023-02-23 20:38 UTC, kvramyasri7 approved these changes

2023-02-23 20:41 UTC, merged