feat(datastore): add support for AppSync RTF
aws-amplify/amplify-js pull request #11000
Opened 2023-02-20 13:47 UTC by iartemiev

#### Description of changes

Add support for AppSync [Enhanced Subscription Filtering](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html) (aka Runtime Filtering / RTF)

Allows DataStore [selective sync](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#selectively-syncing-a-subset-of-your-data) predicates to be applied as a backend subscription filter, instead of receiving all authorized subscriptions and filtering them clientside as was done before this PR. 

RTF has several service constraints (listed below), therefore the current clientside filtering behavior will remain as a fall back in case the customer-supplied filter expression falls outside those limits. 

We have 2 mechanisms for handling this fallback:

1. Adds clientside filter expression validation. Only send filter argument for filter expressions that meet service limits.
2. Catch RTF-specific error messages at connect time and retry subscription connection without the filter expression. This is in case `1.` validation has a false negative and we send a filter expression the service rejects.

These provisions are in place to ensure that we safely fall back to the current, pre-RTF behavior, as this feature is intended to be a non-breaking change. 

### RTF service limits
**_When any of these are exceeded - we automatically fall back to clientside subscription filtering_**

1. A field can be used no more than once in the same group, i.e. in an AND expression
2. A filter can use up to 5 distinct fields total
4. A filter can use up to 10 combinations of fields, i.e. 10 OR expressions
5. `not` predicate group is not supported - use `ne` or `notContains` operators instead

**Dynamic auth modes count towards these limits in the following ways:**
for 2. -> add number of dynamic auth modes to total filter fields to determine if limit is exceeded

for 3. -> each auth rules is combined into each existing filter group. Multiply the number of dynamic auth modes
by the total number of OR expressions to determine if limit is exceeded

Note: RTF also enables real time updates when using dynamic list of owners and list of groups auth modes with DataStore. However, this is handled entirely in the auth request resolver business logic and has already been implemented in the GQL Transformer.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/7534

#### Description of how you validated changes
* Manual testing
* Unit tests
* e2e test run - https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/18099/workflows/aa276927-2cd3-4d1a-8a78-30f98b4bba0e

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-20 17:25 UTC, dpilch commented on packages/datastore/src/sync/processors/subscription.ts
> +															message.includes(
Is there anyway we can make this more robust incase the error messages change in the future?

2023-02-20 17:25 UTC, dpilch commented on packages/datastore/src/sync/processors/subscription.ts
> +			'Backend subscriptions filtering limit exceeded.\n' +
This wouldn't always be accurate right? In the case that a a not group is used the filtering is not disable due to a limit (unless you are using limit here as in limitation)?

2023-02-20 17:25 UTC, dpilch commented on packages/datastore/src/sync/processors/subscription.ts
> +				} different fields for this model.`;
```suggestion
				`Serverside subscription filtering supports a selective sync expression with a maximum of ${
					FILTER_FIELD_SERVICE_LIMIT - dynamicAuthModes
				} different fields for this model.`;
```

2023-02-20 17:33 UTC, iartemiev commented on packages/datastore/tslint.json
> -		"max-line-length": [true, 120],
The line limit is automatically enforced by Prettier whenever possible, i.e. for code that can be broken up into multiple lines. But this lint rule also throws an error for strings that exceed 120 - like the new warnings that get emitted as part of this PR. Felt like an unnecessary constraint.

2023-02-20 17:36 UTC, iartemiev commented on packages/datastore/src/sync/processors/subscription.ts
> +															message.includes(
There's no way I'm aware of other than string matching. The error message comes from the service, so it's unlikely to change on a whim.

2023-02-20 17:37 UTC, iartemiev commented on packages/datastore/src/sync/processors/subscription.ts
> +				} different fields for this model.`;
That sounds a lot better. Thanks!

2023-02-20 17:40 UTC, undefobj commented
Limits on clients have proven to be an anti-pattern in the past that we avoid. They should be set in the services and raised when necessary, either across all APIs or per-customer. Unless there's a safety reason you're trying to address here suggest removing any limits from clients and handling the service throttling/error message as appropriate. If customers bump up against these limits they can submit feedback to AppSync to have them raised.

2023-03-02 18:16 UTC, iartemiev commented
FYI - tried to use "hide as resolved" for Richard's comment above, because I've updated the PR with the change he requested, but GH is just showing it as "hidden".

2023-03-02 20:00 UTC, svidgen reviewed
Might need another offline sync on this. I think I understood the balance we wanted to strike between client-side helpfulness + validation differently.

2023-03-03 13:45 UTC, iartemiev commented on packages/datastore/src/sync/processors/subscription.ts
> +			}, '');
Yep, good call. Updated this and the other 2 instances.

2023-03-03 13:52 UTC, iartemiev commented on packages/datastore/src/sync/utils.ts
> +export function repeatedFieldInGroup(
We can throw this into the catch as well, it'll return a unique error message. But my thought process for doing it ahead of time is that this is an inherent constraint in the RTF implementation and not something that can change on a case-by-case basis

2023-03-06 17:29 UTC, svidgen requested changes
Sorry, I guess I lied about being just about ready to approve. A few suggestions/requests. I think the only blocker for me is the typo.

2023-03-06 17:29 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> +					`You c	urrently have ${dynamicAuthModeFields.size} dynamic auth mode(s) configured on this model: ${dynamicAuthFieldsStr}.`;
```suggestion
					`You currently have ${dynamicAuthModeFields.size} dynamic auth mode(s) configured on this model: ${dynamicAuthFieldsStr}.`;
```

2023-03-06 17:29 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> +				`please re-write your expression using \`ne\` or \`notContains\` operators.`
```suggestion
				`rewrite your expression using \`ne\` or \`notContains\` operators.`
```

2023-03-06 17:29 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> +		case RTFError.NotGroup:
If this is a forever rule, it might be nice down the road to automagically rewrite `not`'s out of queries for customers. (In cases where `not` doesn't turn into two conditions on the same field, I guess. 😅 )

2023-03-06 17:29 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> +				'To enable backend subscription filtering: upgrade your Amplify CLI to the latest version and run `amplify push`'
Might be good to give them both commands they need to run.

```suggestion
				'To enable backend subscription filtering, upgrade your Amplify CLI to the latest version and push your app by running `amplify upgrade` followed by `amplify push`'.
```

2023-03-06 17:29 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> + *
Any synopsis and/or examples to put here?

2023-03-06 18:07 UTC, iartemiev commented on packages/datastore/src/sync/utils.ts
> +		case RTFError.NotGroup:
👍🏻 will add a backlog task for this

2023-03-06 18:16 UTC, iartemiev commented on packages/datastore/src/sync/utils.ts
> + *
Added an example

2023-03-06 18:46 UTC, svidgen submitted a review, later dismissed

2023-03-07 00:33 UTC, manueliglesias reviewed
Looks great! I have some questions and a single change I would like to see regarding deeply nested code.

2023-03-07 00:33 UTC, manueliglesias commented on packages/datastore/src/sync/utils.ts
> +		Object.keys(child).length > 0 && children.push(child);
from https://eslint.org/docs/latest/rules/no-unused-expressions:
> An unused expression which has no effect on the state of the program indicates a logic error.

I know it is not a logic error here, and we used this pattern in other places, but it is clearer to just do the `if`

2023-03-07 00:33 UTC, manueliglesias commented on packages/datastore/src/sync/utils.ts
> +			(isList && root && ('and' in child || 'or' in child))
question: do we have constants we can use here for `and` and `or`?

another question, what about double `not`? is that a condition we care about and need to flatten too in this code path?

2023-03-07 00:33 UTC, manueliglesias commented on packages/datastore/src/sync/utils.ts
> +		isList ? result[type].push(child) : (result[type] = child);
Not blocking, see comment above about the`no-unused-expressions` eslint rule. I know we don't enforce that rule, I just think it is better / more readable style to not have unused expressions and be explicit with an if/else if there are side-effects involved. Ternaries re great for assignments though.

2023-03-07 00:33 UTC, manueliglesias commented on packages/datastore/src/sync/processors/subscription.ts
> +															subscriptions[modelDefinition.name][
We are very deeply nested here, can we simplify this code or extract parts of it to help with readability?

2023-03-07 13:22 UTC, iartemiev commented on packages/datastore/src/sync/utils.ts
> +	if (filterArg || isOwnerAuthorization) {
Agreed, that looks better. Updated with a minor change to the snippet.

2023-03-07 13:29 UTC, iartemiev commented on packages/datastore/src/sync/utils.ts
> +			(isList && root && ('and' in child || 'or' in child))
> do we have constants we can use here for and and or?
We don't. They're hardcoded everywhere else as well. We can circle back with a refactor, but I felt that was out of scope for this PR.

> what about double `not`?
It wouldn't hurt to flatten it, but it's not crucial. Flattening redundant `and` groups is necessary for the selective sync -> index query use case, but flattening double `not`s would be more of an edge case stylistic improvement

2023-03-07 13:32 UTC, iartemiev commented on packages/datastore/src/sync/processors/subscription.ts
> +															subscriptions[modelDefinition.name][
It's at the same level of nesting as the rest of the code in that catch block (e.g., the multi-auth handling). I agree that the SubscriptionProcessor could use a refactor, but I think we should tackle that as a separate task.

2023-03-07 15:50 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +															subscriptions[modelDefinition.name][
We have complexity issues across the board. IMHO, I think this PR is actually *less* complex to review by following suit here. A separate PR or two for refactors would be welcome. But, in the worst-case, we should discuss this + refactor opportunities in the biweekly thing -- get some stories on the board that will meaningfully improve the codebase.

2023-03-07 15:51 UTC, svidgen approved these changes

2023-03-07 18:15 UTC, manueliglesias approved these changes
LGTM 👍

2023-03-07 18:16 UTC, merged