feat: user agent enhancements: part1 core
aws-amplify/amplify-js pull request #11121
Opened 2023-03-23 02:32 UTC by erinleigh90

#### Description of changes
User Agent Enhancements Part I for core:
- Adds type for CustomUserAgent and enums for Category, CategoryAction, and Framework
- Updates core Platform to build the user agent according to the new format `aws-amplify/5.0.14 (1:1,2:2,3:1,4:0)`
- Updates Datastore and GraphQL calls that use userAgentSuffix to pass in the CustomUserAgent type
- First draft of Frontend Framework detection

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/Platform/detectFramework.ts
> +		)
I know that looking for specific things on the DOM isn't as reliable as this but I would treat this as a *fallback* to those other queries (similar to what you had before at some point in a previous PR) rather than the default. The concern about this is that it could, in theory, have to traverse through a huge document before finding a result (not to mention I think it'd probably first allocate the memory to essentially store all the selection results into an array before the iterations even begin).

You might even consider creating a function which takes in matchers that short circuit so you can pass in different matching criteria that go from quick but not always reliable to long but reliable
```ts
const isFramework = (matchers) => matchers.some(matcher => matcher())

export const detectFramework = () => {
  const reactMatchers = [
    () => !!window?.React,
    () => !!document.querySelector('[data-something-reacty]'),
    () => Array.from(document.querySelectorAll('*')).some(e =>
      e.hasOwnProperty('_reactRootContainer')
    );
  ]
  if (isFramework(reactMatchers)) { return Framework.React }
}
```

As you add more frameworks to detect, you may even find that some of the search logic can be reused (especially that last query) so you may be able to optimize further by combining them as well. Just something to consider.

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +import { CustomUserAgent } from '../types/types';
I'm not sure why this folder is structured the way it is but we should really either:
1. Just get rid of the folder - leaving a `types.ts` on the `src` root
2. Get rid of `index.ts` and just rename the current `types.ts` to `index.ts`

Having an index whose sole purpose to to re-export another file seems pretty pointless.

Even if we don't want to make that change in this PR, I would suggest you update this to:
```suggestion
import { CustomUserAgent } from '../types';
```

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	return `(${Object.values(userAgentDetails).sort().toString()})`;
I think the `toString()` can be omitted?

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/index.ts
> +export { ICredentials, CustomUserAgent } from './types';
Similar question to the enums below - does this type have any relevance outside of the user agent context?

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/Platform/index.ts
>  export const Platform = {
Should this be typed?

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/types/types.ts
> +export type Platform = {
I may have missed it, but is this being used anywhere right now?

2023-03-23 18:36 UTC, cshfang commented on packages/core/src/types/types.ts
> +export type CustomUserAgent = {
Ditto here, is there a reason barring us from putting all these relevant things inside `'../Platform'`?
As it stands - it seems like to use all these things together I have to do something like
```ts
import { Category, CategoryAction, Framework } from '../constants';
import { Platform as PlatformType, CustomUserAgent } from '../types';
import { getAmplifyUserAgent, Platform } from '../Platform';
```

2023-03-23 18:36 UTC, cshfang commented on packages/datastore/__tests__/mutation.test.ts
> +import { Constants, Category, Framework } from '@aws-amplify/core';
Just a thought/question but should these be exported from the root core? Can we have them be exported on a scoped path instead, especially keeping V6 propositions ahead?

2023-03-23 19:34 UTC, erinleigh90 commented on packages/core/__tests__/Platform-test.ts
>  		test('without content', () => {
Right, the getAmplifyUserAgent used to take a param called content, now it takes customUserAgent. Will update on this iteration.

2023-03-23 19:39 UTC, erinleigh90 commented on packages/core/src/types/types.ts
> +export type Platform = {
I'm not sure what happened here, I think this was a holdover from someone else's unrelated change that has since disappeared. Will remove.

2023-03-24 00:18 UTC, erinleigh90 commented on packages/core/__tests__/Platform-test.ts
> +import { Category, Framework } from '../src';
I moved the Category and Framework definition to the Platform folder and updated the import to come from '../src/Platform/types', but I don't know if that truly resolves this item, since the core library still needs to export these unless we go with exporting on a scoped path. I'll discuss with the team.

2023-03-24 00:24 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +	return `(${Object.values(userAgentDetails).sort().toString()})`;
Yes, missed porting this change over to the clean feature branch, thank you!

2023-03-27 15:20 UTC, jimblanc commented on packages/core/src/Platform/detectFramework.ts
> +		)
We'll need to make sure this utility is safe on Node (SSR) and RN as well, `document` & `window` won't be available on Node for example. We could just have another set of matches that gets run first that could short circuit this if they're not available.

2023-03-27 15:20 UTC, jimblanc commented on packages/datastore/__tests__/mutation.test.ts
> +import { Constants, Category, Framework } from '@aws-amplify/core';
In this case for v5, I'd probably prefer not changing our module exports to minimize risk (just until we can iron out the practicalities of doing so, e.g. Dustin's PR to `next`). Either way, the exports would still be part of our public API surface.

2023-03-30 23:14 UTC, david-mcafee requested changes
Left some feedback specifically around the framework detection :)

2023-03-30 23:14 UTC, david-mcafee commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
Why do we pass `isReactNative` instead of detecting it here?

2023-03-30 23:14 UTC, david-mcafee commented on packages/core/src/Platform/types.ts
> +	DataStoreJitteredRetry = '4',
Not blocking, just curious: looks like we aren't actually logging these actions anywhere, is that part2 / 3 of user agent enhancements? Would love to discuss offline what actions we are thinking of adding for API + DataStore!

2023-03-30 23:19 UTC, erinleigh90 commented on packages/core/src/Platform/types.ts
> +	DataStoreJitteredRetry = '4',
Yeah, part 4. Will reduce the final project to just what is going in but need to make sure the format works with action.

2023-03-30 23:20 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
Good point 😁

2023-03-30 23:22 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Interesting! I will definitely check on that, there are quite a few global variables related to react, we can probably just look for the global hook in general here. If you have apps that are setup for various react setups I would love to check them out for testing! 

Framework detection is Part III officially so this is the first run at React so we can make sure the format is coming through as we want it. I don't think this should block a merge into the feature branch.

2023-03-30 23:28 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
I guess the only benefit is we aren't pulling in framework here just for reactnative, detectFramework will return the framework result. It keeps platform/index clean of Framework.XXXX

2023-03-30 23:46 UTC, david-mcafee commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
Hm, to me, it just seems odd that the concern of this function is to either 1) detect the framework, or 2) return the Framework name when passed a boolean. If I was debugging this, I would be confused, since I'd expect framework detection to happen in a single place. What do you think?

2023-03-31 13:40 UTC, stocaaro reviewed
Structure makes sense. Have a few nits and one piece of structural preference. Happy to clarify if my comments need it.

2023-03-31 13:40 UTC, stocaaro commented on packages/core/src/Platform/types.ts
> +	None = '0',
Maybe I'm wrong. The right hand values are still numbers, aren't they?

2023-03-31 13:40 UTC, stocaaro commented on packages/core/src/Platform/index.ts
> +	}
This feels like it could be code golfed into something a bit more concise without making it less readable. Maybe:
```ts
userAgentTuples.map(([agentKey, agentValue]) => `${agentKey}/${agentValue ?? ""}`).join(" ")
```

2023-03-31 13:40 UTC, stocaaro commented on packages/core/src/Platform/index.ts
> +const buildUserAgentTuples = (
Would it make more sense for the AWSUserAgent to know how to translate itself into tuples? If this object is publicly exposed, could we decorate it into an object that knows how to translate it to make the translation more of an "is a" vs the current "has a" type of action?

In usage, thinking that `customUserAgent.tuples` or `(new CustomerUserAgentTranslator(userAgent)).tuples` would be more concise and direct in this code, where internally, this could be making `this` refs to access its members.

2023-03-31 14:22 UTC, jimblanc commented on packages/core/src/Platform/detectFramework.ts
> +	const extendedWindow = window as ExtendedWindow;
Along the lines of what we were discussing, we should make sure `window` exists as well before we try to use it.

2023-03-31 14:22 UTC, jimblanc commented on packages/core/src/Platform/index.ts
> +import { UserAgent as AWSUserAgent } from '@aws-sdk/types';
Nit-pick unrelated to your change, but we might want to move `"@aws-sdk/types": "3.6.1",` to `devDependencies`. 

Also this type is fairly simple:

```
/**
 * @public
 *
 * A tuple that represents an API name and optional version
 * of a library built using the AWS SDK.
 */
export type UserAgentPair = [name: string, version?: string];

/**
 * @public
 *
 * User agent data that to be put into the request's user
 * agent.
 */
export type UserAgent = UserAgentPair[];
```

I wonder if we could just duplicate this locally in order to avoid another code dependency on the SDK? Might be more pertinent once we start on the custom clients, just something to consider though.

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	};
+1 I was trying to add this comment yesterday from my phone but decided to review more properly in front of a computer. To add to @stocaaro 's suggestion, I do believe all the properties we are accessing from `customUserAgent` are primitives as well.

I would take it a step further and directly destructure the properties you need to inspect/copy directly on the params to improve readability in the body of this function. E.g.
```
const buildUserAgentTuples = (
  { action, category, framework }: CustomUserAgent = {}
```

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +		userAgentTuples.push([userAgentDetails.category, userAgentDetails.action]);
Does this imply `action` is guaranteed to be present just because `category` is? If so, we may want/need to convey this hard correlation via typing

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	}
I think this can be simplified to improve readability
```suggestion
	userAgentTuples.push([
	  'framework,
	  userAgentDetails.framework ?? detectFramework(Platform.isReactNative)
	]);
```

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +};
Nit:
```suggestion
): AWSUserAgent => buildUserAgentTuples(customUserAgent);
```

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +export const getAmplifyUserAgent = (
Similar line of thinking here - I don't think we have a need to extract the build logic from this function considering this function does nothing except to return the result of that build logic.

Suggestion:
*remove* `getAmplifyUserAgent`
*rename* `buildUserAgentTuples` => `getAmplifyUserAgent`
*update usage of* `buildUserAgentTuples` => `getAmplifyUserAgent`

2023-03-31 17:30 UTC, cshfang commented on packages/core/src/index.ts
> +	Framework,
Nit: I personally think there is value in alphabetizing imports for readability but this already looks much cleaner than before thank you!

2023-03-31 17:39 UTC, erinleigh90 commented on packages/core/src/Platform/types.ts
> +	None = '0',
Right, for framework they are still numbers.

2023-03-31 17:46 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
To make this clear: we are currently detecting ReactNative in an almost deprecated way. I don't want to double down on that, but it's something we can use for now to have this change not break RN customers, until I get to Part III of development (detection of frameworks). I think my solution right now is to move detect framework changes to a new branch so we can merge part1, so it doesn't block all downstream work from getting reviewed.

I also want to bring up that reworking Platform was not part of my original scope, and while it's not a large file, it may be wise to look into Platform refactor as a follow-up to this project, since we are trying to get the user agent enhancements out as soon as possible.

2023-03-31 17:46 UTC, david-mcafee commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
@cshfang - see my comment above, but I'm not sure that checking the renderers size is a valid way to detect React, as the value changes whether or not React Dev Tools is enabled (`1` when enabled, `0` when disabled).

We can possibly change the condition to `size >= 0`, but I haven't done enough digging into this to know if that's the best practice for detecting React, here.

2023-03-31 17:46 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
Note: none of this code will actually be shipped until Part III is complete.

2023-03-31 17:47 UTC, david-mcafee commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
```suggestion
/**
 * TODO: revisit React platform detection logic:
 * currently, the value of `renderers.size` is
 * affected by whether React Dev Tools is enabled.
 */
	if (
		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__ &&
		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size >= 0
```

2023-03-31 17:48 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +	}
Nice! Way better.

2023-03-31 17:49 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +	};
Oh yes, holdover from the previous iteration. It made sense then, not so much now.

Chris, thank you for that, makes a whole lot of sense.

2023-03-31 17:54 UTC, david-mcafee commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Also, as I mentioned before, I think it would be beneficial to add comments clarifying how things are working in this file, and some of the reasoning around why we're detecting platforms the way we are.

2023-03-31 19:40 UTC, cshfang commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Yeah I should've been clear that I was not commenting on whether this is the correct way to detect the framework, only that the logic can be simplified

2023-03-31 21:07 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +export const detectFramework = (isReactNative: Boolean): Framework => {
Resolving this for this PR Since I moved this code. Super helpful conversation for later reference. Thank you!

2023-03-31 21:31 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Thank you for the feedback. Moving the code to a part 3 branch and resolving for now, will reference when I start moving on part 3.

2023-03-31 21:32 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +interface ExtendedWindow extends Window {
Marking as resolved for now but will reference when I move to part 3

2023-03-31 22:45 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	}
I just noticed a comment of mine got lost into the ether..

I think this can be made more concise without losing clarity:
```suggestion
	userAgentTuples.push(['framework', userAgentDetails.framework ? userAgentDetails.framework : detectFramework()]);
```

2023-04-06 17:39 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Resolving for now, will address in Phase 3

2023-04-06 21:23 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +const buildUserAgentTuples = (
Going to go with Chris here.

2023-04-06 21:41 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +	const extendedWindow = window as ExtendedWindow;
Will refer back to this in part 3, resolving for now as this code has been removed

2023-04-06 21:55 UTC, erinleigh90 commented on packages/core/src/Platform/detectFramework.ts
> +		extendedWindow.__REACT_DEVTOOLS_GLOBAL_HOOK__.renderers.size > 0
Resolving, moved code to part 3 branch.

2023-04-12 18:59 UTC, stocaaro approved these changes

2023-04-14 22:34 UTC, AllanZhengYP approved these changes
Looks good to me! 🚀

2023-04-14 23:31 UTC, david-mcafee approved these changes
LGTM!

2023-04-17 14:49 UTC, jimblanc requested changes
Looks good! Some nits below

2023-04-17 14:49 UTC, jimblanc commented on packages/core/package.json
> +		"@aws-sdk/types": "3.6.1"
Nit-pick: This should be at the top of the list (alphabetical)

2023-04-17 14:49 UTC, jimblanc commented on packages/core/src/Platform/detectFramework.ts
> +import { Framework } from './types';
This file needs the copyright header.

```suggestion
// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import { Framework } from './types';
```

2023-04-17 14:49 UTC, jimblanc commented on packages/core/src/Platform/index.ts
> +// Other frameworks may not be detected in cases where DOM is not yet loaded
Nit: Since this is a function, we should use a proper doc-string format:

```suggestion
/**
 * Rerun framework detection once when getAmplifyUserAgent is called if framework is None.
 * ReactNative framework must be detected initially, however other frameworks may not be 
 * detected in cases where DOM is not yet loaded.
 */
```

2023-04-17 14:49 UTC, jimblanc commented on packages/core/src/Platform/index.ts
> +		Platform.framework = framework;
```suggestion
        framework = detectFramework();
		frameworkHasBeenRerun = true;
		Platform.framework = framework;
```

Nit: Run detection first then update states

2023-04-17 15:40 UTC, cshfang commented on packages/core/src/Platform/index.ts
> +	isReactNative: framework === Framework.ReactNative,
Is this just for backward compatibility? Can it be either removed (always rely on comparing framework) or extracted (separate convenience util for checking framework is RN) in V6?

2023-04-17 15:42 UTC, cshfang commented on packages/core/src/Platform/index.ts
>  		/** TODO: add action as second element */
Is this TODO still valid?

2023-04-17 15:44 UTC, cshfang commented on packages/core/src/Platform/types.ts
> +}
Will this get wrapped into Notifications or should we also have an `InAppMessagingAction` enum?

2023-04-17 15:45 UTC, cshfang approved these changes

2023-04-18 15:48 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
> +	isReactNative: framework === Framework.ReactNative,
Yes, this is for backward compatibility, hopefully we can remove the need for this in V6 and move away from the use of navigator.product as well.

2023-04-18 15:48 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
>  		/** TODO: add action as second element */
Nope!

2023-04-18 15:49 UTC, erinleigh90 commented on packages/core/src/Platform/types.ts
> +}
Each category will have it's own action enum. If I missed any in this first pass they will get added as I work on categories.

2023-04-18 16:00 UTC, cshfang approved these changes

2023-04-18 16:07 UTC, jimblanc approved these changes

2023-04-18 16:20 UTC, stocaaro approved these changes

2023-04-18 17:18 UTC, merged

2023-06-20 00:57 UTC, johnf commented
@erinleigh90 There are lots of changes related to this in the 5.3.0 release.
Is there any documentation regarding what this is all about.
It would be amazing of the release notes could expand on larger changes like this.