feat(Auth): resetPassword API rewrite + tests
aws-amplify/amplify-js pull request #11207
Opened 2023-04-07 22:18 UTC by helgabalashova

#### Description of changes
Auth resetPassword API rewrite

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-11 16:12 UTC, haverchuck commented on packages/auth/__tests__/providers/cognito/resetPassword.test.ts
> +describe('ResetPassword API happy pathes', () => {
Nit: "pathes -> paths"

2023-04-12 16:07 UTC, jimblanc approved these changes
Looks good! Some nits below

2023-04-12 16:07 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/resetPassword.ts
> +	}
I don't think we need to do it now, but looking and your & Israel's PRs it seems like this pattern would be repeated for all APIs. I wonder if it makes sense to push this down into the client itself (i.e. `UserPoolHttpClient`) and let the AuthError bubble up unless an API needed some unique error handling.

2023-04-12 16:07 UTC, jimblanc commented on packages/auth/src/types/index.ts
> +export type { ResetPasswordResult } from './results/ResetPasswordResult';
Didn't catch this on the other PR, but I wonder if the type aliases are really required here since these are our types and the names are the same. 

```suggestion
export { AuthUserAttributeKey } from './models/AuthUserAttributeKey';
export { AuthUserAttribute } from './models/AuthUserAttribute';
export { GetAttributeKey } from './models/GetAttributeKey';
export { AuthNextResetPasswordStep } from './models/AuthNextResetPasswordStep';

// Options
export { AuthServiceOptions } from './options/AuthServiceOptions';
export { AuthSignUpOptions } from './options/AuthSignUpOptions';

// Requests
export { ResetPasswordRequest } from './requests/ResetPasswordRequest';
export { SignUpRequest } from './requests/SignUpRequest';

// Results
export { AuthSignUpResult } from './results/AuthSignUpResult';
export { ResetPasswordResult } from './results/ResetPasswordResult';
```

For some reason GitHub won't let me comment on the entire list, but the others above my suggestion can probably be changed as well.

2023-04-12 17:51 UTC, helgabalashova commented on packages/auth/__tests__/providers/cognito/testUtils/authApiTestParams.ts
> +		ClientMetadata: {foo: 'bar'}
command parameters are all CamelCase (we follow the same patter as aws-sdk)

2023-04-12 18:58 UTC, jimblanc submitted a review, later dismissed

2023-04-14 16:36 UTC, haverchuck commented on packages/auth/src/providers/cognito/apis/resetPassword.ts
> +	}
@jimblanc What you are saying is that instead of intercepting the missing username, we just let it go to the Cognito service and return the Cognito erorr?

I tend to agree with that. It seems nice to prevent a round trip, but trying to do 1-off validation handling like this could lead to inconsistencies.

2023-04-14 16:36 UTC, haverchuck requested changes
Commented on Jim's comment.

2023-04-14 16:53 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/resetPassword.ts
> +	}
My suggestion was more about just moving this "common" error handling down a level or two, since this try-catch is essentially just checking for unknown service errors + wrapping any errors in an AuthError. The same logic exists in [signUp](https://github.com/aws-amplify/amplify-js/pull/11153/files#diff-8b8e0c0eaa2c2b2add12d12aae99d2583f07e8a42f9d585bd3b80aad86c0aad8R105) and I imagine it would exist in the other APIs as well by default unless we needed to do some special error handling for particular APIs.

Regarding the pre-request validation, I think I'm ambivalent. I like preventing the unneeded round trip (which might have benefits as far as avoiding cognito throttling, extra network calls, etc.), but keeping client-side validation in sync with the service is always tricky. Now that I think about it though, I wonder if we can just lean on TypeScript to enforce this type of basic validation?

2023-04-14 17:37 UTC, haverchuck commented on packages/auth/src/providers/cognito/apis/resetPassword.ts
> +	}
Argh, sorry @jimblanc I think I misread your comment (or rather applied your comment to the wrong block of code). Moving the wrapping of the service error into an AuthError seems like something that could definitely go into the client abstraction layer.

@helgabalashova Could you make that change for both resetPassword and signUp, if you agree with this?

2023-04-18 22:06 UTC, jimblanc approved these changes
Looks good! Thank you for the refactor.

2023-04-20 15:11 UTC, haverchuck commented on packages/auth/__tests__/providers/cognito/resetPassword.test.ts
> +					CodeDeliveryDetails: {
@helgabalashova @jimblanc How would we feel about peeling out re-used things like CodeDeliveryDetails objects into test utils for re-use?

2023-04-20 15:14 UTC, haverchuck commented on packages/auth/__tests__/providers/cognito/resetPassword.test.ts
> +					CodeDeliveryDetails: {
We could make these changes to signUp test as well. If you think it's overkill, I'm fine with this as is.

2023-04-20 15:16 UTC, haverchuck approved these changes
Left a suggestion for the tests, but I'm fine with this PR as-is if you disagree.

2023-04-20 17:04 UTC, merged