feat(clients): Add custom signature v4 signer
aws-amplify/amplify-js pull request #11273
Opened 2023-04-19 23:38 UTC by cshfang

#### Description of changes

This PR adds an updated sigv4 signer that is more type-safe, consistent with our updated conventions and functional (i.e. not using class) than `Signer.ts`.

#### Description of how you validated changes
Locally tested:
* `signRequest` vs `Signer.sign` to validate output is the same
* `presignUrl` vs `Signer.signUrl` to validate output is the same

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-20 00:11 UTC, elorzafe requested changes
Looks good, just add some docstrings missing

Thanks @cshfang !

2023-04-20 00:11 UTC, elorzafe commented on packages/core/src/clients/middleware/signing/middleware.ts
> +export const signing: Middleware<HttpRequest, HttpResponse, SigningOptions> =
Mentioning @svidgen , we need docstrings here?

2023-04-20 00:11 UTC, elorzafe commented on packages/core/src/clients/middleware/signing/signer/signatureV4/presignUrl.ts
> +export const presignUrl = async (
@svidgen would say docstrings here

2023-04-20 00:11 UTC, elorzafe commented on packages/core/src/clients/middleware/signing/signer/signatureV4/signRequest.ts
> +export const signRequest = async (
docstrings

2023-04-20 00:11 UTC, elorzafe commented on packages/core/src/clients/middleware/signing/utils/getClockOffset.ts
> +export const getClockOffset = (
docstrings here

2023-04-20 00:13 UTC, cshfang commented on packages/core/src/clients/middleware/signing/utils/getClockOffset.ts
> +export const getClockOffset = (
Oh let me remove some files from this PR. This isn't really fully done yet

2023-04-20 00:20 UTC, AllanZhengYP reviewed
Looks good to me! 

Since we will use this signer more intensively, maybe add the Signature v4 test vector to the unit test?

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts
> +	key: SourceData | null,
Nit: This type is specific to AWS SDK. A more general type of WebCrypto hasher's data should be `BufferSource`

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/presignUrl.ts
> +export const presignUrl = async (
This function shares a lot of code with `signRequest`. Is it possible to craft the input request and call the signRequest instead?

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest.ts
> +	body,
Indentation here is different to other files under the `utils` folder.

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalUri.ts
Not sure what's wrong here but different files under `utils` folder have different indentations.

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +	if (isNil(body)) {
Nit: Not sure if it is necessary, compared to `body==null`

2023-04-20 00:20 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +	if (isNil(body)) {
Or remove this if-statement?

2023-04-20 00:52 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +	if (isNil(body)) {
We don't have strict null checking so it could be null or undefined right? Maybe after updating types per comment above this will change but I think we do need to account for anything other than null undefined or whatever qualified under SourceData.. otherwise UNSIGNED_PAYLOAD. But I borrowed some of this logic from the SDK - maybe we don't need it

2023-04-20 03:34 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest.ts
> +	body,
I'm not sure what you're seeing but everything looks consistent to me 🤔

2023-04-20 03:35 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalUri.ts
I'm not sure what you're seeing but everything looks consistent to me 🤔

2023-04-20 03:54 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts
> +	key: SourceData | null,
Hmm are we planning to also ship our own crypto utils? If we using @aws-crypto, then continuing to use `SourceData` seems accurate

2023-04-20 04:39 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/presignUrl.ts
> +export const presignUrl = async (
I extracted the common portions of the code out:
1. Extract common values via a shared function
2. Build requests to sign
3. Pass the build requests to a shared function to get a signature
4. Add the signature to either the request or the URL

2023-04-20 16:47 UTC, AllanZhengYP reviewed
It's in a good shape now. I only have 1 comment left

2023-04-20 16:47 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +import isNil from 'lodash/isNil';
I don't think ladash is added to the core's package.json

2023-04-20 17:16 UTC, elorzafe reviewed
Are you adding unit tests?

2023-04-20 17:31 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +	if (isNil(body)) {
I just realized your original proposal was `body == null` not `body === null`

2023-04-20 17:40 UTC, AllanZhengYP approved these changes
It looks good to me! Thank you @cshfang

2023-04-21 20:10 UTC, AllanZhengYP approved these changes
Approve again!

2023-04-24 16:29 UTC, elorzafe approved these changes
Great work @cshfang ! 🏅

2023-04-24 16:47 UTC, jimblanc approved these changes
Looks good to me, nice work! Some minor comments below.

2023-04-24 16:47 UTC, jimblanc commented on packages/core/__tests__/clients/middleware/signing/signer/signatureV4/testUtils/signingTestTable.ts
> +export const signingTestTable: TestCase[] = [
Really appreciate the thorough test matrix 🙂

2023-04-24 16:47 UTC, jimblanc commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts
> +import { toHex } from '@aws-sdk/util-hex-encoding';
We can include this with your v6 TODO comment above, but both of these utilities appear pretty simple and we might be able to just duplicate them to avoid the dependency like you did for `toUint8Array`.

2023-04-24 16:47 UTC, jimblanc commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +import { isArrayBuffer } from '@aws-sdk/is-array-buffer';
Ditto about duplicating this, super simple util: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/is-array-buffer/src/index.ts

2023-04-24 16:52 UTC, jimblanc commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts
> +import { toHex } from '@aws-sdk/util-hex-encoding';
Discussed offline, but should add explicit dependencies for these as well if we can't duplicate them right away.

2023-04-24 20:09 UTC, AllanZhengYP commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +import { isArrayBuffer } from '@aws-sdk/is-array-buffer';
+1. This package is also marked as internal package by SDK team ([link](https://github.com/aws/aws-sdk-js-v3/blob/master/packages/is-array-buffer/README.md)). Even though it won't change often, depending on it gives us a bad looking.

2023-04-24 20:18 UTC, cshfang commented on packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts
> +import { isArrayBuffer } from '@aws-sdk/is-array-buffer';
That's a good point. I will extract and expand on unit tests

2023-04-24 20:20 UTC, jimblanc approved these changes

2023-04-24 20:31 UTC, AllanZhengYP approved these changes

2023-04-24 21:09 UTC, merged