feat(auth): resendSignUpCode API
aws-amplify/amplify-js pull request #11281
Opened 2023-04-20 21:49 UTC by Samaritan1011001

#### Description of changes

Adds the re-written resendSignUpCode API with the necessary types and clients

#### Issue #, if available

#### Description of how you validated changes
TODO: validate the changes on a sample app

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-20 23:42 UTC, helgabalashova reviewed
I left you a couple of comments. Also, I don't think you add new types to types index file

2023-04-20 23:42 UTC, helgabalashova commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +	try {
no need to have try/catch block here since we moved this error handling to http client

2023-04-20 23:42 UTC, helgabalashova commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +export async function resendSignUpCode<
function type is definitely different (look at how signUp and resetPassword are defined now). I think you can check with @israx on latest changes

2023-04-20 23:42 UTC, helgabalashova commented on packages/auth/src/providers/cognito/index.ts
> +export type { CognitoUserAttributeKey } from './types/models/CognitoUserAttributeKey';
no need for type here. I fixed it in one of my PRs (make sure your branch is up to date)

2023-04-21 21:29 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/index.ts
> +export type { CognitoUserAttributeKey } from './types/models/CognitoUserAttributeKey';
Not sure what the fix is, can you point me to the changes you made and where I should get these types from?

2023-04-21 21:33 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/index.ts
> +export type { CognitoUserAttributeKey } from './types/models/CognitoUserAttributeKey';
Removed a few but `CognitoUserAttributeKey` and `AuthPluginOptions` still needs to be exported here right? 
Can you point me to the fix you mention?

2023-04-21 22:22 UTC, israx requested changes

2023-04-24 17:36 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> + * @throws service: {@link SignUpException } - Cognito service errors thrown during the sign-up process.
More of a quesion of coding pattern: Should we use `@throws` in all the upcoming PRs? 

I usually don't use the `@throws` because it's very hard to have an exhausted list of errors in JS generally. Networking errors or runtime errors are likely to be thrown too. This is why TS models the errors as `unknown`. 
But it seems like we are going to have each line of code caught and re-wrapped by `SignUpException`.

2023-05-09 01:14 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> + * @throws service: {@link SignUpException } - Cognito service errors thrown during the sign-up process.
Thanks, I had to update the doc string. But still have the `@throws` so what would you recommend otherwise. I followe `signUp` API's lead on the patterns.

2023-05-09 01:16 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +	ServiceOptions extends AuthServiceOptions
Made this change but ServiceOptions are unused as I use `resendRequest.options?.serviceOptions?.clientMetadata`. 
If we are removing generics then I remove `ServiceOptions extends AuthServiceOptions` altogether?

2023-05-09 12:35 UTC, israx commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +	ServiceOptions extends AuthServiceOptions
yeah and we are just passing `CognitoResendSignUpCodeOptions` as type argument directly in the request instead

2023-05-10 00:02 UTC, elorzafe reviewed
Is lookng very good @Samaritan1011001 

I think we need some tests unless I am missing something

Thanks!

2023-05-10 00:02 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/HttpClients.ts
>  const USER_AGENT = 'amplify test';
I would add a `TODO` here

2023-05-10 00:02 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/ResendSignUpCodeClient.ts
> +} from '@aws-sdk/client-cognito-identity-provider';
We should not use `@aws-sdk` this time

2023-05-10 20:19 UTC, israx commented on packages/auth/src/providers/cognito/types/options/AuthPluginOptions.ts
> +export type AuthPluginOptions = any;
We should remove it, I think `AuthServiceOptions` is used instead

2023-05-10 20:22 UTC, israx commented on packages/auth/src/providers/cognito/utils/clients/ResendSignUpCodeClient.ts
> +} from '@aws-sdk/client-cognito-identity-provider';
All the current implemented APIs on next are using the aws-sdk types for now. Probably just adding a TODO for replacing all the commands if that is the intention in the future.

2023-05-10 20:24 UTC, israx commented on packages/auth/src/providers/cognito/utils/clients/ResendSignUpCodeClient.ts
> +} from '@aws-sdk/client-cognito-identity-provider';
This wound't add any additional bundle size as these commands are just used as types

2023-05-11 19:37 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/ResendSignUpCodeClient.ts
> +} from '@aws-sdk/client-cognito-identity-provider';
can we add the `type` keyword to help review it please

2023-05-11 19:38 UTC, elorzafe submitted a review, later dismissed
Looks good, a nit comment if you can add `type` keyword on the imported types.

Thanks @Samaritan1011001

2023-05-12 19:46 UTC, AllanZhengYP reviewed
This PR looks good to me, I only have 2 aesthetic feedbacks

2023-05-12 19:46 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +	};
Maybe cleaner to use the desturcture, it will look like
```suggestion
	const { CodeDeliveryDetails: {
	  DeliveryMedium,
	  AttributeName,
	  Destination,
	 } }: ResendConfirmationCodeCommandOutput =
		await resendSignUpConfirmationCodeClient({
			Username: username,
			ClientMetadata:
				resendRequest.options?.serviceOptions?.clientMetadata ??
				config.clientMetadata,
		});
```

2023-05-12 19:46 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/index.ts
> +// apis
Very nit: I don't think `// apis` and `// models`, `// options` comment are really necessary. Grouping in lines and the import path is pretty self-explanatory

2023-05-12 20:24 UTC, israx approved these changes
Thanks Manoj. It is looking good. The only update left I think is to import all the sdk commands as `types`.

2023-05-12 20:24 UTC, israx commented on packages/auth/src/providers/cognito/utils/clients/ResendSignUpCodeClient.ts
> +import {
I think here we are missing the `type` syntax annotation

2023-05-17 18:37 UTC, israx approved these changes

2023-05-18 17:51 UTC, elorzafe approved these changes
Great work @Samaritan1011001 🎖️

2023-05-18 18:26 UTC, AllanZhengYP approved these changes
Looks good to me!

2023-05-18 18:35 UTC, merged