feat(auth): add SRP sign-in API
aws-amplify/amplify-js pull request #11372
Opened 2023-05-15 21:09 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-15 21:53 UTC, elorzafe commented on packages/auth/src/providers/cognito/index.ts
> +export { signInWithSRP } from './apis/signInWithSRP';
We don't have to export this on public facing APIs/

2023-05-16 18:50 UTC, AllanZhengYP approved these changes
Looks good to me. Only have a minor naming question

2023-05-16 18:50 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/utils/internalAuthSession.ts
> +export function setInternalAuthSession(session: string | undefined) {
According to the purpose, will it be better to be named `setActiveSignInSession()`? `Internal` is a bit over-generalized.

2023-05-16 18:50 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +	const authenticationHelper = new AuthenticationHelper(userPoolName);
This is not a blocking comment -- I hope we can make this class functional in the future.

2023-05-16 20:00 UTC, AllanZhengYP submitted a review, later dismissed

2023-05-17 17:54 UTC, elorzafe requested changes
PR looking good, thanks @israx my only concern is the types that we are exporting will bloat the list of possible things for customers to import. Can we remove those exported types and then add those incrementally when is needed.

2023-05-17 17:54 UTC, elorzafe commented on packages/auth/src/providers/cognito/index.ts
> +export { AuthFlowType } from './types/models/AuthFlowType';
do we need to export all these types?

2023-05-18 20:20 UTC, haverchuck commented on packages/auth/src/providers/cognito/index.ts
> +export { AuthFlowType } from './types/models/AuthFlowType';
Why don't we just export `AuthFlowType` for now, and we can figure out the rest later?

2023-05-19 22:49 UTC, AllanZhengYP approved these changes

2023-05-19 22:49 UTC, AllanZhengYP commented on packages/auth/__tests__/providers/cognito/signInWithSRP.test.ts
> +				}
Very nit:
```suggestion
				async (): Promise<RespondToAuthChallengeCommandOutput> =>
					authAPITestParams.RespondToAuthChallengeCommandOutput;
```

2023-05-19 22:49 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/types/options/CognitoResetPasswordOptions.ts
> +import { ClientMetadata } from "../models/ClientMetadata";
Very nit: 
```suggestion
import { ClientMetadata } from '../models/ClientMetadata';
```

2023-05-22 17:20 UTC, elorzafe approved these changes

2023-05-22 17:23 UTC, AllanZhengYP approved these changes

2023-05-22 17:24 UTC, merged