feat(core): Consistent API detection pattern with stubs for 8 framework targets
aws-amplify/amplify-js pull request #11384
Opened 2023-05-17 20:45 UTC by stocaaro

#### Description of changes
Framework detection for custom user agent

Mapping and logic to cover all of:
```ts
	// < 100 - Web frameworks
	WebUnknown = '0',
	React = '1',
	NextJs = '2',
	Angular = '3',
	VueJs = '4',
	Nuxt = '5',
	Svelte = '6',

	// 100s - Server side frameworks
	ServerSideUnknown = '100',
	ReactSSR = '101',
	NextJsSSR = '102',
	AngularSSR = '103',
	VueJsSSR = '104',
	NuxtSSR = '105',
	SvelteSSR = '106',

	// 200s - Mobile framework
	ReactNative = '201',
	Expo = '202',
```

#### Description of how you validated changes
Tested by building sample apps to cover the supported framework detection methods.

Updated tests to exercise the behavior, including adding testing for Unknown type retry after an interval.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-17 23:03 UTC, jimblanc requested changes
Nice work! I like this approach, very clean. One blocking comment for the copyright stuff, but otherwise LGTM

2023-05-17 23:35 UTC, AllanZhengYP approved these changes
Looks good to me on top of other comments. 

It'll be really helpful if more description is added regarding the rationales of the solution(like the timeout detetion).

2023-05-18 14:33 UTC, stocaaro commented on packages/core/src/Platform/Detection/Angular.ts
> +export function angularWebDetect() {
On it. Agreed that this will represent an ongoing effort. It'll be interesting to see what % of use this covers in the wild.

2023-05-18 14:34 UTC, stocaaro commented on packages/core/src/Platform/Detection/Angular.ts
> +import { processExists, windowExists } from './helpers';
Ack. Might be worth linting for this so we aren't dependent upon your/someone's attention to detail.

2023-05-18 19:08 UTC, erinleigh90 approved these changes
Just had one question on retry, but not blocking. LGTM!

2023-05-18 19:08 UTC, erinleigh90 commented on packages/core/src/Platform/index.ts
>  const rerunFrameworkDetection = () => {
Do we need the rerun of framework detection to be controlled both here and in detectFramework, or would it be possible to consolidate the retry logic to one or the other?

2023-05-18 21:46 UTC, stocaaro commented on packages/core/src/Platform/index.ts
>  const rerunFrameworkDetection = () => {
You make a good point.  I hadn't looked up the call stack to identify this alternative solution. For the usecase that I had encountered, I'm not sure that this would consistently reset to the correct value without a time delay to guarantee space for the runtime to get setup. I've gone ahead and updated this to keep the interface, but delay execution until usage using `get` methods. We can sync on if this is the right way to approach the problem.

2023-05-22 13:07 UTC, jimblanc approved these changes

2023-05-22 14:27 UTC, merged