feat: custom user agent Auth changes for UI handoff
aws-amplify/amplify-js pull request #11606
Opened 2023-07-10 21:57 UTC by erinleigh90

#### Description of changes
Creates and exports InternalAuth class from /internals scope with added customUserAgentDetails parameter on public API's.

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-04 23:07 UTC, stocaaro submitted a review, later dismissed
Got my [version diff](https://github.com/aws-amplify/amplify-js/pull/11606/files/cfe55be8a75c90eced61ffd43cf90f841992fc15..01d5c2e10eecff0b6ef8b07a5d76477112b4753e#diff-d6abeead864c341b445fb8f3021ac370aec8e25133d51edd99641df7c1284b68) figured on this one.

LGTM

2023-08-05 00:22 UTC, jimblanc requested changes
Need to confirm the visibility of `internalSignUp` on the customer-facing class, otherwise looks okay

2023-08-05 00:22 UTC, jimblanc commented on packages/auth/src/internals/InternalAuth.ts
> +	public internalSignUp(
Won't this API be exposed on the customer facing `Auth` class (which extends from this) as well?

2023-08-07 18:22 UTC, erinleigh90 commented on packages/auth/src/internals/InternalAuth.ts
> +	public internalSignUp(
Yes, you are right, thank you for catching!

2023-08-07 20:49 UTC, jimblanc submitted a review, later dismissed
Looks good!

2023-08-07 20:54 UTC, elorzafe submitted a review, later dismissed
Looks good!

Thanks @erinleigh90 🥇

2023-08-07 20:59 UTC, elorzafe approved these changes

2023-08-07 21:01 UTC, jimblanc submitted a review, later dismissed

2023-08-07 21:25 UTC, elorzafe approved these changes

2023-08-07 21:26 UTC, david-mcafee approved these changes
Approving bundle size limit increases on behalf of the Data team.

2023-08-07 21:26 UTC, jimblanc approved these changes

2023-08-07 21:33 UTC, merged