feat: custom user agent CognitoUser changes for UI handoff
aws-amplify/amplify-js pull request #11643
Opened 2023-07-18 04:22 UTC by erinleigh90

#### Description of changes
- Creates and exports InternalCognitoUser class from /internals scope with added customUserAgentDetails parameter on public API's that result in service calls
- Sends received customUserAgentDetails through to storage service calls
- Send user agent information from Auth to CognitoUser

NOTES
- To see the changes to InternalCognitoUser after moving the changes over from CognitoUser, see [this comparison](https://github.com/erinleigh90/amplify-js/compare/378bc6b8575ebf8a111bbf0b062f83bf42b425ae...badcffcf7d930d8dfc5435fb28d7f14fcbaf3ec6#diff-e663fb319a13d200f6200fed8357e4975cbe1171a9743d6b8f9720fc852ac83e)

#### Description of how you validated changes
yarn tests pass

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x]  Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-18 23:30 UTC, elorzafe requested changes
Overall looks good @erinleigh90 

My only concern is `InternalCognitoUserPool` is not `extended` by the external one.

2023-07-18 23:30 UTC, elorzafe commented on packages/amazon-cognito-identity-js/src/internals/InternalCognitoUserPool.js
> +export default class CognitoUserPool {
Should this be called `InternalCognitoUserPool`?

2023-07-18 23:30 UTC, elorzafe commented on packages/amazon-cognito-identity-js/src/internals/InternalCognitoUserPool.js
> +export default class CognitoUserPool {
Why `CognitoUserPool` class is not extending this one?

2023-07-19 00:50 UTC, jimblanc reviewed
Same concern as Francisco around the `CognitoUserPool` extension, but mostly looks good. It might be a good idea to run the integ tests against this branch just due to the volume of changes (too late now, but `--no-verify` would be useful here to avoid all the prettier changes).

2023-07-19 08:28 UTC, erinleigh90 commented on packages/amazon-cognito-identity-js/src/internals/InternalCognitoUserPool.js
> +export default class CognitoUserPool {
Removed this class, that will be a separate PR for CognitoUserPool changes.

2023-07-19 13:08 UTC, israx requested changes
User agent changes look good. I really wanna see this metrics. 

My only concern is about not changing the public facing API types. Although those changes are not breaking. Proposed return values don't align with return values for v6.

2023-07-19 13:37 UTC, jimblanc commented on .circleci/config.yml
> +      - feat/custom-user-agent-ui/cognito
Hum appears this didn't trigger a run in circle CI. Probably need to push feature branch to main repo (can keep the PR branch how it is).

2023-07-26 06:30 UTC, erinleigh90 commented on packages/amazon-cognito-identity-js/src/Client.js
Go back through and update jsdocs

2023-07-26 14:29 UTC, stocaaro submitted a review, later dismissed

2024-11-05 19:49 UTC, ashika112 commented
This feature was merged in the above linked PRs. Making this draft invalid. Closing this in favor of merged PRs :)

2024-11-05 19:49 UTC, closed without merging