feat(core): add storage mechanisms
aws-amplify/amplify-js pull request #11676
Opened 2023-07-25 14:33 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-25 20:37 UTC, elorzafe requested changes
Biggest concern is adding another dependency and maybe split the helpers in separate files just in case there are issue with tree shaking.

2023-07-25 20:37 UTC, elorzafe commented on packages/core/src/StorageHelper/reactnative.ts
> +class AsyncStorageClass implements KeyValueStorageInterface {
I would add a `TODO` that this needs to be included on `react-native` Amplify package

2023-07-25 20:37 UTC, elorzafe commented on packages/core/src/StorageHelper/index.ts
> +export const SessionStorage = new SessionStorageClass();
What if this is an abstract class, the logic is the same except the constructor, what do you think?

2023-07-25 20:37 UTC, elorzafe commented on packages/core/src/StorageHelper/index.ts
> +import * as Cookies from 'js-cookie';
Would this be tree shakable? maybe we need to add this to a different module?

2023-07-25 20:37 UTC, elorzafe commented on packages/core/package.json
> +		"js-cookie": "3.0.5"
Do we need to add another dependency? could be possible to not have this?

2023-07-26 15:59 UTC, israx commented on packages/core/package.json
> +		"js-cookie": "3.0.5"
Yeah I think we discussed this in the design already. Pretty much `js-cookie` is to handle the overwhelming cookies operations. The package is pretty light weight and well supported: https://www.npmjs.com/package/js-cookie

2023-07-26 20:33 UTC, israx commented on packages/core/src/StorageHelper/index.ts
> +export const SessionStorage = new SessionStorageClass();
I don't think an abstract class will be the right way. It seems to me that it is more like a hacky thing. I mean, yeah abstract classes can't be instantiated but they are mainly used for OOP scenarios. The other solution is just to have a class with static members.

2023-07-26 21:38 UTC, elorzafe submitted a review, later dismissed
Thanks @israx 

Good work 🏅

2023-07-27 14:07 UTC, jimblanc reviewed
Looks good! Some small comments below

2023-07-27 14:07 UTC, jimblanc commented on packages/core/package.json
> +		"js-cookie": "3.0.5"
Looks good but we might want to loosen up the dependency in-case customers have this in their graph as well

```suggestion
		"js-cookie": "^3.0.5"
```

2023-07-27 14:07 UTC, jimblanc commented on packages/core/src/index.ts
> +} from './StorageHelper';
Do we need to export these from the umbrella package as well so customers can customize them?

Here: https://github.com/aws-amplify/amplify-js/blob/next/packages/aws-amplify/src/utils/index.ts (`aws-amplify/utils` route)

2023-07-27 18:49 UTC, jimblanc approved these changes
Looks good!

2023-07-28 16:28 UTC, elorzafe approved these changes

2023-07-28 16:28 UTC, merged