Chore: Remove API & PubSub from `next` for dev preview
aws-amplify/amplify-js pull request #11692
Opened 2023-07-27 19:48 UTC by jimblanc

#### Description of changes

This change excludes API (GraphQL & Rest) & PubSub from the umbrella package for v6 dev preview.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-27 20:21 UTC, elorzafe requested changes
We also need to make `api-rest` as private

2023-07-27 20:39 UTC, israx approved these changes

2023-07-27 23:52 UTC, elorzafe approved these changes

2023-07-28 14:10 UTC, israx approved these changes

2023-07-28 14:13 UTC, merged