feat(storage): implement getProperties functional
aws-amplify/amplify-js pull request #11727
Opened 2023-08-04 19:12 UTC by kvramyasri7

#### Description of changes

Add `getProperties` functional implementation

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-07 16:31 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		const final_key =
nit:
```suggestion
		const finalKey =
```

2023-08-07 16:31 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +			Key: final_key,
```suggestion
			Key: finalKey,
```

2023-08-07 16:31 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +			key: final_key,
```suggestion
			key: finalKey,
```

2023-08-07 16:31 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		});
This is a service error, you should not use the validation error pattern and return pre-defined name and message. Here you should check if this is error from service endpoint with friendly name and message already, if so throw directly; If not(networking error for instance), throw StorageError with underlying error.

2023-08-07 17:06 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		});
can we just throw an error and will that work @AllanZhengYP ?

2023-08-07 18:36 UTC, israx reviewed
We should consider testing more error cases.

1. Testing validation errors
2. Testing service errors

For each test we should check if the error was correctly mapped for an `StorageError`

2023-08-07 18:36 UTC, israx commented on packages/storage/src/errors/types/validation.ts
> +		message: 'Missing key',
Is this message enough to let customers know how to solve the validation error ? probably adding more context here.

2023-08-07 18:36 UTC, israx commented on packages/storage/__tests__/providers/s3/getProperties.test.ts
> +test.skip('getProperties API happy path case', async () => {
happy and error test cases should be inside a describe block each.

2023-08-07 18:36 UTC, israx commented on packages/storage/__tests__/providers/s3/getProperties.test.ts
> +test.skip('getProperties API should return a not found error', async () => {
should be part of the error cases describe block

2023-08-07 18:36 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +export const getProperties = async function (
what errors do this API throw? We should document all possible errors including service and validation errors

2023-08-07 18:36 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		return getPropertiesResponse;
```suggestion
    return {
			   key: finalKey,
		   	 contentType: response.ContentType,
			contentLength: response.ContentLength,
			eTag: response.ETag,
			lastModified: response.LastModified,
			metadata: response.Metadata,
		}
```

2023-08-07 18:36 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	try {
we don't really need a try and catch clause. If it fails, the error will be caught by the customers code

2023-08-07 18:36 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	try {
we should use `try and catch` if we depend on the result for a subsequent call to a service.

2023-08-07 18:38 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		});
how are we mapping service errors ? We need to map the service errors to be consistent on the way errors are thrown

2023-08-07 18:54 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		});
Thanks for the feedback. Looking at auth Error handling for reference.

2023-08-07 19:16 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	try {
yeah but for the hubEvents do you think we need this `try` &  `catch` blocks🤔?

2023-08-07 19:58 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +export const getProperties = async function (
Updated thanks! took a reference from Auth✌️

2023-08-07 21:32 UTC, israx commented on packages/storage/src/providers/s3/apis/getProperties.ts
> + * @throws service: {@link NotFoundException} - thrown when there is no given object in bucket
the `NotFoundException` is too specific. The service will throw different errors not only one.

2023-08-07 21:32 UTC, israx commented on packages/storage/src/errors/utils/assertServiceError.ts
> +export function assertServiceError(
how is this being used?

2023-08-07 22:00 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> + * @throws service: {@link NotFoundException} - thrown when there is no given object in bucket
Got it thanks updated.

2023-08-08 02:28 UTC, ashwinkumar6 commented on packages/storage/src/types/params.ts
>  export type StorageDownloadFileParameter<Options extends StorageOptions> =
should we rename these `StorageDownloadFileParameter` as well ?
or i'm wondering if only makes sense to update those related to getProperties 

cause we have also updated `StorageDownloadDataParameter`

2023-08-08 02:34 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +			identityId: awsCredsIdentityId,
Should we move lines 28-40 to a separate utils function. These might be common among different APIs 
(thanks for feedback Allan)

2023-08-08 02:39 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		const response = await headObject(options, params);
Can we manually create an `options` object and then pass it here so it's more evident as to what we're passing

2023-08-08 02:40 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		const response = await headObject(options, params);
and that can be typed as well

2023-08-08 02:52 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		const response = await headObject(options, params);
do we need to infer types manually? @ashwinkumar6

2023-08-08 02:53 UTC, kvramyasri7 commented on packages/storage/src/types/params.ts
>  export type StorageDownloadFileParameter<Options extends StorageOptions> =
to avoid confusion I am just updating `getProperties` params. But, we can do that as well.

2023-08-08 03:10 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		const response = await headObject(options, params);
we could do it manually like what we have done for response

2023-08-08 16:02 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +			identityId: awsCredsIdentityId,
will add a TODO here and will replace.

2023-08-08 16:53 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +import { StorageOptions } from '../../../types/params';
That's a good catch. Will make it consistent. Thanks.

2023-08-09 21:44 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const { key, options: { accessLevel = defaultAccessLevel } = {} } = req;
```suggestion
  // TODO should we use targetIdentityId from req as well 
	const { key, options: { accessLevel = defaultAccessLevel } = {} } = req;
```

2023-08-09 21:48 UTC, ashwinkumar6 approved these changes

2023-08-10 18:01 UTC, AllanZhengYP reviewed
It's getting closer, thank you @kvramyasri7

2023-08-10 18:01 UTC, AllanZhengYP commented on packages/storage/src/AwsClients/S3/headObject.ts
> +	const headers = {};
This can be in-line on line 47

2023-08-10 18:24 UTC, kvramyasri7 commented on packages/storage/src/types/results.ts
> +};
So the result type of `S3GetPropertiesResult` is `StorageGetPropertiesResult & S3Item`,  basically `S3Item` does not have contentType.

2023-08-10 19:14 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const finalKey = getFinalKey(accessLevel, awsCredsIdentityId, key);
Updated. Thanks!

2023-08-10 20:02 UTC, AllanZhengYP reviewed
Almost there. I only have a couple more comments

2023-08-10 20:02 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/types/results.ts
>  type S3ObjectInformation = {
Rename to `S3Item` and extend it from `StorageItem` which excludes `versionId` and `contentType`

2023-08-10 20:18 UTC, kvramyasri7 commented on packages/storage/src/AwsClients/S3/headObject.ts
> -			Metadata: deserializeMetadata(response.headers),
Gotcha updating. 🚶‍♀️

2023-08-10 21:14 UTC, HuiSF requested changes

2023-08-10 21:14 UTC, HuiSF commented on packages/storage/src/providers/s3/types/results.ts
> +	//TODO add versionId
Is this TODO message meant for somewhere else? 😅

2023-08-10 21:14 UTC, HuiSF commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	};
If you don't want to use object literal inline calling `headObject`, please type it, `accessLevel` and `targetIdentityId` are not properties of this parameter.

But I recommend just write the object literal inline, so you don't need to import the type.

2023-08-10 21:14 UTC, HuiSF commented on packages/storage/src/providers/s3/utils/resolveStorageConfig.ts
> +	const { defaultAccessLevel } = AmplifyV6.libraryOptions?.Storage ?? {};
Can destruct `defaultAccessLevel` at line 18.

2023-08-10 21:25 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/resolveStorageConfig.ts
> +	const { defaultAccessLevel } = AmplifyV6.libraryOptions?.Storage ?? {};
`defaultAccessLevel` is not available on `getConfig` method. It's available on `libraryOptions `.

2023-08-10 22:18 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/resolveStorageConfig.ts
> +	const { identityId, credentials } = await AmplifyV6.Auth.fetchAuthSession();
That's right. It will be exported from `aws-amplify/auth`

2023-08-10 22:29 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/resolveStorageConfig.ts
> +	const { identityId, credentials } = await AmplifyV6.Auth.fetchAuthSession();
Right now in next branch it is causing build_failure. can I add a todo for that and change later on once fetchAuthSession is merged. 🤔

2023-08-10 23:58 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const { identityId, credentials, defaultAccessLevel, bucket, region } =
Thanks updated!

2023-08-11 15:47 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const finalKey = await getKeyWithPrefix(accessLevel!, identityId!, key);
Thanks for the suggestion. Updated.

2023-08-11 16:24 UTC, AllanZhengYP commented on packages/storage/src/AwsClients/S3/headObject.ts
> +		assertServiceError(error);
Sorry the suggestion does not mean to be exact. Can you build static function like @HuiSF suggestion to build the service error?

2023-08-11 16:24 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const response = await headObject(headObjectOptions, headObjectParams);
I just realize we need to throw an error with recoverSuggestion here. Suggesting customer needs to create either the bucket or the object because they do not exist

2023-08-11 16:48 UTC, kvramyasri7 commented on packages/storage/src/AwsClients/S3/headObject.ts
> +		assertServiceError(error);
if (response.statusCode >= 300)  {
```suggestion
		const error = await parseXmlError(response);
		StorageError.fromXmlError(error);
		assertServiceError(error);
```
	}

Will this work?

2023-08-11 16:51 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const response = await headObject(headObjectOptions, headObjectParams);
we are doing it in while getting it from `resolveStorageConfig`. Do we need to it here again?

2023-08-11 18:20 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +	// TODO import fetchAuthSession from
```suggestion
	// TODO import fetchAuthSession directly from `aws-amplify`
```

2023-08-11 18:38 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	}
Have we asserted the `req.options?.targetIdentityId` is always set when accessLevel is `protected`? If not let's add it. Also I prefer conditional assignment here: `const targetIdentityId = [condition] ? [val1] : [val2]`

2023-08-11 18:38 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const response = await headObject(headObjectOptions, headObjectParams);
These can be in-lined too.

2023-08-11 18:58 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const response = await headObject(headObjectOptions, headObjectParams);
I have to do that because of the type and using inline object lteral.

2023-08-11 20:46 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	}
Thanks for this suggestion. Updated.

2023-08-11 21:41 UTC, HuiSF commented on packages/storage/src/providers/s3/apis/getProperties.ts
> + */
Great ideas to add throws here, thanks.
One suggestion on the formate:

Probably need to verify the format of the added comment docs. E.g. the doc of `getProperties` looks like this currently:

<img width="584" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/10602282/d80624b2-5588-4da6-be51-d5929b785fe3">

```suggestion
/**
 * Gets the properties of a file. The properties include S3 system metadata and
 * the user metadata that was provided when uploading the file.
 *
 * @param {StorageOperationRequest} req The request to make an API call.
 * @returns {Promise<S3GetPropertiesResult>} A promise that resolves the properties.
 * @throws A {@link GetPropertiesException} when the underlying S3 service returned error.
 * @throws A {@link StorageValidationErrorCode} when API call parameters are invalid.
 */
```

<img width="561" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/10602282/64ee92d9-e2eb-4706-9605-a4809bde5631">

Please check the accuracy other the inline-docs else where, too.

2023-08-11 21:41 UTC, HuiSF commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		targetIdentityId = identityId ?? req.options?.targetIdentityId;
I think when `accessLevel === 'protected'` the `targetIdentityId` from the `req` has a higher priority.

2023-08-11 21:41 UTC, HuiSF commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		targetIdentityId: targetIdentityId,
Still these two properties are not defined in the interface of the first param of `headObject` function.

2023-08-11 21:41 UTC, HuiSF commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +}
Um I have a question about the approach of using `assertValidationError` here - I understood this is useful when assert non-undefined values in pure JS. 

But considering the TS, both `identityId` and `credentials` can be `undefined` looking at the type `AuthSession`. using `assertValidationError` doesn't narrow `string | undefined` to `string`.

The return type of `resolveCredentials` is going to be 
```typescript
{
  identityId?: string,
  credentials?: AWSCredentials,
}
```

I think I heard we are going to enable `strict` and `alwaysStrict` in TS? If so this will require quite a lot of manual changes. Take the above return type, you need to check `undefined` again in the consumer of `resolveCredentials`.

Gut feeling that we should use `if (!identityId) throw` inline check to make it easier for refactoring later. cc @AllanZhengYP

2023-08-11 21:49 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +		targetIdentityId: targetIdentityId,
sorry. changed it in recent commit.

2023-08-11 22:07 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getProperties.ts
> +	const response = await headObject(headObjectOptions, headObjectParams);
Thanks for the suggestion. Updated.

2023-08-11 22:24 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +}
>But considering the TS, both identityId and credentials can be undefined looking at the type AuthSession. using assertValidationError doesn't narrow string | undefined to string.

I don't think this is correct, the assertion function does narrow the types, [see playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKANygmRAC540BrVHAd1QEpGiSzC8arRABuAFDjQkWAjB5CGAo1TIAtgCNSAHzShEWVCGASo8APTn4qzaXjamqfYePj5qRfBwaAVvAC88ADeUAC+psSkFFBcphZWNlowEu6eUL4ATAHBYeJAA)

2023-08-11 22:31 UTC, HuiSF commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +}
Ahh nice, I didn't look the `assertValidationError` closely. 👍
Please ignore the comment regarding the strict mode. But I think we need to assert `identityId`, too.

2023-08-11 22:33 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +}
Yeah. Thanks updated.

2023-08-11 23:04 UTC, HuiSF approved these changes

2023-08-11 23:04 UTC, HuiSF commented on packages/storage/src/errors/StorageError.ts
> +				'Please add the object with this key to the bucket as the key is not found.';
nit: This `recoverSuggestion` may not cover the case that API caller provided a wrong combination of accessLevel, key and targetIdentityId.

2023-08-14 14:58 UTC, israx approved these changes
LGTM. Seems that some unit tests are failing.

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/src/AwsClients/S3/headObject.ts
> +	url.pathname = serializePathnameObjectKey(url, input.Key!);
Why is this change needed?

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/src/AwsClients/S3/headObject.ts
> +		throw StorageError.formServiceError(error, response.statusCode);
Nit: from previous review:
```suggestion
		throw StorageError.fromServiceError(error, response.statusCode);
```

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/src/AwsClients/S3/headObject.ts
> -			$metadata: parseMetadata(response),
Let's keep this still, we might need it for logger later.

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/__tests__/AwsClients/S3/cases/headObject.ts
> +		//$metadata: expect.objectContaining(expectedMetadata),
Let's keep this for now, see the comments below:

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/types/results.ts
> +type S3Item = {
Not a blocking issue. In the future this needs to be extended from `StorageItem`.

2023-08-14 17:42 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/types/results.ts
> +export type S3DownloadDataResult = StorageDownloadDataResult & S3Item;
I'd prefer to use generics like below:

```suggestion
export type S3DownloadDataResult = StorageDownloadDataResult<S3Item>;
```

2023-08-14 18:14 UTC, kvramyasri7 commented on packages/storage/src/AwsClients/S3/headObject.ts
> +	url.pathname = serializePathnameObjectKey(url, input.Key!);
Reverted back. Thanks.

2023-08-14 18:39 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/types/results.ts
> +export type S3GetPropertiesResult = StorageItem<S3Item>;
nit: I think this should just S3Item:
```suggestion
export type S3GetPropertiesResult = S3Item;
```

2023-08-14 18:39 UTC, AllanZhengYP commented on packages/storage/src/types/results.ts
> +export type StorageItem<T = {}> = T & {
```suggestion
export type StorageItem = {
```

2023-08-14 18:39 UTC, AllanZhengYP commented on packages/storage/src/types/results.ts
>  };
```suggestion
export type StorageDownloadDataResult<T extends StorageItem> = T & {
	body: Payload;
};
```

2023-08-14 18:39 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/types/results.ts
> +type S3Item = {
This should be some thing like:

```
export type S3Item = StorageItem & {
  versionId?: string;
  contentType?: string;
}
```
or 
```
export interface S3Item extends StorageItem {
  versionId?: string;
  contentType?: string;
}
```

2023-08-14 18:57 UTC, AllanZhengYP approved these changes
Looks good to me! 🚀🚀🚀
Thank you so much for putting this together! @kvramyasri7

2023-08-14 19:18 UTC, israx approved these changes

2023-08-14 19:24 UTC, merged

2023-08-21 18:43 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/resolveStorageConfig.ts
> +	const { identityId, credentials } = await AmplifyV6.Auth.fetchAuthSession();
We should use the `fetchAuthSession` from the core package instead. In one from umbrella package is suppose to be public-facing. Using it internally will alter our dependency structure of the Storage scoped package.

@HuiSF @Samaritan1011001