fix(core): fail to clean up framework observers
aws-amplify/amplify-js pull request #11782
Opened 2023-08-10 19:53 UTC by HuiSF

#### Description of changes

Added logic to clean up the Framework detection observers, and ignore new incoming observers after the detection completes.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/11770

#### Description of how you validated changes

Unit tests.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-10 20:00 UTC, erinleigh90 approved these changes
LGTM

2023-08-10 21:22 UTC, erinleigh90 submitted a review, later dismissed

2023-08-10 23:22 UTC, jimblanc approved these changes

2023-08-10 23:38 UTC, cwomack submitted a review, later dismissed
LGTM!

2023-08-11 17:00 UTC, jimblanc submitted a review, later dismissed

2023-08-11 17:31 UTC, erinleigh90 approved these changes

2023-08-11 17:49 UTC, david-mcafee requested changes

2023-08-11 17:49 UTC, david-mcafee commented on packages/core/__tests__/Platform-test.ts
> +
Your test uses fake timers, but they are never reset. Would suggest cleaning that up in an `afterEach` block, maybe something like: 

```suggestion

afterEach(() => {
    jest.useRealTimers();
});
```

2023-08-11 18:29 UTC, david-mcafee commented on packages/core/__tests__/Platform-test.ts
> +		jest.useRealTimers();
nit: I'd prefer using `afterEach` (see [previous suggestion](https://github.com/aws-amplify/amplify-js/pull/11782/files#r1291633571)) for better isolation between tests, but not a blocker.

2023-08-11 18:29 UTC, david-mcafee approved these changes

2023-08-11 19:29 UTC, jimblanc approved these changes

2023-08-11 19:32 UTC, merged