chore(auth): refactor tests to include custom user pool clients
aws-amplify/amplify-js pull request #11792
Opened 2023-08-12 20:27 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-14 18:44 UTC, elorzafe requested changes
Overall looking good!

I would validate if tokens are not `null` and also if the region is valid

Thanks @israx

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/base.ts
> +	body: string
Nit: can this be a generic type or assume this is a JSON.stringify?

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/types/models.ts
> +// TODO: replace by `custom:${string}` once categories that use auth have upgraded TS
TODO(v6)

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/utils.ts
> +	return userPoolId?.split('_')[0] || '';
Should this throw an error if the split length is `1`?

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/setUpTOTP.ts
> +	const { tokens } = await fetchAuthSession({ forceRefresh: false });
this could be `null` in that case it should be check?

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/resendSignUpCode.ts
> +		{ region: getRegion(authConfig.userPoolId) },
Should we validate the region is not empty?

2023-08-14 18:44 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/fetchMFAPreference.ts
> +	const { tokens } = await fetchAuthSession({ forceRefresh: false });
Maybe we need to check if tokens is not `null`

2023-08-14 18:45 UTC, israx commented on packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/base.ts
> +	body: string
yeah it is JSON.stringify

2023-08-14 19:14 UTC, israx commented on packages/auth/src/providers/cognito/apis/setUpTOTP.ts
> +	const { tokens } = await fetchAuthSession({ forceRefresh: false });
added an assertion guard to check if tokens are falsy

2023-08-14 21:52 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/utils.ts
> +	if (!region || typeof region !== 'string' || region.length <= 1)
```suggestion
	if (userPoolId?.indexOf('_') < 0 || !region || typeof region !== 'string')
```

2023-08-15 17:23 UTC, elorzafe approved these changes
Thanks @israx good work! 🎖️

2023-08-16 14:25 UTC, jimblanc approved these changes
LGTM! Some nits & questions below

2023-08-16 14:25 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/verifyTOTPSetup.ts
>  	// TODO: remove mocked when auth token provider is implemented.
```suggestion
```

2023-08-16 14:25 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/types.ts
> +
```suggestion
```

Nit but I think this is already included at the top, did the linter script give you trouble here? Not a big deal either way

2023-08-16 14:25 UTC, jimblanc commented on packages/auth/tsconfig.json
> +		"types": ["jest", "node"]
Just curious what did we need to enable global `node` types for?

2023-08-16 14:27 UTC, merged