Hub types rfc
aws-amplify/amplify-js pull request #11816
Opened 2023-08-17 01:41 UTC by kvramyasri7

#### Description of changes

1. Adding types to Hub API
2. Created Hub folder to have types and HUB logic 
3. Created types folder to have StorageHubTypes, AuthHubTypes, AnalyticsHubTypes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-17 17:39 UTC, israx reviewed
we can potentially remove this method now

2023-08-17 17:39 UTC, israx commented on packages/core/src/Hub/index.ts
> +function isLegacyCallback<
I think this is going to be deprecated

2023-08-17 17:39 UTC, israx commented on packages/core/src/Hub/types/HubTypes.ts
> +export const AMPLIFY_SYMBOL = (
This is not a type but a value

2023-08-17 17:41 UTC, kvramyasri7 commented on packages/core/src/Hub/types/HubTypes.ts
> +export const AMPLIFY_SYMBOL = (
sorry, missed it, will updated this. Can we move this to `index.ts` or do we need to create a new file for this.

2023-08-17 17:55 UTC, israx reviewed
Thanks @kvramyasri7  for putting this together. I think we are missing a type in the dispatch API

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +	private patterns: IPattern<any>[] = [];
can we add a type here?

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +	private patterns: IPattern<any>[] = [];
I think this is to handle RegEx cases

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
>  	 * @deprecated Instead of calling Hub.remove, call the result of Hub.listen.
we can potentially remove this

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +		if (this.protectedChannels.indexOf(channel as string) > -1) {
```suggestion
    if (typeof channel === 'string' && this.protectedChannels.indexOf(channel) > -1) {
```

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
>  		if (isLegacyCallback(callback)) {
We can remove this now

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +			let holder = this.listeners[channel as string];
I'm wonder if we should check here if the channel is a `string` or `RegEx` instance

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +				this.listeners[channel as string] = holder;
ditto

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as string];
ditto

2023-08-17 17:55 UTC, israx commented on packages/core/src/Hub/index.ts
> +		payload: HubPayload<EventData>,
I think we are missing an important [type util](https://stackblitz.com/edit/rfc-typescript-v6?file=core%2Findex.ts%3AL113) here.

2023-08-17 18:04 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
>  		if (isLegacyCallback(callback)) {
Removed it in recent commit. Thanks for suggestion

2023-08-17 19:26 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +			let holder = this.listeners[channel as string];
string is a type we cannot check for the instance of it and should we change it to `String` ?

2023-08-23 17:37 UTC, israx commented on packages/core/src/Hub/index.ts
> +	EventData extends AmplifyEventDataMap = AmplifyEventDataMap
We shouldn't add generics on top of the HubClass. How is it used ?

2023-08-23 17:41 UTC, israx commented on packages/core/src/Hub/index.ts
> +			throw new Error('No callback supplied to Hub');
I think now we can use `AmplifyError`

2023-08-23 17:43 UTC, israx commented on packages/core/src/Hub/types/AuthTypes.ts
> +	| { event: 'autoSignIn_failure'; data: null };
I think this events need to be updated

2023-08-23 17:59 UTC, stocaaro requested changes
`as` is probably an indication that we're cutting corners. Can we review the `as` usage and identify alternative strategies for these implementation patterns?

2023-08-23 17:59 UTC, stocaaro commented on packages/core/__tests__/Hub-test.ts
> -	test('Remove listener', () => {
Will there be a corrolary of remove listener in the changed implementation?

2023-08-23 17:59 UTC, stocaaro commented on packages/core/src/Hub/index.ts
> +		channel: string & {},
`string & {}`? I was expecting this to just be `string`. What do we get from combining with object? Why isn't the object behavior included in the combined function interface down on 91?

2023-08-23 17:59 UTC, stocaaro commented on packages/core/src/Hub/index.ts
> +			this.protectedChannels.indexOf(channel) > -1
Aren't AmplifyChannel's also strings? Wondering if the error here will fire for every internal call.

2023-08-23 17:59 UTC, stocaaro commented on packages/core/src/Hub/index.ts
> +		(holder as any).push({
Whats up with this `as any`? This seems concerning since `as` is usually a bit of a "lets pretend" type idiom.  Maybe the same can be achieved with guard clauses or type narrowing?

2023-08-23 17:59 UTC, stocaaro commented on packages/core/src/Hub/types/AuthTypes.ts
> +// TODO Need to update types of data
Thankyou for this line. Was going to comment on the `any`'s. Glad to see that clarification is planned for a future change.

2023-08-23 17:59 UTC, stocaaro commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
Channel becomes a number to index listeners? This looks funny. `.listeners` is an array, but channel is a string, right? Are we using the right underlying object? Should this be a different structure, maybe a map?  Not sure I'm thinking through the full problem, but it looks funny.

2023-08-23 18:12 UTC, israx commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
The current implementation is accessing array elements with an string instead of number at run time (didn't know it was supported) but TS only admits numbers as index

2023-08-23 21:39 UTC, kvramyasri7 commented on packages/core/__tests__/Hub-test.ts
> -	test('Remove listener', () => {
Added this test back. Thanks for mentioning.

2023-08-23 21:40 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +		channel: string & {},
We have updated this one to of only type string please take a look at it.

2023-08-23 21:53 UTC, israx submitted a review, later dismissed
Looks good. Only improving the error message and also add more description on the PR to highlight all the changes

2023-08-23 21:53 UTC, israx commented on packages/core/src/Hub/index.ts
> +				message: 'Service Worker not available',
I think `message` is not accurate.

2023-08-23 21:58 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +				message: 'Service Worker not available',
Thanks updtaed.

2023-08-23 22:11 UTC, stocaaro commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
Got it. So this is funky and we're not planning to improve upon it?

2023-08-24 12:32 UTC, israx commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
I think we can do a better job refactoring this code so each channel is mapped to a number instead. We would need to modify some run time behavior in order to do it. I think if it is not an overwhelming job we can address it on this PR. Otherwise we can add a `TODO` for a next PR

2023-08-24 16:44 UTC, israx commented on packages/core/src/Hub/index.ts
> +			this.protectedChannels.indexOf(channel) > -1
It won't fire as long as each category has added an `ampSymbol` while using `dispatch`

2023-08-24 16:46 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
I am adding `TODO` for this change as it involves change in run time behavior too and need to test in sample app. Will address this in a separate PR and added more description to this PR. What do you think @israx @stocaaro ?

2023-08-24 16:47 UTC, israx commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
Sounds good to me

2023-08-24 18:01 UTC, stocaaro approved these changes
Are we introducing any new behavior here that needs to be unit tested? I don't think we are, but with my approval want to ask the question.

2023-08-24 18:07 UTC, israx approved these changes
Awesome. Thanks @kvramyasri7

2023-08-24 18:08 UTC, merged

2023-08-24 18:18 UTC, kvramyasri7 commented
> 
We are not introducing anything new in this PR. But please free to comment if I am missing anything. Thanks.

2023-12-02 18:58 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +			this.protectedChannels.indexOf(channel) > -1
Thanks for explanation people. Forgot resolve this argument. Doing it right away.

2023-12-05 21:49 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +		(holder as any).push({
Thanks for letting ME know. I will take a look at it. But not sure why typescript accepted `as any` is acceptable. May be TS compiler is okay with pretending. Just kidding 😅. For sure we need to add guard clauses/type narrowing so we only allow few `types`.

2023-12-05 21:51 UTC, kvramyasri7 commented on packages/core/src/Hub/index.ts
> +		const holder = this.listeners[channel as unknown as number];
yes, looks good to me too