Chore(storage): TODO Item1 for apis
aws-amplify/amplify-js pull request #11841
Opened 2023-08-21 05:16 UTC by kvramyasri7

#### Description of changes

1. change to import fetchAuthSession.
2. change assertValidationError for expiration after urlExpiration assignment.
3. change expiration change a little bit to get correct value,

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [X] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-21 18:25 UTC, AllanZhengYP requested changes

2023-08-21 18:25 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
Can you refer to the interface in the design doc and make sure the `S3GetUrlOptions` interface is up-to-date? I believe the `options.expirations` should be `options.expiresIn` instead.

2023-08-21 18:25 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +			awsCredExpiration.getTime() < urlExpiration
The `awsCredExpiration.getTime()` is an EPOCH time stamp in ms, whereas the `urlExpiration` is the number of seconds from now to the time when the URL becomes expires. The 2 numbers are not comparable. You can make a function to compute the URL `urlExpiration`, like a funtion `getUrlDurationInSeconds`

2023-08-21 18:41 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +import { fetchAuthSession } from 'aws-amplify/auth';
```suggestion
import { fetchAuthSession } from 'aws-amplify/core';
```

The storage package should NOT have dependency over `auth` package.

2023-08-21 22:26 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/resolveCredentials.ts
> +import { fetchAuthSession } from 'aws-amplify/auth';
Updated. Thanks

2023-08-22 19:13 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getUrl.ts
Updated it. Thanks for the clarification

2023-08-22 20:11 UTC, AllanZhengYP requested changes

2023-08-22 20:11 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +): number {
Nit: use arrow function

2023-08-22 20:11 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +		awsCredExpiration.getTime() / 1000 < urlExpiration
Not exact code but you need to calculate the the time to expire to compare it with `urlExpiration`. 
```suggestion
		(awsCredExpiration.getTime() - Date.now()) / 1000 < urlExpiration
```

2023-08-22 20:11 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +	return urlExpiration;
nit: The `/1000` causes fractional numbers, it's better have a `Math.floor()` here to make sure the response is an integer. It's a nice-to-have feature that give maintainer a better task when debugging.

2023-08-22 20:11 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +	urlExpiration: number
The arguments naming can be more intuitive, not necessarily the same variable name in the calling function. 

Also, since both variable refers to a time value, it's better to make sure they are in the same representation(Date instance, or time in seconds from now, or timestamp in MS, etc.). You can do in-line transitions when calling this function.

2023-08-23 00:12 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +		awsCredExpiration.getTime() / 1000 < urlExpiration
Fixed Thanks for the clarification

2023-08-23 19:13 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/utils/getKeyWithPrefix.ts
> +export const getKeyWithPrefix = function ({
```
export const getKeyWithPrefix = ({
	accessLevel,
	targetIdentityId,
	key,
}: GetKeyWithPrefixOptions) => {
	const { prefixResolver = defaultPrefixResolver } =
		AmplifyV6.libraryOptions?.Storage ?? {};
	return (
		prefixResolver({
			accessLevel,
			targetIdentityId,
		}) + key
	);
};
```

2023-08-23 19:17 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/getKeyWithPrefix.ts
> +export const getKeyWithPrefix = function ({
Sorry missed it. will update.

2023-08-23 20:06 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +		if (awsCredExpiration) {
You might need to remove outer if statement.

2023-08-23 20:06 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +				(awsCredExpiration?.getTime() - Date.now()) / 1000
`?` should not be necessary
```suggestion
				(awsCredExpiration.getTime() - Date.now()) / 1000
```

2023-08-23 20:06 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +					: urlExpirationInMS;
`urlExpirationInMS` should be `urlExpirationInSec`.
```suggestion
        Math.min(awsCredExpirationInSec, urlExpirationInSec)
```

2023-08-23 20:06 UTC, AllanZhengYP commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +	const urlInSec = urlExpirationInMS * 1000;
This should not be necessary if you convert above.

2023-08-23 21:08 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +		if (awsCredExpiration) {
Updated. Thanks.

2023-08-23 21:08 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/getUrl.ts
> +					: urlExpirationInMS;
This is cool. Thanks for the suggestion

2023-08-23 21:19 UTC, AllanZhengYP approved these changes
💯

2023-08-23 21:33 UTC, ashwinkumar6 approved these changes

2023-08-23 21:34 UTC, merged

2023-12-02 18:54 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/getUrlDurationInSeconds.ts
> +	urlExpiration: number
Forgot to comment. Synced off-line and resolving right away.