feat(auth): make a subset of auth apis runnable with the server context
aws-amplify/amplify-js pull request #11877
Opened 2023-08-24 20:40 UTC by HuiSF

#### Description of changes

Made the following APIs to be callable with Amplify server context.
* `getCurrentUser`
* `fetchUserAttributes`

#### Issue #, if available

#### Description of how you validated changes

Making API call in Next.js server.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-24 20:56 UTC, stocaaro approved these changes
How do we unit test this type of behavior for the server?

2023-08-24 21:05 UTC, israx commented on packages/auth/src/providers/cognito/apis/server/fetchUserAttributes.ts
> +export const fetchUserAttributes = (
should we add doc strings?

2023-08-24 23:48 UTC, HuiSF commented on packages/auth/src/providers/cognito/apis/server/fetchUserAttributes.ts
> +export const fetchUserAttributes = (
Yup, I will add the docs to all server side API as a whole in a separate PR.

2023-08-24 23:50 UTC, HuiSF commented
> How do we unit test this type of behavior for the server?

The only difference between server and client is where the Amplify instance comes from. The existing unit tests has been verifying the common share internal logic, so an extra set of unit tests probably unnecessary.

I will add unit tests to all server side APIs to verify `getAmplifyServerContext` function at least in a separate PR.

2023-08-25 12:00 UTC, israx submitted a review, later dismissed

2023-08-25 16:09 UTC, stocaaro submitted a review, later dismissed

2023-08-25 16:42 UTC, jimblanc requested changes
Looks good, one blocking comment on version range

2023-08-25 16:42 UTC, jimblanc commented on packages/auth/package.json
> +		"@aws-amplify/core": "^6.0.0",
```suggestion
		"@aws-amplify/core": "6.0.0",
```

The dev dep shouldn't be pinned, it's for our internal dev and lerna will handle it

2023-08-25 16:42 UTC, jimblanc commented on packages/core/internals/package.json
> +	"name": "@aws-amplify/core/internals",
Do we need a new path for this? Could we possible re-use `@aws-amplify/core/internals/utils`?

2023-08-25 16:59 UTC, jimblanc approved these changes

2023-08-25 17:25 UTC, israx approved these changes

2023-08-25 17:56 UTC, merged