v6 feat(auth) sign out
aws-amplify/amplify-js pull request #11880
Opened 2023-08-24 23:13 UTC by elorzafe

#### Description of changes

`signOut` API
- [x] clear local tokens
- [x] token revocation
- [x] logout endpoint for OAuth
- [ ] global sign out

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-24 23:39 UTC, erinleigh90 requested changes
Had a couple of questions but otherwise lgtm

2023-08-24 23:39 UTC, erinleigh90 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +async function revokeTokens({
What is the benefit of this layer of abstraction vs calling revokeToken directly?

2023-08-24 23:39 UTC, erinleigh90 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +			oAuthSignOutRedirect(authConfig);
Isn't this already being called through handleOAuthSignOut? Does it need to be called twice here?

2023-08-24 23:39 UTC, erinleigh90 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +			oAuthSignOutRedirect(authConfig);
I'm wondering if all of this code from 85-89 can be moved to handleOAuthSignOut since it is all repeated above in clientSignOut as well

2023-08-24 23:43 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +			await tokenOrchestrator.tokenStore.loadTokens();
Should we be using fetchAuthSession here? and in line 73?

2023-08-24 23:43 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		tokenOrchestrator.clearTokens();
We should also call `cognitoCredentialsProvider.clear()` and `IdentityIdProvider.clear()`

2023-08-24 23:43 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		tokenOrchestrator.clearTokens();
Same here: We should also call `cognitoCredentialsProvider.clear()` and `IdentityIdProvider.clear()`

2023-08-24 23:58 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +			await tokenOrchestrator.tokenStore.loadTokens();
`fetchAuthSession` doesnt return `refreshToken`

2023-08-24 23:59 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		tokenOrchestrator.clearTokens();
But how can be called if is decoupled?, when `fetchAuthSession` is called, it will not have tokens unless I am missing something.

2023-08-25 00:01 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +			oAuthSignOutRedirect(authConfig);
yes! good catch!

Thank you!

2023-08-25 00:05 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +async function revokeTokens({
Good catch, is doing the same lol

2023-08-25 14:46 UTC, israx commented on packages/auth/src/types/results.ts
> +export type AuthSignOutResult = void;
The result doesn't conform to the stablished API definition

2023-08-25 15:05 UTC, israx commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		await handleOAuthSignOut(authConfig);
this doesn't resolve to a promise, so we don't really need to await

2023-08-25 15:06 UTC, israx reviewed
My biggest concern is that we are not confirming and aligning to the proposed API definition result

2023-08-25 15:10 UTC, israx commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		throwSignOutError(err);
I'm not sure we need this util because the underlying client already maps to an `AuthError`

2023-08-25 15:11 UTC, israx commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		throwSignOutError(err);
Although I think based on the stablished API definition we would need to **return** the error instead

2023-08-25 15:53 UTC, erinleigh90 submitted a review, later dismissed
LGTM!

2023-08-25 17:25 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +		throwSignOutError(err);
From our conversation for dev preview it will not throw, we can chat more for GA launch if we can add an E2E story that customers can retry easily to make sure the tokens were revoked or the global signout was done

2023-08-25 17:26 UTC, elorzafe commented on packages/auth/src/types/results.ts
> +export type AuthSignOutResult = void;
Is ok if we modify that for GA launch, is adding and not removing.

2023-08-25 18:37 UTC, israx submitted a review, later dismissed
I'm still hesitant to click the `approve` button as we are not conforming with native. I see the point where exposing `service` errors in the result might not be useful for customers and that there's not a clear scape hatch. But I think the DX is better than just swallowing service errors.

For now I'm okay with this API signature as changing the API result shouldn't be breaking, and considering that we need a discussion.

2023-08-25 21:31 UTC, jimblanc approved these changes

2023-08-25 21:31 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +	oAuthLogoutEndpoint += Object.entries({
Non-blocking issue, but would prefer if we just used URL to build this

2023-08-25 21:33 UTC, israx submitted a review, later dismissed

2023-08-25 22:33 UTC, jimblanc approved these changes

2023-08-25 22:43 UTC, Samaritan1011001 approved these changes

2023-08-25 22:45 UTC, merged