Update Auth config from review
aws-amplify/amplify-js pull request #11909
Opened 2023-08-26 02:14 UTC by elorzafe

#### Description of changes

Update Auth config types

- removing `clientMetadata` from Auth config
#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-28 14:20 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/confirmSignUp.ts
>  	const authConfig = Amplify.getConfig().Auth;
For all of these APIs, I would prefer to just use `Auth.Cognito` here since these APIs are cognito specific

2023-08-28 14:20 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/types.ts
> +		authConfig.Cognito.userPoolId &&
Don't we need another level here for `authConfig.Cognito &&`

2023-08-28 16:01 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/confirmSignUp.ts
>  	const authConfig = Amplify.getConfig().Auth;
Make sense

2023-08-28 16:41 UTC, erinleigh90 commented on packages/auth/src/providers/cognito/credentialsProvider/IdentityIdProvider.ts
> +	const identityPoolId = authConfig?.Cognito.identityPoolId;
nit/question: I think this applies across the board, but I just noticed here: should we also check that Cognito is defined before getting identityPoolId?

If authConfig is defined, do we expect Cognito to always be populated? I think for now the answer would be yes, but I believe the point of creating this Cognito umbrella would be that we expect there to be other config that is not Cognito going forward.

2023-08-28 19:41 UTC, elorzafe commented on packages/auth/src/providers/cognito/credentialsProvider/IdentityIdProvider.ts
> +	const identityPoolId = authConfig?.Cognito.identityPoolId;
Is a good question Erin, this should be checked here as well.

2023-08-28 19:42 UTC, elorzafe commented on packages/auth/src/providers/cognito/credentialsProvider/IdentityIdProvider.ts
> +	const identityPoolId = authConfig?.Cognito.identityPoolId;
I will create a separate PR to fix this

2023-08-28 20:00 UTC, jimblanc requested changes
Looks good, just need to fix import paths

2023-08-28 20:05 UTC, israx submitted a review, later dismissed
lgtm

2023-08-28 20:24 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signOut.ts
> +import {
good catch

2023-08-28 20:24 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +import { CognitoUserPoolConfig } from '@aws-amplify/core/lib-esm/singleton/Auth/types';
good catch

2023-08-28 20:24 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +import { CognitoUserPoolConfig } from '@aws-amplify/core/lib-esm/singleton/Auth/types';
good catch

2023-08-28 20:24 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/types.ts
> +import { CognitoUserPoolConfig } from '@aws-amplify/core/lib-esm/singleton/Auth/types';
good catch

2023-08-28 20:33 UTC, israx approved these changes

2023-08-28 20:43 UTC, jimblanc approved these changes

2023-08-28 20:43 UTC, merged

2023-10-02 05:31 UTC, kvramyasri7 commented on packages/core/src/singleton/Auth/utils/index.ts
> +			!!cognitoConfig.userPoolClientId && !!cognitoConfig.userPoolClientId;
nit: should it be `!!cognitoConfig.userPoolId && !!cognitoConfig.userPoolClientId;` @elorzafe ?