feat(auth): add hub events
aws-amplify/amplify-js pull request #11918
Opened 2023-08-28 21:59 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-28 22:29 UTC, elorzafe requested changes
Can we have a unit test?

2023-08-29 13:42 UTC, jimblanc submitted a review, later dismissed

2023-08-29 16:40 UTC, kvramyasri7 approved these changes
Nothing blocking. LGTM. Thanks for doing this @israx

2023-08-29 16:40 UTC, kvramyasri7 commented on packages/core/src/Hub/types/AuthTypes.ts
> +	/** Dispatched when a user signs in with a oauth provider such as Google.*/
very nit : 
```suggestion
	/** Dispatched when a user signs in with an oauth provider such as Google.*/
```

2023-08-29 16:40 UTC, kvramyasri7 commented on packages/auth/__tests__/providers/cognito/hub.test.ts
> +// SPDX-License-Identifier: Apache-2.0
```suggestion
// SPDX-License-Identifier: Apache-2.0

```

2023-08-29 18:12 UTC, jimblanc approved these changes

2023-08-29 19:19 UTC, jimblanc approved these changes

2023-08-29 19:30 UTC, kvramyasri7 approved these changes

2023-08-29 21:28 UTC, elorzafe approved these changes

2023-08-29 21:28 UTC, merged