fix(auth): rename assertTokenProviderConfig to assertUserPoolClientIdInConfig
aws-amplify/amplify-js pull request #11933
Opened 2023-08-30 01:52 UTC by Samaritan1011001

#### Description of changes

Update the assertion method name and reworded the error message to appropriate message. 
Discovery: Not having a `UserPoolClientId` in config threw Auth Token Provider not found exception which is not correct.

#### Issue #, if available

#### Description of how you validated changes
yarn test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-30 17:20 UTC, HuiSF approved these changes

2023-08-30 17:20 UTC, HuiSF commented on packages/core/src/singleton/Auth/utils/index.ts
> +		message: 'UserPoolClientId not present in Config',
nit: prefer that messages end with a period.

2023-08-30 17:41 UTC, israx requested changes
Thanks for putting this together. The name is much more clear now. Although the purpose of the assertion function is to check the `userPoolId` and `userPoolClientId` are not falsy.

2023-08-30 17:41 UTC, israx commented on packages/core/src/singleton/Auth/utils/index.ts
> +		assertionValid = !!cognitoConfig.userPoolClientId;
we also need to check if the `cognitoConfig.userPoolId` is not null.  These are required to make API calls and to get the `region` . I think the previous change intended doing it but had a duplication on `userPoolClientId`

2023-08-30 18:11 UTC, Samaritan1011001 commented on packages/core/src/singleton/Auth/utils/index.ts
> +		assertionValid = !!cognitoConfig.userPoolClientId;
Ah, makes sense! I thought it was a typo but couldn't figure out. I'll update it.

2023-08-31 15:00 UTC, israx commented on packages/core/src/singleton/Auth/utils/index.ts
>  	});
```suggestion
return asserts(assertionValid, {
		name: 'UserPoolConfigException',
		message: 'UserPoolClientId or userPoolId are not present in Config.',
		recoverySuggestion: 'Make sure to provide UserPoolClientId and UserPoolId in the config.',
	});
```
Wondering if we should improve this message as it might be miss leading if customers are passing the `clientId` but not the `userpoolId`

2023-09-08 15:20 UTC, closed without merging

2023-09-08 15:21 UTC, stocaaro commented
This needs to be recreated or redirected to `next/main`.