chore(auth): add authenticated client side validation
aws-amplify/amplify-js pull request #12033
Opened 2023-09-13 20:56 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-13 21:41 UTC, elorzafe approved these changes
Looks good

Thanks @israx 🏅

2023-09-13 21:42 UTC, elorzafe requested changes
Sorry @israx 

can we add also this check for `signInWithRedirect`

Thanks!

2023-09-14 19:14 UTC, elorzafe submitted a review, later dismissed

2023-09-14 21:40 UTC, jimblanc reviewed
Looks good, some nits

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +				'There is already a signed in user because auth tokens were found.',
```suggestion
				'There is already a signed in user.',
```

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +			recoverySuggestion: 'Please call signOut before calling signIn again.',
Just to match tone of the other recovery suggestions elsewhere in the lib.

```suggestion
			recoverySuggestion: 'Call signOut before calling signIn again',
```

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/types.ts
> +				'Please try to sign in first before calling this API again',
```suggestion
				'Sign in before calling this API again',
```

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/types.ts
> +				'Please try to sign in first before calling this API again',
```suggestion
				'Sign in before calling this API again',
```

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/types.ts
> +				'Please try to sign in first before calling this API again',
```suggestion
				'Sign in before calling this API again',
```

2023-09-14 21:40 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +export async function isUserAuthenticated() {
Nit pick but the current name makes it sound like this behaves like a predicate (i.e. returns a bool to know if user is signed in).

```suggestion
export async function assertUserNotAuthenticated() {
```

2023-09-15 13:17 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +export async function isUserAuthenticated() {
Yeah agree. Sounds more like a predicate. I changed it already. Thanks

2023-09-15 13:50 UTC, jimblanc approved these changes

2023-09-15 14:11 UTC, stocaaro approved these changes

2023-09-15 14:11 UTC, stocaaro commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +	} catch (error) {}
Should we do something with this catch? Maybe log?

2023-09-15 14:29 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInHelpers.ts
> +	} catch (error) {}
good point. If `getCurrentUser` throws it's because no tokens were found. So in the context of sign-in that is expected always. So logging something doesn't really help here.

2023-09-15 14:29 UTC, merged

2024-02-15 10:12 UTC, TeoChi-CF commented
To bad as this change made no longer possible to revalidate user password :(