chore(auth): fix unnecessary network calls in getCurrentUser API
aws-amplify/amplify-js pull request #12052
Opened 2023-09-14 15:49 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-14 15:58 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> -	const { tokens } = await fetchAuthSession(amplify, {
Isn't this more of a bug in `fetchAuthSession`? I.e. it should only make a network call if needs to refresh tokens. Would it make more sense to fix it there to avoid using the token providers directly? Thinking about a case where a customer doesn't have cognito providers configured, but calls the cognito API, might be other edge cases

2023-09-14 16:02 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> -	const { tokens } = await fetchAuthSession(amplify, {
I think this API is mainly focused on the usage of userPools. Checked with the other platforms and they rely on tokens mainly. About the edge case, I think a validation error will be thrown, at the end this API is meant to be a Cognito implementation.

2023-09-14 16:03 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +		forceRefresh: getCurrentUserRequest?.recache,
What is this `recache` thing?

2023-09-14 16:04 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +		forceRefresh: getCurrentUserRequest?.recache,
That was the BR naming suggestion in the API reviews to by pass cache

2023-09-14 16:11 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> -	const { tokens } = await fetchAuthSession(amplify, {
Got it, that's fair. But isn't it also true that `fetchAuthSession` shouldn't make network calls unless it needs to refresh?

2023-09-14 16:18 UTC, HuiSF requested changes

2023-09-14 16:18 UTC, HuiSF commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +	const tokens = await CognitoUserPoolsTokenProvider.getTokens({
This is going to break SSR use case as this change uses the client singleton,

2023-09-14 16:19 UTC, AllanZhengYP approved these changes
The change looks good to me! We need to fix the token storage issue with `fetchAuthSession` separately.

2023-09-14 16:24 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +	const tokens = await CognitoUserPoolsTokenProvider.getTokens({
is there away to not have fetchAuthSession for the SSR case ?

2023-09-14 21:13 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> -	const { tokens } = await fetchAuthSession(amplify, {
yeah I mean I just wanted to decoupled credentials from this API.

2023-09-14 21:14 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +		forceRefresh: getCurrentUserRequest?.recache,
removing this flag after discussing async

2023-09-14 21:14 UTC, israx commented on packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts
> +	const tokens = await CognitoUserPoolsTokenProvider.getTokens({
just pushed a solution based on your recommendation. Now tokens are retrieved from the internal Auth class

2023-09-14 21:29 UTC, HuiSF approved these changes

2023-09-14 21:29 UTC, HuiSF commented on packages/auth/src/providers/cognito/apis/getCurrentUser.ts
> -import { AuthUser, GetCurrentUserRequest } from '../../../types';
Probably can remove `GetCurrentUserRequest` from types now.

2023-09-15 14:12 UTC, stocaaro approved these changes

2023-09-15 14:47 UTC, stocaaro approved these changes

2023-09-15 16:24 UTC, merged