Datastore v6
aws-amplify/amplify-js pull request #12076
Opened 2023-09-18 20:59 UTC by elorzafe

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-18 21:11 UTC, david-mcafee commented on package.json
> +			"packages/api",
nit: previously had these in alphabetical order. Not a blocker.

2023-09-18 21:24 UTC, david-mcafee submitted a review, later dismissed
Left a few comments on my first pass of this PR - still have more of the diff to review, but wanted to get some initial discussion going. Thanks!

2023-09-18 21:24 UTC, david-mcafee commented on packages/api/src/index.ts
> +export { generateClient };
Since you're making updates to the API category, I'd also reflect that in the PR title / commit message.

2023-09-18 21:24 UTC, david-mcafee commented on packages/datastore/src/authModeStrategies/multiAuthStrategy.ts
> +						authModes.add('jwt');
Same here (i.e. constants), and below

2023-09-18 21:24 UTC, david-mcafee commented on packages/datastore/src/sync/processors/mutation.ts
> +		// 		}
I wouldn't want to ship this without re-enabling the background process manager. Want to avoid unintended side effects.

2023-09-18 21:24 UTC, david-mcafee commented on packages/datastore/src/sync/processors/mutation.ts
> +							new Promise<void>(res => res())
Why not `onTerminate`?

2023-09-18 21:24 UTC, david-mcafee commented on packages/datastore/src/sync/processors/subscription.ts
> +													debugger;
Remove `debugger`

2023-09-18 21:24 UTC, david-mcafee commented on packages/datastore/src/sync/processors/subscription.ts
> +												// Hub.remove('api', boundFunction);
Why is this commented out?

2023-09-20 01:40 UTC, elorzafe commented on packages/datastore/src/authModeStrategies/multiAuthStrategy.ts
> +						authModes.add('jwt');
its typed

2023-09-20 01:40 UTC, elorzafe commented on packages/datastore/src/authModeStrategies/multiAuthStrategy.ts
> +					authModes.add('lambda');
its typed

2023-09-20 12:55 UTC, jimblanc commented on packages/api-rest/package.json
> +		"axios": "0.26.0",
Why are we downgrading axios so much? Wasn't there a plan to remove Axios or is that covered by other work? Also we should consider using `^` on this dep to improve flattening in customer apps.

2023-09-20 12:55 UTC, jimblanc commented on packages/api-rest/package.json
>  		"url": "0.11.0"
We'll need to remove this dependency at some point to avoid introducing another install warning.

```suggestion
		"url": "0.11.0"
```

2023-09-20 15:08 UTC, svidgen requested changes

2023-09-20 15:08 UTC, svidgen commented on packages/datastore/package.json
> -					"strictNullChecks": true
The corresponding flag in `tsconfig.json` is pretty critical, IIRC. So, it should be left on here as well; else, I think we are *likely* releasing incorrect types.

2023-09-20 15:08 UTC, svidgen commented on packages/datastore/package.json
> +			"__tests__/mutation.test.ts"
These are actually pretty critical. I'm not sure I can be persuaded to ship with these omitted.

2023-09-20 17:32 UTC, elorzafe commented on packages/datastore/src/sync/processors/subscription.ts
> +												// Hub.remove('api', boundFunction);
Good catch looking now

2023-09-20 17:39 UTC, elorzafe commented on packages/api-rest/package.json
> +		"axios": "0.26.0",
This is the as what we have on v5, we will remove this once the api-rest work is completed

2023-09-20 17:40 UTC, elorzafe commented on packages/core/src/singleton/API/types.ts
>  		modelIntrospectionSchema?: any;
This are coming from parseAmplifyConfig

2023-09-20 17:40 UTC, elorzafe commented on packages/datastore/package.json
> +				"diagnostics": false,
re enabled

2023-09-20 17:46 UTC, elorzafe commented on packages/datastore/package.json
> +			"__tests__/mutation.test.ts"
I would need some help with the mocks there

2023-09-20 20:21 UTC, jimblanc approved these changes

2023-09-20 20:25 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +});
I don't know what it means for `Amplify.configure()` to re-configure DataStore mid-lifetime.

Highly advised to **simply remove this** until we understand the intended use-case and consequences of this.

2023-09-20 20:27 UTC, svidgen approved these changes
Approving to ship preview with caveats:

1. The currently-skipped tests safeguard against control flow errors. These errors were witnessed in high frequency for the Studio use case. This may affect Studio's ability to actually test against this successfully.
2. We need a V5 versus V6 comparison of the customer-facing exported types. My understanding is that the config changes result in incorrect types.
3. Dynamic reconfiguration on DataStore is a special class of reconfiguration. I would highly advise removing it entirely until we understand the use-cases and have well-defined behavior.

Approving to unblock downstream consumption of core interfaces. But, we'll need to see tasks to dig on each of the above.

2023-09-20 20:29 UTC, merged