feat(data): add GraphQL API config and credential helpers
aws-amplify/amplify-js pull request #12125
Opened 2023-09-26 01:32 UTC by david-mcafee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-27 21:56 UTC, svidgen reviewed
I was actually under the impression that `fetchAuthSession()` was performing sufficient validation. But, maybe the validation is "disconnected" from auth modes requested at the `graphql()` call-site.

Help me understand!

cc @elorzafe

2023-09-27 21:56 UTC, svidgen commented on packages/api-graphql/src/utils/resolveAuthSession.ts
> +	);
If I'm reading this right, it's too aggressive. Not all of these values are necessarily defined, are they?

https://github.com/aws-amplify/amplify-js/blob/next/main/packages/core/src/singleton/Auth/index.ts#L50-L52

cc @elorzafe

2023-09-27 22:17 UTC, david-mcafee commented on packages/api-graphql/src/utils/resolveAuthSession.ts
> +	);
If you take a look at the tests, that should help clarify things. This is essentially making sure that _something_ is present. As long as one of these exists, it does not fail.

2023-09-27 22:21 UTC, david-mcafee commented on packages/api-graphql/src/utils/resolveAuthSession.ts
> +	);
Looking through the Auth code, it _does_ appear that it throws if nothing is provided. @elorzafe - do you have context as to why other categories are making these checks on `fetchAuthSession`?

2023-09-27 22:21 UTC, david-mcafee commented
> I was actually under the impression that `fetchAuthSession()` was performing sufficient validation. But, maybe the validation is "disconnected" from auth modes requested at the `graphql()` call-site.
> 
> Help me understand!
> 
> cc @elorzafe

Took a better look at `fetchAuthSession`, and you're correct. I can remove this util, but I would still be in favor of keeping the config util.

2023-09-29 14:04 UTC, svidgen approved these changes

2023-10-02 17:11 UTC, stocaaro submitted a review, later dismissed

2023-10-04 13:17 UTC, svidgen requested changes

2023-10-04 13:17 UTC, svidgen commented on packages/api-graphql/src/utils/resolveConfig.ts
>  		Amplify.getConfig().API?.GraphQL ?? {};
This category config is `API.GraphQL` here, but `API.AppSync` in the tests.

I believe this one (`GraphQL`) is correct, per the config design review.

2023-10-04 16:26 UTC, david-mcafee commented on packages/api-graphql/src/utils/resolveConfig.ts
>  		Amplify.getConfig().API?.GraphQL ?? {};
Started this PR before the new config changes came in, will update.

2023-10-04 17:19 UTC, stocaaro approved these changes

2023-10-04 19:04 UTC, stocaaro submitted a review, later dismissed

2023-10-04 20:04 UTC, jimblanc reviewed
Looks good

2023-10-04 20:04 UTC, jimblanc commented on packages/api-graphql/src/utils/errors/validation.ts
> +	[APIValidationErrorCode.NoAuthSession]: {
Is this getting used anywhere? If so I'd refactor the message to be a little more user friendly

2023-10-04 20:05 UTC, david-mcafee commented on packages/api-graphql/src/utils/errors/validation.ts
> +	[APIValidationErrorCode.NoAuthSession]: {
Not any more! Will remove

2023-10-04 20:11 UTC, jimblanc submitted a review, later dismissed

2023-10-04 20:13 UTC, david-mcafee commented on packages/api-graphql/src/utils/resolveConfig.ts
> +	);
The check is validating that if there’s a custom endpoint being used, and the customer _only_ supplies the region, it will fail unless they also supply the endpoint.

2023-10-04 20:14 UTC, david-mcafee commented on packages/api-graphql/src/utils/resolveConfig.ts
> +	assertValidationError(!!region, APIValidationErrorCode.NoRegion);
Good point - will remove.

2023-10-04 21:20 UTC, svidgen submitted a review, later dismissed

2023-10-04 23:38 UTC, closed without merging