feat(api): update REST API config interface
aws-amplify/amplify-js pull request #12122
Opened 2023-09-25 22:42 UTC by AllanZhengYP

#### Description of changes

Update the REST API configuration interface. This change does not change the GraphQL interface yet although we intend
make the REST and GraphQL endpoint config interface align. 

#### Issue #, if available

#### Description of how you validated changes
Unit test

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-26 16:32 UTC, elorzafe commented on packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts
> +import { ApiAuthMode } from '@aws-amplify/core/lib-esm/singleton/API/types';
I missed that, this should be exported from `internal` utils right, not `lib-esm`

2023-09-26 16:36 UTC, elorzafe commented on packages/core/src/singleton/API/types.ts
> +	| { type: 'iam'; region?: string; service?: string }
should we make `region` required or we would try to parse it from `url`?

2023-09-26 16:38 UTC, elorzafe requested changes
Overall looks good,have minor comments

Thanks @AllanZhengYP 🎖️

2023-09-27 16:08 UTC, AllanZhengYP commented on packages/core/src/singleton/API/types.ts
> +	| { type: 'iam'; region?: string; service?: string }
We'll attempt to parse it from `url`.

2023-09-27 22:04 UTC, david-mcafee commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -			case 'jwt':
@elorzafe - are we planning on changing this?

2023-09-27 22:04 UTC, david-mcafee commented on packages/core/src/parseAWSExports.ts
> +				} as any,
Why `as any`?

2023-09-28 22:49 UTC, AllanZhengYP commented on packages/core/src/singleton/API/types.ts
> +			headers?: () => Promise<Headers>;
Need to accept apiName here.

2023-09-28 22:49 UTC, AllanZhengYP commented on packages/core/src/singleton/API/types.ts
> +	 * Option API key string. Required only if the auth mode is 'apiKey'.
```suggestion
	 * Optional API key string. Required only if the auth mode is 'apiKey'.
```

2023-09-28 23:03 UTC, elorzafe commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -			case 'jwt':
it will be `oidc` or `userPool`

2023-09-29 00:20 UTC, david-mcafee requested changes

2023-09-29 00:20 UTC, david-mcafee commented on packages/core/src/singleton/API/types.ts
> +type GraphQLEndpointConfig = {
Not entirely sure about the naming. What about something like: 

```suggestion
type APIGraphQLConfig = {
```

2023-09-29 00:20 UTC, david-mcafee commented on packages/core/src/parseAWSExports.ts
> +			GraphQL: {
What about `graphql_headers`?

Also, shouldn't we be mapping `graphql_endpoint` to the custom domain endpoint? Same for `graphql_endpoint_iam_region`?

2023-09-29 00:20 UTC, david-mcafee commented on packages/core/src/singleton/API/types.ts
> -		userAgentSuffix?: string;
Why are these being removed?

2023-09-29 00:38 UTC, elorzafe requested changes
Please update the large diff by adding a line to `subscribe`, and a change related to apiKey as well.

Thanks @AllanZhengYP 🏅

2023-09-29 00:38 UTC, elorzafe commented on packages/core/src/parseAWSExports.ts
> +				defaultAuthMode: authTypeMapping[aws_appsync_authenticationType],
Can this be `undefined`?

2023-09-29 00:38 UTC, elorzafe commented on packages/core/src/parseAWSExports.ts
> +						[name]: {
what happen if `name` is `undefined`?

2023-09-29 00:38 UTC, elorzafe commented on packages/core/src/singleton/API/types.ts
> +	 * Endpoint to custom GraphQL API.
```suggestion
	 * Custom domain endpoint for GraphQL API.
```

What do you think about this?

2023-09-29 00:38 UTC, elorzafe commented on packages/datastore/src/datastore/datastore.ts
> +			apiKey = currentAppSyncConfig.apiKey;
This is no longer needed, is safe to set `aws_appsync_apiKey: currentAppSyncConfig.GraphQL.apiKey` on L2458

2023-09-29 00:38 UTC, elorzafe commented on packages/datastore/src/sync/processors/subscription.ts
> +											queryObservable.subscribe({
Can you add the new line to avoid the difference

2023-09-29 00:38 UTC, elorzafe commented on packages/core/__tests__/parseAWSExports.test.ts
> +import internal from 'stream';
why is this needed?

2023-09-29 16:48 UTC, AllanZhengYP commented on packages/core/src/parseAWSExports.ts
> +						[name]: {
Name always exists in `aws-exports` from CLI, do you think we need to validate it here?

2023-09-29 16:49 UTC, AllanZhengYP commented on packages/datastore/src/datastore/datastore.ts
> +			apiKey = currentAppSyncConfig.apiKey;
Sounds good. Thank you for confirmation!

2023-09-29 18:41 UTC, AllanZhengYP commented on packages/core/src/parseAWSExports.ts
> +				defaultAuthMode: authTypeMapping[aws_appsync_authenticationType],
@elorzafe Should we throw error here if CLI is giving non-standard auth types?

2023-09-29 19:16 UTC, elorzafe commented on packages/core/src/parseAWSExports.ts
> +				defaultAuthMode: authTypeMapping[aws_appsync_authenticationType],
Maybe if is null I would fallback to `iam` and add a logger message

2023-09-29 19:18 UTC, elorzafe commented on packages/core/src/parseAWSExports.ts
> +						[name]: {
if thats the case then I am cool with this

2023-09-29 19:57 UTC, stocaaro reviewed
Looks good overall. Seems like it covers almost everything I was trying to fix in my change. Might be worth changing a couple lines to get it all the way there.  Good either way if you would prefer to leave that work as a followup that I can do when this ships.

2023-09-29 19:57 UTC, stocaaro commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +			authenticationType: GraphQL?.defaultAuthMode,
It looks like you're trying to avoid doubling up with [my change](https://github.com/aws-amplify/amplify-js/pull/12118). Based on this implementation, if you change this to `authMode` doesn't it do everything I was trying to  accomplish. No worries if its this easy, would be glad to see it done here and discard my change.

I suppose we should also drop `authToken`.  I think thats essentially it, right?

2023-09-29 21:49 UTC, elorzafe approved these changes
Looks great

Thanks @AllanZhengYP 🏅

2023-09-29 23:07 UTC, stocaaro approved these changes

2023-09-29 23:55 UTC, david-mcafee commented on packages/core/package.json
> +		"graphql": "15.8.0",
Why is this needed?

2023-09-29 23:56 UTC, david-mcafee requested changes
Only concern is around the additional dev dependency

2023-09-30 00:01 UTC, david-mcafee submitted a review, later dismissed

2023-10-02 17:07 UTC, stocaaro submitted a review, later dismissed

2023-10-02 18:48 UTC, elorzafe approved these changes
Looks good!

Thanks @AllanZhengYP 🏅

2023-10-02 19:11 UTC, david-mcafee approved these changes
LGTM! 🚀

2023-10-02 19:12 UTC, merged

2023-10-02 19:12 UTC, jimblanc approved these changes