[WIP]feat(api-rest): internal API handling GraphQL requests
aws-amplify/amplify-js pull request #12138
Opened 2023-09-27 16:47 UTC by AllanZhengYP

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-09-27 22:06 UTC, david-mcafee commented on packages/api-rest/src/RestClient.ts
> +	ajax(url: string, method: string, init: any) {
Can we remove `any` here?

2023-09-28 20:55 UTC, AllanZhengYP commented on packages/api-rest/src/RestClient.ts
> +	ajax(url: string, method: string, init: any) {
@david-mcafee  Don't worry about it. This file will be removed.

2023-09-28 21:30 UTC, david-mcafee requested changes
Left a few preliminary comments.

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/RestClient.ts
> +	constructor(options: any) {
Can we type this?

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/RestClient.ts
> +	ajax(url: string, method: string, init: any) {
Same here

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/internalPost.ts
> +	return internalPost(Amplify, input);
Why pass `Amplify` here?

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/utils/resolveCredentials.ts
> +	const { credentials } = await amplify.Auth.fetchAuthSession();
If it's token-based auth, won't this be empty?

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +			const { body: responsePayload } = await this._api.post({
Why this update to the return type?

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/errors/CanceledError.ts
> +	!!error && error instanceof CanceledError;
This was using `axios` previously - https://github.com/aws-amplify/amplify-js/blob/main/packages/api-rest/src/RestClient.ts#L300-L302. Is this comparable?

2023-09-28 21:30 UTC, david-mcafee commented on packages/api-rest/src/utils/parseUrl.ts
> + * Custom domain is not supported.
`Custom domain is not supported`?

2023-09-28 21:32 UTC, AllanZhengYP commented on packages/api-rest/src/internalPost.ts
> +	return internalPost(Amplify, input);
The client-side `internalPost` accepts the Singleton. However, the SSR version of `internalPost` uses a different instance.

2023-09-28 21:33 UTC, AllanZhengYP commented on packages/api-rest/src/utils/resolveCredentials.ts
> +	const { credentials } = await amplify.Auth.fetchAuthSession();
@david-mcafee  Yes, that's why we throw validation error in the line below

2023-09-28 21:35 UTC, AllanZhengYP commented on packages/api-rest/src/errors/CanceledError.ts
> +	!!error && error instanceof CanceledError;
@david-mcafee No, you can NOT use this to an error thrown by Axios, which is ok

2023-09-28 21:36 UTC, AllanZhengYP commented on packages/api-rest/src/utils/parseUrl.ts
> + * Custom domain is not supported.
For graphql calls, you need to specify the `signinRegionInfo` config anyway, then `parseUrl` will not be called.

2023-09-28 21:42 UTC, david-mcafee commented on packages/api-rest/src/utils/parseUrl.ts
> + * Custom domain is not supported.
Do you mean that when calling the REST api, `signinRegionInfo` has to be specified when using a custom endpoint?

2023-09-28 22:00 UTC, AllanZhengYP commented on packages/api-rest/src/utils/parseUrl.ts
> + * Custom domain is not supported.
@david-mcafee You need to provide `signingServiceInfo` when your auth mode is `iam`, and signing region cannot be inferred from url(i.e. custom endpoint). See the entrypoint readme: 
```
/**
 * Internal-only REST POST handler to send GraphQL request to given endpoint. By default, it will use IAM to authorize
 * the request. In some auth modes, the IAM auth has to be disabled. Here's how to set up the request auth correctly:
 * * If auth mode is 'iam', you MUST NOT set 'authorization' header and 'x-api-key' header, since it would disable IAM
 *   auth. You MUST also set 'input.options.signingServiceInfo' option.
 *   * The including 'input.options.signingServiceInfo.service' and 'input.options.signingServiceInfo.region' are
 *     optional. If omitted, the signing service and region will be inferred from url.
 * * If auth mode is 'none', you MUST NOT set 'options.signingServiceInfo' option.
 * * If auth mode is 'apiKey', you MUST set 'x-api-key' custom header.
 * * If auth mode is 'oidc' or 'lambda' or 'userPool', you MUST set 'authorization' header.
 *
 * @internal
 */
```

2023-09-28 22:01 UTC, AllanZhengYP commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +			const { body: responsePayload } = await this._api.post({
To support http status code, and headers along with body.

2023-09-29 18:13 UTC, svidgen submitted a review, later dismissed
`api-graphql` changes look sane. Approving for that subset of the diff.

2023-09-29 18:23 UTC, david-mcafee commented on packages/api-rest/src/utils/resolveCredentials.ts
> +	const { credentials } = await amplify.Auth.fetchAuthSession();
But we should be supporting token-based auth, when credentials are empty. Right?

2023-09-29 18:39 UTC, david-mcafee submitted a review, later dismissed
Approving changes to `api-graphql`

2023-09-29 20:38 UTC, jimblanc approved these changes
Looks good, some non-blocking nits & questions

2023-09-29 20:38 UTC, jimblanc commented on packages/api-rest/internals/post/package.json
> +	"name": "@aws-amplify/api-rest/internals/post",
~Not a huge deal since it's internal, but why does this API have its own path vs just being exported from `internals`? Ditto for `/server` route~

Nevermind, it looks like this is because technically we have two internal posts?

2023-09-29 20:38 UTC, jimblanc commented on packages/api-rest/src/errors/CancelledError.ts
> +export class CancelledError extends RestApiError {
Nit: Would prefer for this to be called `CancelError` to align with the `isCancelError` predicate

2023-09-29 20:38 UTC, jimblanc commented on packages/api-rest/src/internal/post.ts
Nit: Can we rename `internal/` as `internals/` to align with the export path?

2023-09-29 20:38 UTC, jimblanc commented on packages/api-rest/src/internalPost.ts
> +import { post as internalPost } from './internal/post';
The folder structure here is a little hard to grok because we technically have two "internal" POST APIs 🤔 I think I'd almost prefer a different API name to differentiate them and move this to `internals/`. Maybe `postGraphQL` or something? Not a huge deal and I might be missing something

2023-09-29 21:08 UTC, stocaaro approved these changes

2023-09-29 21:28 UTC, AllanZhengYP commented on packages/api-rest/src/errors/CancelledError.ts
> +export class CancelledError extends RestApiError {
Will follow up on separate PR

2023-09-29 21:47 UTC, svidgen approved these changes

2023-09-29 22:01 UTC, jimblanc approved these changes

2023-09-29 22:05 UTC, merged

2023-10-09 19:27 UTC, david-mcafee commented on packages/api-rest/src/errors/CanceledError.ts
> +export class CanceledError extends RestApiError {
Nevermind this. Both are technically correct, but the single "L" is more common.