chore: Fix appsync argument passing
aws-amplify/amplify-js pull request #12169
Opened 2023-10-02 21:10 UTC by stocaaro

#### Description of changes
Review all attribute in the `InternalGraphQLAPI` interface.
- Remove unneeded attributes
- Pass through attributes that should be used
- Allow `atuhType` to be passed in different from the default

#### Description of how you validated changes
Verified that unit tests work as expected following this change. (Small test changed needed to keep mock match working).

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-02 21:48 UTC, AllanZhengYP approved these changes

2023-10-02 21:49 UTC, AllanZhengYP requested changes

2023-10-02 21:49 UTC, AllanZhengYP commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -				))),
`authMode` must be kept I think

2023-10-02 21:55 UTC, stocaaro commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -				))),
I was thinking this too. The first arg maps through as `defaultAuthenticationType` which isn't used. I thought maybe this should override with the input, but this doesn't match the v5 implementation. Is there a new feature in v6 that needs this, and if so, what is the target behavior?

2023-10-02 23:14 UTC, svidgen requested changes

2023-10-02 23:14 UTC, svidgen commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -				))),
It gets used here in V5: https://github.com/aws-amplify/amplify-js/blob/main/packages/api-graphql/src/internals/InternalGraphQLAPI.ts#L126-L127

I suspect it was inadvertently stripped out of the function during the config shuffle.

@david-mcafee Can you confirm? Is it on your radar to fix and/or test that auth mode overrides at the call site behave correctly in V6?

2023-10-03 14:46 UTC, stocaaro commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -				))),
Updated to pass this through. Its interesting that the argument is named `defaultAuthenticationType` in the v5 version since this looks like something that is passed through from the API call.

I have updated this change to mirror the v5 pass through logic.

2023-10-03 21:44 UTC, AllanZhengYP approved these changes

2023-10-04 14:25 UTC, svidgen approved these changes

2023-10-04 14:32 UTC, merged