Update Token Storage to use V5 keys
aws-amplify/amplify-js pull request #12184
Opened 2023-10-04 02:41 UTC by elorzafe

#### Description of changes

Refactor token store to use V5 keys (avoid migration)

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-04 17:25 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
Why is the `.oauth` required? Was that how it was in v5?

2023-10-04 17:25 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +			(await this.keyValueStorage.getItem(authKeys.oauthSignIn)) ||
Prefer `??` over `||`

2023-10-04 17:25 UTC, cshfang commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +				(await this.getKeyValueStorage().getItem(authKeys.clockDrift)) || '0';
Prefer `??` over `||`

Here and several other places in this PR (some were existing but this is a good chance to fix those)

2023-10-04 19:43 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
On V5 it does not use the provider or identifier, is just called `amplify-signin-with-hostedUI`

2023-10-04 19:43 UTC, elorzafe commented on packages/auth/__tests__/providers/cognito/tokenProvider.test.ts
> +	test('load tokens from store', async () => {
good point, I will add those as well

2023-10-04 20:34 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
Oh so why is it needed here?

2023-10-04 21:21 UTC, israx commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> -	private authKeys: AuthKeys<keyof typeof AuthTokenStorageKeys> | undefined;
This was intentionally added to memoize the `authKeys`

2023-10-04 21:22 UTC, israx commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +		const lastAuthUser = tokens.accessToken?.payload?.sub || 'user';
is that how lastAuthUser is defined in v5?

2023-10-04 21:30 UTC, israx commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +			(await this.getKeyValueStorage().getItem(authKeys.deviceMetadata)) || '{}'
now we need to get the 3 device keys separate. `deviceKey`, `deviceGroupKey` and `secretPasswordKey`

2023-10-04 21:31 UTC, israx commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +			(await this.getKeyValueStorage().getItem(authKeys.deviceMetadata)) || '{}'
and JSON.parse shouldn't be valid anymore

2023-10-04 21:31 UTC, israx commented on packages/auth/src/providers/cognito/tokenProvider/types.ts
> +	deviceMetadata: 'deviceKey',
we need to add all the device and oauth keys here as well

2023-10-04 21:35 UTC, israx requested changes
Thanks @elorzafe . I think we are missing some keys. Specially the device ones.

2023-10-05 00:10 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
so the app can scoped down to the userpool, thinking if a customer has two userpools and one is using hostedui and the other don't, this change allows to scope down this behavior to only the cliend id that has enable hostedUI

2023-10-05 00:13 UTC, elorzafe commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> -	private authKeys: AuthKeys<keyof typeof AuthTokenStorageKeys> | undefined;
the problem is that is updated when a new user logs in

2023-10-05 00:14 UTC, elorzafe commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +		const lastAuthUser = tokens.accessToken?.payload?.sub || 'user';
I will update this

2023-10-05 00:43 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
Looking at the keys are using here

```typescript
export const OAuthStorageKeys = {
	inflightOAuth: 'inflightOAuth',
	oauthSignIn: 'oauthSignIn',
	oauthPKCE: 'oauthPKCE',
	oauthState: 'oauthState',
};
```

all of them are already prefixed/suffixed by `oauth`, so this `.oauth` may be redundant? I think that's what Chris meant...

2023-10-05 07:00 UTC, ashwinkumar6 commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +			authKeys.randomPasswordKey
I think we cache device metadata [with name "deviceMetadata"](https://github.com/elorzafe/aws-amplify/blob/0697591e7523638c2ad49734b315cccc7a01ba01/packages/auth/src/providers/cognito/tokenProvider/cacheTokens.ts#L44) as a single object which contains `deviceKey`, `deviceGroupKey` `randomPassword` inside it.

But when we try to get them we individually search for these keys.
There might be miss-match in storing and reading

2023-10-05 15:52 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
makes sense, good catch

2023-10-05 15:53 UTC, elorzafe commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +			authKeys.randomPasswordKey
@ashwinkumar6 is not needed because the key contains the `username` as part of the prefix

2023-10-05 16:54 UTC, ashwinkumar6 commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +			authKeys.randomPasswordKey
Ahhhh yes got it thanks, 
we can use this to support multiple users

2023-10-05 17:07 UTC, israx approved these changes
lgtm . Thanks @elorzafe

2023-10-05 19:01 UTC, ashwinkumar6 submitted a review, later dismissed

2023-10-05 19:08 UTC, cshfang approved these changes
Couple places with the `||` again but approved otherwise

2023-10-05 19:08 UTC, cshfang commented on packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
> +		(access_token && decodeJWT(access_token).payload.username) || 'username';
Nit: Prefer `??`

2023-10-05 19:08 UTC, cshfang commented on packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
> +		(accessToken && decodeJWT(accessToken).payload.username) || 'username';
Nit: Prefer `??`

2023-10-05 19:13 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts
> +	return getAuthStorageKeys(OAuthStorageKeys)(provider, `${identifier}.oauth`);
updated

2023-10-05 19:17 UTC, jimblanc approved these changes

2023-10-05 19:18 UTC, HuiSF approved these changes

2023-10-05 19:18 UTC, ashwinkumar6 approved these changes

2023-10-05 19:24 UTC, cshfang approved these changes

2023-10-05 19:52 UTC, cshfang approved these changes

2023-10-05 19:56 UTC, ashwinkumar6 approved these changes

2023-10-05 20:04 UTC, merged