feat(auth): add auto sign-in support
aws-amplify/amplify-js pull request #12229
Opened 2023-10-06 22:02 UTC by israx

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-06 22:49 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signUp.ts
> +
❤️

2023-10-06 22:51 UTC, elorzafe commented on packages/auth/src/providers/cognito/types/options.ts
> +	autoSignIn?: SignInOptions | true;
is this ok?

2023-10-06 23:07 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +	}, MAX_AUTOSIGNIN_POLLING_MS);
shouldnt this be only for link verification?

2023-10-06 23:11 UTC, AllanZhengYP reviewed
Thanks a lot for pushing this through the line. I only have a few clarification question, otherwise it looks solid.

2023-10-06 23:11 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/types/options.ts
> +	autoSignIn?: SignInOptions | true;
Can we do this?
```suggestion
	autoSignIn?: SignInOptions | boolean;
```

2023-10-06 23:11 UTC, AllanZhengYP commented on packages/core/src/Hub/types/AuthTypes.ts
> +export type AuthAnyAttribute = string & {};
Nit: why do we need `{}`?

2023-10-09 12:59 UTC, israx commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +	let timer: NodeJS.Timer | undefined;
yeah good catch.

2023-10-09 13:09 UTC, israx commented on packages/auth/src/providers/cognito/types/options.ts
> +	autoSignIn?: SignInOptions | true;
yeah I think we can do it. The idea was that having `true` will be more explicit to enabling auto-sign-in but we still have a pending discussion to consider enabling it by default so I think it make sense to have a boolean.

2023-10-09 13:11 UTC, israx commented on packages/core/src/Hub/types/AuthTypes.ts
> +export type AuthAnyAttribute = string & {};
I removed all the auth types from core. I was initially trying to create a public auto sign-in hub event and forgot to remove these unused types.

2023-10-09 16:41 UTC, israx commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +const debouncedAutoSignInWithLink = debounce(handleAutoSignInWithLink, 300);
it's fired when `debouncedAutoSignInWithLink` is called. Or when `autoSignIn` invoked.

So the sequence would be `call autoSignIn` -> `call debouncedAutoSignInWithLink` -> `call setTimeOut`

2023-10-09 16:44 UTC, israx commented on packages/auth/src/providers/cognito/apis/confirmSignUp.ts
> +							stopListener();
It didn't end up working that well. The issue was that `Hub.listen` runs sync and the confirmSignUp ends up returning a value before `Hub.listen` is resolved.

2023-10-09 17:48 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +				reject(error);
I just realize how bed I misunderstood the code. Thank you a lot!

2023-10-09 17:49 UTC, AllanZhengYP submitted a review, later dismissed
Thank you for putting this together!🚀

2023-10-09 21:03 UTC, elorzafe commented on packages/auth/__tests__/providers/cognito/autoSignIn.test.ts
> +	test('Auto sign-in should resolve to a signIn output', async () => {
should this test call `signUp` before?

2023-10-09 21:09 UTC, israx commented on packages/auth/__tests__/providers/cognito/autoSignIn.test.ts
> +	test('Auto sign-in should resolve to a signIn output', async () => {
I did try calling signUp before but I think jest has some running conditions and it is not able to set the context of the `autoSignIn` API on time and it throws an Error. This doesn't happen while manual testing.

2023-10-09 21:10 UTC, israx commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> +	autoSignIn = initialAutoSignIn;
yeap. Internal only. These are not exposed to customers

2023-10-09 21:11 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +		const currentTime = Date.now() - start;
I would rename this to elapsedTime or something like that

2023-10-09 21:13 UTC, elorzafe requested changes
I think this is very close, can you add more tests.

- Multiple confirmSignUp are made
- Different user is confirmed
- Timeouts using jest timers
- ConfirmSignUp fails
- AutoSignIn fails

2023-10-09 21:23 UTC, elorzafe commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +					resetAutoSignIn();
this could defined on  `finally`

2023-10-09 21:30 UTC, israx commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +					resetAutoSignIn();
This is code doesn't always run. It is inside a condition.

2023-10-09 23:02 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signUp.ts
> +	if (signInServiceOptions || autoSignIn === true) {
I think you need to check if `autoSignIn` is an object as well?

2023-10-09 23:03 UTC, elorzafe commented on packages/auth/src/providers/cognito/apis/signUp.ts
> +	if (signInServiceOptions || autoSignIn === true) {
nvm, it seems that is capture on `signInServiceOptions`

2023-10-09 23:08 UTC, elorzafe submitted a review, later dismissed
Looks good

Thanks @israx 🏅

2023-10-09 23:13 UTC, AllanZhengYP commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * enable this option you need to go to Amazon Cognito [console](https://aws.amazon.com/pm/cognito/?trk=f5fef02c-2926-48d3-898a-b4d668742a20&sc_channel=ps&ef_id=CjwKCAjwyY6pBhA9EiwAMzmfwVpQnKgvNQ-yA7
Can you sanitize the link to remove the tracking datas?

2023-10-10 00:54 UTC, jimblanc commented on packages/aws-amplify/package.json
> +			"limit": "29.91 kB"
Dang, this is unfortunate. What's adding the new bundle size? It might be unavoidable but just as a sanity check we're not doing something odd.

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> +				'The autoSignIn flow has not started, been cancelled or been completed.',
```suggestion
				'The autoSignIn flow has not started or has been cancelled/completed.',
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * Auto signs a user in
```suggestion
 * Signs a user in automatically after signing up.
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * This API will auto sign a user in if the autoSignIn flow has been completed on the following cases:
```suggestion
 * This API will automatically sign a user in if the autoSignIn flow has been completed in the following cases:
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * This is the default option for autoSignIn.
```suggestion
 * - User confirmed their account with a verification code sent to their phone or email (default option).
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * - User was able to confirm their account with a verification link sent to their phone or email. In order to
```suggestion
 * - User confirmed their account with a verification link sent to their phone or email. In order to
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * enable this option you need to go to Amazon Cognito [console](https://aws.amazon.com/pm/cognito/?trk=f5fef02c-2926-48d3-898a-b4d668742a20&sc_channel=ps&ef_id=CjwKCAjwyY6pBhA9EiwAMzmfwVpQnKgvNQ-yA7
```suggestion
 * enable this option you need to go to the Amazon Cognito [console](https://aws.amazon.com/pm/cognito/), 
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * ```
```suggestion
 * Amplify.configure({
 *   Auth: {
 *     Cognito: {
 *       ...cognitoConfig,
 *       signUpVerificationMethod: "link" // the default value is "code"
 *     }
 *   }
 * });
 * ```
```

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * ```typescript
Does this example render correctly? It's missing the `*` on many lines.

2023-10-10 00:54 UTC, jimblanc commented on packages/auth/src/providers/cognito/utils/signUpHelpers.ts
> +export const HubInternal = new HubClass('internal-hub');
Nit: If we need to have an internal Hub, I would prefer for it to live in Core

2023-10-10 13:30 UTC, israx commented on packages/aws-amplify/package.json
> +			"limit": "29.91 kB"
yeah the issue is that is tight with sign-in

2023-10-10 13:44 UTC, israx commented on packages/auth/src/providers/cognito/apis/autoSignIn.ts
> + * ```typescript
just added the missing *

2023-10-10 16:16 UTC, jimblanc approved these changes

2023-10-10 16:23 UTC, AllanZhengYP approved these changes

2023-10-10 16:32 UTC, merged