Reenable dataastore unit tests
aws-amplify/amplify-js pull request #12325
Opened 2023-10-17 16:25 UTC by elorzafe

#### Description of changes

Reenabling datastore unit tests

#### Issue #, if available

There are 4 tests that are presenting issues compared to v5

splitted `DataStore.ts` tests into different modules per `describe` section
```
Test Suites: 29 passed, 29 total
Tests:       18 skipped, 1112 passed, 1130 total
Snapshots:   8 passed, 8 total
Time:        146.002s, estimated 246s
```

v5 has 1116 tests
#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-17 18:35 UTC, david-mcafee requested changes
Left some initial feedback. I have two primary concerns:

1. I don't think we should be skipping tests
2. It's not possible to parse the diff since the changes were moved around into separate files.

2023-10-17 18:35 UTC, david-mcafee commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> -	private _api = {
How was this updated without updating the GQL API tests? Those rely on this to work. Additionally, can you explain why this is necessary, in the first place?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/DataStore-1.ts
> +import 'fake-indexeddb/auto';
Can we revert this file split? This makes it impossible to parse what is actually being updated in these tests. I don't disagree that this should be split, but I would prefer it not to be in the context of major changes.

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/util.ts
> +	debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/util.ts
> +	debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/DataStore-3.ts
> +	debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +		debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +			debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +		debugger;
```suggestion
```

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +	const whatisthis = jest.requireActual('@aws-amplify/api-rest/internals');
Can we clean this up, since this isn't needed for debugging these tests anymore?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +		return Promise.reject(axiosError);
We don't use axios anymore, so this should be renamed

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +		it.skip('Should result in Network Error and get handled without breaking the Mutation Processor', async () => {
Is there a ticket for re-enabling skipped tests?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +		it.skip('Should send datastore details with the x-amz-user-agent in the rest api request', async done => {
Same here

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +			await new Promise(res => setTimeout(res, 1000));
What's going on here?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/__tests__/mutation.test.ts
> +// });
This is likely why you had to update the API category instantiation. Why not use this pattern?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +		// here is the problem
?

2023-10-17 18:35 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +// });
Why is this being commented out?

2023-10-17 19:00 UTC, svidgen commented on packages/datastore/__tests__/DataStore-1.ts
> +import 'fake-indexeddb/auto';
I was thinking the same. The reorganization is good, but it makes it pretty difficult to tell what if anything has actually changed.

If it's too difficult at this stage, we should at least get some links to a diff tool posted here to help review.

2023-10-17 19:48 UTC, elorzafe commented on packages/datastore/src/datastore/datastore.ts
> +		// here is the problem
good catch cleaning..

2023-10-17 19:49 UTC, elorzafe commented on packages/datastore/__tests__/mutation.test.ts
> +			await new Promise(res => setTimeout(res, 1000));
I was testing something, I am going to revert that

2023-10-17 19:50 UTC, elorzafe commented on packages/datastore/__tests__/DataStore-1.ts
> +import 'fake-indexeddb/auto';
I will revert back

2023-10-17 22:31 UTC, elorzafe commented on packages/datastore/src/datastore/datastore.ts
> +// });
good catch, reverting back

2023-10-17 22:42 UTC, elorzafe commented on packages/datastore/__tests__/mutation.test.ts
> +		it.skip('Should result in Network Error and get handled without breaking the Mutation Processor', async () => {
I can create that for the skip tests

2023-10-17 22:42 UTC, elorzafe commented on packages/datastore/__tests__/mutation.test.ts
> +		it.skip('Should result in Network Error and get handled without breaking the Mutation Processor', async () => {
only 4 compare to V5

2023-10-18 09:08 UTC, david-mcafee commented on packages/datastore/__tests__/DataStore.ts
> +		await DataStore.clear();
If we're skipping this test, I wouldn't make any updates to it (i.e. I would revert calling `DataStore.clear`)

2023-10-18 09:09 UTC, david-mcafee commented on packages/datastore/__tests__/DataStore.ts
> +		await DataStore.clear();
Can move these to an `afterEach`, and add a comment as to why these are now necessary?

2023-10-18 14:05 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> +
Strange. Do you recall if this move actually fixed something?

2023-10-18 14:23 UTC, svidgen submitted a review, later dismissed
It looks like some superfluous changes were mixed in with changes that look essential to adapting to V6-isms. Would be *ideal* to revert ay of those unnecessary, superfluous changes. But, *not critical* as part of this PR, IMO.

Thanks for doing this!

2023-10-18 14:23 UTC, svidgen commented on packages/datastore/__tests__/DataStore.ts
> +		await expect(promise).rejects.toThrow(
These changes were ultimately not needed. Correct?

2023-10-18 16:40 UTC, elorzafe commented on packages/datastore/__tests__/DataStore.ts
> +		await expect(promise).rejects.toThrow(
I will revert that

2023-10-18 16:41 UTC, elorzafe commented on packages/datastore/__tests__/DataStore.ts
> +
reverting that back

2023-10-19 01:28 UTC, elorzafe commented on packages/datastore/__tests__/DataStore.ts
> +		await DataStore.clear();
After trying this got into a rabbit hole

2023-10-20 16:33 UTC, svidgen approved these changes

2023-10-20 16:35 UTC, david-mcafee approved these changes

2023-10-20 16:57 UTC, merged