chore: remove type check for domElementId in autoTrackMedia
aws-amplify/amplify-js pull request #12433
Opened 2023-10-25 22:40 UTC by kvramyasri7

#### Description of changes

This change removes type check `domElementId` in `autoTackMedia` util function from `record` api

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-25 22:59 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +	if (!domElementId) {
later at line#197 it cast domElementId type to string. will that work without checking the type infront?

2023-10-25 23:09 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +	if (!domElementId) {
I believe that should be working  as the type of `properties: Record<string, unknown>`. which has  I do not see any red underscore or TS complaints😅.  That is a record which is `{}` can be casted to a string.

2023-10-25 23:20 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +	if (!domElementId) {
ok, just wondering if a user give the value with number `123`. When force type casting to string type, what could happen? I guess browser would just log an error in console. Not sure how react native would handle this.

2023-10-25 23:27 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +	if (!domElementId) {
Very Good Point. umm, RN I did not think about it. 😭 Any tip ?

2023-10-25 23:30 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +	if (!domElementId) {
I believe it does the same what the other logger messages do and just return from there isn't it?

2023-10-27 16:59 UTC, 5d requested changes

2023-10-27 16:59 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AnalyticsError({
For Analytics category, I think we only throw errors for config validation.

2023-10-27 17:44 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AnalyticsError({
umm, but why is it? any specific reason. Let me go and re-change it from `AnalyticsError` to `AmplifyError`

2023-10-27 17:55 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AnalyticsError({
For Analytics, the APIs are designed in fire and forget style, which is returning void. The customer won't have chance to catch those errors. It's better to just log and return here.

2023-10-27 18:15 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AnalyticsError({
Good to know. Thanks Di. Updated.

2023-10-27 18:45 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AmplifyError({
Could you give me an example code how customer could catch the error you thrown here?

2023-10-27 18:48 UTC, kvramyasri7 commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AmplifyError({
Web Or RN ?

2023-10-27 19:30 UTC, 5d commented on packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts
> +		throw new AmplifyError({
Either of them, I just want to understand how throwing `AmplifyError` would help here for customer to do error handling.

2024-03-14 00:10 UTC, closed without merging