feat: ssr support for graphql
aws-amplify/amplify-js pull request #12430
Opened 2023-10-25 21:54 UTC by iartemiev

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-25 21:55 UTC, iartemiev commented on .github/workflows/callable-release-verification.yml
> +  #   e2e:
This is temporary to get out a tagged release for testing. Will revert

2023-10-25 21:55 UTC, iartemiev commented on .github/workflows/push-preid-release.yml
> +      - ssr-api
Same as above. Will revert

2023-10-25 21:55 UTC, iartemiev commented on packages/adapter-nextjs/package.json
> +				"statements": 83
Also temporary. Writing unit tests now. Will revert

2023-10-25 22:07 UTC, svidgen commented on packages/api-graphql/src/types/index.ts
> +type GraphQLClient<
Maybe `GraphQLMethod`

2023-10-25 22:07 UTC, svidgen commented on packages/api-graphql/src/types/index.ts
> +export type GraphQLClientSSR<
Maybe `GraphQLMethodSSR`

2023-10-25 22:10 UTC, svidgen commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +			| ((fn: (amplify: any) => Promise<any>) => Promise<AmplifyClassV6>),
Not sure where the best place for this comment is, but at some point this should probably be renamed. We're not so much passing in "amplify" anymore as we are a contextualized `executor` or something like that.

2023-10-25 22:31 UTC, HuiSF commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +};
nit: 

```suggestion
	return typeof amplify !== 'function';
};
```

2023-10-25 22:31 UTC, HuiSF commented on packages/api-graphql/src/types/index.ts
> +	contextSpec: any,
```
import { AmplifyServer } from '@aws-amplify/core/internals/adapter-core';
```

```suggestion
	contextSpec: AmplifyServer.ContextSpec,
```

2023-10-25 22:31 UTC, HuiSF commented on packages/api-graphql/src/types/index.ts
> +
Is this actually the interface of the `client.graphql` method? If so should we use the type in `internalGraphQLAPI.ts` instead of the inline type?

2023-10-25 22:31 UTC, HuiSF commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +			| ((fn: (amplify: any) => Promise<any>) => Promise<AmplifyClassV6>),
Are we going to use the new types added in this PR?
(no `any` needed then)

2023-10-25 22:31 UTC, HuiSF commented on packages/adapter-nextjs/src/index.ts
> +} from './generateServerClient';
Should these factory functions be exported from a subpath `/graphql` so they are with a namespace, otherwise would be confusing to learn what they are generating without a doc.

2023-10-25 22:31 UTC, HuiSF commented on packages/adapter-nextjs/src/generateServerClient.ts
> +
I would keep exporting types from the `aws-amplify/api` path.

2023-10-25 22:31 UTC, HuiSF commented on packages/adapter-nextjs/src/generateServerClient.ts
> +			'generateServerClientUsingCookies is only compatible with the `cookies` Dynamic Function available in Server Components'
Prefer to use `AmplifyServerContextError`.

2023-10-25 22:31 UTC, HuiSF commented on packages/adapter-nextjs/src/generateServerClient.ts
> +	});
This ResourceConfig should be able to get by calling `getConfig()` on the injected `amplify` instance though. Can this be optimized to avoid calling getAmplifyConfig() in this case?

2023-10-25 22:50 UTC, iartemiev commented on packages/adapter-nextjs/src/generateServerClient.ts
> +
Agreed. This was a bad copy-paste from my other branch

2023-10-25 22:58 UTC, iartemiev commented on packages/adapter-nextjs/src/generateServerClient.ts
> +	});
For this client, yes, we could just call `getAmplify`, to get the instance and then get the config off of that. But that won't work for `generateServerClient`.

2023-10-25 23:34 UTC, iartemiev commented on packages/adapter-nextjs/src/index.ts
> +} from './generateServerClient';
You're right it should be from `/api`

2023-10-25 23:44 UTC, iartemiev commented on packages/api-graphql/src/types/index.ts
> +
They're slightly different types. We'll attempt to consolidate in a future PR

2023-10-25 23:51 UTC, HuiSF commented on packages/adapter-nextjs/package.json
> +			"types": "./lib-esm/generateServerClient.d.ts",
Following the setup in other packages, we prefer to have an `api` directory in `src` containing the exports, so here would be `./lib-esm/api/index.d.ts`.

2023-10-25 23:51 UTC, HuiSF commented on packages/api-graphql/src/GraphQLAPI.ts
> +		// amplify: AmplifyClassV6 | (() => Promise<AmplifyClassV6>),
nit: remove

2023-10-26 00:05 UTC, HuiSF submitted a review, later dismissed

2023-10-26 01:18 UTC, jimblanc submitted a review, later dismissed

2023-10-26 02:15 UTC, svidgen requested changes
Just one thing I want to make fairly certain of before merging: Ensure the the `TODO` added in docstring format I called out doesn't appear anywhere in the IDE.

2023-10-26 02:15 UTC, svidgen commented on packages/adapter-nextjs/src/api/generateServerClient.ts
> +export function generateServerClient<
Docstring with usage example would be good.

2023-10-26 02:15 UTC, svidgen commented on packages/adapter-nextjs/__tests__/generateServerClient.test.ts
> +});
😓

2023-10-26 02:15 UTC, svidgen commented on packages/api-graphql/src/types/index.ts
> + */
Does this show up in the IDE as a customer-facing docstring anywhere?

2023-10-26 02:17 UTC, svidgen commented on packages/api-graphql/src/types/index.ts
> + */
^ This comment is the *potential* blocker. If you can be 99% sure this doesn't show up anywhere, I think I'm OK to merge. But, strong preference would be to leave TODO's like this out of docstrings to avoid any possibility of leaking them into the customer experience.

That, or it might not actually be a bad idea to make an audit of docstrings *across the board* **soon** as part of a ... "docstring bash".

2023-10-26 03:30 UTC, david-mcafee reviewed
Only one non-blocking suggestion to add outside of Jon's comments.

2023-10-26 03:30 UTC, david-mcafee commented on packages/api/src/server.ts
> +// move this import and ServerClientGenerationParams into `api-graphql`
Not a blocker, but if you are updating this PR already it would be worth adding this so that we don't lose track of existing TODOs:

```suggestion
// TODO: move this import and ServerClientGenerationParams into `api-graphql`
```

2023-10-26 12:12 UTC, iartemiev commented on packages/adapter-nextjs/src/api/generateServerClient.ts
> +export function generateServerClient<
Added

2023-10-26 12:13 UTC, iartemiev commented on packages/api-graphql/src/types/index.ts
> + */
This got left behind accidentally. Removed

2023-10-26 13:11 UTC, jimblanc submitted a review, later dismissed

2023-10-26 13:50 UTC, svidgen approved these changes
Thanks!

2023-10-26 14:33 UTC, svidgen approved these changes

2023-10-26 15:02 UTC, jimblanc approved these changes

2023-10-26 15:11 UTC, merged