chore(deps): upgrade axios to 1.6.0
aws-amplify/amplify-js pull request #12489
Opened 2023-11-01 01:20 UTC by elorzafe

#### Description of changes

- upgrade axios version on `api-rest`
- upgrade typescript version to `5.0.2` and build scripts on `api-rest`, `api-graphql` and `api` packages similar to `core`

#### Issue #, if available

Axios version needs to be upgrade

#### Description of how you validated changes
- unit tests
- smoke test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-01 01:23 UTC, david-mcafee submitted a review, later dismissed
LGTM!

2023-11-01 16:51 UTC, AllanZhengYP approved these changes
The change looks good to me

2023-11-01 20:44 UTC, AllanZhengYP commented on packages/api/package.json
> +		"typescript": "5.0.2"
Can you do a quick check with the v6 [tsc-compatibility-test](https://github.com/aws-amplify/amplify-js/tree/main/scripts/tsc-compliance-test) to make sure we don't break interface consumption in older TSC?

2023-11-01 20:44 UTC, AllanZhengYP approved these changes
Looks good to me!

2023-11-02 22:12 UTC, david-mcafee requested changes

2023-11-02 22:12 UTC, david-mcafee commented on .github/workflows/push-preid-release.yml
> +      - fix/v5-upgrade-axios
Remove?

2023-11-02 23:04 UTC, jimblanc reviewed
Looks good, some nits & questions

2023-11-02 23:04 UTC, jimblanc commented on packages/api-graphql/package.json
> +		"build:esm:watch": "rimraf lib-esm && tsc -m esnext --outDir lib-esm --watch",
Nit but tabbing error

2023-11-02 23:04 UTC, jimblanc commented on packages/api-graphql/tsconfig.json
> +		"importHelpers": false,
Should this be true to reduce bundle size?

2023-11-02 23:04 UTC, jimblanc commented on packages/api-rest/package.json
> +    "axios": "1.6.0",
I wonder if we want to use `^1.6.0` to improve flattening with customer apps when new versions are released 🤔

2023-11-02 23:04 UTC, jimblanc commented on packages/api-rest/package.json
> +		"build:esm:watch": "rimraf lib-esm && tsc -m esnext --outDir lib-esm --watch",
Nit: Tabbing error

2023-11-02 23:04 UTC, jimblanc commented on packages/api-rest/tsconfig.json
> +		"importHelpers": false
Ditto

2023-11-02 23:04 UTC, jimblanc commented on packages/api/tsconfig.json
> +		"importHelpers": false,
Ditto

2023-11-03 16:16 UTC, elorzafe commented on packages/api-graphql/tsconfig.json
> +		"importHelpers": false,
good call, let me update that

2023-11-03 16:16 UTC, elorzafe commented on packages/api-rest/package.json
> +    "axios": "1.6.0",
The only concern with that is that could break something, specially since we are using a deprecated api

2023-11-03 19:12 UTC, AllanZhengYP approved these changes
Approving again. The bundle size increase reflects the Axios' own size increase from 0.26 to 1.6

2023-11-03 20:43 UTC, stocaaro submitted a review, later dismissed

2023-11-06 19:02 UTC, AllanZhengYP approved these changes

2023-11-06 20:56 UTC, elorzafe commented on .github/workflows/push-preid-release.yml
> +      - fix/v5-upgrade-axios
```suggestion
      - feat/example-preid-branch/main
```

2023-11-06 20:56 UTC, jimblanc approved these changes

2023-11-06 21:02 UTC, AllanZhengYP approved these changes

2023-11-06 21:16 UTC, merged