fix(auth): vend the helpful types for custom providers
aws-amplify/amplify-js pull request #12497
Opened 2023-11-02 20:41 UTC by Samaritan1011001

#### Description of changes

Vends the helpful types for constructing custom auth providers

#### Issue #, if available

#### Description of how you validated changes
yarn link

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-02 20:59 UTC, elorzafe submitted a review, later dismissed

2023-11-02 22:56 UTC, israx submitted a review, later dismissed

2023-11-03 22:26 UTC, elorzafe approved these changes

2023-11-03 22:33 UTC, stocaaro approved these changes

2023-11-03 23:14 UTC, jimblanc approved these changes

2023-11-03 23:17 UTC, jimblanc requested changes

2023-11-03 23:17 UTC, jimblanc commented on packages/auth/src/index.ts
> +	AWSCredentialsAndIdentityId,
Discussed offline, but should should rename these to not be AWS specific since they're intended for custom providers which may or may not use AWS

2023-11-03 23:21 UTC, elorzafe commented on packages/auth/src/index.ts
> +	AWSCredentialsAndIdentityId,
I think this is valid because we are expecting AWSCredentials, we are not mentioning what underlying service is used to generate credentials, it could STS, Cognito Identity Pools or other

2023-11-03 23:23 UTC, Samaritan1011001 commented on packages/auth/src/index.ts
> +	AWSCredentialsAndIdentityId,
Agreed. Pointed this out myself and making the change already.

2023-11-07 00:44 UTC, elorzafe approved these changes

2023-11-07 22:40 UTC, jimblanc approved these changes

2023-11-07 22:56 UTC, merged