fix: Arrays returned as objects
aws-amplify/amplify-js pull request #12676
Opened 2023-12-05 18:58 UTC by stocaaro

#### Description of changes
When customers retrieve models with `a.string().array()` fields, the content has been repackage as objects.

Testing shows that this doesn't impact direct `client.graphql(...)` calls.

This change adds a test that fails without the corresponding fix to the flatten logic, correcting it to not translate `Array`'s into `Record` type objects.

#### Issue #, if available
- https://github.com/aws-amplify/amplify-js/issues/12663

#### Description of how you validated changes
- Manually tested in an app
- Added unit test coverage, confirming repro failure

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-05 19:34 UTC, svidgen reviewed
Thinking about concern raised OOB

2023-12-05 19:34 UTC, svidgen requested changes
Meant to flip to not approved while we/I think

2023-12-05 20:25 UTC, svidgen approved these changes
OK. Re-approving. I think this is OK. But, would be great if we could get some test coverage around custom selection set to give us more confidence without the extra manual validation next time these LOC are touched.

2023-12-06 16:50 UTC, iartemiev approved these changes

2023-12-06 17:06 UTC, merged