fix: Multi-level item in selectionSet is not received
aws-amplify/amplify-js pull request #12701
Opened 2023-12-13 04:14 UTC by erickriva

2023-12-15 13:08 UTC, iartemiev requested changes
Thank you for the contribution! The PR looks good overall. I suggested a couple of changes to get the build passing.

2023-12-15 13:08 UTC, iartemiev commented on packages/api-graphql/src/internals/APIClient.ts
> +		modelName?: string
Let's make this param required. That'll resolve the build error
```suggestion
		modelName: string
```

2023-12-15 14:14 UTC, iartemiev commented
@erickriva - bundle size check failed. I just pushed up a commit increasing the limit for this package.

2023-12-15 14:31 UTC, iartemiev approved these changes

2023-12-18 22:55 UTC, svidgen reviewed
I think I'm 98% there. I'm just a little confused on one point around the recursive merge at the moment.

I've also included a suggested docstring, but this was done in passing. It's a nit, largely written so I could summarize what I was looking at.

2023-12-18 22:55 UTC, svidgen commented on packages/api-graphql/src/internals/APIClient.ts
> +				sourceValue
I might be having a slow brain day. But, the method is `source, target`, and we're flipping that here when recurse. This ends up mutating `source`, doesn't it? I'm not sure I can explain how this is correct if it is. If you can confirm this is the intended call, can you help me understand?

Assuming I'm just missing the point, it would be helpful to add a comment explaining why this is correct. I would anticipate being confused about this again 6 months from now otherwise.

2023-12-18 22:55 UTC, svidgen commented on packages/api-graphql/src/internals/APIClient.ts
> +function deepMergeSelectionSetObjects<T extends Record<string, any>>(
```suggestion
/**
 * Recursively merges selection set objects from `source` onto `target`.
 *
 * `target` will be updated. `source` will be left alone
 *
 * @param source The object to merge into target.
 * @param target The object to be mutated.
 */
function deepMergeSelectionSetObjects<T extends Record<string, any>>(
```

2023-12-19 01:02 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +				sourceValue
You're right. The params had inverted order, I forgot that line from my tests. Besides that, `Object.assign` is not really necessary, so I get rid of it.
Your comment is accurate. `source` is not mutated, and `target` receives props from `source`.

2023-12-19 01:03 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +function deepMergeSelectionSetObjects<T extends Record<string, any>>(
JSDoc added. Thank you.

2023-12-19 13:54 UTC, iartemiev commented on packages/api-graphql/src/internals/APIClient.ts
> +			target[key] = sourceValue;
@erickriva - would you be able to refactor as suggested here?

2023-12-19 14:35 UTC, iartemiev requested changes
Blocking on the prototype pollution issue discovered by CodeQL

2023-12-19 14:42 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +			target[key] = sourceValue;
I'm looking into it.

2023-12-19 19:31 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +			target[key] = sourceValue;
@iartemiev I have read a lot about it and the main recommendation is to use `Map` instead of `Object`.
There is also an recommendation for `Object.freeze` if an object is absolutely necessary.
What do you think? Can we can go to `Map`, or it needs to keep using `Object`? Is there another option you can think?

2023-12-20 13:58 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +			target[key] = sourceValue;
Found another much easier solution and `Map` was not necessary.
Took more time than I thought because CodeQL was not running in my account repos to test it and verify it was fixed before commit it here, but finally it worked.

2023-12-20 20:06 UTC, erickriva commented on packages/api-graphql/src/internals/APIClient.ts
> +				target[key] = sourceValue;
CodeQL reporting this error again here, but it does not report (with this exact same code) when I create a repository to test specifically this function 😒

2023-12-21 12:36 UTC, iartemiev commented
@erickriva the prototype pollution mitigation looks good! The only apparent remaining blocker is a minor lint error:
> ERROR: src/internals/APIClient.ts:496:11 - Identifier 'key' is never reassigned; use 'const' instead of 'let'.

You can verify locally by running `yarn lint`

2023-12-21 12:38 UTC, iartemiev commented on packages/api-graphql/src/internals/APIClient.ts
> +	for (let key in source) {
To fix lint error:
```suggestion
	for (const key in source) {
```

2023-12-21 13:09 UTC, iartemiev approved these changes

2023-12-21 15:15 UTC, svidgen approved these changes
Awesome! Thank-you!

2023-12-21 15:19 UTC, merged