refactor(datastore): Refactor conflict resolution tests optimize for concise/readable
aws-amplify/amplify-js pull request #12732
Opened 2023-12-20 15:55 UTC by stocaaro

#### Description of changes

Outcome: 
- ~1300 lines -> ~700 lines aimed at maintaining readability. All assertions are the same as they where before this refactor.
- All test assertions are maintained with the same expected result for each test

We want to add OCC tests in a subsequent change. Rather than duplicating these tests as they where, I have refactored them, extracting out shared logic that isn't core to the testing story into a test harness aimed to enable/clarify these tests specifically.

#### Description of how you validated changes
The test suite continues to run to success

#### Related changes
1. https://github.com/aws-amplify/amplify-js/pull/12728
2. :seedling:  **refactor(datastore): Refactor conflict resolution tests towards readability**
3. https://github.com/stocaaro/amplify-js/pull/85
4. https://github.com/stocaaro/amplify-js/pull/86
5. https://github.com/stocaaro/amplify-js/pull/87

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-20 16:14 UTC, svidgen approved these changes
I have a couple opinions, but non-blocking. Overall I think this is trending in the right direction, and don't want to impede the positive changes.

2023-12-20 16:14 UTC, svidgen commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		}
I'm still not super in love with this. If this is the only place `connectionSpeed` is used, I would vote for `connectionSpeed` be called `userInputLatency` or something like that.

2023-12-20 16:14 UTC, svidgen commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
Can we make this configuration more transparent without losing the semantics? I'd really like to be able to more easily see what connection speed and latency do specifically to timings, even if only on hover.

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/helpers/util.ts
> +export async function waitForExpectModelUpdateGraphqlCallCount({
This function deserves better comments and some internal annotations to describe the expected behavior. Ex. Why do we now pass `5_000` instead of `undefined` to the retry function?

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/helpers/fakes/graphqlService.ts
> +	private makeOCCConflictUnhandeled(existingObject, call) {
Add a comment

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +				// const response: SubscriptionLogTuple = [
I think this was removed in a subsequent change. Should have been removed here.

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +                    mutation operation($input: UpdatePostInput!, $condition: ModelPostConditionInput) {
This query is essentially static. Pull it to the top of the file to keep this code concise.

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +export class UpdateSequenceHarness {
Needs a robust comment with example use to ensure that its not hard to understand and work with later.

2023-12-20 16:25 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
Yep. It was on my notes to do so and I missed circling back to make that happen. Will see whats possible today.

2023-12-20 17:13 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -						externalNumberOfUpdates: 0,
Unless I'm missing something (and it's quite possible that I am!), I'm not seeing that we're making this assertion in any of these tests. Is there a reason for removing this? This becomes important in later tests, because we want to ensure that we're indeed receiving the "external" update on the fake service. When I was fine tuning these tests and there was any change in a latency or pause, the fake service would miss the update.

2023-12-20 17:16 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					await harness.expectUpdateCallCount(2);
I would rename this, since this is doing more than verifying the expected update call count - it's also ensuring that the fake service has settled, which wasn't immediately clear to me. Also, I would personally prefer to keep the comment here, or at least be able to view it on hover.

2023-12-20 17:20 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +			await pause(200);
This is confusing to me. I'd rather we explicitly perform the pause in the tests so that it's clear what we're doing and why (i.e. we're simulating an artificial "button click"). This also seems really easy to break, and not know why it's breaking, IMO.

2023-12-20 17:26 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		this.expectedNumberOfInternalUpdates++;
I'd explain why here

2023-12-20 17:27 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +			await this.outboxSettled();
I'm confused what's happening here, since the tests explicitly wait on consecutive updates without a param. IMO following this pattern makes it more difficult to track down what's happening.

2023-12-20 17:28 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					await harness.outboxSettled();
Doesn't `revise` optionally wait on the outbox? I think we should either update `revise` to not do that, or remove this here. I'd favor the former.

2023-12-20 17:30 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					await harness.expectUpdateCallCount(2);
Also, when I originally wrote these tests, @svidgen suggested that we use a variable (that is incremented) on each revision so that if we decided to change the number of revisions in the future, we wouldn't have to also update these values. I'd suggest we stick with that approach, but that's more of a nit.

2023-12-20 17:31 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.connectionSpeed = 'fast';
I'd probably add a comment here explaining that this changes the behavior of `revise`

2023-12-20 17:36 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/util.ts
> -	externalNumberOfUpdates,
We need to know the number of external updates received in order to verify that all subscription messages have been sent - otherwise we risk running into a scenario where the test appears to be "complete", but if we'd waited a bit longer, we'd get additional subscription messages that would end up reverting the original change (i.e. the behavior we're attempting to test here).

2023-12-20 17:39 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
>  					});
We intentionally set the latencies _after_ the initial update. See comment above. We want to make sure that the initial save happens successfully and doesn't get merged with the updates (on purpose).

2023-12-20 17:39 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'low';
Same here.

2023-12-20 17:40 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
See next comment

2023-12-20 17:44 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.latency = 'high';
I won't put comments on all of these, but we shouldn't set this yet (see above comment).

2023-12-20 17:53 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
We previously set the latencies _after_ the initial create. We want to make sure that the initial save happens successfully and doesn't get merged with the updates (i.e. we're not concerned with testing the original save in any way in most of these tests, except for the ones where we do not await the outbox). If there is a reason for moving this to the beginning of the test, I would 1) add a very long pause at the end of this test to make sure no other subscription messages eventually come through, and 2) would add back the check on the fake service to validate that external messages are coming through (that is, on the tests that have external updates). The hardest thing about these tests is ensuring that your assertions truly test the final state of things.

2023-12-20 17:59 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.connectionSpeed = 'slow';
To me this is less readable than before. On one of my previous revisions it was suggested that I have a flag for whether or not to pause, but that become more confusing and less readable - it becomes unclear what's happening in the test (i.e. are we pausing, are we not pausing, and why). Since it's _already_ unclear what's happening with DataStore in this tested behavior, I think it's better to be more explicit, even if that means more repeated lines of test code. Additionally, if someone is updating these and uses the wrong value (since `connectionSpeed` could be confused with setting the actual connection speed), it's possible we'd have incorrect test results.

2023-12-20 18:04 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.connectionSpeed = 'fast';
This is incorrect. Since you are setting connectionSpeed to `fast` you are now also adding an unnecessary pause between revisions, even though we are already waiting on the empty outbox.

2023-12-20 18:06 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.connectionSpeed = 'fast';
This is also incorrect - we should not be pausing between updates. Instead, we should rely on the outbox being settled.

2023-12-20 18:10 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		}
I have made the name change we discussed.

2023-12-20 18:10 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						await harness.expectUpdateCallCount(3);
My worry here is that we're combing the number of expected updates with the number of external updates, but we have no way to validate what is what. In this case, we make 3 revisions by the primary client but expect 2 updates to be sent to the service for the primary client, and a single updates to be made by the external client.

2023-12-20 18:11 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						 * primary client's first update. TODO - Can we just settle the outbox?
No, because that never enters the outbox.

2023-12-20 18:14 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.connectionSpeed = 'fast';
This is problematic because we will end up pausing on the third revision. If you look at the original test, we do _not_ pause on the third revision (on purpose), and expect the external update to go out at roughly the same time. We also do not pause after the last revision and instead wait on the outbox.

2023-12-20 18:18 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					await harness.expectUpdateCallCount(2);
If I changed the name to `expectGraphqlSettledWithUpdateCallCount`, would this be clear enough to communicate whats happening here?

I went back and forth with the call count tracking. It gets trickier later on with OCC because OCC fails on collision which triggers a retry shifting the count.

I understand how we landed on tracking updates as variables, but even in the prior tests we where adjusting in some tests. I found it harder to navigate than just having a single static value per test, which is what prompted my refactor to simplify in this direction.

Really appreciate the context. I'll setup some time to chat about this.

2023-12-20 18:18 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -						externalNumberOfUpdates: 0,
You found this in the later comment thread above. Archiving for now.

2023-12-20 18:20 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.connectionSpeed = 'fast';
Good call. This is now added as a comment that shows in the on hover tooltip for this.

2023-12-20 18:20 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +				// const response: SubscriptionLogTuple = [
I don't understand, sorry! Can you explain?

2023-12-20 18:21 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		 */
This comment doesn't belong here, since we use this util in each test, yet some tests do not increase the latency / do wait for the outbox to clear after each mutation.

2023-12-20 18:22 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					await harness.outboxSettled();
You are on point. Somehow the feature to use the flag was added in this change and adopted in the next one. I'm going to need to do a big rebase anyway, so no reason not to pull it forward since it doesn't cause these test expectations to change.

Will post an update with this change in a few.

2023-12-20 18:32 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						await harness.expectUpdateCallCount(3);
I should probably elaborate on this more to be clear :). Though today we do not make any additional validations on the fake service, we _should_ (was previously discussed on my PR, and if there's nothing in the backlog, there should be - will check after this review). Nonetheless, I think it's more readable if we are explicit in the tests about how many updates we expect, and how many external updates we expect.

2023-12-20 18:34 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'low';
This is reset by the fake service, so unnecessary.

2023-12-20 18:36 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		this.expectedNumberOfInternalUpdates++;
I have removed this because it was disused when I migrated to explicitly declaring the count here, which was prompted by the incongruity between revision calls and graphql calls.

I suppose we could input more information to calculate the number of calls, but I think we would want to make explicit. Something like:
`revisions + external calls - local merges + retried exceptions`

2023-12-20 18:39 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
I'm guessing my previous comment was removed since this was updated, but we should not be setting the latency prior to the first save, since we want to ensure that nothing is accidentally preventing the initial save from happening. We should set the latencies _after_ the initial save. If I remember correctly, if we set the latency before the first save, we potentially enter a situation where the outbox is empty, but we are not guaranteed that the fake service has completed the save.

2023-12-20 18:46 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'low';
Good call. Fixing. Also, related to some of the above threads, I agree that create doesn't need to be subject to the latency specified in the test. Similar, `userInputLatency` and `settleOutboxAfterRevisions` settings only apply to revisions. I'd like to keep them together, but am apply a revision to all tests to move these settings below the create for all the reasons you've identified. I'll post this update after I review the rest of your comments.

2023-12-20 18:52 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		if (value === 'low') {
In my thinking, I'd like to keep setting this to `low` in all tests where its not `high` for clarity for the person working on these tests next, so that its clear that each test is a explicitly `high` or `low`. This is inconsistent with how I've used `settleOutboxAfterRevisions`, which defaults to false and is turned true in tests where we want this behavior. I might consider making `latency` a bool renamed something like `elevatedLatency`, which defaults to false and isn't included in tests where latency isn't elevated.  Either, both of these could just be command functions, eg: `harness.settleOutboxAfterRevisions()` and `harness.elevatedLatency()`.

Thoughts?

2023-12-20 18:52 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						 * primary client's first update. TODO - Can we just settle the outbox?
Yeah. I discovered this in testing, but apparently forgot to remove the TODO. Doing so now.

2023-12-20 18:54 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						await harness.expectUpdateCallCount(3);
Discussed elsewhere. We should catch up on this one.

2023-12-20 18:56 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.connectionSpeed = 'fast';
Ack changing

2023-12-20 18:57 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.connectionSpeed = 'fast';
Ack. Updated

2023-12-20 18:58 UTC, david-mcafee requested changes
At a high-level, I would argue that some of these changes make the tests _less_ readable than before, but perhaps that’s just me!!! Understanding what’s happening in DataStore at any given moment is quite difficult with all of the async concurrent behavior, and though abstracting the repeated logic out of the tests means less lines of code, I would argue that I (personally) have a harder time understanding what’s happening at each step, and I worry that we'll make updates to the tests in the future that will result in different behavior being tested (and thus would no longer identify a regression). If I was paged at 3am and had to figure out what’s broken with DataStore, I’d want the tests to be as easy to reason about as possible, with no additional cognitive overload, even if that means tests are repeating themselves too much. 

At a minimum, I think we should 1) keep the manual pauses between DataStore updates (as an example, some of these tests now pause when they should not), 2) re-add some of the comments back into the tests (see specific feedback below, but adding comments to the helpers does not work because we do not always wait on the outbox, etc), and 3) go back to setting the latencies _after_ the initial save has completed.

There are a few places where we are _potentially_ no longer testing the same behavior as before. Even though the assertions are the same, that doesn’t necessarily mean that DataStore is processing the updates in the same way - for instance, the assertions across most of the tests are the same, even though the tests are testing different DataStore patterns. I also think we should continue to supply the "external" update number to the assertion testing that the fake service has settled so that, in the future, we can update the fake service to differentiate between primary client / external client updates, since that's a weak spot in these tests (and I would argue one of the most important updates we should make before committing the fix).

Lastly, since this is a pretty big refactor, I think it would be smart to test these "manually" by adding a very long pause at the end of each of these tests to make sure no other subscription messages eventually come through.

2023-12-20 18:59 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.connectionSpeed = 'slow';
I would be interested in your thoughts with the change to `userInputLatency` and the addition of comments that appear on hover.
<img width="879" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/94858815/25716681-7c4e-4d13-b7a7-ed4577bfb8cc">

2023-12-20 18:59 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
Update. More thorough comment on a different thread.

2023-12-20 19:04 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					harness.latency = 'high';
Ack. New update is in that does this.

2023-12-20 21:48 UTC, stocaaro commented on packages/datastore/__tests__/helpers/util.ts
> -	externalNumberOfUpdates,
We discussed this and I have discussed this with Jon. I'm recommending we settle on having a single number now and augmenting this as needed. It's simpler to work with, but potentially harder to reason around. As discussed elsewhere both merges and retries impact this.

We have discussed the benefit of digging in and adding tests for merges and retries (as a maybe later opportunity).

2023-12-20 21:50 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +			await this.outboxSettled();
We discussed this out of band and settled on adding a comment above the `postHarness.revise` function that articulated which settings impact revision operations in what ways.

<img width="687" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/94858815/b41eae27-a67f-4676-b858-d38fd156dcec">

2023-12-20 21:53 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +			await pause(200);
I've posed this to Jon. The pause to bring things down to human time had raised questions/concerns earlier. He has recommended changing this to `userInputLatency`, which has been done and with your input, the `revise` function comment now clarifies the impact of this setting on the revise function.

I think this is a good midpoint to settle on for this change, but happy to iterate further if you have more input.

2023-12-20 22:19 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +	userInputLatency: 'fasterThanOutbox' | 'slowerThanOutbox' =
This isn't necessarily faster or slower than the outbox (if that were the case, we could simply wait on the outbox). Thoughts on making this a boolean?

2023-12-20 22:24 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		if (settleOutbox) {
```suggestion
// We set this to `false` when we want to test updating a record that is still in the outbox.
		if (settleOutbox) {
```

2023-12-20 22:32 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						harness.userInputLatency = 'slowerThanOutbox';
We don't pause between revisions on the original test - is there a reason to do that here?

```suggestion
						harness.userInputLatency = 'fasterThanOutbox';
```

2023-12-20 22:36 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						await harness.expectGraphqlSettledWithUpdateCallCount(3);
I may be misunderstanding something, but we previously made three revisions from the original client, and one from the external client. Due to the merge, we subtract one from the original revisions, and end up with 4.

2023-12-20 22:37 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -							['original title', null, undefined],
Was this incorrect?

2023-12-20 22:38 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -							['original title', null, undefined],
Same here?

2023-12-20 22:38 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -							['original title', null, undefined],
Same here

2023-12-20 22:39 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -							['original title', 'original blogId', undefined],
I won't leave a comment on all of these, perhaps let's discuss offline?

2023-12-20 22:41 UTC, svidgen commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +	userInputLatency: 'fasterThanOutbox' | 'slowerThanOutbox' =
Changing this was my suggestion. But, if it helps speed things along, I'm OK either way. We'll have plenty of time for more refactors later if we think this PR is moving things in a better (more readable/grokkable) direction.

2023-12-20 22:52 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> -							['original title', null, undefined],
This case was including creates, unlike the above tests. I normalized to only include the create event, which dropped the initial create request.

2023-12-20 22:57 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						await harness.expectGraphqlSettledWithUpdateCallCount(3);
Nevermind, I can't count!

2023-12-20 23:14 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +	userInputLatency: 'fasterThanOutbox' | 'slowerThanOutbox' =
We've updated this to change the language and idioms slightly. The result will be the same.

2023-12-21 17:20 UTC, david-mcafee approved these changes
LGTM!! 🎉

2023-12-21 17:25 UTC, svidgen approved these changes

2023-12-21 17:30 UTC, merged