refactor(datastore): Refactor test names and make subscriptions more latent / realistic
aws-amplify/amplify-js pull request #12740
Opened 2023-12-21 18:12 UTC by stocaaro

#### Description of changes
Outcome:
- Test names changed to align with the harness features used per test
- Wait for [all subscriptions to be published](https://github.com/stocaaro/amplify-js/blob/03-consecutive-updates-take2/packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts#L221) before proceeding (remove a race condition between test assertions and subscription updates)

#### Description of how you validated changes
Tests updated in reference to how users receive settled updates twice in sample apps (once via mutation response and then later via subscription update). 

#### Related changes

1. https://github.com/aws-amplify/amplify-js/pull/12728
2. https://github.com/aws-amplify/amplify-js/pull/12732
3. :seedling:  **refactor(datastore): Refactor test names and make subscriptions more latent / realistic**
4. https://github.com/stocaaro/amplify-js/pull/86 (currently reconstructing)
5. https://github.com/stocaaro/amplify-js/pull/87

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-21 19:43 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		await Promise.all(subscriptionDeliveryPromiseList);
Can you add a comment explaining what this is doing, and why?

2023-12-21 20:09 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +const highSubscriptionLatency = 1100;
Since this change requires us to update our test assertions (i.e. more sub messages are coming through), can you add a comment here explaining _why_ we have a different value for this from the other latencies?

2023-12-21 20:10 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/fakes/graphqlService.ts
> +export let subscriptionDeliveryPromiseList: Promise<void>[] = [];
Can you add a comment above this explaining what this is?

2023-12-21 20:12 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						['post title 0', 3],
Is this coming through because of the increased subscription latency, the fact that we are now waiting on all subs to be published when awaiting the outbox, or both?

2023-12-21 20:16 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						['post title 0', 2],
In this situation, I'm assuming we are now getting not only the local sub messages, but also the sub message from the service since we've changed the behavior of `outboxSettled`? Don't need a comment in the code, but can you explain why that's better, here?

2023-12-21 20:19 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +							['update from second client', 4],
I'm trying to understand why we now get two sub messages for the external update. Going to think about this more, but maybe you know why.

2023-12-21 20:22 UTC, david-mcafee requested changes
Since these changes result in different test assertions, I think I'd like to see a few comments explaining exactly what's happening (and why) - specific comments requesting those changes are included inline.

2023-12-21 22:26 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						['post title 0', 3],
Correct. When the subscription arrives after the mutation response has been processed out of the outbox, then datastore registers the update twice, like what I have observed in the sample apps I've been checking these against.

2023-12-21 22:26 UTC, stocaaro commented on packages/datastore/__tests__/helpers/fakes/graphqlService.ts
> +export let subscriptionDeliveryPromiseList: Promise<void>[] = [];
On it.

2023-12-21 22:26 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +const highSubscriptionLatency = 1100;
Good call.

2023-12-21 22:27 UTC, stocaaro commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
> +		await Promise.all(subscriptionDeliveryPromiseList);
I'm going to split this out and change the function names a bit.

2023-12-21 22:35 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						['post title 0', 2],
- The local change doesn't increment the version, so `['post title 0', 1]` is the local update.
- When the mutation response is process and dequeued successfully from the inbox we get the first updated version message `['post title 0', 2]`
- When the update subscription received the update (and there is no corresponding change pending in the outbox) then we get the duplicate message `['post title 0', 2]`

This is the sequence of events that occurs when we settle both the outbox and the subscription messages between revisions while the latency of subscription messages is higher than the mutation responses. (otherwise, the subscription update is dropped in favor of the outbox mutation being processed).

I'm preferring a change to this behavior because the OCC tests coming in the next change run into issues when the subscriptions are processed first and this behavior is more consistent with how sample apps work (it is possible, but unlikely that the subscription update would process first).

2023-12-21 22:38 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +							['update from second client', 4],
I'm not sure, just looking at it. I'll go do some debugging and get back to you.

2023-12-21 23:46 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +							['update from second client', 4],
Alright. I don't love this, but the first `['update from second client', 4]` is actually the subscription message from the prior 'post title 1' update.

[Just before sending subscription updates](https://github.com/stocaaro/amplify-js/blob/03-consecutive-updates-take2/packages/datastore/src/datastore/datastore.ts#L2141-L2158), datastore looks up the actual value in storage for the item right now. It sends the current value along instead of the received item content.

In this case, the external update happens in the 100ms gap between when 'post title 1''s mutation returns and is process and when the subscription event for 'post title 1' arrives, and so that subscription event carries the update value.

2024-01-02 23:07 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +				test('no input delay, high latency where we wait for the create to clear the outbox', async () => {
nit (and not a blocker): a comment summarizing what we mean by "no input delay" at this first test may be useful. Took me a second to remember what this was, and why it existed.

2024-01-02 23:20 UTC, david-mcafee commented on packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts
>  	 * Do we want to settle the outbox after each `Post` revision call?
Since this now also awaits subscription responses, I'd probably update this comment:

```suggestion
	 * Determines whether we settle the outbox and await for the subscription response after each mutation.
```

2024-01-02 23:23 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +							['update from second client', 4],
Thanks for digging into this / adding the comment!

2024-01-02 23:26 UTC, david-mcafee submitted a review, later dismissed
Thanks for responding to my previous questions on this one! Left two minor (non-blocking) suggestions.

2024-01-03 15:49 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +				test('no input delay, high latency where we wait for the create to clear the outbox', async () => {
Yep. In our last revision before the break, we moved input delay to being a flag that can be turned on instead of a field that is set to true or false in each test. Since the `no input delay` tests don't have any harness call to hover over for comment, I think its valuable to get a comment in here for the first test, so I've added one.

2024-01-03 16:04 UTC, iartemiev approved these changes

2024-01-03 16:55 UTC, david-mcafee approved these changes

2024-01-03 16:55 UTC, merged