test(datastore): Add OptimisticConcurrency tests
aws-amplify/amplify-js pull request #12795
Opened 2024-01-04 17:24 UTC by stocaaro

#### Description of changes
Outcomes:
- Update graphql service fake to mimic OptimisticConcurrency(OCC) conflict resolution
- Add OptimisticConcurrency (OCC) tests for all cases covered by the existing Automerge tests
- Update service call cont expectation to reflect multiple event types, provide more rich feedback for failures

#### Description of how you validated changes
By comparing sample app results to test expectations and iterating until they align.

There is existing odd behavior where errors occur at in low latency conditions where the retry message includes null values for fields, which overwrites external updates. I will do sample app testing to confirm that this is consistent with the real world behavior.

#### Related changes

1. https://github.com/aws-amplify/amplify-js/pull/12728
2. https://github.com/aws-amplify/amplify-js/pull/12732
3. https://github.com/aws-amplify/amplify-js/pull/12740
4. :seedling:  **test(datastore): Add OptimisticConcurrency tests**
5. https://github.com/stocaaro/amplify-js/pull/87

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-05 02:11 UTC, david-mcafee requested changes
Overall this looks great! I do think removing the incorrect comment is a blocker, since it would lead to significant confusion (at least for me!) down the line.

2024-01-05 02:11 UTC, david-mcafee commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +					 */
This comment only applies to the auto-merge tests, and should be removed for the OCC tests.

```suggestion
```

2024-01-05 16:50 UTC, stocaaro commented
@david-mcafee - Appreciate the suggestions.  I've accepted both suggested changes and have re-read all of the comments to make sure nothing else thats coming across is auto-merge centric.

2024-01-06 03:13 UTC, david-mcafee submitted a review, later dismissed
LGTM! 🎉

2024-01-08 16:34 UTC, svidgen commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						false
I'm guessing this is the "we don't wait for the create to clear the outbox" part of the test. Uncertain whether this warrants some clarification in the tests, but on first read of the tests above, I found myself puzzling over where/how where converse of this happening. It *might* be worth making this field required and "naming" it.

Or, probably better, just using the same `await harness.fullSettle()` call in the converse cases if that does what it looks like it does.

If you agree with some extra explicitness here, I'd probably defer the change to a followup after we're done resolving the core issue.

2024-01-08 16:34 UTC, svidgen commented on packages/datastore/__tests__/helpers/fakes/graphqlService.ts
> +		}
This `else` branch looks like a no-op. Since the fake is branching on `canOccMerge()` first anyway, I think I'd prefer that this `throw` to alert us that "we shouldn't be here", unless I'm failing to see or grok a use-case for this branch.

I think this is the only area of the PR that concerns me at the moment. Unless I'm just having a slow brain day, can we either turn this into a `throw` or add a comment explaining the branch?

2024-01-08 17:45 UTC, stocaaro commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						false
Yeah. Prior to my work there was a line or two to settle each of the tests (except for the 2 tests where we don't settle after create).

I had considered making this a named arg, but settled on this with a description in the function comment.
<img width="963" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/94858815/85f0af19-fa27-486d-a6d1-2c005487f75d">

I would agree that in PR, this looks very abstract, where in editor, it's pretty well documented for posterity.

There are now 32 tests, of which 4 skip settle after create.  I like the factoring of explicitly disabling the settling behavior instead of injecting it.

Given this conect, thoughts/preferences?

2024-01-08 17:48 UTC, stocaaro commented on packages/datastore/__tests__/helpers/fakes/graphqlService.ts
> +		}
Rereading this, I think this branch will never be reached since I have extracted the `canOccMerge` function, we're essentially doing the version check twice. I'll get a refactor out around this.

2024-01-08 18:10 UTC, svidgen commented on packages/datastore/__tests__/conflictResolutionBehavior.test.ts
> +						false
Given the docstrings/tooltips, let's defer refactoring unless it notably impedes future PR-ing.

2024-01-08 21:14 UTC, svidgen approved these changes

2024-01-08 21:37 UTC, iartemiev approved these changes

2024-01-08 21:38 UTC, merged