fix(data): update datastore-storage-adapter subpaths
aws-amplify/amplify-js pull request #13083
Opened 2024-03-05 04:22 UTC by david-mcafee

#### Description of changes

fix(data): update datastore-storage-adapter subpaths

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-05 06:55 UTC, stocaaro submitted a review, later dismissed

2024-03-05 14:38 UTC, svidgen submitted a review, later dismissed

2024-03-05 14:46 UTC, iartemiev approved these changes

2024-03-05 14:54 UTC, jimblanc requested changes

2024-03-05 14:54 UTC, jimblanc commented on packages/aws-amplify/package.json
> +		"./datastore-storage-adapter": {
I'm a bit confused by this, `datastore-storage-adapter` isn't a dependency of `aws-amplify` so why are we vending a new export path for it? Is this related to the xml2js change? Blocking PR just to be safe as this will change the export surface of the library

2024-03-05 23:25 UTC, jimblanc reviewed
We also need to add the new shim files to your `files` list in the package.json for them to get distributed to NPM. I'd recommend testing in Verdaccio with React + RN to make sure all the import paths are usable.

Storage example: https://github.com/aws-amplify/amplify-js/blob/main/packages/storage/package.json#L61

2024-03-05 23:25 UTC, jimblanc commented on packages/datastore-storage-adapter/package.json
> +	"exports": {
I think we'll also need export paths for `SQLiteAdapter` & `ExpoSQLiteAdapter` pointing to the corresponding artifacts (same as the shim files)

2024-03-05 23:25 UTC, jimblanc commented on packages/datastore-storage-adapter/package.json
> +		".": {
Missing the RN entry point looks like?

2024-05-24 02:54 UTC, danrivett commented
This looks to have gone stale. Any update here? Be great to get #12801 fixed.

2024-10-17 17:31 UTC, closed without merging