feat(storage): list API to accept both prefix and path
aws-amplify/amplify-js pull request #13100
Opened 2024-03-09 01:57 UTC by Samaritan1011001

#### Description of changes

List API will now accept either prefix or path as input. Depending on which is given, their respective types are suggested in the IDE. 
Some notes, 
- If prefix is given, options provided the accessLevel, targetIdentityId (this is as is currently in V6) 
- if no input object is given or its empty, prefix with empty string route is taken.
- If path is given, options does not show accessLevel, targetIdentityId (gen2 feature)

#### Issue #, if available

#### Description of how you validated changes
Linked to a sample app and could complete the list operation both ways

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-12 22:14 UTC, ashika112 requested changes

2024-03-12 22:14 UTC, ashika112 commented on packages/storage/src/providers/s3/types/options.ts
> + * Input options type for S3 list API to list all items for a prefix.
```suggestion
 * Input options type with prefix for S3 list all API.
```

2024-03-12 22:14 UTC, ashika112 commented on packages/storage/src/providers/s3/types/options.ts
> + * Input options type for S3 list API to list all items for a prefix.
you can make similar change for all doc string

2024-03-12 22:14 UTC, ashika112 commented on packages/storage/src/providers/s3/types/inputs.ts
> +export type ListInput =
i think we should keep this separated as before and only union path/prefix on each level. This will also keep consistency with how we make changes in other APIs

2024-03-12 22:14 UTC, ashika112 commented on packages/storage/src/providers/s3/types/outputs.ts
> + * Output type for S3 list API.
same with output

2024-03-12 22:14 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/list.ts
> +	(
u dont want to change the interface. this will break customers

2024-03-12 22:18 UTC, ashika112 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +				path: undefined,
Also this path and other path seems confusing. Could we rename the tests to reflect `path` only for the input parameter and name other differently

2024-03-12 22:20 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> -	const { options = {}, prefix: path = '' } = input ?? {};
Same here. It is weird we had path but can we rename that to something so we can differentiate btw `path` as input vs this.

2024-03-12 22:25 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> +		const { path } = input as StorageOperationInputPath;
So here, can we just built a similar util that change the original? Since we dont want input to be strict union of the three for others outside of list? Wdyt?

2024-03-13 00:41 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> -	const { options = {}, prefix: path = '' } = input ?? {};
Yeah, it was confusing, that's why I removed the renaming to path. 
Now, we get the prefix or path from input based on the input via `validateStorageOperationInput`

2024-03-13 00:42 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/list.ts
> +	(
Got it. I reverted it to the previous state but now the `ListAllInput` is union of path and prefix types. Same for `ListPaginationInput`

2024-03-13 00:43 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/types/inputs.ts
> +export type ListInput =
Updated it, lmk if that's better.

2024-03-13 00:55 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> +		const { path } = input as StorageOperationInputPath;
That's because in the case of empty input to list API it will assert No key or path which we don't want. That's why I put the assertion in it's respective branches.

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +			},
I dont think we need to call multiple strings here like test on accessLevels. Just - path as string , path as function should be good.

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/list.ts
> +	 * List files with given prefix or path in pages
On this you are gonna need 4 overloads -> separately for `path` vs `perfix` for `listAll` and `listPaginated`

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/server/list.ts
>  	AmplifyServer,
same on overloads in this file and u need to separate out deprecation warnings as well

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/types/outputs.ts
> -export type ListAllOutput = StorageListOutput<ListOutputItem>;
shouldn't `ListOutputItem` be removed?

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/index.ts
> -	ListAllInput,
Again i guess these shouldn't be removed

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> +		const { path } = input as StorageOperationInputPath;
I think the check for trailing slash might cover this ?

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> -	assertValidationError(
this shouldn't be removed right

2024-03-14 02:39 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> +			!!path,
minor difference between this and other validation. Previous validation where checking if path even exists while these one check for value of the parameter

2024-03-14 02:53 UTC, kvramyasri7 approved these changes

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
>  				expect.assertions(4);
yeah!!.. They are helpful to count the assertions. This is the standard we had when you are on leave Ashikaaa..

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +					StorageValidationErrorCode.InvalidStorageOperationInput,
+1

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +			},
I recommend to test everything as recommended by @stocaaro  for more reffernce.

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/src/index.ts
> -	ListAllInput,
I think we can remove this....

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/types/outputs.ts
> -export type ListAllOutput = StorageListOutput<ListOutputItem>;
Noo....

2024-03-14 02:53 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> -	assertValidationError(
Yesss.....  Ashikaaa....

2024-03-14 02:54 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/apis/server/list.ts
>  	AmplifyServer,
ohhh!!! Thanks for the suggestion Ashikaaaaaa

2024-03-14 14:41 UTC, ashwinkumar6 commented on packages/storage/src/index.ts
> -	ListAllInput,
I think removing anything from 
`packages/storage/src/index.ts` or `packages/storage/src/providers/s3/index.ts` would be a breaking change. We have an export test for all API exposed but no

2024-03-14 16:56 UTC, ashwinkumar6 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +			},
agree with Ashika,
Question: 
1. Is it possible to have path as undefined (`await list()`).
2. If i have a gen2 backend and i call `await list()` would this make use of prefix or path. Would we face error if it uses prefix
3. post prefix depreciation would `await list()` be supported

2024-03-14 16:56 UTC, ashwinkumar6 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +					{ ...listResultItem, path: path ?? '' },
would need to dig in to recollect but when would path be `''` 
(for prefix and path test)

2024-03-14 16:56 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +			items: listResult as ListOutputItemKey[],
would we be able to get by without using `as` maybe with type narrowing

2024-03-14 16:56 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/types/outputs.ts
> +import { StrictUnion } from '@aws-amplify/core/internals/utils';
i think this can be cleaned up

2024-03-14 16:56 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/types/outputs.ts
> +export type ListOutputItemKey = Omit<ItemKey, 'metadata'>;
should we had `deprecated` doc string for this

2024-03-18 23:02 UTC, Samaritan1011001 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +			},
1. yes, it takes the default prefix : `public/`
2. It would use a default prefix: `public/`
3. I will say no but that's a future decision to take in the next major version as it is breaking.

2024-03-18 23:03 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> -	assertValidationError(
Created a separate function as discussed.

2024-03-18 23:03 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
> +			!!path,
No longer valid as this is separate function now that checks for only undefined.

2024-03-18 23:04 UTC, Samaritan1011001 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +					{ ...listResultItem, path: path ?? '' },
Thanks for catching. Updated this.

2024-03-18 23:05 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +			items: listResult as ListOutputItemKey[],
Separated out the functions and duplicated it to be more clear.

2024-03-18 23:05 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/types/outputs.ts
> +import { StrictUnion } from '@aws-amplify/core/internals/utils';
What do you mean?

2024-03-19 01:17 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/types/outputs.ts
> +import { StrictUnion } from '@aws-amplify/core/internals/utils';
Sorry I mean I think this isn't used to we can remove it

2024-03-20 14:34 UTC, kvramyasri7 commented on packages/storage/src/providers/s3/types/outputs.ts
> +import { StrictUnion } from '@aws-amplify/core/internals/utils';
What??? @ashwinkumar6

2024-03-22 17:09 UTC, ashika112 commented on packages/storage/src/providers/s3/types/options.ts
> +export type ListAllOptionsPrefix = StorageListAllOptions &
missed deprecation warning

2024-03-22 17:09 UTC, ashika112 commented on packages/storage/src/providers/s3/types/options.ts
> +export type ListPaginateOptionsPrefix = StorageListPaginateOptions &
missed deprecation warning

2024-03-22 17:09 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +export const validateStorageInputPrefix = (
can we name this `validateStorageListOperationInput` and also update type name accordingly?

2024-03-22 17:09 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +		// Assert if there is a leading slash in the input path
```suggestion
		// Assert on no leading slash in the path parameter
```

2024-03-22 17:09 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +		// Assert if there is a leading slash in the input path
Nice. I missed it on mine.

2024-03-22 17:13 UTC, ashika112 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
>  				expect.assertions(4);
@Samaritan1011001 can u include these as well in revision. Atleast for `path` cases

2024-03-22 22:06 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +export const validateStorageInputPrefix = (
We will do `validateStorageOperationInputWithPrefix`

2024-03-22 22:18 UTC, ashwinkumar6 commented on packages/storage/src/types/inputs.ts
> +export type StorageOperationPrefixInputType = StrictUnion<
I'm wondering if we can improve this type name 
- This type is a union of path and prefix
- There's another type with a very similar name 'StorageOperationInputPrefix'

If this type is only used by the `validateStorageInputPrefix()` util, maybe we could name it based on that

2024-03-22 22:24 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/utils/client/utils/parsePayload.ts
> +			throw new Error(`Failed to parse XML response: ${error}`);
good catch

2024-03-22 23:35 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +export const isInputWithPath = (
It's only ever used in this file so I prefer we just keep it here. But good catch, I'll make it local and not export it.

2024-03-22 23:40 UTC, Samaritan1011001 commented on packages/storage/src/types/inputs.ts
> +export type StorageOperationPrefixInputType = StrictUnion<
Ty, renamed it to `StorageOperationInputWithPrefixPath` . These are internal types so it should be good enough and seeing the type definition is self explanatory on what's happening.

2024-03-22 23:41 UTC, ashwinkumar6 submitted a review, later dismissed
couple of nits
LGTM, great job !!! 💯

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/list.ts
>  };
```suggestion
): Promise<Output> => listInternal(Amplify, input ?? {}) as Promise<Output>
```

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/list.ts
>  };
super nit

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/server/list.ts
> +	) as Promise<Output>;
super nit:
same as previous comment

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +		inputType === STORAGE_INPUT_PREFIX
super nit,
should we store `inputType === STORAGE_INPUT_PREFIX` in a separate variable like isStorageWithPrefix since it's used in multiple places

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +		Prefix: path,
nit:
should we directly define path here like
```
Prefix: isStorageWithPrefix ? `${generatedPrefix}${objectKey}` : objectKey;
```

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listAllPrefix = async ({
nit
should we also add deprication doc strings to these internal util functions, might be easier to cleanup

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listPrefix = async ({
nit:
same as above (deprication doc string)

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +				key: undefined,
QQ, is this and the case above the same

2024-03-22 23:41 UTC, ashwinkumar6 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +			try {
nit
I think in error cases to make sure the assertion in catch block is we can add `expect.assertions(<count>)`

2024-03-22 23:49 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +		inputType === STORAGE_INPUT_PREFIX
Just two places, don't see much advantage in storing it in a variable other than one less comparison.

2024-03-22 23:53 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listAllPrefix = async ({
Think the function name along with the code flow is self explanatory. I'll add in a comment above it for clarity if you would like.

2024-03-22 23:55 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listAllPrefix = async ({
Oh the deprecation message, I see, well one would remove everything prefix so again think it's self explanatory with the funciton name

2024-03-22 23:57 UTC, ashika112 commented on packages/storage/src/providers/s3/utils/validateStorageInputWithPrefix.ts
> +export const isInputWithPath = (
+1. Also this will be only need till Prefix is all deprecated.

2024-03-22 23:58 UTC, Samaritan1011001 commented on packages/storage/__tests__/providers/s3/apis/list.test.ts
> +				key: undefined,
Good catch, ty

2024-03-23 00:01 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listPrefix = async ({
+1 we can add this. Can we verify if this is done in copy key as well.? 

I think this will help make deprecation easier later.

2024-03-23 00:10 UTC, ashwinkumar6 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +const _listPrefix = async ({
Added on `copyWithKey` as well :white_check_mark:

2024-03-23 00:12 UTC, ashwinkumar6 approved these changes

2024-03-25 14:24 UTC, jimblanc reviewed
Looking pretty good, some questions & nits below

2024-03-25 14:24 UTC, jimblanc commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +		? isInputWithPrefix
Nit: This ternary is pretty complex, I think I'd prefer just if/else blocks. Additionally, this would let you extract the input objects which are identical.

2024-03-25 14:24 UTC, jimblanc commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +	generatedPrefix,
Question: What does generatedPrefix mean in the context of `path`? Is this just the path the customer passed in? Also do we even need this param? It looks like `_listPath` doesn't use it internally.

2024-03-25 14:24 UTC, jimblanc commented on packages/storage/src/providers/s3/types/options.ts
> +export type ListAllOptionsPath = Omit<StorageListAllOptions, 'accessLevel'> &
Sanity check: Where does `targetIdentityId` get pulled in? Do we need to remove that anywhere?

2024-03-25 14:24 UTC, jimblanc commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +const _isInputWithPath = (
Isn't this duplicated with the existing `isInputWithPath`?

2024-03-25 14:24 UTC, jimblanc commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +export const validateStorageOperationInputWithPrefix = (
Nit: Any way we can refactor this to use `validateStorageOperationInput`, or at least reduce code duplication? E.g. this function is missing a recent validation check that was added to `validateStorageOperationInput`. Would be ideal to not have to maintain validation rules in two places

2024-03-25 18:14 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/types/options.ts
> +export type ListAllOptionsPath = Omit<StorageListAllOptions, 'accessLevel'> &
It comes from the [ReadOptions](https://github.com/aws-amplify/amplify-js/pull/13100/files/34ad9f6a6fad8bf3c25f9091487c46512eeab932#diff-380e33ff82765e24f6b3c2872d359ee7946bf0109f3f1f96af5def4cf374170bL22) which is not included in the path types like the one above.

2024-03-25 18:15 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +const _isInputWithPath = (
I kept the same name and local. The difference is the type of the Input. Did this so this can be removed together when deprecating the `prefix` code path later.

2024-03-25 18:19 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +export const validateStorageOperationInputWithPrefix = (
Agreed. But it was decided with @ashika112 that duplication is better in this case because it will make it easier to remove prefix things. Plus adding this to `validateStorageOperationInput` made it more complex because it is valid to have empty `prefix` in list API which is not the same as `key` on other APIs

2024-03-25 18:33 UTC, jimblanc approved these changes

2024-03-25 20:24 UTC, Samaritan1011001 commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +export const validateStorageOperationInputWithPrefix = (
@jimblanc Upon more thought, I included the validation for prefix & path as well. 
https://github.com/aws-amplify/amplify-js/pull/13100/files#diff-5262fafa91521452d88353f3bd256f307a638e57d38d8e67dfda317c30be6bcaR25

2024-03-25 21:25 UTC, ashika112 commented on packages/storage/src/errors/types/validation.ts
> +	[StorageValidationErrorCode.PathAndPrefixNotAllowed]: {
I know this is still in discussion if we need separate validation or not in Jim's PR. Lets finalize this in that PR and add change in Jim's PR if needed. @jimblanc

2024-03-25 21:44 UTC, jimblanc commented on packages/storage/src/errors/types/validation.ts
> +		message: 'Missing `prefix` parameter in Input.',
Nit: Can we remove the ticks to be consistent with `InvalidStorageOperationInput` (or vice-versa)

2024-03-25 21:44 UTC, jimblanc commented on packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts
> +		!('prefix' in input && 'path' in input),
Technically this won't catch `undefined` or `null` values. Maybe we just want to do something like: `!(input as Input).key || !(input as Input).path,`

2024-03-26 19:59 UTC, ashwinkumar6 submitted a review, later dismissed

2024-03-26 21:57 UTC, ashika112 approved these changes

2024-03-26 22:04 UTC, jimblanc approved these changes
LGTM one small nit

2024-03-26 22:12 UTC, Samaritan1011001 commented on packages/storage/src/errors/types/validation.ts
> +			'Path or prefix parameter must be specified in the input. Both can not be specified at the same time.',
Updated it to `Both path and prefix can not be specified at the same time.`

2024-03-26 23:21 UTC, ashwinkumar6 approved these changes

2024-03-26 23:23 UTC, ashika112 approved these changes

2024-03-26 23:59 UTC, jimblanc approved these changes

2024-03-26 23:59 UTC, merged