feat(data): add 'sortDirection' support for list and index queries
aws-amplify/amplify-js pull request #13164
Opened 2024-03-22 23:01 UTC by david-mcafee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-25 18:47 UTC, dzhan-aws commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +				sortDirection: 'ASC',
Correct me if I'm wrong but here it seems like we are adding `sortDirection: 'ASC'` to make the tests pass, which makes me feel like this parameter is required instead of optional, does it mean customers need to always pass this `sortDirection` value?

2024-03-25 21:22 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +				sortDirection: 'ASC',
The tests pass without this parameter. However, similar to how we include `filter` I've included `sortDirection` in each test. If anyone feels strongly that this should not be included, I can instead create a sort direction-specific test.

2024-03-26 11:17 UTC, iartemiev requested changes

2024-03-26 11:17 UTC, iartemiev commented on packages/api-graphql/src/internals/APIClient.ts
> +							acc[fieldName] = `${fields[fieldName].type}!`;
The `!` after the type makes these required input fields for list operations. AppSync will reject this query if the PK/SK aren't present in variables. 

They need to be optional:
```suggestion
							acc[fieldName] = `${fields[fieldName].type}`;
```

2024-03-26 17:57 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +				sortDirection: 'ASC',
Comments are outdated as new tests have been added to this PR.

2024-03-26 23:36 UTC, iartemiev approved these changes

2024-03-27 15:43 UTC, svidgen reviewed
Just one concern that prevents me from hitting the approve bubble:

The Q below about `listTodos` -> `query`. I don't understand how/why that changed. If it was incorrect previously, why weren't the tests failing? (Or were they? But, if they were, how did they make it into `main`???)

2024-03-27 15:43 UTC, svidgen commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +						],
You're not asserting on the correct parsing of these return items in any way. No need to rev at this point. But, going forward, I would generally skip the extra LOC.

2024-03-27 15:43 UTC, svidgen commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +		test('PK and SK index query, with sort direction (ascending)', async () => {
I'm not sure I'm convinced of the value of this test and the one that follows. Are we trying to ensure the client doesn't change the ordering of the results? If so, these tests don't really convince me. E.g., the client could still be performing its own sorting on the result and pass these tests, but fail on more complex scenarios.

If we're worried about accidentally introducing sorting, I think I'd rather see a more concise test that "fuzzes" results with larger, auto-generated `items` collections. Rinse/Repeat 3x or something.

```ts
for (const i in [1,2,3]) {
  for (const d of ['ASC', 'DESC']) {
    test(`Client respects sort order returned by server (${d} run ${i})`, async () => {
      // generate 10x result, randomly sorted
      // establish mocking
      // run query with `sortDirection: d`
      // ensure client returns results back in same order as mocked
     })
  }
}
```

I don't want to block the whole PR on this. But, if we're actually worried that the client could change the order of results, let's follow up with something more convincing please. Else, I'd actually suggest scrapping these two tests.

(Or, have I misunderstood the point of these?)

2024-03-27 15:43 UTC, svidgen commented on packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts
> +								'query ($filter: ModelTodoFilterInput, $sortDirection: ModelSortDirection, $id: ID, $limit: Int, $nextToken: String)',
Here and below, I don't understand how/why this changed. I see all the fixtures are naming their tests `query`, so this certainly seems right. But, this doesn't look like a new convention, and the test body doesn't appear to have changed.

How was this testing passing prior to this change? Is this actually asserting what we expect? Please help me understand!

2024-03-27 17:14 UTC, iartemiev commented on packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts
> +								'query ($filter: ModelTodoFilterInput, $sortDirection: ModelSortDirection, $id: ID, $limit: Int, $nextToken: String)',
Both/either would be valid here since we're matching on a substring via `expect.stringContaining`. 

The full document should look something like:

```gql
query ($filter: ModelTodoFilterInput, $sortDirection: ModelSortDirection, $id: ID, $limit: Int, $nextToken: String) {
  listTodos(
    filter: $filter,
    sortDirection: $sortDirection, 
    id: $id,
    limit: $limit,
    nextToken: $nextToken) { 
        items { ... }
    }
}
```

So I'd expect the assert to succeed for both `query...` and `listTodos...`.

That being said, the diff is confusing. Since we care about both the operation-level variables and the query field variables, let's include both in the assertion, like we have in `generateClient.test.ts.snap`

2024-03-27 18:03 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +						],
You're correct, and I had actually meant to remove these.

2024-03-27 18:11 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +		test('PK and SK index query, with sort direction (ascending)', async () => {
I think that the most important part of these tests is that they assert that a result is returned when including `sortDirection`. Correct me if I'm wrong, but I don't see a world were we perform any kind of sorting client-side, so removing that piece of these tests is fine with me (was including as a safeguard because it was an easy addition, but agree that the testing against regressions isn't exhaustive). 

However, I would still be in favor of having these tests as they are the only one that tests this functionality "E2E", but I can remove the testing of the sort order.

2024-03-27 18:13 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts
> +								'query ($filter: ModelTodoFilterInput, $sortDirection: ModelSortDirection, $id: ID, $limit: Int, $nextToken: String)',
I was actually just adding both in right now, thanks for following up with this comment, Ivan!

2024-03-27 18:13 UTC, svidgen commented on packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts
> +								'query ($filter: ModelTodoFilterInput, $sortDirection: ModelSortDirection, $id: ID, $limit: Int, $nextToken: String)',
Ohhh ... right. That makes sense. I didn't catch that we were matching a completely separate line.

I think that satisfies me for this PR.

To seed a TODO for subsequent PR's, let's start moving in the direction of having *a few* snapshot tests with tests that assert on specific details about the graphql we're trying to clamp down on. E.g., let's move towards actually *parsing* the graphql and assert on the AST. We're already doing some of this in DataStore tests and now in the `data-schema` integ tests. Shouldn't be too much of a lift to start moving on that direction.

2024-03-27 18:13 UTC, svidgen approved these changes

2024-03-27 18:15 UTC, svidgen commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +		test('PK and SK index query, with sort direction (ascending)', async () => {
OK. I'm not sure these are critical, but not enough doubt to ask to remove them then. Maybe we just need to work on our test naming!

2024-03-27 18:17 UTC, svidgen commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +		test('PK and SK index query, with sort direction (ascending)', async () => {
Well, and actually in looking again, what caught my eye was the comment that does suggest the purpose of these tests is to assert on something related to sort order...

It *might* actually be worth either a rev or quick followup PR to clarify what these tests are clamping down on. (And whether that's distinct from already-clamped behavior in other tests.)

2024-03-27 18:17 UTC, david-mcafee commented on packages/api-graphql/__tests__/internals/generateClient.test.ts
> +		test('PK and SK index query, with sort direction (ascending)', async () => {
Updated.

2024-03-27 18:17 UTC, svidgen approved these changes

2024-03-27 18:30 UTC, iartemiev approved these changes

2024-03-27 18:31 UTC, merged