Update/storage types
aws-amplify/amplify-js pull request #13270
Opened 2024-04-19 21:21 UTC by ashika112

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-22 22:51 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/server/getUrl.ts
> +): Promise<GetUrlOutputWithPath>;
Wondering on `getUrl` if we should duplicate this for consistency or make it `GetUrlOutput` for both? Keeping together makes it just this API users in NMV.

2024-04-22 23:02 UTC, ashika112 commented on packages/storage/__tests__/providers/s3/apis/copy.test.ts
> +				source: { accessLevel?: StorageAccessLevel; targetIdentityId?: string };
Note on this: This is how a customer would have to pass in today if it is not done directly on API call. Please let me know if that is not the case.

2024-04-23 19:01 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link CopyOutputWithPath} instead.
Need to change this to `CopyWithPathOutput`
```suggestion
 * @deprecated Use {@link CopyWithPathOutput} instead.
```

2024-04-23 19:01 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link RemoveOutputWithPath} instead.
```suggestion
 * @deprecated Use {@link RemoveWithPathOutput} instead.
```

2024-04-23 19:02 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link GetPropertiesOutputWithPath} instead.
```suggestion
 * @deprecated Use {@link GetPropertiesWithPathOutput} instead.
```

2024-04-23 19:02 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + *  @deprecated Use {@link UploadDataOutputWithPath} instead.
```suggestion
 *  @deprecated Use {@link UploadDataWithPathOutput} instead.
```

2024-04-23 19:02 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link DownloadDataOutputWithPath} instead.
```suggestion
 * @deprecated Use {@link DownloadDataWithPathOutput} instead.
```

2024-04-23 19:03 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> +export type ListOutputItemWithPath = Omit<ItemWithPath, 'metadata'>;
Should this be `ListItemWithPathOutput`?

2024-04-23 19:03 UTC, elorzafe commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link ListOutputItemWithPath} instead.
Should this be `ListItemWithPathOutput`

2024-04-23 19:06 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts
> +			: { path: objectKey, ...result };
Should this be `finalKey`?

2024-04-23 19:09 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/server/list.ts
> + * @param input - The `ListPaginateInputWithPrefix` object.
Should this be
```suggestion
 * @param input - The `ListPaginateWithPrefixInput` object.
```
?

2024-04-23 19:11 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/server/copy.ts
> + * @param input - The CopyInput object.
Should this have also `CopyWithPathInput`?

2024-04-23 19:12 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/internal/remove.ts
> +				path: objectKey,
Should this be `finalKey`?

2024-04-23 19:13 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/internal/getProperties.ts
> +		: { path: objectKey, ...result };
Should this be `finalKey`?

2024-04-23 19:14 UTC, elorzafe commented on packages/storage/src/providers/s3/apis/downloadData.ts
> +			: { path: objectKey, ...result };
Should this be `finalKey`?

2024-04-23 19:19 UTC, jimblanc reviewed
Looking good, thanks for getting this out so quickly! Variety of nits & questions below but overall looking solid.

2024-04-23 19:19 UTC, jimblanc commented on packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts
> +			: { path: objectKey, ...result };
`objectKey` should work here, functionally it's the same (controlled by the logic above on line 96)

2024-04-23 19:19 UTC, jimblanc commented on packages/storage/src/providers/s3/apis/server/copy.ts
> + * @param input - The CopyInput object.
Not for this overload signature

2024-04-23 19:33 UTC, ashika112 commented on packages/storage/__tests__/providers/s3/apis/copy.test.ts
> +			): Promise<CopyWithPathOutput> => copy(input);
So i purposefully did this so we can have both direct usage and wrapper usage. Meaning This is used in all path happy cases but error cases one will have the direct usage. I mean we want to test both ways

2024-04-23 20:05 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/remove.ts
> +				path: objectKey,
objectKey === finalKey in term of functionality for path

2024-04-23 20:05 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/getProperties.ts
> +		: { path: objectKey, ...result };
objectKey === finalKey in term of functionality for path

2024-04-23 20:05 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/downloadData.ts
> +			: { path: objectKey, ...result };
objectKey === finalKey in term of functionality for path

2024-04-23 20:06 UTC, erinleigh90 requested changes
Found one issue, aside from that and the deprecation message changes pointed out by others, I'm good to approve.

2024-04-23 20:14 UTC, ashika112 commented on packages/storage/src/providers/s3/types/outputs.ts
> +export type ListOutputItemWithPath = Omit<ItemWithPath, 'metadata'>;
This is internal type and those still have `WithKey` `WithPath` references which we probably may clean up

2024-04-23 20:15 UTC, ashika112 commented on packages/storage/src/providers/s3/types/outputs.ts
> + * @deprecated Use {@link ListOutputItemWithPath} instead.
internal types still will have some refernces to `WithPath` or `WithKey`

2024-04-23 20:16 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +	ListOutputItemWithKey,
I think this is miss. Thanks

2024-04-23 20:17 UTC, ashika112 commented on packages/storage/src/providers/s3/apis/internal/list.ts
> +	| ListAllWithPathOutput
Oh man nice catch yes 🙏

2024-04-23 20:51 UTC, ashika112 commented on packages/storage/src/types/inputs.ts
> +	destination: StorageOperationInputWithPath;
there are still some internal type refernces `WithKey` and `WithPath` we do this for clear separation of concern but we should think about cleaning some of these up.

2024-04-23 21:07 UTC, elorzafe approved these changes

2024-04-23 21:21 UTC, jimblanc approved these changes

2024-04-23 21:49 UTC, erinleigh90 approved these changes

2024-04-23 21:52 UTC, merged

2024-04-23 21:55 UTC, ashwinkumar6 approved these changes

2024-04-23 21:56 UTC, ashwinkumar6 commented
lgtm, great work 🚀🚀🚀