[Feat] Storage Path changes Gen 2
aws-amplify/amplify-js pull request #13294
Opened 2024-04-25 23:27 UTC by ashika112

#### Description of changes
- PR to merge `gen2-storage` against `main`
- This PR introduces `path` parameter usage to all Storage APIs.
- This PR also introduces deprecation warning for `key` and `accessLevel` usage to all Storage APIs

#### Description of how you validated changes
- manual testing against multiple framework
- integ test
- unit test

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-25 23:58 UTC, ashika112 commented
Reminder to Merge commit

2024-04-26 14:16 UTC, jimblanc requested changes
We'll need to revert this commit first: https://github.com/aws-amplify/amplify-js/pull/13294/commits/77b2b20d021de3804feb8041414e9c7b68ef0bbf

2024-04-26 16:18 UTC, jimblanc approved these changes

2024-04-26 16:19 UTC, svidgen approved these changes

2024-04-26 17:21 UTC, merged