release(required): Parsing custom oAuth in amplify_outputs
aws-amplify/amplify-js pull request #13469
Opened 2024-06-05 22:36 UTC by ashika112

#### Description of changes
The `parseAmplifyOutputs` function does not take into account any custom oAuth Provider and this lead to providers in oAuth config having undefined values breaking the UI Authenticator component.

In additon to the fix for Amplify outputs, the PR loosens up the OAuth config type.  Since looking into the issue, realized our parse utility provided for adding custom oAuth as string to list of providers outside of our `CustomProvider` in `OAuthConfig`. 

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/13466

#### Description of how you validated changes
- unit tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-05 22:52 UTC, jimblanc approved these changes
Change looks good to me pending additional testing.

2024-06-05 22:59 UTC, reesscot commented on packages/core/src/singleton/Auth/types.ts
> +	providers?: (OAuthProvider | CustomProvider)[] | string[];
I thought the custom providers had to be in a CustomProvider object?

2024-06-05 23:03 UTC, calebpollman requested changes
Left a blocking comment

2024-06-05 23:03 UTC, calebpollman commented on packages/core/src/parseAmplifyOutputs.ts
> +	return providers.map(provider => providerNames[provider] ?? provider);
Concerned that this is going to break the `Authenticator`. Need to see a passing test run through our CI before  approval

2024-06-05 23:30 UTC, ashika112 commented on packages/core/src/parseAmplifyOutputs.ts
> +	return providers.map(provider => providerNames[provider] ?? provider);
how can we do that? @calebpollman

Also , the output of this and gen1 parser is the same. It wasn't before. I updated our mock comparison to check the same [here] (https://github.com/aws-amplify/amplify-js/pull/13469/files#diff-b729da5fc469a5a8411d893651231dee6138148eb593396542ae3a11346ef96eR25)

and [here](https://github.com/aws-amplify/amplify-js/pull/13469/files#diff-b729da5fc469a5a8411d893651231dee6138148eb593396542ae3a11346ef96eR25)

2024-06-05 23:31 UTC, ashika112 commented on packages/core/src/parseAmplifyOutputs.ts
> +	return providers.map(provider => providerNames[provider] ?? provider);
and that gets compared in this test https://github.com/aws-amplify/amplify-js/blob/main/packages/core/__tests__/utils/parseAmplifyConfigCompatibility.test.ts#L10

2024-06-05 23:33 UTC, ashika112 commented on packages/core/src/singleton/Auth/types.ts
> +	providers?: (OAuthProvider | CustomProvider)[] | string[];
long story short, what we were doing in gen1 has an issue. This loosens the type to account for issue coming from [this typecasting ](https://github.com/aws-amplify/amplify-js/pull/13469/files#diff-fa4b039ec83dc5858b6f57efdb0d580f57133da49c31ab9b5836aa218358118eL328)

2024-06-06 15:37 UTC, reesscot commented on packages/core/src/singleton/Auth/types.ts
> +	providers?: (OAuthProvider | CustomProvider)[] | string[];
Since we don't actually ever return a CustomProvider, shouldn't it be removed from the type?

2024-06-06 18:36 UTC, israx approved these changes

2024-06-06 18:57 UTC, ashika112 commented on packages/core/src/singleton/Auth/types.ts
> +	providers?: (OAuthProvider | CustomProvider)[] | string[];
This is type is publicly available through `Amplify.configure()` and `Amplify.getConfig()` any change to that would be breaking change

2024-06-06 21:17 UTC, ashika112 commented
Closing in favor of https://github.com/aws-amplify/amplify-js/pull/13473

2024-06-06 21:17 UTC, closed without merging