fix(auth): Added missing UserContextData to Cognito User Pool operation SignUp
aws-amplify/amplify-js pull request #13477
Opened 2024-06-07 14:45 UTC by armandsyah134

#### Description of changes

- Adding missing property `UserContextData` in `SignUp` call to Cognito User Pools (CUP)
- `UserContextData` is an important property for Sign Up calls, and should be added to the `SignUp` operation
    - Other CUP apis are passing in `UserContextData` (e.g. [ConfirmSignUp](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/apis/confirmSignUp.ts#L72))
- `UserContextData` is already in your API [contract](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/types.ts#L1477) 

#### Issue #, if available

N/a (will make an issue for this if required

#### Description of how you validated changes

- Added unit test for validating `UserContextData` present in SignUp call
- Performed local testing by linking changed library to sample NextJS app and testing sign up flow
    - Validated that UserContextData was present in our logs

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [n/a] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-07 14:48 UTC, israx submitted a review, later dismissed
LGTM

2024-06-07 14:53 UTC, jimblanc commented on yarn.lock
We can omit the yarn.lock change from this PR

2024-06-07 15:01 UTC, armandsyah134 commented on yarn.lock
omitted yarn lock file from pr

2024-06-07 15:02 UTC, israx approved these changes

2024-06-07 15:13 UTC, jimblanc requested changes
Change looks good to me, but please hold off on merging until we can discuss (blocking PR). Thank you for the contribution!

2024-06-07 15:18 UTC, cshfang commented on packages/auth/src/providers/cognito/apis/signUp.ts
> +	});
Nit: Can we move this directly into line 96? I think `getUserContextData` is expressive enough to convey the context there when used directly. Also prefer not to have the PascalCased variable as it easily gets confused with types/interfaces/classes

2024-06-17 13:29 UTC, jimblanc approved these changes

2024-06-17 14:36 UTC, haverchuck approved these changes

2024-06-18 15:34 UTC, jimblanc approved these changes

2024-06-18 16:01 UTC, israx approved these changes

2024-06-20 19:31 UTC, jimblanc approved these changes

2024-06-20 19:41 UTC, merged