feat(auth): Enable resumable SignIn
aws-amplify/amplify-js pull request #13483
Opened 2024-06-07 21:28 UTC by joon-won

#### Description of changes

- Enable v6 users to have an option to continue SignIn process after a full browser reload by storing, then utilizing session in session storage

#### Issue #, if available

- #10469 
- #12810 

#### Description of how you validated changes

- Unit tests (IP)
- Smoke Test on sample application

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-10 14:41 UTC, israx reviewed
Thanks @joon-won . We are getting close. A couple of things, 

1. we should consider creating an internal sync `sessionStorage` util so we don't have change sync behavior of the `signInStore`

2. we must avoid losing or modifying state at all cost. Left comments bellow and pointed out the tests needed

2024-06-10 14:41 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.username) ?? ('' as string);
are we sure we want to default to an empty string ? What would happen with the underling API calls that use this value ?

2024-06-10 14:41 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	) ?? '') as ChallengeName;
ditto about the defaulting to an empty string

2024-06-10 14:41 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.signInSession) ?? ('' as string);
ditto about the defaulting to an empty string

2024-06-10 14:41 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	clearPersistedSignInState();
we should not do this. We might be creating undesired side effects and losing state as result. Let's consider the following scenarios:

1. `confirmSignIn` ->  confirmSignIn fails -> `confirmSign`  
2. `confirmSignIn` ->  confirmSignIn fails -> user reloads page -> `confirmSign`  

Please let's test both cases and make sure state is not lost

2024-06-10 14:44 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +			return getInitialState();
probably rename it to `setInitialState`

2024-06-10 14:47 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const EXPIRATION_MINUTES = 5;
are we sure 5 minutes is the right default time ? The authentication session expiry time can be set from 3 to 15 minutes. We might to consider increasing it a bit more

2024-06-10 17:19 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const EXPIRATION_MINUTES = 5;
Great point, can there any potential issue if I match it with the maximum possible expiry time, 15 mins?

2024-06-10 18:12 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	const expiry = sessionStorage.getItem(SIGN_IN_STATE_KEYS.expiry) as string;
I see, thanks for pointing this out. 
Seems like sync sessionStorage util will be required to resolve the issue, as removing the cast from current code will cause an error

2024-06-10 18:12 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	keys[key] = `CognitoSignInState.${key}`;
Working on it!

2024-06-10 18:23 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.username) ?? ('' as string);
This is not ideal, yet not defaulting it to an empty string will cause error due to `SignInState` implementation `username?: string` part. This is one of the original implementation so decided not to change it

2024-06-10 18:28 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	) ?? '') as ChallengeName;
Yeah, this one also comes out from the same issue. Original implementation of `SignInState` will require default value for it to best of my understanding (IDE is complaining about it). Modifying the current implementation of it was an option I've considered, yet I went very conservative about it because I wasn't sure if it's in the design scope

2024-06-10 18:29 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.signInSession) ?? ('' as string);
Same issue as above 2, removed casting.

2024-06-10 18:36 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	clearPersistedSignInState();
Oh, thanks for pointing it out. I've totally missed out on the possibility. Removed the line clearing the sessionStorage

2024-06-10 18:48 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.username) ?? ('' as string);
can it be default to an `undefined` value instead ?

2024-06-10 20:30 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		sessionStorage.getItem(SIGN_IN_STATE_KEYS.username) ?? ('' as string);
Yup it can be. I've defaulted them to `undefined`

2024-06-11 20:39 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const EXPIRATION_MINUTES = 5;
For future reference, we've decided to default it to 3 minute

2024-06-11 20:41 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	keys[key] = `CognitoSignInState.${key}`;
For future reference, `SIGN_IN_STATE_KEYS` is now an object

2024-06-14 02:09 UTC, cshfang requested changes

2024-06-14 02:09 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	const expiry = syncSessionStorage.getItem(signInStateKeys.expiry) as string;
I think this is incorrectly cast. The result of this *might* be `null` so casting it to string is actually unsafe. What should happen instead is to update your `isExpired` function to expect `null` as a possible input and handling it appropriately

2024-06-14 02:09 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	signInStore.dispatch({ type: 'SET_INITIAL_STATE' });
We already went over this but this used to dispatch an action to clear the state. This was *the same thing* as setting to initial state before because the initial state was ALWAYS the default (empty) state. However, this is no longer true - so we actually want to dispatch (and add) an action like.. `SET_EMPTY_STATE` or `RESET_STATE` to actually "clear out" the state. This was a miss by me in my original POC!

2024-06-14 21:24 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const clearPersistedSignInState = (keys: Record<string, string>) => {
Gotcha, the idea was to give better visibility to users over what's passed. Nonetheless, I agree we won't have any other usability for the method.

2024-06-14 21:25 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	for (const key in keys) {
Per our conversation above removed parameter passing and made it just refer to `SIGN_IN_KEYS`

2024-06-14 21:26 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	clearSignInStateKeysFromSessionStorage();
Removed method `clearSignInStateKeysFromSessionStorage()` and make it call `clearPersistedSignInState()` directly as we have discarded idea of exporting `clearSignInStateKeysFromSessionStorage()`

2024-06-14 21:27 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +}
Per our previous conversation, `clearPersistedSignInState()` no longer takes params.

2024-06-14 21:36 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const setInitialState = (): SignInState => {
Makes sense, modified it to `initializeState()`, this will give better image

2024-06-14 21:40 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	const expiry = syncSessionStorage.getItem(signInStateKeys.expiry) as string;
That's a great point, I'll add one more safety layer onto it, trying to prevent potential risks coming out of `syncSessionStorage.getItem(signInStateKeys.expiry)` being null

2024-06-15 05:04 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	signInStore.dispatch({ type: 'SET_INITIAL_STATE' });
Thanks for helping me out on debugging! I probably needed longer time to find it out myself. Learned a lesson here about dispatcher and reducer 👍

2024-06-20 22:14 UTC, joon-won commented on packages/auth/src/providers/cognito/utils/signInStore.ts
>  		default:
NIT: this default state is never reachable due to `signInReducer` requiring a type of `SignInState`. This is the only line case in this file that's not being covered

2024-06-21 14:07 UTC, israx requested changes
Thanks @joon-won for putting these together. 

Sorry for not catching this earlier but I realize that the `SET_INITIAL_STATE` action is already being dispatched and modifying the state based on the `expiry` time might lead to mutating the state. I think is worth considering adding a new action and dispatching it if the session was already persisted.

2024-06-21 14:07 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	let currentState = reducer(getDefaultState(), { type: 'SET_INITIAL_STATE' });
Thinking twice, we can probably dispatch a different action if the session was already persisted. That way we can addressed the concerns above

```suggestion
const action = isStatePersisted() ? {type:'SET_PERSISTED_STATE'} : { type: 'SET_INITIAL_STATE' };
let currentState = reducer(getDefaultState(), action );
```

2024-06-21 14:07 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const clearPersistedSignInState = () => {
I think we still need to address this comment. I was suggesting to pass the `syncSessionStorage` as an argument. 

```suggestion
const clearPersistedSignInState = (storage:SyncStorageInterface) => {
```

2024-06-21 19:50 UTC, joon-won commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +	test('State is updated after ', async () => {
Sorry, seems it was cut off. Good finding!

2024-06-21 21:05 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +	test('syncSessionStorage instance should show the same behavior', () => {
Is this test merely for `syncSessionStorage instanof SyncSessionStorage === true`?

2024-06-21 21:05 UTC, HuiSF commented on packages/core/__tests__/storage/storage-mechanisms-node-runtime.test.ts
> +	test('test syncSessionStorage operations in node environment', () => {
Does this test even run? It gets the fallback InMemoryStorage in Node env.

2024-06-21 21:14 UTC, cshfang commented on packages/core/__tests__/storage/storage-mechanisms-node-runtime.test.ts
> +import {
I think we can just delete this whole test file. Even in Node environment, these would just fallback to in-memory versions. The fact that these are passing just means the `catch` blocks aren't running. So, effectively, this entire test suite is useless.

2024-06-21 21:16 UTC, cshfang commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +	test('should clear out storage', () => {
Nit to comment: it('clears...

2024-06-21 21:19 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
>  		default:
You can add this info as a code comment :)

2024-06-21 21:19 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +export function cleanActiveSignInState(): void {
nit: use consistent function expiression pattern throughout

2024-06-21 21:19 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		username = '',
Are these inital state correct? would this cause storing empty strings always into session storage with the `signInStateKeys`?

2024-06-21 21:21 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +	test('should clear out storage', () => {
Updated 😊

2024-06-21 21:29 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const clearPersistedSignInState = () => {
This is probably my fault because my argument is "Do we really need to pass this in? This function isn't exported from the module and the module scope contains the reference to the `syncSessionStorage` instance already right?"

2024-06-21 21:29 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		username = '',
The defaults were because `setItem` is typed as non-nullable. We can use a guard clause in the body instead to early return - but is even a real situation where this would be called with a partial state?

2024-06-21 21:29 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	storage = syncSessionStorage,
Imo - this is redundant for the same reason I gave above around the `syncSessionStorage` reference already being accessible via the module scope. I do understand the rationale of making things more pure but here, we should be able to treat it as a member method of this module.

2024-06-21 21:29 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	let currentState = reducer(getDefaultState(), { type: 'SET_INITIAL_STATE' });
It's not a super necessary refactor imo, but I am onboard with the change. Essentially, taking the logic out of the mutation function and making a determination of which type of action to dispatch makes sense.

We can repurpose `RESET_STATE` as `SET_DEFAULT_STATE` so it makes more sense for either use case (clear and setting an initial empty state)

2024-07-10 13:42 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	}
let's delete this code please

2024-07-10 13:59 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	username = '',
As previously discussed, let's avoid setting default values

2024-07-10 14:11 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +			persistSignInState(state);
the `state` being passed in is not the latest `state` from the store. The `persistSignInState` should take the `action` as an argument instead.

```suggestion
persistSignInState(action.value);
```

2024-07-10 14:13 UTC, israx commented on packages/core/__tests__/storage/storage-mechanisms-node-runtime.test.ts
> -/**
why are we deleting this file? — We should keep the same coverage

2024-07-11 13:07 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		if (isExpired(expiry)) {
you can collapse the 2 if statements into one

```suggestion
if (expiry&&isExpired(expiry)) {
```

2024-07-11 13:09 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	}
```suggestion
username && syncSessionStorage.setItem(signInStateKeys.username, username);
```

2024-07-11 13:10 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		syncSessionStorage.setItem(signInStateKeys.signInSession, signInSession);
same suggestion of using the && operator

2024-07-11 13:10 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	if (challengeName) {
same suggestion of using the && operator

2024-07-11 13:11 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
>  		String(Date.now() + MS_TO_EXPIRY),
you want to update the session expiry only when a new session is passed

2024-08-21 21:02 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
>  				signInSession: action.value,
I think we need to persist the session here too.

2024-08-21 21:15 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +		setActiveSignInState(user1);
can you spy `persistSignInState` method and make sure is called with the right parameters?

2024-08-21 21:17 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +		);
Based on the test description, these values shouldn't be set manually but instead set when `signInStore.dispatch` is called

2024-08-21 21:18 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +		});
can you spy `persistSignInState` method and make sure is called with the right parameters when `signInStore.dispatch` is called here?

2024-08-21 21:23 UTC, cshfang commented on packages/auth/src/providers/cognito/utils/signInStore.ts
>  			return {
Why don't we need to persist when session is set?

2024-08-21 21:23 UTC, cshfang commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +	it('will throw if trying to delete a non existing key', () => {
Nit: Are we expecting this *not* to throw - like the expect below?

2024-08-22 13:32 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +	test('Stored session is expired thus State should default to undefined', async () => {
nit
```suggestion
	test('should return undefined sign-in state values when stored session is expired', async () => {
```

2024-08-22 13:42 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +	test('Stored session is not expired thus State should be rehydrated', () => {
Nit. The wording could be improved for better clarity.

```suggestion
The stored sign-in state should be rehydrated if the sign-in session is still valid.
```

2024-08-22 13:49 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +		});
ditto about extracting this logic into a `helper` or putting it in a `beforeEach`

2024-08-22 13:50 UTC, israx commented on packages/auth/__tests__/providers/cognito/signInResumable.test.ts
> +		});
ditto about extracting this logic into a `helper` or putting it in a `beforeEach`, and removing `signInStore.dispatch`

2024-08-22 23:55 UTC, cshfang approved these changes

2024-08-23 15:41 UTC, israx approved these changes

2024-08-23 17:49 UTC, jimblanc submitted a review, later dismissed

2024-08-23 17:49 UTC, jimblanc commented on packages/aws-amplify/jest.config.js
> +			functions: 63.3,
Where'd the drop come from? Anyway to bring this back up?

2024-08-26 19:49 UTC, HuiSF commented on packages/core/src/storage/SyncKeyValueStorage.ts
> +		if (!this.storage) throw new PlatformNotSupportedError();
Can implement a getter function to handle the exception throwing at one single place (saving a few bits probably :D ).

2024-08-26 19:49 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +	isBrowser: jest.fn(() => false),
Why is this mock needed? The `SyncSessionStorage` impl. doesn't seem rely on this function.

2024-08-26 19:49 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +		sessionStorage.clear();
nit: A new instance of `SyncSessionStorage` is being created before each test, this client probably is not needed?

2024-08-26 19:49 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +		expect(sessionStorage.getItem(signInStateKeys.username)).toEqual(
nit: could use `strictEqual` for this type of tests

2024-08-26 19:49 UTC, HuiSF commented on packages/core/__tests__/storage/SyncSessionStorage.test.ts
> +		sessionStorage.clear();
In this test, there were no key-values written into the newly created instance of the `SyncSessionStorage` before calling the `clear()`, this test may not be accurate.

2024-08-26 19:49 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	expiry: 'CognitoSignInState.expiry',
nit: can assign `CognitoSignInState` to a constant and construct the strings here (can save a few bytes I presume)

2024-08-26 19:49 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	clearPersistedSignInState();
I think `clearPersistedSignInState()` should be invoked at line 82, under the `case 'RESET_STATE'` event in the reducer.

2024-08-26 19:49 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +		logger.warn('Session Expired');
sanity check: do we really need this log? (it increases bundle size)

2024-08-26 19:49 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const MS_TO_EXPIRY = 1000 * 60 * EXPIRATION_MINUTES;
```suggestion
const MS_TO_EXPIRY = 3 * 60 * 1000; // 3 mins
```

2024-08-28 18:30 UTC, HuiSF commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +	clearPersistedSignInState();
Since you've moved this call to the reducer, we can probably remove it here.

2024-08-28 21:23 UTC, israx commented on packages/auth/src/providers/cognito/utils/signInStore.ts
> +const tgtState = 'CognitoSignInState';
Constants should follow an UPPER_CASE_SNAKE syntax

2024-09-20 18:55 UTC, cshfang commented on packages/auth/src/providers/cognito/apis/signInWithCustomSRPAuth.ts
> +			signInStore.dispatch({ type: 'RESET_STATE' });
Why did this move up in the block?

2024-09-20 18:55 UTC, cshfang commented on packages/auth/src/providers/cognito/apis/signInWithUserPassword.ts
> +			signInStore.dispatch({ type: 'RESET_STATE' });
Ditto here

2024-09-20 19:27 UTC, cshfang approved these changes

2024-09-23 20:52 UTC, HuiSF approved these changes

2024-09-23 22:02 UTC, merged

2024-11-28 11:13 UTC, aca-stev commented
Hi, I noticed this PR was previously merged but later reverted. Could you share why it was reverted and if there are plans to  re-integrate? Thanks!

2024-12-20 02:58 UTC, joon-won commented
Hey @aca-stev, this PR was previously reverted due to our internal plan change. This is now re-released with [Amplify JS 6.11.0](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%406.11.0), please feel free to reach out if you have any further questions or concerns!