fix(aws-amplify): createKeyValueStorageFromCookieStorageAdapter misses default path and secure values
aws-amplify/amplify-js pull request #13508
Opened 2024-06-18 17:18 UTC by HuiSF

#### Description of changes

Added default `path: '/'` and `secure: true` to the cookies setting options from the server side.

#### Issue #, if available

#### Description of how you validated changes

1. E2E tests
2. Manual testing with a Next.js sample app

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-18 17:23 UTC, cshfang submitted a review, later dismissed

2024-06-18 17:23 UTC, ashika112 submitted a review, later dismissed

2024-06-18 17:24 UTC, jimblanc requested changes
Change looks good to me, but as this is auth related please hold off until we have sign-off.

2024-06-18 17:43 UTC, cshfang approved these changes

2024-06-18 18:07 UTC, israx submitted a review, later dismissed

2024-06-18 19:49 UTC, ashika112 approved these changes

2024-07-11 17:55 UTC, ashika112 approved these changes

2024-07-11 18:01 UTC, ashika112 commented on packages/aws-amplify/src/adapter-core/storageFactories/createKeyValueStorageFromCookieStorageAdapter.ts
> +			cookieStorageAdapter.delete(key);
in case this fails, then self recovery will be the fallback right?

2024-07-11 18:25 UTC, HuiSF commented on packages/aws-amplify/src/adapter-core/storageFactories/createKeyValueStorageFromCookieStorageAdapter.ts
> +			cookieStorageAdapter.delete(key);
You meant the `.delete` operation itself would fail? If so, this operation just sets client cookie with a expiry time in the past so browser will remove it. I can't think a reason it may fail. (unless the HTTP response never gets delivered to the client)

2024-07-11 19:53 UTC, cshfang approved these changes

2024-07-12 18:21 UTC, AllanZhengYP approved these changes

2024-07-12 18:21 UTC, AllanZhengYP approved these changes

2024-07-18 20:30 UTC, haverchuck commented
Have we tested this for both a) apps that were spun up before the fix, with tokens already persisted, and b) new apps?

2024-07-18 22:21 UTC, HuiSF commented
> Have we tested this for both a) apps that were spun up before the fix, with tokens already persisted, and b) new apps?

@haverchuck here's the manual testing setup:

### Set 1

1. A next.js sample app with the page router installed the `latest` version of `aws-amplify` and `@aws-amplify/adapter-nextjs`
2. access route `/fetch-auth-session/test` with expired access token, server-side refreshed tokens are set back in the browser cookie store with `/fetch-auth-session` path (wrong cookie persisted)
3. Swap the `aws-amplify` and `@aws-amplify/adapter-nextjs` with a version that contains this PR fix
4. Wait till the tokens set in step 2 expired, and refresh the page, the originally cookie item set with path `/fetch-auth-session` got removed, and the newly refreshed tokens are set in the cookie store with `/` path.

### Set 3

1. A next.js sample with the page router installed a version of `aws-amplify` and `@aws-amplify/adapter-nextjs` that contains this PR fix
2. access route `/fetch-auth-session/test`
3. Wait till the access token expires, then refresh the page, the newly refreshed tokens are set in the cookie store with `/` path.

2024-07-19 21:35 UTC, haverchuck approved these changes

2024-07-19 23:36 UTC, merged