Setting Store Tokens should only clear tokens that no longer have a value
aws-amplify/amplify-js pull request #13584
Opened 2024-07-12 15:23 UTC by jon-armen

#### Description of changes
Setting Store Tokens should only clear tokens that no longer have a value.  This resolves thrashing events when a consumer is listening to storage events, preventing them from seeing a 'clear' followed immediately by a 'set' value.

#### Issue #, if available
#13583 

#### Checklist
- [X] PR description included
- [X] `yarn test` passes
- [X] Unit Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [X] Relevant documentation is changed or added (and PR referenced)

#### Checklist for repo maintainers
- [ ] Verify E2E tests for existing workflows are working as expected or add E2E tests for newly added workflows
- [ ] New source file paths included in this PR have been added to CODEOWNERS, if appropriate

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-07-15 18:48 UTC, cwomack commented
Hello, @jon-armen and thanks for taking the time to submit this PR! We'll get this reviewed by the team internally and follow up with any questions or feedback that we have.

2024-12-06 11:55 UTC, itsramiel commented
@cwomack Can you please bring life to this pr? I believe such changes can also fix #14033

2024-12-16 21:19 UTC, joon-won commented
Thanks for working on this issue @jon-armen,  could you also add some tests for the behavior?

2024-12-16 21:45 UTC, jon-armen commented
@joon-won  I'll see if I can get some tests together in the next few days.  @itsramiel , do you have thoughts on tests you might like to see to validate your use case?

2024-12-17 07:54 UTC, itsramiel commented
> @joon-won I'll see if I can get some tests together in the next few days. @itsramiel , do you have thoughts on tests you might like to see to validate your use case?

One way that comes to mind is to call `storeTokens`, followed by `loadTokens` without awaiting them, but making sure both settled, given that a `loadTokens` was called before to make sure there were tokens in the first place:
```ts
    // Start storeTokens and loadTokens simultaneously
    const storePromise = tokenStore.storeTokens(tokens);
    const loadPromise = tokenStore.loadTokens();

    const [storeResult, loadResult] = await Promise.allSettled([
      storePromise,
      loadPromise,
    ]);
  ```
  
  However I am not sure this will work always, half of the times, or never in tests since it really depends on how the js env handles async calls and running other functions while sync calls are awaited. But that would be my approach

2024-12-17 07:57 UTC, itsramiel commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
Typewise, `tokens.username`, `tokens.accessToken` and `tokens.clockDrift` are non optional types so technically no need for the `if...else` on line 100, 110, and 165 since also in the before changes they were just being set.

Maybe we can remove the if...else from those ones?

2024-12-18 21:35 UTC, blakedunson requested changes

2024-12-18 21:35 UTC, blakedunson commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
do we need a statement to removeItem(authKeys.oauthMetdata)?

2024-12-18 21:35 UTC, blakedunson commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> -		await this.clearTokens();
we should assert that in the absence of this all keys in https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/tokenProvider/types.ts#L27 are cleared if unspecified.

2024-12-20 03:24 UTC, jon-armen commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
Yes, good catch.  I don't think that was in tokens when I put this together a few months ago.

2024-12-20 03:33 UTC, jon-armen commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
I've removed the extra if/else statements.

2024-12-20 22:32 UTC, Samaritan1011001 commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
Don't think we should set/remove `oauthMetdata` here. It's separately managed on [line 243](https://github.com/aws-amplify/amplify-js/pull/13584/files#diff-3d8dadc4be4df6d2988d636749da62786244d353c6998015920a8e93e1552542R243).

2024-12-23 23:22 UTC, joon-won commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
Regarding `oauthMetadata`, I agree with @Samaritan1011001. Do we know if we need to set / remove it in `storeTokens` ?

2024-12-24 00:11 UTC, joon-won commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> -		await this.clearTokens();
Seems we are no longer clearing `this.getLastAuthUserKey()`, will this change introduce any change in behavior?

2025-01-06 18:56 UTC, HuiSF requested changes

2025-01-06 18:56 UTC, HuiSF commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +		}
```suggestion
```

2025-01-06 18:57 UTC, HuiSF commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +		}
Hi @jon-armen thanks again for contributing. Could you take a look at the comments from @Samaritan1011001 and @joon-won above? 

`tokens.oauthMetadata` is actually causing Typescript build error atm.

2025-01-07 23:03 UTC, jon-armen commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
Removed, I don't see a need to have it here since it is managed separately as mentioned by @Samaritan1011001

2025-01-07 23:04 UTC, jon-armen commented on packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
> +		}
@HuiSF , removed based on comments above

2025-01-07 23:22 UTC, joon-won commented
> @joon-won I'll see if I can get some tests together in the next few days. @itsramiel , do you have thoughts on tests you might like to see to validate your use case?

Hi @jon-armen , thanks for updating the PR! Could you share with us if you have bandwidth to work on the tests or maybe it's close to completion 😄? We are happy to help if you need any hand.

2025-01-07 23:28 UTC, jon-armen commented
@joon-won - If you could assist with the tests, it would be much appreciated.  I'm unfortunately swamped between work and personal life.

2025-01-07 23:33 UTC, joon-won commented
> @joon-won - If you could assist with the tests, it would be much appreciated. I'm unfortunately swamped between work and personal life.

Absolutely! Again, we appreciate your contribution. Please let us know if there is anything you'd love to share with us anytime.

2025-01-10 01:21 UTC, AllanZhengYP commented
@jon-armen 

I'm happy to help driving this PR. Although I do not have write permission to your fork, I opened a PR there that would fix the failing unit test: https://github.com/jon-armen/amplify-js/pull/2. Can you either add me to your fork or merge my PR?

2025-01-10 01:27 UTC, jon-armen commented
> @jon-armen
> 
> I'm happy to help driving this PR. Although I do not have write permission to your fork, I opened a PR there that would fix the failing unit test: [jon-armen#2](https://github.com/jon-armen/amplify-js/pull/2). Can you either add me to your fork or merge my PR?

You should have access to the fork now.  I also merged your PR in.

2025-01-22 21:39 UTC, AllanZhengYP commented
We don't have merge permission so we cherry-picked the commits from this PR: https://github.com/jon-armen/amplify-js/pull/3 to this PR

2025-01-22 21:59 UTC, blakedunson approved these changes

2025-01-22 22:19 UTC, AllanZhengYP approved these changes

2025-01-22 22:29 UTC, joon-won approved these changes

2025-01-22 22:55 UTC, HuiSF commented on packages/auth/__tests__/providers/cognito/tokenProvider/tokenStore.test.ts
> +		jest.clearAllMocks();
Would this clear the mock done on line 26? if the mock is expected to work as always need to move it into `beforeEach()` right? Will this affect the accuracy of the test?

2025-01-22 23:26 UTC, HuiSF commented on packages/auth/__tests__/providers/cognito/tokenProvider/tokenStore.test.ts
> +		jest.clearAllMocks();
Never mind... I was thinking of `jest.resetAllMocks()` 😅

2025-01-22 23:26 UTC, HuiSF approved these changes

2025-01-22 23:28 UTC, merged

2025-01-25 00:07 UTC, joon-won commented
This change went live with [Amplify v6.12.2](https://www.npmjs.com/package/aws-amplify), thank you!