fix(storage): fixed stray line of Progress Event when multipart upload is complete
aws-amplify/amplify-js pull request #13652
Opened 2024-07-26 21:31 UTC by yuhengshs

#### Description of changes

#### Issue #, if available

issue # 11072
https://github.com/aws-amplify/amplify-js/issues/11072

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Unit Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

#### Checklist for repo maintainers

- [ ] Verify E2E tests for existing workflows are working as expected or add E2E tests for newly added workflows
- [ ] New source file paths included in this PR have been added to CODEOWNERS, if appropriate

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-07-29 20:09 UTC, AllanZhengYP requested changes
Can you make sure it's also fixed in the resumable upload task? https://github.com/aws-amplify/amplify-js/blob/ed8e0bb7ded214925a38aa20d4a5576ebe7fb4f5/packages/storage/src/providers/AWSS3UploadTask.ts#L283

Also can you add some unit test to prevent future regressions?

2024-07-30 19:40 UTC, AllanZhengYP approved these changes
It looks good, thank you! @yuhengshs

2024-07-30 22:05 UTC, jimblanc approved these changes

2024-08-01 21:03 UTC, ashika112 approved these changes

2024-08-01 22:38 UTC, merged