multi-endpoint base implementation
aws-amplify/amplify-js pull request #14086
Opened 2024-12-17 21:04 UTC by svidgen

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Unit Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

#### Checklist for repo maintainers

- [ ] Verify E2E tests for existing workflows are working as expected or add E2E tests for newly added workflows
- [ ] New source file paths included in this PR have been added to CODEOWNERS, if appropriate

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-18 19:39 UTC, blakedunson approved these changes

2024-12-18 23:06 UTC, stocaaro commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +		const memoKey = appSyncGraphqlEndpoint ?? 'none';
Is this memoKey sufficient? Wondering if a websocket might ever be accessed with different authtypes to achieve different permissions where both would have the same endpoint (or something similar)

I think in all case, overriding a graphql calls authtype works, but maybe a client with authtype A will be recreated with authtype B and the dev will be surprised that they get the original instance with type A...

Any other config that might be needed in the memoKey to avoid surprises?

2024-12-18 23:09 UTC, svidgen commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +		this.appSyncRealTime.set(memoKey, realtimeProvider);
Yeah. I weighed it against a conditional check to do the same. This seemed simpler to read. But, I don't mind changing it if you disagree.

2024-12-18 23:16 UTC, svidgen commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +		const memoKey = appSyncGraphqlEndpoint ?? 'none';
I think it should be OK. We have normally used a single socket for all connections regardless of the authmode needed by the subscription itself. In chatting with Ivan about how to do this, I think he leaned towards keeping connections pooled by client &mdash in most cases, I think that's *slightly better* for customers. Fewer local resources consumed at the very least, etc.. It's marginal. I wouldn't die on that hill.

If it causes issues, I think this behavior is pretty OK for us to change later.

2024-12-18 23:18 UTC, svidgen commented on packages/api-graphql/src/internals/generateClient.ts
> +		} else {
It's very deliberately skipping both to avoid attaching `.models` etc. and potentially causing confusion there &mdash; if someone were logging out the client and poking around for example, they'd see methods from their MIS that have nothing to do with the endpoint.

2024-12-18 23:20 UTC, svidgen commented on packages/api-graphql/src/types/index.ts
> +				  }
FWIW, I did go down the generic route and found that TS was too confused to offer suggestions while typing (pressing ctrl+space in particular). I'm not sure if I made a mistake, but I then had to go on a small crusade to simplify the types down into the "dumbest" possible versions of themselves and it seemed to contribute to resolving the issue.

2024-12-18 23:21 UTC, svidgen commented on packages/api-graphql/src/internals/v6.ts
> +		} as any,
I'll take another look at this one. I feel like I kicked this from every side I could to no avail. But, might holdover from when I was trying to use generics args in the base types.

2024-12-18 23:22 UTC, svidgen commented on packages/api-graphql/src/server/generateClient.ts
> +			innerOptions as any,
I'll take another look at this one also. But, I think this was in the same camp as above: TS just having a hard time connecting the dots between a generic param, and me feeling like finding the "right" cast didn't offer me much confidence.

2024-12-18 23:27 UTC, svidgen commented on packages/api-graphql/src/internals/server/generateClientWithAmplifyInstance.ts
> +			throw new Error(
It's probably more LOC to do so to accommodate the slightly different error messaging. Is it worth it to you?

2024-12-18 23:29 UTC, svidgen commented on packages/api-graphql/src/internals/v6.ts
> +	const clientEndpoint: string = (internals as any).endpoint;
Yep. I'll take another look at this one too. This one in particular is an `any` cast for different reasons than the others.

2024-12-19 20:55 UTC, iartemiev submitted a review, later dismissed

2024-12-19 21:14 UTC, blakedunson approved these changes

2024-12-19 22:27 UTC, stocaaro submitted a review, later dismissed

2024-12-19 22:27 UTC, stocaaro commented on packages/api-graphql/src/internals/InternalGraphQLAPI.ts
> +		this.appSyncRealTime.set(memoKey, realtimeProvider);
The conditional check seems like fewer moving parts or things to go wrong, but I also don't think I can come up with an example of when this would fail us, so this is a nit at best.

2024-12-19 22:27 UTC, stocaaro commented on packages/api-graphql/src/internals/server/generateClientWithAmplifyInstance.ts
> +			throw new Error(
nit. Probably not worth it.

2024-12-19 22:27 UTC, stocaaro commented on packages/api-graphql/src/types/index.ts
> +				  }
Hmm. Don't think we have the prettify wrapper here, but I think that might improve the CX on a more concise solution. Not sure where I land on this, this seems pretty long form.

2024-12-20 17:46 UTC, iartemiev submitted a review, later dismissed

2024-12-23 16:06 UTC, HuiSF requested changes

2024-12-23 16:06 UTC, HuiSF commented on packages/adapter-nextjs/src/api/generateServerClient.ts
> +} from '@aws-amplify/api-graphql/dist/esm/internals/types';
Wrong import path.

2024-12-23 16:07 UTC, cshfang commented on packages/api/__tests__/SRR.test.ts
> +import { enableFetchMocks } from 'jest-fetch-mock';
Should this file be ~SRR~ SSR?

2024-12-23 16:15 UTC, svidgen commented on packages/adapter-nextjs/src/api/generateServerClient.ts
> +} from '@aws-amplify/api-graphql/dist/esm/internals/types';
Good catch. Fixing ... Thank-you!

2024-12-23 16:15 UTC, svidgen commented on packages/api/__tests__/SRR.test.ts
> +import { enableFetchMocks } from 'jest-fetch-mock';
Yes. Good catch. Thank-you!

2024-12-23 16:39 UTC, iartemiev approved these changes

2024-12-23 16:54 UTC, HuiSF approved these changes

2024-12-23 17:24 UTC, merged