Made changes on most of the files
aws-amplify/amplify-js pull request #6602
Opened 2020-08-18 21:56 UTC by kendevops

_Description of changes:_
Updating the React Native S3Album UI Component to include more features 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-22 16:19 UTC, eddiekeller requested changes
Thanks for the submission! I have a few comments of things that we can update here.

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +		const { picker, level, identityId } = this.props;
nit - looks like this `identityId` variable isn't being used anywhere in the render function. We can ignore destructuring it here.

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +	getKey(file) {
Since we are expecting certain properties to be present on this `file` argument, let's add a typing here so we have some explicit type safety.

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +		return key.replace(/\s/g, '_');
For my own knowledge - why is replacing the whitespace with an underscore the correct choice here?

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +			}
Let's pull this check outside of the `if (fileToKey)` block. I don't know if `name` is a required property on the `file` argument, but for safety, we can catch that case too if we move it outside of the current scope it is in.

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +			}
It feels to me like we can split this out into its own method. Then, on line 57, we could simply do something like:

```
const key = fileToKey ? this.getKeyFromFile(fileToKey) : encodeURI(name);
```

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +					logger.debug('update an image');
nit - I'm not totally sure what this message is trying to say. Can we make it more clear?

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +				logger.debug('handle pick error', err);
nit - let's keep this `logger.warn()` since we are logging a caught error

2021-06-22 16:19 UTC, eddiekeller commented on packages/aws-amplify-react-native/src/Storage/S3Album.tsx
> +		const pickerTitle = this.props.pickerTitle || 'Pick';
nit - syntax

```
const { pickerTitle = 'Pick' } = this.props;
```

Actually, we could also just add this to the destructuring on line 118

2022-10-07 17:18 UTC, abdallahshaban557 commented
Hi @kendevops - this React Native component is on its path to deprecation. Apologies for not getting to this sooner!

2022-10-07 17:18 UTC, closed without merging