feat(@aws-amplify/datastore): Add SSR support for DataStore
aws-amplify/amplify-js pull request #6726
Opened 2020-09-04 00:44 UTC by ericclemmons

_Issue #, if available:_ Based on #6146, this solves the security concerns with DataStore & `PubSub.subscribe` in Node environments.

- [x] `PubSub.subscribe` throws in Node.  This behavior wasn't explicitly supported and shouldn't be for security reasons. (Multi-tenant apps may share sensitive information across a single, accessible socket)

- [x] `DataStore` doesn't start the sync engine in Node.

- [x] `withSSRContext` includes `DataStore` as a default module (along with `API` and `Auth`).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-04 15:23 UTC, sammartinez approved these changes
Soft approval as I want weigh in from @manueliglesias and @elorzafe on this before we merge

2020-09-04 16:56 UTC, elorzafe approved these changes
Nice work @ericclemmons 🌮 🎉 🥇 !

2020-09-04 17:01 UTC, sammartinez requested changes
Lets add the unit tests needed to resolve the unit test failure and Ill be happy to do a full approval

2020-09-04 17:09 UTC, manueliglesias approved these changes
Minor comment, LGTM! 🎉

2020-09-04 17:09 UTC, manueliglesias commented on packages/datastore/src/sync/index.ts
> +							let ctlSubsObservable, dataSubsObservable;
Can we type-annotate these?

2020-09-04 19:06 UTC, ericclemmons commented on packages/datastore/src/sync/index.ts
> +							let ctlSubsObservable, dataSubsObservable;
@manueliglesias Sure thing.  `this.subscriptionsProcessor.start()` returns these types:

```
const ctlObservable: Observable<CONTROL_MSG>
const dataObservable: Observable<[TransformerMutationType, SchemaModel, Readonly<{
    id: string;
} & Record<string, any>>]>
```

I'll add those, or use a `ReturnType` utility of `start()` to cast those unless you have a better solution!

2020-09-04 19:38 UTC, ericclemmons commented on packages/pubsub/src/PubSub.ts
> +				'Subscriptions are not supported in Node to prevent memory leaks.'
I'm leaning towards the following @sammartinez :

```suggestion
				'Subscriptions are not supported in Node.'
```

2020-09-04 19:44 UTC, manueliglesias commented on packages/datastore/src/sync/index.ts
> +							let ctlSubsObservable, dataSubsObservable;
`Readonly<{id: string;} & Record<string, any>>` should be the same as `PersistentModel`, so:

```
let ctlSubsObservable: Observable<CONTROL_MSG>;
let dataSubsObservable: Observable<[
	TransformerMutationType,
	SchemaModel,
	PersistentModel
]>;
```

2020-09-04 19:54 UTC, ericclemmons commented on packages/datastore/src/sync/index.ts
> +							let ctlSubsObservable, dataSubsObservable;
I'll update. See my latest commits for what I re-used.

2020-09-04 19:57 UTC, sammartinez approved these changes
LGTM 🌮

2020-09-04 20:05 UTC, ericclemmons commented on packages/datastore/src/sync/index.ts
> +							let ctlSubsObservable, dataSubsObservable;
Fixed! Pushing now.  Funny how TypeScript's annotations showed me the definition rather than `PersistentModel`.

2020-09-04 20:31 UTC, merged

2020-09-25 16:41 UTC, adamup928 commented
I see this change now prevents subscriptions from being established in a Node environment, and I understand the justification above regarding multi-tenant apps sharing sockets.  In our implementation, however, we are using the PubSub module in a client application running in a desktop environment and built with Electron.  This pull request breaks the functionality of the application entirely, and we can not use the latest update.

Is there a recommendation for this scenario?  Could we introduce a mode that allows subscriptions to be made when explicitly set?

2020-09-25 17:18 UTC, ericclemmons commented
@adamup928 Oh no! Can you open a [new issue as a feature request](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=feature_request.md&title=)?

You're absolutely right: the restriction in Node **does not apply** to Electron apps, so we can do better detection to unblock you.

Let's discuss more in that issue, but here are 2 solutions I'm aware of:

- Remove the `isNode` check from this PR in favor of a `if (config.ssr)`. In this scenario, we're blocking those connections in SSR scenarios specifically.  If Amplify is being used in an Electron app, SSR wouldn't be applicable. (Unless you say otherwise :D)
- Expand our `browserOrNode` utility to have other checks like `isElectron`, `isReactNative` so we're less generic.

2020-09-25 17:29 UTC, adamup928 commented
Thanks, @ericclemmons.  Done!  Here it is: https://github.com/aws-amplify/amplify-js/issues/6873