fix(@aws-amplify/datastore): Nullable Arrays
aws-amplify/amplify-js pull request #6784
Opened 2020-09-14 20:20 UTC by seang96

Issue #, if available: #6500

Description of changes:
This is based off of ondojo's initial PR tagged above.
I added a new field that gets stored in the schema generated from @aws-amplify/cli called isArrayRequired. PR #(TO BE MADE)
I added tests for the nullable arrays

This PR should support the table below:

declaration | null | [] | [null] | [{ foo: 'BAR' }]
-- | -- | -- | -- | --
[Type!]! | no | yes | no | yes
[Type]! | no | yes | yes | yes
[Type!] | yes | yes | no | yes
[Type] | yes | yes | yes | yes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-23 17:33 UTC, iartemiev requested changes
Looks great! Just a minor naming change requested

2020-09-23 17:33 UTC, iartemiev commented on packages/datastore/src/types.ts
> +	isArrayRequired?: boolean;
Hey @seang96, thank you so much for this PR! I talked it over with @yuth from the CLI team and we wanted to see if you could change `isArrayRequired` -> `isArrayNullable` in this PR, as well as in your related [CLI PR](https://github.com/aws-amplify/amplify-cli/pull/5327). 
We'll merge both PRs promptly once the change has been made.

2020-09-25 12:36 UTC, seang96 commented on packages/datastore/src/types.ts
> +	isArrayRequired?: boolean;
> 
> 
> Hey @seang96, thank you so much for this PR! I talked it over with @yuth from the CLI team and we wanted to see if you could change `isArrayRequired` -> `isArrayNullable` in this PR, as well as in your related [CLI PR](https://github.com/aws-amplify/amplify-cli/pull/5327).
> We'll merge both PRs promptly once the change has been made.

I pushed the respective changes! Sorry for the delay, got caught up in other projects.

2020-09-25 17:36 UTC, iartemiev commented on packages/datastore/src/types.ts
> +	isArrayRequired?: boolean;
No worries, thanks for updating! We should flip the behavior as well though since isNullable has effectively the opposite meaning of isRequired, i.e. where you had `isArrayRequired` should now be `!isArrayNullable`. Sorry for the confusion.

2020-09-25 18:54 UTC, seang96 commented on packages/datastore/src/types.ts
> +	isArrayRequired?: boolean;
No problem, I did not think about the implications for the name change haha. Commit is pushed.

2020-09-26 12:43 UTC, iartemiev approved these changes

2020-09-26 12:59 UTC, merged