feat(@aws-amplify/datastore): add Selective Sync
aws-amplify/amplify-js pull request #7001
Opened 2020-10-19 13:56 UTC by iartemiev

**In draft until https://github.com/aws-amplify/amplify-cli/pull/5586 is merged.**

## DataStore - Selective Sync Feature
Enables developers to apply a query and/or filter to their DataStore base and delta sync.

You can now limit the data that gets synced down into your users' local store, instead of syncing down the entire contents of the associated DynamoDB table.

Additional details:
* Provides code completion ("Intellisense") for returning a valid expression (just like Query predicates). 
* Applies the same filtering to inbound AppSync subscriptions.
* Adds new `DataStore.stop()` method for stopping the sync & subscriptions without clearing out the contents of the local store.

Misc.:
* renames asyncstorage.ts -> AsyncStorageAdapter.ts
* renames indexeddb.ts -> IndexedDBAdapter.ts
* make Reachability.ts more WebWorker-friendly

Addresses the following feature requests/issues:
* https://github.com/aws-amplify/amplify-js/issues/4957
* https://github.com/aws-amplify/amplify-js/issues/5119

### Basic usage

Selective Sync is configured by specifying `syncExpressions`, a newly added _optional_ configuration parameter.
Customers can choose which model(s) they would like to apply an expression to. 

```typescript
import { DataStore, syncExpression } from 'aws-amplify';
import { Post } from './models';

DataStore.configure({
  syncExpressions: [
    syncExpression(Post, () => {
      return (c) => c.rating('gt', 5);
    })
  ]
});
```
When DataStore starts syncing, only Posts with `rating > 5` will be synced down to the user's local store

### Reevalute expressions at runtime
Sync expressions get evaluated in `DataStore.start()` so it's possible to reevaluate them at runtime.

```typescript
let rating = 5;

DataStore.configure({
  syncExpressions: [
    syncExpression(Post, () => {
      return (c) => c.rating('gt', rating));
    })
  ]
});
```
If you want to start syncing down Posts with `rating > 1`, you can do:
```typescript
async function changeSync() {
  rating = 1;
  await DataStore.stop(); // or DataStore.clear() if you also want to empty the contents of the local store
  await DataStore.start();
}
```
Upon calling `start()` (or executing a DataStore operation, e.g., `query`, `save`, `delete`, or `observe`), DataStore will reevaluate the `syncExpressions`. 
In the above case, the predicate will contain the value `1`, so all Posts with `rating > 1` will get synced down.

### Using async expressions
You can pass a Promise to `syncExpression`:
```typescript
DataStore.configure({
  syncExpressions: [
    syncExpression(Post, async () => {
      const ratingValue = await getRatingValue();
      return (c) => c.rating('gt', ratingValue);
    })
  ]
});
```
DataStore will wait for the Promise to resolve before applying the expression to sync. Async expressions can also be reevaluated at runtime, just like synchronous expressions (see previous section). 

### Shorthand
If you don't need to add any logic to your `syncExpression`, you can use the following shorthand (returning the predicate, as opposed to a function or promise that in turn returns a predicate like in the above examples):
```typescript
DataStore.configure({
  syncExpressions: [
    syncExpression(Post, (c) => c.rating('gt', 5))
  ]
});
```

### Advanced use case
You can utilize Selective Sync in order to have your base sync retrieve items from DynamoDB via query against a table, LSI, or GSI. By default, the base sync will perform a scan.
In order to do that, your `syncExpression` should return a predicate that maps to a queryable expression.

For example, for the following schema:
```graphql
type User @model
  @key(name: "byLastName", fields: ["lastName", "createdAt"]) {
  id: ID!
  firstName: String!
  lastName: String!
  createdAt: AWSDateTime!
}
```

This sync expression will produce a query operation:

```typescript
DataStore.configure({
  syncExpressions: [
    syncExpression(User, async () => {
      const lastName = await getLastNameForSync();
      return (c) => c.lastName('eq', lastName).createdAt('gt', '2020-10-10')
    })
  ]
});
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-20 16:25 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +	stop = async function clear() {
Because I copy-pasted the `clear` method 😹  Will fix this along with a few other things

2020-10-21 19:00 UTC, iartemiev commented on packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
> +	ModelSortPredicateCreator,
Just FYI to reviewers, the sort code is showing up in the diff for AsyncStorageAdapter and IndexedDBAdatper due to a file rename and delete. It's not actually new code, it's just that we had duplicate files (e.g., asyncstorage.ts and AsyncStorageAdapter.ts and the latter was out of date).

2020-10-21 20:10 UTC, amhinson approved these changes
Looks good to me! 👍

2020-10-22 03:33 UTC, manueliglesias commented on packages/datastore/src/types.ts
> +		syncExpressions?: SyncExpression<any>[];
I think this can be changed to:

```suggestion
		syncExpressions?: SyncExpression<PersistentModel>[];
```

2020-10-22 05:11 UTC, manueliglesias requested changes
This looks great! I am very excited for this feature 😄 

I added minor comments.

2020-10-22 05:11 UTC, manueliglesias commented on packages/datastore/src/datastore/datastore.ts
> +			if (map.get(modelDefinition)) {
```suggestion
			if (map.has(modelDefinition)) {
```

2020-10-23 14:46 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +					const condition = await this.unwrapPromise(conditionProducer);
Leaving this in for now per our conversation

2020-10-27 23:44 UTC, manueliglesias approved these changes
LGTM, just wait for @elorzafe 's review

👍 

Thanks @iartemiev !

2020-10-28 00:16 UTC, elorzafe requested changes
Thanks @iartemiev this looks great!

I would double check `stop` function to see there is no race condition in case the app invokes `start` and `stop` repeatedly

2020-10-28 13:34 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +			const predicateChanged =
That's an interesting point, Francisco. I'll give this some more thought. 

I think determining whether the filter condition is more or less strict is straightforward in certain cases, e.g., when using conditional operators with numbers and dates, or when adding progressively more characters to a string while utilizing the `startsWith` or `contains` operators (`c.firstName('startsWith', 'F')` --> `c.firstName('startsWith', 'Fr')`). But for multi-field or nested filters, it can get very complicated.

I also like the idea of being able to selectively `clear` a model. Currently, the customer would need to call `DataStore.clear()` followed by `DataStore.start()` if they want to make sure the original data is no longer there. But as you suggest, this can be made more efficient by allowing them to only clear certain models.

2020-10-28 18:51 UTC, elorzafe approved these changes
Thanks @iartemiev this is awesome!! 🌮 🎉 🥇

2020-10-28 18:51 UTC, elorzafe commented on packages/datastore/src/datastore/datastore.ts
> +			const predicateChanged =
Thanks Ivan, I was curious if there was a chance to improvement on this release. But I agree, this can get more complex. We can do another revision for this in the future.

2020-10-28 19:51 UTC, merged

2020-11-25 09:06 UTC, LaurentEscalier commented
Hey there 👋 
Hey @iartemiev 

I've updated `aws-amplify` to the latest version in my project and have since then been facing the following issue.

Datastore now adds a $filter parameter of type Model${typeName}FilterInput to the GraphQL sync operations that my app is sending:

```
{
   "query":"query operation($limit: Int, $nextToken: String, $lastSync: AWSTimestamp, $filter: ModelMyModelFilterInput) {\n  syncMyModels(limit: $limit, nextToken: $nextToken, lastSync: $lastSync, filter: $filter) {\n    items {\n      id\n      data\n      _version\n      _lastChangedAt\n      _deleted\n    }\n    nextToken\n    startedAt\n  }\n}\n",
   "variables":{
      "limit":1000,
      "nextToken":null,
      "lastSync":0,
      "filter":null
   }
}
```

Which results in the following errors in the response.

```
{
   "data":null,
   "errors":[
      {
         "path":null,
         "locations":[
            {
               "line":1,
               "column":84,
               "sourceName":null
            }
         ],
         "message":"Validation error of type UnknownType: Unknown type ModelMyModelFilterInput"
      },
      {
         "path":null,
         "locations":[
            {
               "line":2,
               "column":84,
               "sourceName":null
            }
         ],
         "message":"Validation error of type UnknownArgument: Unknown field argument filter @ 'syncMyModels'"
      }
   ]
}
```

Now, I understand why this happens: the related AppSync Backend schema does not expect any $filter parameter on this operation and also doesn't know about a type named `ModelMyModelFilterInput`.

The way I see it is that this Pull Request has added a change (somewhere around [here](https://github.com/aws-amplify/amplify-js/blob/aws-amplify%403.3.5/packages/datastore/src/sync/utils.ts#L276)) that forces me to update my AppSync Backend.

How should I proceed with that ? Where is this required Backend change documented ?

2020-11-25 14:15 UTC, iartemiev commented
@LaurentEscalier there is no backend change required for those using the CLI - which is the recommended approach for DataStore - as we've always included an optional filter argument in the generated query input type. It was just unused until this change.

In your case, you can run `amplify api gql-compile` in the root of your project and then copy the generated schema from `amplify/backend/api/your-app-name/build/schema.graphql` to the schema location referenced in your CloudFormation template. Or you can copy-paste the input types piecemeal from the generated schema into the schema you're using. See [this doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlschema.html) for more info on how to update the schema in a CF stack.