feat(auth): Added fetchOptions configuration on auth module
aws-amplify/amplify-js pull request #7109
Opened 2020-11-03 18:37 UTC by dgonsan

Issue #, if available:
#6905

Description of changes:

Added fetchOptions to Auth module configuration, it's a new  optional parameter that allows to use the already existing fetchOptions configuration available in amazon-cognito-idenity-js from the auth module  and its components.

The changes are just a simple pass through of the new optional parameter from the Auth class to the CognitoUserPool class that makes use of it.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-09 17:06 UTC, drochetti requested changes

2021-02-09 17:06 UTC, drochetti commented on packages/amazon-cognito-identity-js/index.d.ts
> +        fetchOptions?: any;
I would like to see an actual type. What options are available?

nit: fix formatting

2021-02-09 17:06 UTC, drochetti commented on packages/auth/src/types/Auth.ts
> +	fetchOptions?: any;
use the type defined in `packages/amazon-cognito-identity-js/index.d.ts`

2021-03-18 15:24 UTC, dgonsan commented on packages/amazon-cognito-identity-js/index.d.ts
> +        fetchOptions?: any;
I added a IFetchOptions type to amazon-cognito-idenity-js with the proper typing and restrictions for fetch options.

2021-03-18 15:25 UTC, dgonsan commented on packages/auth/src/types/Auth.ts
> +	fetchOptions?: any;
I didn't find any define type for fetchOptiions there so I added IFetchOptions one with the fetch options definition.

2021-09-09 12:39 UTC, evcodes reviewed
This looks good to me, just need to fix the merge conflicts so we can merge in your first PR 💯  

Thank you for contributing to Amplify 👍🏼

2021-10-01 15:27 UTC, dgonsan commented
I rebased all the changes on the main branch and solved the conflicts.

2021-12-17 11:46 UTC, dgonsan commented
Hey @evcodes , sorry for the delay I was busy with other projects and didn't have time to come back to this pull request until now.

1. What tests do you want me to add? Because there is no new feature here, the feature is in the cognito module and was implemented long time ago, this just adds the option to pass the values to the other module to use that feature.

2. It's just and additional configuration option, probably should be added in this section of the documentation: https://docs.amplify.aws/lib/auth/start/q/platform/js/#configure-your-application

```
    // OPTIONAL: Configuration for fetch options on authentication requests
    fetchOptions: {
        // OPTIONAL - Authentication credentials mode
        // See: https://github.github.io/fetch/#credentials
        credentials: 'same-origin' | 'include' | 'omit';
    }
```

This allows retrieving/sending credentials in the authentication request which in our case is used to set additional cookies required by our application.

2024-01-09 21:18 UTC, cwomack commented
Hey, @dgonsan sorry for the delays in communication on this PR.  With the release of Amplify v6, the `amazon-cognito-identity-js package` is no longer used (was last used in v5.x).  Would you be able to see if the new `fetchAuthSession` API in v6 is sufficient to accomplish what you're looking for in this PR ([link](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#retrieve-a-user-session))? If not, can you elaborate a little more on what the use case is that you're looking for? Thank you!

2024-02-16 19:11 UTC, cwomack commented
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

2024-02-16 19:11 UTC, closed without merging