add showToasts prop to authenticator
aws-amplify/amplify-js pull request #7129
Opened 2020-11-06 15:47 UTC by Luke-Davies

_Issue #, if available:_
None

_Description of changes:_
Adds a property to the `amplify-authenticator` called `showToasts` which is defaulted to `true`.

Setting this to `false` will prevent `amplify-toast` from rendering when `TOAST_AUTH_ERROR_EVENT` events are raised on the `UI_AUTH_CHANNEL`.

This is useful if you want to roll your own alerting components for auth error messages.

React Example:

```
import React, { useState, useEffect } from 'react';
import { Hub, HubCallback } from '@aws-amplify/core';
import {
  AmplifyAuthenticator,
} from '@aws-amplify/ui-react';
import {
 UI_AUTH_CHANNEL, TOAST_AUTH_ERROR_EVENT
} from '@aws-amplify/ui-components';

const MyAuth: React.FC = ({ children }) => {

  const [alertMessage, setAlertMessage] = useState('');

  const handleToastErrors: HubCallback = ({ payload }) => {
    if (payload.event === TOAST_AUTH_ERROR_EVENT && payload.message) {
      setAlertMessage(payload.message);
    }
  };

  useEffect(() => {
    Hub.listen(UI_AUTH_CHANNEL, handleToastErrors);
    return () => Hub.remove(UI_AUTH_CHANNEL, handleToastErrors);
  });

  return (
    <>
      {alertMessage && (<div>{alertMessage}</div>)}
      <AmplifyAuthenticator showToasts={false}>
        // ...........
      </AmplifyAuthenticator>
    </>
  );
}
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-20 09:41 UTC, ThrowingSpoon commented
Could this get reviewed please? Would be awesome to have 💪

2021-01-20 10:15 UTC, Luke-Davies commented
Not sure if I'm supposed to randomly bug people for reviews sorry! @elorzafe @sammartinez @manueliglesias 

This is a pretty simple change.

Could argue that it should be `hideToasts` instead of `showToasts` to match [this prop in amplify-sign-in](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx#L67). Opinions welcome.

2021-01-21 02:50 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
> +  @Prop() showToasts: boolean = true;
As you mentioned, I like `hideToasts = false` better because users would only use this prop when they want to hide them. And you can do `<amplify-authenticator hide-toasts /> too!

2021-01-21 03:02 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
> +        {this.showToasts && this.toastMessage ? (
Instead of mixing `&&` and `?`, can we use `&&` for both?
```ts
this.showToasts && this.toastMessage && (
  // ...
)
```

2021-01-21 03:03 UTC, wlee221 requested changes
Sorry about the late review! Just got some nits but looks good to me otherwise 👍

2021-01-21 03:20 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
> +  @Prop() showToasts: boolean = true;
On second thought, I think we should use `hideToast` because there is only one toast at a time.

2021-01-21 11:20 UTC, Luke-Davies commented
Thanks @wlee221! 
Both changes made and tested locally.
I've updated the PR name & description to reflect the prop change from `showToasts` --> `hideToast`

2021-01-21 15:52 UTC, ericclemmons commented
Thanks for taking this need on @Luke-Davies.

I support @wlee221's feedback, and wanted to offer some context into past discussions around this need.

The UI components are, as we know, powered by Web Components and often rely on "slots" for customizing individual components.

What we _didn't know_ at the time is if `hideToast` would be equivalent to overriding an `amplify-toast` slot (if it existed):

```js
<AmplifyAuthenticator>
  <!-- Default components here -->
  <div slot="ampify-toast">
    <!-- Nothing to see here! -->
  </div>
</AmplifyAuthenticator>
```

Do either of y'all know if this is better, worse, or possible?  IIRC, the rationale for `hideSignUp` was because the sign-up language was "too deep" in the component to replace with an empty `slot`:
https://github.com/aws-amplify/amplify-js/pull/6098/files

Again, I'm supportive of this PR to unblock customers! I just wanted to share _where we left off_ in conversations in the past.

2021-01-21 16:58 UTC, Luke-Davies commented
Thanks for the context @ericclemmons. I had considered trying to implement this feature by introducing a slot and would absolutely support that solution if it is more in-keeping with the design choices made for the project so far.

If a slot is introduced then I would suggest something other than `amplify-toast` for the name.

For example; our app displays a modal for auth errors because we found that some customers were not seeing the toast on certain devices unless they happened to scroll to the top of the page. Currently, we're showing this modal as well as the toast (until we can hide the toast).

Perhaps `amplify-auth-alert` or just `amplify-alert` would be a better name for the slot if that approach is preferred?

2021-01-21 21:08 UTC, ericclemmons commented
I agree, `amplify-toast` isn't great. It matches the original desire of a "toast" notification, but we also considered `amplify-notification` among others.

I just found https://github.com/aws-amplify/amplify-js/issues/6479 as well, so we're not the only ones who've talked about this :D

So, in terms of preference having _fewer props_ would be preferential. Especially since a `slot` would allow _customization_ compared to hiding entirely.

@wlee221 What are your thoughts on the matter? Do you prefer props vs. slots, and what name would you use? (Assuming it would work!)

2021-01-21 23:29 UTC, wlee221 commented
I can't believe I missed the slot approach! I just tested that using slots works as intended, so this is really up to what we want to do.

I'm kind of divided on slots vs props though. If it were just for hiding toast, I would have argued that `hideToast` is more intuitive for customers. I find it unintuitive to pass an empty element to slot to hide a section:
```
<amplify-authenticator>
  <div slot="amplify-toast"></div>
</amplify-authenticator>
```
And it's not clear what the code is trying to do on first glance. I think the purpose of hiding an element deviates from customization, which slot specializes in. 

That being said, customers are asking for customizations on amplify-toast as well on #6479. Slots do well for covering both use cases, so I think slot is the best way to go. And I agree with @ericclemmons' comment that fewer props are preferential. 

So tldr; we should go with slots. For the slot name, I like `amplify-alert` or just `alert` because it conveys that there's an error better than other suggestions imo.

2021-01-22 13:34 UTC, Luke-Davies commented
@wlee221 @ericclemmons 
I've raised a new PR for the slotted approach. Please see PR #7601 

I believe we can close one.

2021-03-08 21:24 UTC, Luke-Davies commented
Coming back to this following a discussion on #7601 (`slot` approach). To understand why we've come back to `props`, see [this thread](https://github.com/aws-amplify/amplify-js/pull/7601#discussion_r588767972).

2021-03-08 21:34 UTC, Luke-Davies commented
@wlee221 One final change I wasn't sure of on this was whether to wrap `Hub.listen(UI_AUTH_CHANNEL, this.handleToastEvent);` and `Hub.remove(UI_AUTH_CHANNEL, this.handleToastEvent);` with `if (!this.hideToast)`. The `prop` could technically be updated though (I'm not sure why anyone would) which could result in the callback not being removed.

Let me know if you think it's worth doing.

2021-03-09 00:30 UTC, wlee221 commented
I think this is a pretty simple optimization worth doing. As mentioned, I don't see a good reason for changing the `hideToast` value dynamically.

2021-03-09 19:35 UTC, wlee221 approved these changes
This LGTM 👍  Thanks a lot for your contribution throughout this!

2021-03-10 21:17 UTC, merged