feat(@amplify/datastore): add local validations to AppSync scalars
aws-amplify/amplify-js pull request #7212
Opened 2020-11-17 05:02 UTC by wei

_Issue #, if available:_
Resolves #5963

_Description of changes:_
Perform some basic local validations for all [AppSync Defined Scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html). Currently there are no validations on these fields so one can store anything in e.g. `AWSDateTime` field locally. During datastore sync, AppSync does validations and graphql requests will fail. 

This PR uses basic regex to validate all the fields listed. However, some of the fields could use better validations. e.g. `2020-99-99T00:00:00Z` will pass validation with the current regex, We cannot use the built-in date function because AppSync supports non-standard ISO 8601 standard:

> The seconds field in the timezone offset will be considered valid even though it is not part of the ISO 8601 standard. 

Ideally, we should reuse AppSync's validation logic here for parity but having basic validations is much better than no validations : )

Screenshot of example error:
![image](https://user-images.githubusercontent.com/5880908/99348491-b8141b00-2867-11eb-8aad-99e6dc9482be.png)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-17 17:09 UTC, iartemiev requested changes
Looks great, @wei! Thank you! 🚀

I added a minor ask for an additional test, otherwise, PR is ready to be merged.

2020-11-17 17:09 UTC, iartemiev commented on packages/datastore/__tests__/DataStore.ts
> +			}).not.toThrow();
Let's also add a mix of valid and invalid items in a list and expect it to throw. 

E.g., 
```js
ips: ['1.1.1.1', 'not.an.ip'],
```

2020-11-17 18:27 UTC, wei commented on packages/datastore/__tests__/DataStore.ts
> +			}).not.toThrow();
Added in latest commit https://github.com/aws-amplify/amplify-js/pull/7212/commits/816635410fa8f140b8ef9906b211d309ddbd06a7

2020-11-17 20:40 UTC, wei commented
This PR should not be merged until rebasing after https://github.com/aws-amplify/amplify-js/pull/7216 is reviewed and merged.

2020-11-19 15:06 UTC, iartemiev approved these changes
Thanks again @wei this is a very helpful improvement!

2020-11-19 15:06 UTC, merged