Added removePluggable function to PubSub
aws-amplify/amplify-js pull request #7256
Opened 2020-11-22 19:22 UTC by zacharyrogers1

Added the ability to remove providers from PubSub after creation. This should allow for users to be able to reconfigure their PubSub providers when changing authentication states or wanting to reconfigure regions. 

Issue #, if available: #7103

Description of changes:

Previously the pubsub providers list could not be modified once created. This meant that when a user changed authentication states or wanted to change their connection region for IoT they would be unable to do so. New function will allow websocket providers to be removed so that new addpluggables may be added. Calling PubSub.removePluggable() will not delete the old provider, simply remove it from the internal list of providers so that a new one can be added.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-25 08:45 UTC, AraiHaruki commented
Will this be merged?
I need this feature.

2021-09-02 12:41 UTC, kirkryan commented
@renebrandel - Hey! Any chance we could have AWS reviewer allocated to this please amigo? This is a REALLY useful feature - basically it's a key functionality that is missing from the PubSub client in that there is currently no way of removing a provider - which means you can end up with multiple duplicate providers and in the worst-case sending AND receiving multiple times duplicate data which quickly has performance and cost implications for any client using the current AWS Pubsub client.

Kirk - AWS Community Builder

2021-09-02 16:37 UTC, sammartinez commented
> @renebrandel - Hey! Any chance we could have AWS reviewer allocated to this please amigo? This is a REALLY useful feature - basically it's a key functionality that is missing from the PubSub client in that there is currently no way of removing a provider - which means you can end up with multiple duplicate providers and in the worst-case sending AND receiving multiple times duplicate data which quickly has performance and cost implications for any client using the current AWS Pubsub client.
> 
> Kirk - AWS Community Builder

Hey Kirk! Thanks for raising this to us, we are starting the process internally and will provide an update next week on progress of getting this pull request merged in for our customers.

2021-09-02 17:13 UTC, kirkryan commented
> > @renebrandel - Hey! Any chance we could have AWS reviewer allocated to this please amigo? This is a REALLY useful feature - basically it's a key functionality that is missing from the PubSub client in that there is currently no way of removing a provider - which means you can end up with multiple duplicate providers and in the worst-case sending AND receiving multiple times duplicate data which quickly has performance and cost implications for any client using the current AWS Pubsub client.
> > Kirk - AWS Community Builder
> 
> Hey Kirk! Thanks for raising this to us, we are starting the process internally and will provide an update next week on progress of getting this pull request merged in for our customers.

AWSome - thanks @sammartinez - if you need any further technical/business justification @renebrandel know's my details and I'm happy to help out.

Many thanks! Once implemented I'm happy to update the documentation as a separate PR.

2021-09-02 19:47 UTC, elorzafe requested changes
I would check the function argument (plugin name instead of passing the actual plugin and the other will be the way is filtered

2021-09-02 19:47 UTC, elorzafe commented on packages/pubsub/src/PubSub.ts
> +	removePluggable(options: ProvidertOptions) {
We used on the library in other categories `providerName` as the argument

Can you add the JS doc for this. For example
```
/**
 * remove plugin from PubSub category
 * @param providerName - the name of the plugin
 */

2021-09-02 19:47 UTC, elorzafe commented on packages/pubsub/src/PubSub.ts
> +		return this._pluggables.splice(indexOfPluggableToRemove, 1)[0];
I think is better to do something like this, `indexOf` for `providerName` would not work because is an array of objects not an array of strings.

```
this._pluggables = this._pluggables.filter(
			pluggable => pluggable.getProviderName() !== providerName
		);
```


Why do you need to return the plugin that was removed, just to know if it was removed?

2021-09-02 21:19 UTC, david-mcafee commented on packages/pubsub/src/PubSub.ts
> +	removePluggable(options: ProvidertOptions) {
+1

2021-09-02 21:22 UTC, david-mcafee commented on packages/pubsub/src/PubSub.ts
> +		return this._pluggables.splice(indexOfPluggableToRemove, 1)[0];
+1 on this approach.

I'd also be curious to know why we're returning the plugin that was removed. Perhaps we could include a return type on the function to make that explicit, if there's a valid reason to do so?

2021-09-02 21:29 UTC, david-mcafee requested changes
Left a few comments. Thanks again for creating this PR!!

2021-09-02 21:29 UTC, david-mcafee commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +			const removedPluggable = pubsub.removePluggable({provider: 'AWSIoTProvider'});
Could you update this unit test to do the following?

1. Add a provider
2. Remove the provider
3. Add a new provider (different from the first)
4. Verify that the correct provider is being used
3. This way, instead of validating the return value of `removePluggable`, validate that the correct provider exists (and that the removed one does not). Otherwise, we are only testing the return value of `removeProvider`

2021-09-02 21:29 UTC, david-mcafee commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +		test('should remove MqttOverWSProvider', () => {
The above comment could also be applied here, as well

2021-09-05 14:27 UTC, zacharyrogers1 commented on packages/pubsub/src/PubSub.ts
> +	removePluggable(options: ProvidertOptions) {
Changed signature of function to accept providerName. Thanks for the suggestion.

2021-09-05 14:28 UTC, zacharyrogers1 commented on packages/pubsub/src/PubSub.ts
> +		return this._pluggables.splice(indexOfPluggableToRemove, 1)[0];
Changed implementation of removePluggable to be identical to what you suggested. Thanks for the feedback!

2021-09-05 14:29 UTC, zacharyrogers1 commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +			const removedPluggable = pubsub.removePluggable({provider: 'AWSIoTProvider'});
Updated test to incorporate test flow you suggested:

1. addProvider
2. removeProvider
3. add new Provider
4. Call publish on pubsub class and verify that the new provider publish function was called and the old provider was not called.

2021-09-05 14:30 UTC, zacharyrogers1 commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +		test('should remove MqttOverWSProvider', () => {
Added same test logic to this function.

2021-09-05 14:34 UTC, zacharyrogers1 commented
Thank you everyone for the review. It was very helpful for my first contribution to this project. I believe I have taken all of your feedback into account and updated the tests/code. 

Please let me know if there is anything else to add/remove.

2021-09-07 20:22 UTC, david-mcafee commented
> Thank you everyone for the review. It was very helpful for my first contribution to this project. I believe I have taken all of your feedback into account and updated the tests/code.
> 
> Please let me know if there is anything else to add/remove.

Thanks, @zacharyrogers1! Taking a look at your changes now.

2021-09-07 23:27 UTC, david-mcafee approved these changes
Everything looks good! Thanks so much for this PR! I added a few updates to this PR as well (JS Doc, and updates to the unit tests).

2021-09-07 23:27 UTC, david-mcafee commented on packages/pubsub/src/PubSub.ts
> +	 */
I added this minor JSDoc comment

2021-09-07 23:27 UTC, david-mcafee commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +			pubsub.publish('someTopic', { msg: 'published Message' });
I made a minor update here to remove the Provider on publish. It's necessary to specify the Provider if there are multiple that are registered. If we specify it in this test, we aren't testing that the second Provider was successfully removed. By not specifying the Provider, we ensure that the second (removed) Provider did not publish a message.

2021-09-07 23:27 UTC, david-mcafee commented on packages/pubsub/__tests__/PubSub-unit-test.ts
> +			pubsub.publish('someTopic', { msg: 'published Message' });
I made the same update here

2021-09-07 23:29 UTC, david-mcafee commented on packages/pubsub/src/PubSub.ts
> +		return this._pluggables.splice(indexOfPluggableToRemove, 1)[0];
Ofcourse! Thanks for addressing this feedback!

2021-09-07 23:41 UTC, elorzafe approved these changes
LGTM! thanks @zacharyrogers1 🌮 🥇

2021-09-08 20:57 UTC, merged