7406 undefined currentuser
aws-amplify/amplify-js pull request #7442
Opened 2020-12-23 21:46 UTC by wlee221

_Issue #, if available:_ Fixes #7406. 

_Description of changes:_ When customer uses custom implementation of `amplify-require-new-password` with `slots`, `componentWillLoad` fires before `user` has been set. Therefore, `currentUser` doesn't get defined and ends up in the #7406 error. This PR watches for `user` prop change and initializes `currentUser` on change.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-23 22:08 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +    if (this.currentUser && this.currentUser.challengeParam && this.currentUser.challengeParam.requiredAttributes) {
This can be simplified to `this.currentUser?.challengeParam?.requiredAttributes`, but `eslint` is throwing syntax error because it is referencing monorepo `typescript@3.6.4`. I'll follow up with another pr that bumps monorepo typescript version.

2020-12-23 22:11 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +  private currentUser: CognitoUserInterface = null;
`currentUser` has no reason to be a state, so I changed it to a private variable.

2020-12-25 04:48 UTC, harrysolovay commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> -  private requiredAttributes: object = {};
Use a `Record<PropertyKey, any>` (or preferably a narrower type) instead of `object`. `object` will allow seemingly-incompatible types. For instance.

```ts
const x: object = [];
``

2020-12-25 04:50 UTC, harrysolovay commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +  private currentUser: CognitoUserInterface = null;
Why assign `null`? If we had a stricter config, that would be a type error. Why not just leave uninitialized? It's not preferable, but we've disabled strict property initialization. So this'll do the trick:

```ts
private currentUser: CognitoUserInterface;
```

2020-12-25 04:52 UTC, harrysolovay commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +    if (this.currentUser && this.currentUser.challengeParam && this.currentUser.challengeParam.requiredAttributes) {
I believe there's a reason we haven't already done this. You should first follow up with @sammartinez about TS version.

2020-12-25 04:52 UTC, harrysolovay requested changes
Looking pretty good. Just a few minor comments :)

2020-12-25 11:43 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +    if (this.currentUser && this.currentUser.challengeParam && this.currentUser.challengeParam.requiredAttributes) {
Good point, I will!

2020-12-25 11:43 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> -  private requiredAttributes: object = {};
Agreed, will do!

2020-12-25 11:44 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +  private currentUser: CognitoUserInterface = null;
you're right, fixing it now.

2020-12-25 12:05 UTC, harrysolovay approved these changes
Sweet! LGTM

2020-12-25 12:31 UTC, wlee221 commented
Thanks @harrysolovay for the comments!

2020-12-25 12:32 UTC, merged