fix(@aws-amplify/datastore): only include changed fields in update mutation input
aws-amplify/amplify-js pull request #7466
Opened 2020-12-30 17:21 UTC by iartemiev

_Description of changes:_
The current implementation of DataStore will include all of the fields for a model in the mutation input for update mutations. This prevents the AutoMerge conflict resolution strategy from working as expected.

This PR relies on Immer patches to discern which fields were by the user and only sends the changed fields in the update mutation query input variables.

If we have the following schema
```gql
type Todo @model {
  id: ID!
  name: String!
  completed: Boolean
}
```

And we perform an update
```js
const current = await DataStore.query(Todo, '0a121e7d-188c-4773-81b6-d3bd30a31c05');

DataStore.save(Todo.copyOf(current, updated => {
  updated.name = 'updated';
}));
```

The resulting GraphQL mutation will be:

**Currently**
```json
{
    "query": "mutation operation($input: UpdateTodoInput!, $condition: ModelTodoConditionInput) {\n  updateTodo(input: $input, condition: $condition) {\n    id\n    name\n    completed\n    owner\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n",
    "variables": {
        "input": {
            "id": "0a121e7d-188c-4773-81b6-d3bd30a31c05",
            "name": "updated",
            **"completed": null,**
            "_version": 1
        },
        "condition": null
    }
}
```
**With PR**
```json
{
    "query": "mutation operation($input: UpdateTodoInput!, $condition: ModelTodoConditionInput) {\n  updateTodo(input: $input, condition: $condition) {\n    id\n    name\n    completed\n    owner\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n",
    "variables": {
        "input": {
            "id": "0a121e7d-188c-4773-81b6-d3bd30a31c05",
            "name": "updated",
            "_version": 1
        },
        "condition": null
    }
}
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-30 18:50 UTC, nubpro commented on packages/datastore/src/util.ts
> +	);
is something off with your formatter?

2020-12-30 19:02 UTC, iartemiev commented on packages/datastore/src/util.ts
> +	);
No. Mine is working as expected. 
The contributor who originally added that code must have not had theirs configured correctly.

2020-12-31 03:44 UTC, nubpro commented on packages/datastore/src/util.ts
> +	);
Cool, I believe it was @wei

2021-01-05 17:10 UTC, amhinson approved these changes
LGTM 👍

2021-01-06 19:01 UTC, manueliglesias requested changes
It is looking good!

I would like to see some unit tests, specially around handling of fields of type `array` and the scenario where required fields weren't updated but they should still be sent to the mutation.

2021-01-06 19:01 UTC, manueliglesias commented on packages/datastore/src/storage/storage.ts
> +				// As well as the internal fields
What about fields that weren't updated but are marked as `required: true` in the schema?

2021-01-06 19:12 UTC, iartemiev commented on packages/datastore/src/storage/storage.ts
> +				// As well as the internal fields
Those fields are only required when performing create mutations. For update mutations, AppSync only requires `id` and `_version`

2021-01-06 19:18 UTC, iartemiev commented
@manueliglesias agreed re: tests. I don't think it'll be possible to validate the functionality all the way through via unit tests (will be adding an integration test for that) but should be able to at least test the relevant changes in storage.ts and mutation.ts.

Regarding required fields, AppSync does not expect them on an update. They're only required when creating a new record. WRT arrays/lists, this PR treats them the same way as we are now, i.e., sending the entire updated list as the value. Will be adding tests around these scenarios (:

2021-01-25 20:44 UTC, manueliglesias approved these changes
LGTM 👍 🎉 

Thanks @iartemiev , I just left a couple of questions

2021-01-25 20:44 UTC, manueliglesias commented on packages/datastore/__tests__/DataStore.ts
> +import FDBCursor from 'fake-indexeddb/build/FDBCursor';
I didn't see where this is being used

2021-01-25 20:44 UTC, manueliglesias commented on packages/datastore/__tests__/DataStore.ts
> +			expect(patches).toBeUndefined();
Why would we want `undefined` vs `[]`?

2021-01-25 20:44 UTC, manueliglesias commented on packages/datastore/src/datastore/datastore.ts
> +		) {
Is this block fixing a bug? (the new condition).

2021-01-25 20:44 UTC, manueliglesias commented on packages/datastore/src/storage/storage.ts
> +				const updatedFields = patches.map(patch => patch.path && patch.path[0]);
I see in [immer docs](https://immerjs.github.io/immer/docs/patches) that `path` is an array, why do we take just `[0]`? I am assuming that it is because we handle non-model fields separately, is this assumption correct?

Do we need something special here to handle setting non-model fields? (e.g. `myModel.someField.someOtherField`)

> The generated patches are similar (but not the same) to the RFC-6902 JSON patch standard, except that the path property is an array, rather than a string. This makes processing patches easier. If you want to normalize to the official specification, patch.path = patch.path.join("/") should do the trick

2021-01-25 21:16 UTC, iartemiev commented on packages/datastore/__tests__/DataStore.ts
> +import FDBCursor from 'fake-indexeddb/build/FDBCursor';
Good catch. I think VSC auto-imported that for me. Will delete

2021-01-25 21:19 UTC, iartemiev commented on packages/datastore/__tests__/DataStore.ts
> +			expect(patches).toBeUndefined();
Patches are set inside of `copyOf` so we should only expect a value for updates. For saves, it will be `undefined`.

2021-01-25 21:21 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +		) {
It's a bug that happened when running some of the tests I had added. It was breaking on the next line (532) when attempting to JSON parse an undefined value.

2021-01-25 21:56 UTC, iartemiev commented on packages/datastore/src/storage/storage.ts
> +				const updatedFields = patches.map(patch => patch.path && patch.path[0]);
Manuel and I synced on this offline. Basically, the path can contain either the field name `["someField"]` - for replace operations. Or for add/delete, it will be the field name and index, e.g., `["someField", 2]`. All we care about is the field name because we’re not actually applying the patches, but just using them to infer which fields were changed. Hence why we're grabbing the 0th element.

2021-01-25 23:54 UTC, merged