Added Accessibility Labels to UI components
aws-amplify/amplify-js pull request #7596
Opened 2021-01-21 08:57 UTC by mirgj

Fixes #7595

_Description of changes:_

Adding Accessibility Labels to the React Native components rendered by AmplifyUI.
This will allow to run automation test with Appium on Android

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-22 16:34 UTC, amhinson requested changes

2021-01-22 16:34 UTC, amhinson commented on packages/aws-amplify-react-native/src/AmplifyUI.tsx
> +	id?: string;
Since this is solely used for testing via the `testID` & `accessibilityLabel`, I'd prefer to leave this as `testID` just so there isn't any question as to what it is for.

2021-01-22 16:34 UTC, amhinson commented on packages/aws-amplify-react-native/src/AmplifyUI.tsx
> +	id?: string;
Same comment as above.

2021-01-22 16:34 UTC, amhinson commented on packages/aws-amplify-react-native/src/Utils/index.ts
> +		? { accessible: true, accessibilityLabel: id }
Is `accessible: true` needed? I haven't tested this on my own, but I don't see any references in the [documentation](https://reactnative.dev/docs/view#accessibilitylabel) about `accessibilityLabel` requiring `accessible` to be `true`. Another thing to note from the [documentation](https://reactnative.dev/docs/view#accessible) is that all touchable elements have `accessible` enabled by default.

2021-01-22 16:34 UTC, amhinson commented on packages/aws-amplify-react-native/src/Utils/index.ts
> +	return Platform.OS === 'android'
From my understanding, I don't think there would be anything wrong with adding both `accessibilityLabel` and `testID` to all platforms. For simplicity, can we just remove this additional logic here and use both properties?

2021-01-24 07:40 UTC, mirgj commented on packages/aws-amplify-react-native/src/Utils/index.ts
> +		? { accessible: true, accessibilityLabel: id }
`accessible: true` should be redundant I can remove that

2021-01-24 07:48 UTC, mirgj commented on packages/aws-amplify-react-native/src/Utils/index.ts
> +	return Platform.OS === 'android'
As I know there are issues on putting both properties together: https://stackoverflow.com/questions/64706072/how-to-set-the-testid-and-the-accessibilitylabel-together-with-react-native

Most of the reference I've read use that syntax to overcome this limitations

2021-01-25 19:08 UTC, amhinson commented on packages/aws-amplify-react-native/src/Utils/index.ts
> +	return Platform.OS === 'android'
Ah ok that makes sense. Thanks for the link!

2021-01-25 19:11 UTC, amhinson approved these changes
LGTM 👍

2021-01-25 19:58 UTC, merged