fix(@aws-amplify/amplify-ui-components): phone_number input issue in require-new-password
aws-amplify/amplify-js pull request #7802
Opened 2021-02-22 20:10 UTC by renegus

_Issue #, if available:_ Fixes #7175 

_Description of changes:_

This issue occurs when creating a new cognito user with temporary password and without a ```phoneNumber```. If ```phoneNumber``` is an required field, the ```amplify-require-new-password``` component will contain a ```dialCode``` dropdown and a ```phoneNumber``` input. Both the dropdown and input field overrides the required ```phone_number```field, and only way to proceed is to enter the entire ```dialCode + phoneNumber``` in the input field.

This issue was fixed using same helper functions ```handlePhoneNumberChange``` and ```composePhoneNumberInput``` as used in components (```sign-up```, ```sign-in```, ```forgot-password```, ```confirm-sign-up```)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-24 19:26 UTC, wlee221 requested changes
@renegus, thanks a ton for catching this! Just got a nit but this LGTM otherwise.

2021-03-24 19:26 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +      );
Can we move this to when `completeNewPassword` is called below so that this is not called on every input change?

2021-03-24 19:33 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx
> +      );
And can we add try catch around this, calling `dispatchToastHubEvent(error)` on error?

2021-05-06 22:48 UTC, wlee221 commented
Hi @renegus, just checking if you're able to work on this PR. I'll put this on auto-close after 2 weeks, but we can reopen or take this over as needed.

2021-06-22 22:12 UTC, eddiekeller commented
Closing this PR as the changes have been merged in here - https://github.com/aws-amplify/amplify-js/pull/8489

2021-06-22 22:12 UTC, closed without merging