Downsizing sample for some language in speech to text
aws-amplify/amplify-js pull request #7835
Opened 2021-02-28 22:15 UTC by SebSchwartz

_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/7808

_Description of changes:_

If language is one of (fr-FR, en-AU, en-GB and fr-CA), downsize the sample to 8kHz and change url to transcribe.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-03 04:21 UTC, wlee221 requested changes
@SebSchwartz, thanks a lot for this PR and even writing a missed unit test! Got one problem with downsampling that we want to address, but the rest LGTM 👍

2021-03-03 04:21 UTC, wlee221 commented on packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
> +				}
If we downsample buffer here, it will be downsampled again inside `sendDataToTranscribe` > [`sendEncodedDataToTranscribe`](https://github.com/aws-amplify/amplify-js/blob/35737d20f69ab7c0f11fdfe942623262448c75ba/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L298) to 16khz instead of 8khz. Let's make sure `downsampleBuffer` is called only once to the correct sample rate.

2021-03-03 04:21 UTC, wlee221 commented on packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
> +				}
One idea on top of my head is to pass `targetSampleRate` down to `sendEncodedDataToTranscribe`, but the implementation is up to you!

2021-03-03 04:21 UTC, wlee221 commented on packages/predictions/__tests__/Providers/AWSAIConvertPredictionsProvider-unit-test.ts
> +		test('Error languageCode not configured ', () => {
This is great, thanks!

2021-03-03 04:21 UTC, wlee221 commented on packages/predictions/__tests__/Providers/AWSAIConvertPredictionsProvider-unit-test.ts
> +			expect(downsampleBufferSpyon).toBeCalled();
As per discussion below, can we check if this has been called once, and with target sample rate 8000?

2021-03-24 22:46 UTC, SebSchwartz commented on packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
> +				}
Yes, you're right, I've adapted the code

2021-03-24 22:46 UTC, SebSchwartz commented on packages/predictions/__tests__/Providers/AWSAIConvertPredictionsProvider-unit-test.ts
> +			expect(downsampleBufferSpyon).toBeCalled();
Done.

2021-03-31 07:18 UTC, SebSchwartz commented
@wlee221 I've changed according to your comments ;)

2021-04-01 00:07 UTC, wlee221 approved these changes
This LGTM, thanks a lot for your contribution! Have you tried this change on your app?

2021-05-12 08:39 UTC, wlee221 commented
Since the fix is straightforward and unit test has been included, I'll go ahead and merge this. Will do simple manual testing after this hits unstable.

2021-05-12 18:17 UTC, merged