test(amazon-cognito-identity-js): add unit test coverage to Cognito Identity JS package
aws-amplify/amplify-js pull request #8134
Opened 2021-04-20 21:21 UTC by nickarocho

#### Description of changes

#### Issue #, if available

#### Checklist

- [ ] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-20 22:37 UTC, nickarocho reviewed
Just a preliminary once-over.

2021-04-20 22:37 UTC, nickarocho commented on packages/amazon-cognito-identity-js/src/CognitoUserSession.js
> +
Should remove this space.

2021-04-20 22:37 UTC, nickarocho commented on packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
> +
Should remove this space.

2021-04-20 22:37 UTC, nickarocho commented on packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
> +
This too.

2021-04-20 22:37 UTC, nickarocho commented on packages/amazon-cognito-identity-js/package.json
> +    "react-native": "^0.54.0",
Do we know if this will have any downstream effects from bumping this dep?

2021-04-20 22:37 UTC, nickarocho commented on packages/amazon-cognito-identity-js/package.json
> +    "test": "jest --config ./jest.config.js",
This is a much better convention, IMO. Makes it a lot easier to maintain granular testing config.

2021-04-21 17:00 UTC, sammartinez commented
Can we validate the 1 broken tests? Seems like CircleCI is yelling about it.

2021-04-21 19:32 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__mocks__/mocks.js
> +			});
Would you consider this more readable?
up for debate 😅 

```suggestion
			.mockImplementationOnce((...[,,callback]) => {
				callback(null, data);
			});
```

2021-04-21 19:33 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__mocks__/mocks.js
> +			});
Same as above

2021-04-21 19:37 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__mocks__/mocks.js
> +	}
You can use the `in` operator to make this check without getting all the properties and looking for one.

```suggestion
  if(!(fnName in AuthenticationHelper.prototype)) {
  		throw new Error(
			`${fnName} provided does not exist in Authentication Helper class`
		);
  }
```

2021-04-21 19:43 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__mocks__/mocks.js
> +	}
This might be more readable with a `switch` statement, and having the `mockImplementationOnce` just once

Something like:
```javascript
let implementation = () => {throw new Error('Invalid property')};

switch(fnName) {
  case genHashDevices:
    implementation = (...[,,callback]) => { callback(null, null) };
    break;
  case getSalt:
  case getVerifiers:
    implementation = (...[,,callback]) => 'deadbeef';
    break;
}


jest
	.spyOn(AuthenticationHelper.prototype, fnName)
	.mockImplementationOnce(implementation);
```

2021-04-21 19:44 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +import 'regenerator-runtime/runtime';
Why is this one needed?

2021-04-21 19:46 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
> +
Looks like this file didn't have changes, if so, let's take it out from the PR

2021-04-21 19:47 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +		expect(result).toBe(null);
What is this testing? Why is a `null` expected in this case?

2021-04-21 19:49 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +		expect(typeof instance.generateRandomString()).toEqual('string');
Should we also assert a length and not just the type of the return value?

2021-04-21 19:56 UTC, amhinson commented on packages/amazon-cognito-identity-js/__tests__/index.test.js
> +	});
Could we do something with a snapshot here to validate what is expected as well? Something similar to this: https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify/__tests__/exports-test.ts

2021-04-21 19:57 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +		expect(result).toMatchObject(new BigInteger());
See comment above about expecting a specific value and not just an assertion on the type. Also, `toMatchObject` is very permissive, we need to expect a specific value

2021-04-21 19:59 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +		expect(expected).toEqual(result);
Nice! yeah, this is what I mean above about asserting a value and not just the type

2021-04-21 20:02 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +	test('Ensure that hkdf algorithm returns a strong hex string', () => {
Let's reword this test's description, it is expecting the result to be an instance of `Buffer`, not verifying that it is *strong* or a hex string.

2021-04-21 20:05 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
> +		}).toThrowError();
Can we check on a specific message here?

2021-04-21 20:06 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
> +	test('Getting user context data without advancedSecurityData', () => {
can we add a test with advancedSecurityData?

2021-04-21 20:07 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
> +		//mockCallback.mock.calls[1][0]).toBe(1);
Remove this

2021-04-21 20:08 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js
> +	ivRefreshToken,
I am curious, what does `iv` stand for?

2021-04-21 20:09 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js
> +	});
Can you add a test for the valid case?

2021-04-21 20:10 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CookieStorage.test.js
> +	Object.defineProperty(window.document, 'cookie', { writable: true });
Can we instead use `jsdom` as environment?

https://jestjs.io/docs/configuration#testenvironment-string

2021-04-21 20:13 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/CookieStorage.test.js
> +			});
Can we check they are actually deleted and not only the return value?

2021-04-21 20:15 UTC, manueliglesias commented on packages/amazon-cognito-identity-js/__tests__/DateHelper.test.js
> +		expect(result.getNowString()).toContain(year);
Let's have this test look at the format of the full string, not just that it containes the year.

Maybe you can mock the Date fn to return fixed values and write the expect accordingly

2021-04-21 20:26 UTC, evcodes commented on packages/amazon-cognito-identity-js/__mocks__/mocks.js
> +			});
javascript is a strange, strange beast

2021-04-21 20:30 UTC, nickarocho commented on packages/amazon-cognito-identity-js/__tests__/index.test.js
> +	});
Fixed! https://github.com/aws-amplify/amplify-js/pull/8134/commits/48fbd3bcfc1662c598e5edb977169d0b0ab8b4be

2021-04-21 21:45 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/AuthenticationHelper.test.js
> +	test('Calculate A works successfully', async () => {
yeah I agree, after looking at this now, it's obvious that this should have been it's own suite with unit tests for each case

2021-04-22 16:51 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
> +	test('Getting user context data without advancedSecurityData', () => {
I did not know how to do this, here's what it said in the comments:

This method returns the encoded data string used for cognito advanced security feature.
	 * This would be generated only when developer has included the JS used for collecting the
	 * data on their client. Please refer to documentation to know more about using AdvancedSecurity
	 * features

2021-04-22 16:54 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js
> +	});
valid/invalid is just defined by the access and refresh tokens so either way it would work as expected but I changed it have tests for the valid sessions too.

2021-04-22 16:59 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CookieStorage.test.js
> +	Object.defineProperty(window.document, 'cookie', { writable: true });
cool!

2021-04-22 19:59 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/CognitoIdToken.test.js
> +		expect(typeof cognitoToken.jwtToken).toBe('string');
Nit: I think it's better to expect the actual value `''`. 
When checking `typeof` we don't know if maybe `testToken` actually got assigned to `jwtToken` somehow.

```suggestion
		expect(cognitoToken.jwtToken).toBe('');
```

2021-04-22 19:59 UTC, iartemiev commented on packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
> +
There are some minor formatting changes it looks like, e.g., https://github.com/aws-amplify/amplify-js/pull/8134/files#diff-4e7fc32caed143fe1cc3fd688b63f9b695af679bc065c5dd6210f9be984894e2L33-R34

Maybe we had never run Prettier on it before 🤷🏻‍♂️

2021-04-22 20:52 UTC, jamesaucode reviewed
Great work!! This is a huge test file

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +		netRequestMockSuccess(true);
Another nit: I wonder if it would be beneficial or a bit overkill if we can have a mock net request function that also takes an operation name? At least for this block it's not immediately clear that `netRequestMockSuccess` means 'mock a successful request once' or that `verifySoftwareToken` does 2 calls, if it's `netRequestMockSuccess(true, 'VerifySoftwareToken)` then `netRequestMockSuccess(true, 'RespondToAuthChallenge`) then it will be easier to understand

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	test('Error case for non-signed in user session', () => {
I think you might need to set `cognitoUser`'s session to an invalid one to test the non-signed in case here

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	test('signOut expected to set signinUserSession to equal null', () => {
I think we should check if the cached user is cleared too

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	test('when inputVerificationCode exists in the callback, call inputVerifier with the data', () => {
This doesn't match what it's doing in the test, I am guessing this is the failure case?

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +describe('MFA test suite', () => {
Should we just remove the 'sendMFAcode' test block you have in line 734? That one seems redundant, and this one is a lot more robust

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +describe('getCognitoUserSession()', () => {
I think this doesn't test the behavior of the function properly, `getCognitoUserSession(authResult)` uses the `authResult` to build the tokens and return them, instead of using the user's `signInUserSession`

2021-04-22 20:52 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	describe('getSession()', () => {
I think this will be better suited to be in a separate test block instead of nested in the `refreshSession` test block

2021-04-23 14:26 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +		const spyon3 = jest.spyOn(
fixed, I think he meant that to be generateHashDevice instead

2021-04-23 14:37 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +		netRequestMockSuccess(true);
I see your point, I propose to do something like this:

`export function netRequestMockSuccess(success, data = {}, operationName = '') {
	if (success) {
		jest
			.spyOn(Client.prototype, 'request')
			.mockImplementationOnce((...[operationName, , callback]) => {
				callback(null, data);
			});
	} else {
		jest
			.spyOn(Client.prototype, 'request')
			.mockImplementationOnce((...[, , callback]) => {
				callback(networkError, null);
			});
	}
}`
and inside the CognitoUser.test.js:
`	netRequestMockSuccess(true, {}, 'verifySoftwareToken');
	netRequestMockSuccess(true, {}, 'RespondToAuthChallenge');
`

I am not sure if you think that having this parameter is beneficial since we would have to explicitly provide an empty object for each time that we want to use the operation name, which is only helpful within the testing file. Open to other possible suggestions

2021-04-23 14:47 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	test('Error case for non-signed in user session', () => {
Sorry, this was meant to be `error case for signed in user session`

2021-04-23 15:04 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	test('signOut expected to set signinUserSession to equal null', () => {
agreed

2021-04-23 15:12 UTC, iartemiev requested changes
Just a couple minor changes requested to StorageHelper.test and StorageHelperRN.test

2021-04-23 15:12 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +		});
I think here we should first check that AsyncStorage and MemoryStorage are actually out of sync by attempting to get a value by one of those keys and `expect` it to be `undefined`. Then perform the sync and get it again, this time `expecting` it to equal the value.
```suggestion
		test('Happy case for syncing', () => {
			const items = {
				'@MemoryStorage:key': 'value1',
			};
			jest.mock('react-native', () => ({
				AsyncStorage: {
					setItem: jest.fn((item, value) => {
						return new Promise((resolve, reject) => {
							items[item] = value;
							resolve(value);
						});
					}),
					getAllKeys: jest.fn(callback => {
						callback(null, Object.keys(items));
					}),
					multiGet: jest.fn((keys, callback) => {
						const values = keys.map(key => [key, items[key] || null]);
						callback && callback(null, values);

						return values;
					}),
				},
			}));

			const StorageHelper = require('../src/StorageHelper-rn.js').default;
			const storageHelper = new StorageHelper();
			const callback = jest.fn();

			// MemoryStorage would then be out of sync with AsyncStorage
			expect(storageHelper.getStorage().getItem('key')).toBeUndefined();
			storageHelper.getStorage().sync(callback);
			expect(callback.mock.calls[0][1]).toEqual('SUCCESS');
			expect(storageHelper.getStorage().getItem('key')).toEqual('value1');
		});
```

2021-04-23 15:18 UTC, iartemiev requested changes
Re-structured one of my requested changes to make it easier to read

2021-04-23 15:18 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +			var items = { key: 'value1', key2: 'value2' };
Let's have `items` simulate the contents of AsyncStorage
```suggestion
			const items = {
				'@MemoryStorage:key': 'value1',
			};
```

2021-04-23 15:18 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +			expect(callback.mock.calls[0][1]).toEqual('SUCCESS');
I think here we should first check that AsyncStorage and MemoryStorage are actually out of sync by attempting to get a value by one of those keys and expect it to be undefined. Then perform the sync and get it again, this time expecting it to equal the value.
```suggestion
			// MemoryStorage would then be out of sync with AsyncStorage
			expect(storageHelper.getStorage().getItem('key')).toBeUndefined();
			storageHelper.getStorage().sync(callback);
			expect(callback.mock.calls[0][1]).toEqual('SUCCESS');
			expect(storageHelper.getStorage().getItem('key')).toEqual('value1');
```

2021-04-23 15:20 UTC, iartemiev commented
One more minor suggestion. Let's add:
```yaml
overrides:
  files: *.test.js
  rules: jest/valid-expect
```
Right above [this line ](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/.eslintrc.yaml#L9) to prevent ESLint from yelling at us in the test files

2021-04-23 16:06 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +describe('getCognitoUserSession()', () => {
you're right and I just changed it to pass in the session data

2021-04-23 16:14 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +	describe('getSession()', () => {
done :)

2021-04-23 16:30 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +			expect(callback.mock.calls[0][1]).toEqual('SUCCESS');
```
// MemoryStorage would then be out of sync with AsyncStorage
expect(storageHelper.getStorage().getItem('key')).toBeUndefined();
storageHelper.getStorage().setItem('key', 'value1');
storageHelper.getStorage().sync(callback);
expect(callback.mock.calls[0][1]).toEqual('SUCCESS');
expect(storageHelper.getStorage().getItem('key')).toEqual('value1');
```

2021-04-23 16:55 UTC, iartemiev requested changes

2021-04-23 16:55 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +			storageHelper.getStorage().setItem('key', 'value1');
Should be no need for this line. The `sync` should add it to MemoryStorage from AsyncStorage

2021-04-23 16:57 UTC, iartemiev commented on packages/amazon-cognito-identity-js/__tests__/StorageHelperRN.test.js
> +			storageHelper.getStorage().setItem('key', 'value1');
Otherwise, we don't know whether the `sync` method is actually working

2021-04-23 17:08 UTC, jamesaucode commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +		netRequestMockSuccess(true);
I can think of a few options.
1. Make the function take operation name as well in second parameter so it becomes `netRequestMockSuccess(true, { data: someData, operationName: 'verifySoftwareToken'})`
But then you will need to change all the other tests that calls this function :/
2. Make another function called `netRequestMockWithOperationName`
3. Add more comments to clarify that the function actually does 2 separate network calls, so 2 mocks are necessary (and that each netRequestMock call only mocks once)
Up for other suggestions!

2021-04-23 18:24 UTC, evcodes commented on packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
> +		netRequestMockSuccess(true);
I think I will go with the comments. Since they are mocking network calls, the details usually doesn't matter but sometimes we need to have some output with specific fields. That's why I added the optional data parameter

2021-04-23 19:21 UTC, iartemiev approved these changes
LGTM 🎉 Thank you guys, this is great!

2021-04-23 19:34 UTC, merged