fix: if not overridden, using formFields in amplify-confirm-sign-in fields (#8254)
aws-amplify/amplify-js pull request #8255
Opened 2021-05-11 14:22 UTC by dennybiasiolli

Close #8254

#### Description of changes
If not overridden, using formFields in amplify-confirm-sign-in fields

#### Issue #, if available
#8254

#### Description of how you validated changes
Waiting for your approval for the suggested changes.
Let me know if you need the same changes in other components.

#### Checklist
- [X] PR description included
- [X] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-12 06:43 UTC, dennybiasiolli commented
Updated adding a few more tests

2021-05-24 16:12 UTC, hkjpotato commented
@dennybiasiolli thank you for submitting the PR! Our team will review it asap. 

At this moment, I am checking the original issue #8254 to better understand the problem scope, and re-run your code fix to see if it introduces any unexpected side effects to the existing component/pattern.

2021-05-24 16:17 UTC, dennybiasiolli commented
Thank you @hkjpotato , I appreciate this, let me know if I have to change something

2021-05-24 22:54 UTC, wlee221 requested changes
Hi @dennybiasiolli, thank you a **lot** for this PR! This is one of the inconsistencies between our auth components that haven't been fixed. I just got some minor change requests, but the PR looks good otherwise.

2021-05-24 22:54 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +		if (formFields === undefined) return undefined;
Can we add `formFields.length > 0` check here? If so, we can return the default form field with just `code`.

2021-05-24 22:54 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
Looks like we are assuming all the other formField items to be of type `string` though it can be `object` too. Can we handle `object` case here, too? For example, it should be able to handle

```tsx
formFields={[
  {
    type: 'username',
    label: 'Custom Username',
    placeholder: 'Custom Username Placeholder',
  },
  {
    type: 'code',
    label: 'Custom Confirmation code',
    placeholder: 'Custom Confirmation Code',
  },
]}
```

2021-05-24 22:54 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts
> +		it('should have default formFields by default', () => {
Thanks a lot for this! We can always have more testing in our ui components :)

2021-05-24 23:15 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
On a second look, I see why you're implementing it this way. Looks like `confirm-sign-in` only expects `code` and does not have input change handlers for other inputs. (Which makes sense because you wouldn't expect other inputs on the `confirm-sign-in`). In that case, I'm fine with this code! Resolving, sorry about the confusion!

2021-05-25 06:47 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +		if (formFields === undefined) return undefined;
Yes no problem, we might need to set a `defaultFormFields` value because the `formFields` is a props, so the user can change it externally.
In case of `undefined` it keeps the default value, but in case of other values (passed by the user) it will be overridden by the user's value.

2021-05-25 07:03 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +		if (formFields === undefined) return undefined;
Here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/d7e06ae2dbca9c45b85c66160c22572f9e83c00e
😄

2021-05-25 07:04 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts
> +		it('should have default formFields by default', () => {
I like to test everything I could :)

2021-05-25 22:54 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +		if (formFields === undefined) return undefined;
ty!

2021-05-25 23:27 UTC, wlee221 requested changes
Following up from #8254. Thanks again for your responsiveness through the thread!

2021-05-25 23:27 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
To follow-up our discussion on https://github.com/aws-amplify/amplify-js/issues/8254#issuecomment-848320872, let's be more flexible in accepting different `formFields` here. The logic should look something like:

```tsx
if (content.type === 'code') {
  // This is a code input field. Attach input handler.
  content.push({
     ...formField, // `inputProps` will be passed over here.
      handleInputChange: event => this.handleCodeChange(event),
    });
} else {
  // This is either a `string`, and/or a custom field that isn't `code`. Pass this directly.
  content.push(formField);
}
```

2021-05-25 23:27 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
Technically, `formField` can be equal to string `"code"`, but I think it's safe to assume that `formField` will be an object here as per our official documentation / support.

2021-05-25 23:33 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +					<amplify-auth-fields formFields={this.constructFormFieldOptions(this.formFields)} />
Last nit, can we construct `formField` once so that this doesn't run on every render? `setup` would be a good place to do so!

2021-05-26 07:49 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
Ok perfect, I'm changing this using
```js
	if (typeof formField === 'string' || formField.type !== 'code') {
		// This is either a `string`, and/or a custom field that isn't `code`. Pass this directly.
		content.push(formField);
	} else {
		// This is a code input field. Attach input handler.
		content.push({
			...formField as FormFieldType, // `inputProps` will be passed over here.
			handleInputChange: event => this.handleCodeChange(event),
		});
	}
```
Notice I switched the `if` case, because of type checking by typescript, checking for formField.type directly could return errors in case of formField of type string

2021-05-26 08:02 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
Commit here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/f2346a1f3b49a4b75a866a1c7159d0b8735b19ba

2021-05-26 08:13 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +					<amplify-auth-fields formFields={this.constructFormFieldOptions(this.formFields)} />
With this solution the component is not working anymore. Even if I use a `v-if` clause with `:user.prop` passing

```js
      <amplify-confirm-sign-in
        v-if="authState === 'confirmSignIn' && user"
        slot="confirm-sign-in"
        header-text="Enter code from your Authenticator App"
        :form-fields.prop="formFields"
        :user.prop="user"
      />
```

2021-05-26 08:59 UTC, dennybiasiolli commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +					<amplify-auth-fields formFields={this.constructFormFieldOptions(this.formFields)} />
Commit here: https://github.com/aws-amplify/amplify-js/pull/8255/commits/370f60b887f21a67185deb78146c627d5d4e5f10

I've added a few tests for checking the calls

2021-05-26 09:04 UTC, dennybiasiolli commented
@wlee221 just a last note: please remember that when customizing the `amplify-confirm-sign-in` it's **mandatory** the `:user.prop` prop, otherwise the component will not work anymore.

Example:

```html
  <amplify-authenticator>
      <amplify-confirm-sign-in
        slot="confirm-sign-in"
        header-text="Enter code from your Authenticator App"
        :formFields.prop="formFields"
        :user.prop="user"
      />
  </amplify-authenticator>
```

and

```js
import { Auth } from 'aws-amplify';
import { onAuthUIStateChange } from '@aws-amplify/ui-components';

export default {
  data() {
    return {
      user: undefined,
      authState: undefined,
      formFields: [
        {
          type: 'code',
          required: true,
          inputProps: {
            type: 'text', // specify the actual html input type here
            inputmode: 'numeric',
            pattern: '[0-9]*',
            autocomplete: 'one-time-code',
            required: true,
          },
        },
      ],
    };
  },
  created() {
    this.unsubscribeAuth = onAuthUIStateChange((authState, authData) => {
      this.authState = authState;
      this.user = authData;
    });
  },
};
```

2021-05-26 22:40 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +			} else {
Yeah, I think that's okay. I can't think of a use case where we need to submit more than just the `code` to Cognito, so I assume users will provide their own handler for these edge cases. If needed, we can make that adjustment later.

2021-05-26 22:56 UTC, wlee221 requested changes
These LGTM! Thanks for all the test cases and quick feedback. You're right -- we need to supply `:user.prop` to get the slot working. I'll raise an issue on documentation for that.

The code changes look solid -- I just got a minor style nit but we should be good to merge very soon! Thanks again @dennybiasiolli.

2021-05-26 22:56 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +	 defaultFormFields: FormFieldTypes = [
Can we add `private` here and down on `constructedFormFieldOptions`? Just a nit for the style consistency 😄

2021-05-26 22:56 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +	 defaultFormFields: FormFieldTypes = [
```suggestion
	private defaultFormFields: FormFieldTypes = [
```

2021-05-26 22:56 UTC, wlee221 commented on packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx
> +	constructedFormFieldOptions: FormFieldTypes | string[];
```suggestion
	private constructedFormFieldOptions: FormFieldTypes | string[];
```

2021-05-27 07:08 UTC, dennybiasiolli commented
@wlee221 done! Changes are made and squashed in previous commits in order to keep commit history clean 😃

2021-05-27 16:58 UTC, wlee221 approved these changes
LGTM! Let's get this merged 😄

2021-05-27 17:22 UTC, merged

2021-06-08 11:36 UTC, dennybiasiolli commented
@wlee221 sorry for my question, is there a place where I can see when this PR goes to production? So I can update my dependencies.
At the moment I have
```
    "@aws-amplify/ui-components": "^1.3.2",
    "@aws-amplify/ui-vue": "^1.0.10",
```

Thanks!

2021-06-10 17:27 UTC, wlee221 commented
Hi, 

I believe on GitHub, you can `watch` our repository for releases:

<img width="342" alt="Screen Shot 2021-06-10 at 10 20 57 AM" src="https://user-images.githubusercontent.com/43682783/121569887-253ef780-c9d6-11eb-94fe-3d5ace2fa7f3.png">

That being said, we haven't released in a while and it's very likely we'll make a release by next week at latest. Until then please note that you can use `yarn add aws-amplify@unstable @aws-amplify/ui-vue@unstable` to unblock yourself.

2021-06-11 06:40 UTC, dennybiasiolli commented
Great, thanks!

2021-06-11 19:13 UTC, wlee221 commented
Ah nvm, it was just released yesterday!

2021-06-14 08:28 UTC, dennybiasiolli commented
Awesome, it works! Thanks again!

2021-06-23 08:33 UTC, hannesj commented
This change makes it impossible to override `handleInputChange`, which is still shown in the documentation [here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#confirm-sign-in). My use case is to use this component, together with a separate `handleSubmit`, in order to fire a `sendCustomChallengeAnswer`, rather than a `confirmSignIn`.

2021-06-23 08:40 UTC, dennybiasiolli commented
@hannesj I think you're right, to fix this it's possible to invert the order of these two lines: https://github.com/aws-amplify/amplify-js/pull/8255/files#diff-de87cdca396cebd58dbe51c8e8ca88fb89e7bf8b6b148d4f4395d98a8d5bf496R132-R133

Can you please open a new issue referring this PR? Then I can provide you a fix for that 😉

2021-06-23 09:49 UTC, dennybiasiolli commented
@hannesj PR here: https://github.com/aws-amplify/amplify-js/pull/8492