Device tracking
aws-amplify/amplify-js pull request #8353
Opened 2021-05-28 09:20 UTC by evcodes

Implementing device tracking for JavaScript to achieve parity across platforms. Native iOS and Android have had these features for some time and we aim to provide this to our customers.

#### Issue #, if available
#1355 

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-02 17:14 UTC, jamesaucode commented
Seems like it's not build because of a tslint rule, should we just turn off max line length for comments? 
```diff
diff --git a/packages/auth/tslint.json b/packages/auth/tslint.json
index 1bb9e144d..b1f7fcaed 100644
--- a/packages/auth/tslint.json
+++ b/packages/auth/tslint.json
@@ -5,7 +5,10 @@
        "jsRules": {},
        "rules": {
                "prefer-const": true,
-               "max-line-length": [true, 120],
+               "max-line-length": [true, {
+                       "limit": 120,
+                       "ignore-pattern": "// "
+               }],
                "no-empty-interface": true,
                "no-var-keyword": true,
                "object-literal-shorthand": true,
```
Or we can probably just disable the max length for the url at line 89

2021-06-03 15:40 UTC, sammartinez commented on packages/auth/src/Auth.ts
> +const maxDevices = 60;
Can we make this 
```suggestion
const MAX_DEVICES = 60;
```

2021-06-03 15:42 UTC, evcodes commented on packages/auth/src/Auth.ts
> +const maxDevices = 60;
done 👍🏼

2021-06-03 17:31 UTC, elorzafe requested changes
Thanks @evcodes ! I think this will be a great contribution.

However I have a few concerns related to API (naming and return values) and also you need to add tests for each method as well.

We can chat more offline.

Thanks!

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +// https://tinyurl.com/c2a9f4hz
I would use the official link instead
```suggestion
// https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListDevices.html#API_ListDevices_RequestSyntax
```

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			currUser.setDeviceStatusRemembered({ onSuccess: res, onFailure: rej });
I would check the error messages, and what information should be returned to the customer

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	public async rememberDevice(): Promise<any> {
Was an API review for the naming? I don't like the idea of return `any`

There are related issues for example if the customer is using a Storage mechanism that is not persisted, e.g. Memory storage in that case I think it should be fair to throw an error because it wouldn't work in practice

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +			currUser.forgetDevice({ onSuccess: res, onFailure: rej });
I would check the error message and what do we want to return to the customers

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	public async forgetDevice(): Promise<any> {
I am not sure about naming, IMO is related to Cognito more than the real action, which I think is not asking for MFA code right.

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +	public async fetchDevices(): Promise<any> {
We should define a type that has useful information (not just Cognito returned data)

2021-06-03 17:31 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +					rej(err);
Error message should be serialized to something useful for customer not just Cognito messaging.

2021-06-03 18:00 UTC, evcodes commented on packages/auth/src/Auth.ts
> +// https://tinyurl.com/c2a9f4hz
based on the tslinting rules, the link was too long, 120 characters

2021-06-07 19:11 UTC, hkjpotato commented on packages/auth/src/Auth.ts
> +// https://tinyurl.com/c2a9f4hz
could consider disable the linting by adding a comment
```
// tslint:disable-next-line:max-line-length
```

2021-06-07 20:58 UTC, hkjpotato commented on packages/auth/src/Auth.ts
> +					rej(err);
It seems a common pattern that we just [throw the raw error](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L696) from Cognito upwards, especially the error is from a direct api call.

We do throw [specific error message](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L702) if we know better about what the error is.

While we should make our errors more explicit, refactoring the pattern could be in another commit to reduce the scope.

2021-06-17 20:17 UTC, elorzafe requested changes
Few small changes, overall looks good!

2021-06-17 20:17 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +		callback.onSuccess('success');
I think this is the issue with `map` you were seeing before

2021-06-17 20:17 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +						obj.onSuccess({ Devices: [] });
I would add test that return some data, so can it can see if that is returned successfully on `Auth.fetchDevices`

2021-06-17 20:17 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +					const deviceList: AuthDevice[] = data.Devices.forEach(device => {
this should be `map` instead of `forEach`, because `forEach` doesnt return anything

2021-06-17 22:30 UTC, elorzafe requested changes
I've just figured out `IAuthDevice` is what Cognito is returning, that shouldn't be the case, we should keep consistency across platforms

2021-06-17 22:30 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			});
you need to validate here the response from `auth.fetchDevices()` if it matches

2021-06-17 22:30 UTC, elorzafe commented on packages/auth/src/types/Auth.ts
> +
This should be equivalent to iOS client to keep parity with them https://aws-amplify.github.io/amplify-ios/docs/Protocols/AuthDevice.html

2021-06-17 23:18 UTC, manueliglesias requested changes
Thanks @evcodes !

Just one change requested and it is good to go on my side

2021-06-17 23:18 UTC, manueliglesias commented on packages/auth/src/types/Auth.ts
>  }
This file is supposed to have TypeScript types only, this class should live somewhere else, or even better, not exist, as it is basically the same as `IAuthDevice`.

```typescript
// instead of:
new AuthDevice({
    DeviceKey: '',
    DeviceAttributes: [
      { Name: 'device_status', Value: 'valid'},
      { Name: 'device_name', Value: 'myDevice'},
      // ...
    ],
});

// do this on Auth.ts:
const deviceInfo: IAuthDevice = {
  id: props.DeviceKey,
  name: props.DeviceAttributes.find(({Name}) => Name === 'device_name').Value, 
};
```

2021-06-18 22:54 UTC, elorzafe approved these changes
This looks great @evcodes ! 🎉 

One minor comment related to error message to make it more clear.

We need to have integration in place before merging this

2021-06-18 22:54 UTC, elorzafe commented on packages/auth/src/common/AuthErrorStrings.ts
> +	DEVICE_CONFIG = 'Device tracking has not been properly configured in Cognito User Pools',
Maybe this is more clear 
```suggestion
	DEVICE_CONFIG = 'Device tracking has not been configured in this User Pool'
```

2021-06-18 22:58 UTC, elorzafe commented
You might also need to fix the issue with circleci

2021-06-23 19:21 UTC, elorzafe approved these changes
Lets merge this! 

Good job @evcodes ! 🌮 🎉 🥇

2021-06-23 20:20 UTC, sammartinez approved these changes
LGTM 🌮  And Approval due to the `angular-devkit/core` issue within the Bundle Size run

2021-06-23 20:32 UTC, manueliglesias approved these changes
LGTM 👍 

Thanks Eddy!

2021-06-23 21:00 UTC, merged