feat(storage): Adding copy API to Storage
aws-amplify/amplify-js pull request #8431
Opened 2021-06-10 21:23 UTC by jamesaucode

#### Description of changes
Adding `Storage.copy`, allowing users to copy files across levels or identity id (if file is in protected)

#### Issue #, if available
fixes #5998 

#### Description of how you validated changes
Added integration tests, unit tests and manually tested

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-16 22:13 UTC, elorzafe requested changes
Thanks @jamesaucode this looks great!

We can chat more offline to look on some cases

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/providers/AWSS3Provider.ts
> +				emitter.on(COPY_PROGRESS, progress => {
What is `emiter` sending on the callback? Like the shape of that data

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/providers/AWSS3ProviderMultipartCopy.ts
> +				const result = await this.s3client.send(copyObjectCommand);
Is this because it happen on the server side and not on the client, we can chat about this offline

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/types/AWSS3Provider.ts
> +interface S3ClientCopyCommandParams {
Sounds a little weird to add some of this, if it was a copy for example you wont need `contentEncoding` why would you like to change it?

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/types/AWSS3Provider.ts
> +	progressCallback?: (progress: CopyProgress) => any;
If is only 0/100 I dont see if we need this right now. We can add it later when it can show more significant data

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/types/Provider.ts
> +	copy?(src: StorageCopyTarget, dest: StorageCopyTarget, config?): Promise<any>;
Seems the target doesn't need the identityId, users can copy to its own prefix (identityId) or public. Not to others users, might be worth it have a different type for Destination without identityId. What do you think?

2021-06-16 22:13 UTC, elorzafe commented on packages/storage/src/types/Storage.ts
> +export type StorageCopyTarget = { key: string; [key: string]: any };
Shouldn't this have `level` and `identityId` for source?

2021-06-16 22:30 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3Provider.ts
> +			logger.warn(`IdentityId only works if level is protected, but level is set to ${srcLevel}`);
Will change the warning message here

2021-06-16 22:53 UTC, jamesaucode commented on packages/storage/src/types/AWSS3Provider.ts
> +interface S3ClientCopyCommandParams {
Will remove `contentEncoding`

2021-06-17 00:29 UTC, elorzafe approved these changes
LGTM 🎉 🌮 

Just confirm which metadata like contentEncoding, contentType, etc are copied from original file so they are not needed.

2021-06-17 00:29 UTC, elorzafe commented on packages/storage/src/common/StorageErrorStrings.ts
> +	NO_SRC_KEY = 'src should be an object with the property "key" with value of type string',
I would say `source param and destination param` instead of `src` or `dst`, `src` is only visible inside of the `copy` function

2021-06-17 17:57 UTC, amhinson approved these changes
Looking specifically at the CircleCI config, LGTM 👍

2021-06-17 19:11 UTC, merged