Switching Unauthenticated Users to Authenticated Users
aws-amplify/amplify-js pull request #8466
Opened 2021-06-17 17:39 UTC by hkjpotato

#### Description of changes
This is the initial draft PR for "Switching Unauthenticated Users to Authenticated Users" to gather comments. Its implementation has been verified by design review, and backend logic clarification.

Note:
- due to the fact that we cannot easily check if a sign in is from a first-time user (a first time user for identity pool, right after user pool sign up) or a returning user, we will always call `getCredentialsForIdentity` if cached guest id is found, in order to link it to the login.
  - for a first-time user, the provided guest id will become the primary id for the login, and thus fix the issue #2089
  - for a returning user, it will keep the previous primary id associated with the login
  - in both cases,  the guest id will be "linked" and disqualified as an unauth identity, thus right at that moment, we remove it from localStorage.
  - if guestId is not found (user has not try to obtain an unauth role before), then it remains the same as today's flow
- we no longer clean the guestId in signout, but do it at a better time: when we know it is disqualified and has to be removed.
  - this helps avoid guestId being [cleaned up too early](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L529).
  - I think it makes sense in terms of "Credentials.clear": cleaning credentials is to clean up the aws credentials (accessKey, secreteKey, sessonToken), not to mutate the status of an identity in the identity pool, but I am open to any suggestion.

To do: 
- gathering feedbacks and update the PR
- update integ tests

Lesson learned:
we rely on [aws-sdk-v3](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-cognito-identity) for interacting with identity pool. It exposes declarative api (e.g. `fromCognitoIdentityPool`) and imperative api (`getCommandId`).
- The declarative API will [cached](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-cognito-identity/src/fromCognitoIdentityPool.ts#L27) or [mutate](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-cognito-identity/src/fromCognitoIdentity.ts#L41) the network request/response.
- If we (Credentials) wants to handle the local cache and data processing ourself, we should favor the imperative api to keep single source of truth.

#### Issue #, if available
#2089

#### Description of how you validated changes
- yarn test
- postman (network api test)
- backend verification

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-17 17:52 UTC, eddiekeller commented on packages/core/src/Credentials.ts
> +		const identityId = this._identityId = await this._getGuestIdentity();
Can we toss this in a `try/catch` block? Else we risk this causing issues if an error occurs.

2021-06-18 18:27 UTC, reesscot requested changes
Looking great, just a few nits for extra clarity in debug statements

2021-06-18 18:27 UTC, reesscot commented on packages/core/src/Credentials.ts
> +			logger.debug('Failed to get the cached identityId', e);
nit: for extra clarity, this could say:
`logger.debug('Failed to get the cached guest identityId', e);`

2021-06-18 18:27 UTC, reesscot commented on packages/core/src/Credentials.ts
> +			logger.debug('Failed to cache identityId', e);
nit: for extra clarity, this could say:
`logger.debug('Failed to cache guest identityId', e);`

2021-06-18 18:31 UTC, reesscot commented
Also, this is the sample I created to test the guest->auth scenario:

https://github.com/aws-amplify/amplify-js-samples-staging/tree/master/samples/react/auth/guest-to-auth-user

2021-06-21 17:58 UTC, reesscot commented on packages/core/src/Credentials.ts
> +			// for a returning user, this will retrieve the previous identity assocaited with the logins
nit: spelling
```suggestion
			// for a returning user, this will retrieve the previous identity associated with the logins
```

2021-06-21 18:12 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +			// for a returning user, this will retrieve the previous identity assocaited with the logins
thanks for catching it! I wonder if I just commit it from the github UI

2021-06-21 18:15 UTC, reesscot commented on packages/core/src/Credentials.ts
> +			// for a returning user, this will retrieve the previous identity assocaited with the logins
I think you can do that, especially with a comment.

2021-06-21 19:13 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +			logger.debug('Failed to get the cached identityId', e);
I have update the according, but still see this "requested change"...should I just comment on this

2021-06-21 20:51 UTC, hkjpotato commented
> Looking great, just a few nits for extra clarity in debug statements

addressed, please re-review it :)

2021-06-21 21:31 UTC, reesscot approved these changes
LGTM 🚀

2021-06-22 17:41 UTC, elorzafe requested changes
Thanks @hkjpotato for this!

I think setting `guestIdentity` for every user is not necessary. Ping me offline if you need to discuss.

Thanks again!

2021-06-22 17:41 UTC, elorzafe commented on packages/core/src/Credentials.ts
> +			// if no guestIdentityId found, call getId with the logins
This comment is not necessary because it reads clear from the code

2021-06-22 17:41 UTC, elorzafe commented on packages/core/src/Credentials.ts
> +			// for a returning user, this will retrieve the previous identity associated with the logins
I would move this comment before calling `GetIdCommand`

2021-06-22 17:41 UTC, elorzafe commented on packages/core/src/Credentials.ts
> +				  IdentityId: guestIdentityId || generatedOrRetrievedIdentityId,
Why do you need to send `guestIdentityId` first and not `generatedOrRetrievedIdentityId`? I would do the opposite so you don't need to link `guestIdentityId` for that user

2021-06-22 17:41 UTC, elorzafe commented on packages/core/src/Credentials.ts
> +				logger.debug(`The guest identity ${guestIdentityId} has been successfully linked to the logins`);
I would add this message only on the following `if` statement

2021-06-22 18:02 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +				  IdentityId: guestIdentityId || generatedOrRetrievedIdentityId,
as discussed offline, this is due to the cognito implementation of these two api in the backend https://paste.amazon.com/show/kaijih/1623951826

the `getId` call will always return a brand new identity for a new customer. The brand new identity will be set as primary identity and cannot be changed.

2021-06-22 18:02 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +				  IdentityId: guestIdentityId || generatedOrRetrievedIdentityId,
> Why do you need to send `guestIdentityId` first and not `generatedOrRetrievedIdentityId`? I would do the opposite so you don't need to link `guestIdentityId` for that user

as discussed offline, this is due to the cognito implementation of these two api in the backend https://paste.amazon.com/show/kaijih/1623951826

the getId call will always return a brand new identity for a new customer. The brand new identity will be set as primary identity and cannot be changed.

2021-06-22 18:03 UTC, elorzafe commented on packages/core/src/Credentials.ts
> +				  IdentityId: guestIdentityId || generatedOrRetrievedIdentityId,
Thanks for the clarification @hkjpotato

2021-06-22 18:08 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +			// if no guestIdentityId found, call getId with the logins
Thanks and agree!, I wrote them down as instructions before writing the code, but should clean them up now since the good code should be self explained :)

2021-06-22 18:08 UTC, hkjpotato commented on packages/core/src/Credentials.ts
> +			// for a returning user, this will retrieve the previous identity associated with the logins
yep

2021-06-22 18:24 UTC, elorzafe approved these changes
Thanks @hkjpotato 🎉

2021-06-22 19:04 UTC, hkjpotato commented
> Thanks @hkjpotato for this!
> 
> I think setting `guestIdentity` for every user is not necessary. Ping me offline if you need to discuss.
> 
> Thanks again!

Thanks @elorzafe for looking to it. I have updated accordingly and verify this design with the cognito dev.

2021-06-23 21:19 UTC, merged