added alt prop and imgprops to s3 img component
aws-amplify/amplify-js pull request #8473
Opened 2021-06-18 22:06 UTC by jacoblogan

#### Description of changes
Updated S3Img to accept a string alt prop as well as imgProps object to pass through properties to the underlying img tag

#### Issue  S3Image attributes like ALT #6396

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-18 23:01 UTC, wlee221 requested changes
LGTM! I especially love the addition of `imgProps`, which alone will open up so many use cases including #6396. Just got two nits.

1. Have you run `yarn && yarn build` after making this changes? Two artifacts should be changed from this PR: `components.d.ts` and `amplify-s3-image/README.md`, but I only see the former.
2. see comment above

2021-06-18 23:09 UTC, jacoblogan commented on packages/amplify-ui-components/src/components/amplify-s3-image/amplify-s3-image.tsx
> +	@Prop() imgProps?: object;
yes, good catch. I'll make those changes

2021-06-21 16:23 UTC, wlee221 approved these changes
LGTM! Thanks @jacoblogan 👍

2021-06-21 16:52 UTC, merged

2021-06-23 14:54 UTC, iartemiev commented
@jacoblogan please use the Squash and Merge option when merging PRs and squash the title to a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary)