chore(@aws-amplify/aws-amplify-react-native): migrate to community Pi…
aws-amplify/amplify-js pull request #8520
Opened 2021-06-30 19:04 UTC by calebpollman

…cker component (#8493)

#### Description of changes

**This is a preliminary PR that will publish a tagged version of _aws-amplify-react-native_ for a customer to test against, once confirmed a PR against _main_ will follow**

- migrate deprecated React Native `Picker` component to [community version](https://github.com/react-native-picker/picker)
- update `Picker` style in Android `PhoneField` component to prevent truncation of rendered value
- add temporary `publish:migrate-rn-picker` script in _package.json_

#### Issue #, if available
https://github.com/aws-amplify/amplify-js/issues/8493

#### Description of how you validated changes
Manually tested on Android and iOS using both expo and vanilla React Native

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-30 19:13 UTC, elorzafe requested changes
You also need to add `migrate-rn-picker` in `release_branch` on `.circleci/config.yml` as well.

2021-06-30 19:13 UTC, elorzafe commented on packages/aws-amplify-react-native/package.json
> +		"react": "^17.0.1"
Why do you need react as peerDependency and not just devDependency?

2021-07-01 16:33 UTC, calebpollman commented on packages/aws-amplify-react-native/package.json
> +		"react": "^17.0.1"
Still working through the root cause of this, but the community version of the React Native `Picker` component crashes due to its usage of _react_ hooks (see below), which would make sense as _react_ hooks were introduced in version `16.8.0`, while we had version `16.0.0` listed as a devDependency prior to this PR. Upgrading the devDependency _react_ version in theory should fix this but the error persisted.

Since this package is not used for standalone development and is only used with React Native projects (which by default already contain _react_), added _react_ to the peerDependencies to warn consumers of the version needs as a workaround. This didn't feel **too** strange as we do not declare _react-native_ in the deps, devDeps, or peerDeps of this package.


That being said, do not feel strongly about this being the solution (and this may be just kicking the can to an extent without a root cause) and am definitely open to feedback :)

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in ForwardRef(PickerAndroid) (at Picker.js:174)
    in Picker
    in RCTView (at View.js:34)
    in View
    in RCTView (at View.js:34)
    in View
    in PhoneField
    in RCTView (at View.js:34)
    in View
    in RCTView (at View.js:34)
    in View (at ScrollView.js:1124)
    in RCTScrollView (at ScrollView.js:1260)
    in ScrollView (at ScrollView.js:1286)
    in ScrollView
    in TouchableWithoutFeedback
    in Wrapper
    in SignUp
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView)
    in Container
    in Authenticator
    in Wrapper (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

2021-07-06 21:16 UTC, elorzafe approved these changes
Thanks @calebpollman 🌮 

This looks good, lets merge it into migrate-rn-picker branch and test it more deeply

2021-07-06 23:40 UTC, merged