feat(@aws-amplify/auth): Add a 'SUCCESS' response on successful call to forgotPasswordSubmit
aws-amplify/amplify-js pull request #8744
Opened 2021-08-11 17:15 UTC by Khairo-kh

#### Description of changes

The function `forgotPasswordSubmit` does not return anything on successful password reset. This PR adds a 'SUCCESS' response when the password reset is successful. 
The `forgotPasswordSubmit` function is a part of the forgot password flow where users get a verification code (email or SMS ..) and provide that code along with the new password to the forgotPasswordSubmit function to reset the password.   

#### Issue #, if available

#8453 

#### Description of how you validated changes
- linked a test app with my local AmplifyJS project with yarn linking and verified that we get 'SUCCESS' response when successfully submitting the verification code and the new password.
- `yarn test` passes

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-11 23:45 UTC, evcodes requested changes
Hey Khairo, thank you for this!

We can also add this to the other methods that have onSuccess with no parameters. Note: you will have to change the files within Auth.ts as you have done for confirm password. That can be its own PR.

For me to approve this, I would like you to modify this [test](https://github.com/aws-amplify/amplify-js/blob/fc7f8ab6c965b980b87d9a0d47583672813162bf/packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js#L1169-L1173)  so that it checks for "SUCCESS"

Other than that, everything looks great!

2021-08-16 17:11 UTC, evcodes approved these changes
LGTM, thank you for this!

2021-08-17 00:07 UTC, Khairo-kh commented
@evcodes I added a 'SUCCESS' response to `verifyUserAttributes` method with this PR as it seems to be the only one left without a response in case of a successful call. Tests have been modified accordingly. Please let me know if any changes are needed.

2021-08-18 15:59 UTC, evcodes approved these changes
Thank you for these changes @Khairo-kh, @elorzafe  does this look good to merge?

2021-08-19 14:23 UTC, merged