Update .d.ts file to match the actual code
aws-amplify/amplify-js pull request #8825
Opened 2021-08-30 21:54 UTC by MatrixFrog

#### Description of changes

I noticed that a few places in packages/auth/src/Auth.ts are returning `CognitoUser | any` (which is equivalent to `any`) when they probably should return `CognitoUser`. When I changed them, I got several type errors, some of which were caused by the fact that the auth package was calling functions from the amazon-cognito-identity-js package _correctly_, but in a way that appeared _incorrect_ based on the types in the .d.ts file.

So, this changes the .d.ts file to match the code, which should then unblock the change from `CognitoUser | any` to `CognitoUser`
 
#### Description of how you validated changes

Tests pass. I'm not sure what other validation I should do.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-30 22:31 UTC, MatrixFrog commented on packages/amazon-cognito-identity-js/index.d.ts
> +			clientMetadata: any
I just put `any` here out of laziness, to be honest, but maybe someone can suggest a more specific type :)

2021-12-22 18:52 UTC, evcodes commented on packages/amazon-cognito-identity-js/index.d.ts
> +			clientMetadata: any
This works:
```suggestion
			clientMetadata?: ClientMetadata
```

2021-12-22 18:53 UTC, evcodes commented on packages/amazon-cognito-identity-js/index.d.ts
> +			clientMetadata: any
Same thing here:
```suggestion
			clientMetadata?: ClientMetadata
```

2021-12-22 18:53 UTC, evcodes commented on packages/amazon-cognito-identity-js/index.d.ts
> +			clientMetadata: any
```suggestion
			clientMetadata?: ClientMetadata
```

2021-12-22 18:54 UTC, evcodes requested changes
I added some comments. There is another PR that addressed one of your methods but the others are not handled yet so we can merge this once you get your changes across the line

2022-01-14 08:42 UTC, MatrixFrog commented
thanks, I think this should be good now :)

2022-10-18 17:09 UTC, haverchuck submitted a review, later dismissed

2022-10-18 17:18 UTC, AllanZhengYP submitted a review, later dismissed
Confirmed the d.ts change aligns with the JSDoc. Looks good to me!

2022-10-24 16:28 UTC, haverchuck approved these changes

2022-10-24 16:48 UTC, AllanZhengYP approved these changes

2022-10-24 17:08 UTC, merged