Storage category public API Typescript improvement
aws-amplify/amplify-js pull request #8832
Opened 2021-08-31 22:33 UTC by jamesaucode

#### Description of changes
This patch will introduce Typescript support for Storage.
instead of having `any` type config and `any` or `object` return types, all APIs will have proper types, including conditional return type on `get`.
Custom provider use case will still be supported.

Example of using the default provider:
```ts
// no changes, defaults to using our AWSS3Provider implementation
const res = await storage.get('key', { download: false }); // string

const res2 = await storage.get('key', { download: true }); // GetObjectCommandOutput

// Typescript or your editor's LSP will be able to show you warning for incorrect usage now
await storage.get('key', { invalidConfig: true }); // Error: Argument of 'invalidConfig' is not assignable ....
```

Example of using custom providers:
```ts
class CustomProvider implements StorageProvider {
  getProviderName() {
    return 'customProvider' as const
  }
  get(key: string, config: { foo: boolean; bar: number; }) {
    return 'get';
  }
  ...
}

storage.get<CustomProvider>('key', {
  provider: 'customProvider',
  foo: true,
  bar: 20,
});
```

List of changes:
- Enabled type checking on all unit tests in Storage, ts-jest **will fail** now if there are any typescript errors even in unit tests
  - Added some type practicing tests by calling apis with all available configs
- Rewrote some unit tests to remove any typescript compilation error
- `AWSS3Provider`'s `getProviderName` now returns `'AWSS3'` instead of `string`, which allows us to do conditional check like `ReturnType<Provider['getProviderName']> extends 'AWSS3' ? ... : ...`
- All main Storage APIs (get, put, remove, list, copy) will accept a `StorageProvider` as generic type, defaults to `AWSS3Provider`

#### Issue #, if available

#### Description of how you validated changes
Unit tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-01 19:00 UTC, jamesaucode commented on packages/storage/package.json
> +				"diagnostics": {
Enabling diagnostic so unit tests will also be type tested to ensure our Typescript types are not breaking in future iterations

2021-09-02 15:59 UTC, svidgen approved these changes
Neat stuff!

Not at all a blocker, but was this the feature we had discussed creating typed provider instances around?

2021-09-02 16:20 UTC, katiegoines approved these changes

2021-09-02 18:29 UTC, jamesaucode commented
> Neat stuff!
> 
> Not at all a blocker, but was this the feature we had discussed creating typed provider instances around?

Yes! But we are not doing typed provider instance yet to keep parity across categories

2021-09-07 17:18 UTC, petercwk approved these changes

2021-09-16 19:02 UTC, evcodes approved these changes
LGTM 👍🏼

2021-09-16 20:37 UTC, jamesaucode commented
Added some changes to make sure current custom provider calls still works

e.g
```ts
storage.get('key', {
  provider: 'myProvider',
  foo: true,
  bar: 20,
  prop1: 1,
  prop2: 2,
}); // config will allow anything here since provider is specified
```

if they want stricter type checking then they can pass their provider in the generic type argument
```ts
storage.get<MyProvider>('key', {
  provider: 'myProvider',
  foo: true,
  bar: 20,
});
```

2021-09-16 20:39 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3Provider.ts
> +	getProviderName(): 'AWSS3' {
stricten return type to 'AWSS3' so if we do conditional checks like `T extends { provider: 'AWSS3' } ? ... : ...`

2021-09-16 20:41 UTC, jamesaucode commented on packages/storage/__tests__/Storage-unit-test.ts
> +		test('get with custom provider should work with no generic type provided', async () => {
These tests are for backwards compatibility for custom provider users.
As long as the config has `provider: string`, it means they are using their custom provider, in that case we allow any shape for the config.
If they want better type checking then they can do `storage.get<MyProvider>(...)`

2021-09-16 20:43 UTC, jamesaucode commented on packages/storage/src/Storage.ts
> +		const provider = config?.provider || DEFAULT_PROVIDER;
Changed this from the original object deconstruction method because Typescript could not infer that `Storage<Operation>Config<T>` has `provider: string`

2021-09-16 22:50 UTC, elorzafe requested changes
Just have two comments, `copy` should be optional to not make it breaking change

Awesome work! @jamesaucode 🥇

2021-09-16 22:50 UTC, elorzafe commented on packages/storage/src/types/Provider.ts
> +	copy(src: StorageCopySource, dest: StorageCopyDestination, config?): Promise<any>;
Do we need to make this non optional? this would be a breaking change. I would make it optional as it was before, could be an issue?

2021-09-16 22:50 UTC, elorzafe commented on packages/storage/__tests__/Storage-unit-test.ts
> +class TestCustomProvider implements StorageProvider {
I would add a provider without `copy` to make it backwards compatible (currently is optional)

2021-09-16 23:51 UTC, jamesaucode commented on packages/storage/src/types/Provider.ts
> +	copy(src: StorageCopySource, dest: StorageCopyDestination, config?): Promise<any>;
reverted the change, it's back to being optional!

2021-09-16 23:53 UTC, jamesaucode commented on packages/storage/__tests__/Storage-unit-test.ts
> +class TestCustomProvider implements StorageProvider {
good point. I removed the `copy` function  from this class and moved it to another.

2021-09-17 02:45 UTC, elorzafe approved these changes
Great work @jamesaucode 🎉 🌮 🏅

2021-09-20 21:27 UTC, manueliglesias approved these changes
LGTM 🎉

2021-09-21 23:43 UTC, merged