(cognito) callback error with error objects
aws-amplify/amplify-js pull request #8923
Opened 2021-09-20 15:04 UTC by naseemkullah

fixes https://github.com/aws-amplify/amplify-js/issues/8919

cc @chrisbonifacio

2021-09-20 21:37 UTC, ashika01 commented on packages/amazon-cognito-identity-js/src/Client.js
> -					return callback(error);
this return is missed. Could you add that in? also what happened to the error object here? Am I missing something?

2021-09-20 21:41 UTC, naseemkullah commented on packages/amazon-cognito-identity-js/src/Client.js
> -					return callback(error);
the  `else if` just above checks to see if it is an `instaceof Error` which means it is already an error object 👍 
in this case we only need to add the `code` property and then it can be returned which is done below (fallback)

2021-09-23 13:54 UTC, naseemkullah commented
friendly ping

2021-09-23 14:13 UTC, evcodes commented
Hey @naseemkullah, thanks for your contribution! You help make Amplify better!

After pulling in your PR, I found that many of the client tests are now not passing. To merge this into main we would need to update those tests. I wrote the tests so if you need help with Jest please do not hesitate to reach out.

2021-09-23 14:13 UTC, evcodes requested changes
Update amazon-cognito-identity-js Client unit tests

2021-09-23 14:18 UTC, naseemkullah commented
Hey @evcodes my pleasure!

> After pulling in your PR, I found that many of the client tests are now not passing. To merge this into main we would need to update those tests. I wrote the tests so if you need help with Jest please do not hesitate to reach out.

Ah I was under the impression that  the following meant that unit tests pass, but i will try locally, thanks!
![image](https://user-images.githubusercontent.com/24660299/134524238-9b097af6-d8eb-4b3a-8afa-d01a5660e822.png)

2021-09-23 14:19 UTC, evcodes commented
> Hey @evcodes my pleasure!
> 
> > After pulling in your PR, I found that many of the client tests are now not passing. To merge this into main we would need to update those tests. I wrote the tests so if you need help with Jest please do not hesitate to reach out.
> 
> Ah I was under the impression that the following meant that unit tests pass, but i will try locally, thanks!
> ![image](https://user-images.githubusercontent.com/24660299/134524238-9b097af6-d8eb-4b3a-8afa-d01a5660e822.png)

You're right, I noticed that the lines that were missing coverage were the last 10 lines of Client.js which means that these changes do not introduce new test cases - I am going to go ahead and merge this in.

2021-09-23 14:20 UTC, evcodes approved these changes
LGTM - looking into token revocation changes and unit tests for that.

2021-09-23 14:20 UTC, merged