feat(@aws-amplify/datastore): lazy loading Has_Many implementation
aws-amplify/amplify-js pull request #9121
Opened 2021-10-27 17:31 UTC by ArkamJ

#### Description of changes
LazyLoading HasMany case implementation using AsyncCollection class.  Unit tests included.

#### Issue #, if available

#### Description of how you validated changes
IndexedDB unit tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-01 19:21 UTC, iartemiev requested changes

2021-11-01 19:23 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +						);
Weird formatting in the diff... Here're just the 2 relevant lines:
```ts
const relatedModel: PersistentModelConstructor<typeof relatedModelName> = getModelConstructorByModelName(

c[associatedWith].eq(this.id)
```

2021-11-01 19:46 UTC, svidgen requested changes

2021-11-01 19:46 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +		const max = arg && arg.hasOwnProperty('max') ? arg.max : this.values.length;
Let's make this typed, please:

```suggestion
	async toArray({max = Number.MAX_SAFE_INTEGER}: {max?: number} = {}): Promise<T[]> {
```

2021-11-01 20:02 UTC, ArkamJ commented on packages/datastore/src/datastore/datastore.ts
> +						);
Ohh got it. Added that in

2021-11-01 20:03 UTC, ArkamJ commented on packages/datastore/src/datastore/datastore.ts
> +		const max = arg && arg.hasOwnProperty('max') ? arg.max : this.values.length;
Got it!

2021-11-03 18:26 UTC, svidgen requested changes
Sorry! One more little blocker -- I'm sorry I missed this last couple times I looked at this.

2021-11-03 18:26 UTC, svidgen commented on packages/datastore/__tests__/indexeddb.test.ts
> +	test('AsyncCollection toArray test', async () => {
I missed this the first time through these tests, but when we're using `.then()`, we need to make sure jest waits for test completion. It's safest IMO to use call pass `done` into the test body and `done()` explicitly when the test is all wrapped up. I actually struggled with this in some of my tests and found it to be the safest, most clear way to do it.

However you want to handle it though, let's make sure tests with `.then()` have some way of making sure jest waits for test completion. It might be simplest to test only a single `.then()` to ensure we have a promise, but to pretty much use `await` everywhere else.

2021-11-03 22:30 UTC, svidgen requested changes

2021-11-03 22:30 UTC, svidgen commented on packages/datastore/__tests__/indexeddb.test.ts
> +			done();
Sorry. I misread the snippet you shared internally. This doesn't quite solve the problem. I'll try to find time to sync up tomorrow with you.

2021-11-03 22:39 UTC, svidgen requested changes

2021-11-03 22:39 UTC, svidgen commented on packages/datastore/__tests__/indexeddb.test.ts
> +			done();
If you want to revise in the interim, the problem is the same here. A call to `.then()` puts work "off to the side" and execution continues to the next line immediately. That means `done()` is called and the test function both return before any of the promises callbacks are made. If one of those fails, it'll likely happen outside the scope of the test. Jest will probably complain about it if they fail, but I don't think it'll record it as an actual test failure.

It may be best to separate out all of these options scenarios anyway. Look into possibly using `test.each` or dynamically creating the tests. (Unless there's opposition to that idea -- though I did it for predicates and everyone seemed OK with it!) Then you'll only have a single `.then()` to worry about, and you can just `done()` _inside_ of that.

```
songs.toArray(options).then(value => {
  expect(value).toStrictEqual(expectedValues);
  done();
});
```

2021-11-05 20:00 UTC, svidgen approved these changes
No blockers that I can see!

2021-11-05 20:00 UTC, svidgen commented on packages/datastore/__tests__/indexeddb.test.ts
> +				}
Nit: This is kind of a convoluted way to get at `exectedValues`, IMO. But, it works!

2021-11-08 22:28 UTC, iartemiev approved these changes
LGTM! 👍🏻  Thanks Arkam!

2021-11-08 23:02 UTC, merged