ObserveQuery performance and type enhancements
aws-amplify/amplify-js pull request #9141
Opened 2021-11-01 23:04 UTC by nickarocho

#### Description of changes

- constrains ObserveQuery options with an explicit, unique Type
- adds a time interval/limit Promise race to return data when Model datasets are very large (i.e. have lots of fields in the Schema)

I'll be re-working the sample app/integ tests to utilize this data set to account for worst-case scenarios

#### Issue #, if available

#### Description of how you validated changes
`yarn test`, manual testing - adding integ test and reworking sample app next

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-02 21:10 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +					if (!raceInFlight) racePromises();
Why not just return all the results from the local store right away?

2021-11-02 21:15 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +					await Promise.race([timerPromise, limitPromise]);
I know this already works as expected, but I think technically, we would want `limitPromise.promise` here, i.e. the promise itself not just the object that contains that promise as one of its properties

2021-11-02 21:17 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +			let timerPromise: Promise<any>;
currently, this is `Promise<string>` but since we don't use the resolved value anywhere, we can change line 1250 to `resolve()` and make this `Promise<void>`

2021-11-02 21:30 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +			function LimitPromise(): void {
Lets rename this to something more generic and move it to util. Can be e.g. `DeferredPromise`, `OpenPromise`, etc.

2021-11-03 16:35 UTC, nickarocho reviewed
Thanks for the feedback, Ivan! Helpful and thorough as always. I've made some adjustments if you want to give it another look.

2021-11-03 16:35 UTC, nickarocho commented on packages/datastore/src/datastore/datastore.ts
> +					if (!raceInFlight) racePromises();
Yup, another good call.

2021-11-03 16:35 UTC, nickarocho commented on packages/datastore/src/datastore/datastore.ts
> +					await Promise.race([timerPromise, limitPromise]);
True, kind of interesting how the `Promise.race` worked with just the object and not the promise itself 🤷🏻‍♂️

2021-11-04 14:23 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +						if (!raceInFlight) racePromises();
Trending towards spaghetti, IMO. And I don't see any unit test changes to accompany the change in behavior. Is there an opportunity to factor out some of the time-limited-snapshot mechanism (_buffer_?) into its own little testable class? (`MessageBuffer`? `SubscriptionBuffer`?) I could see that exercise simplifying both the buffering logic and the `observeQuery` method. (I could also see it being a fool's errand!)

What do you think? Opportunity or fool's errand?

2021-11-04 14:25 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +						if (!raceInFlight) racePromises();
This comment is intended to apply generally to the buffering mechanism, not just these LOC, FWIW! I just didn't want to select every line in the diff to make this comment!

2021-11-09 03:07 UTC, jamesaucode commented on packages/datastore/src/util.ts
> +	private timer: NodeJS.Timer;
It feels weird to have a `NodeJS` type here. Do you think it's better to use `ReturnType<typeof setTimeout>` instead? 😄 This way we can just let Typescript infer the type for us.
```suggestion
	private timer: ReturnType<typeof setTimeout>;
```

2021-11-09 16:52 UTC, iartemiev requested changes
Looks good! Just some minor changes requested

2021-11-09 16:52 UTC, iartemiev commented on packages/datastore/src/util.ts
> +}
We can re-write this into a class like this:

```suggestion
class DeferredPromise {
	public promise: Promise<void>;
	public resolve: () => void;
	public reject: () => void;

	constructor() {
		const self = this;
		this.promise = new Promise((resolve, reject) => {
			self.resolve = resolve;
			self.reject = reject;
		});
	}
}
```

2021-11-09 16:52 UTC, iartemiev commented on packages/datastore/__tests__/utils.test.ts
> +			expect(spyOnRace).toBeCalledTimes(1);
We should expect `bufferCallback` to be called as well

2021-11-09 16:52 UTC, iartemiev commented on packages/datastore/__tests__/utils.test.ts
> +
I think it would be nice if we could test both happy paths, i.e. "limit wins" as well as "timer wins". We can discuss how to accomplish that

2021-11-09 16:52 UTC, iartemiev commented on packages/datastore/src/util.ts
> +		this.TIMER_INTERVAL = options.maxInterval;
Same issue as we were seeing previously with the errorHandler. `options.maxInterval` will always overwrite `TIMER_INTERVAL` here. If we want it to default to 2000, we'd want to do:
```suggestion
		this.timerInterval = options.maxInterval || 2000;
```
Also, no need to make that property all caps, since it's configurable

2021-11-09 21:44 UTC, nickarocho commented on packages/datastore/__tests__/utils.test.ts
> +
Thank you for helping me think about this and implement paths for each!

2021-11-10 13:26 UTC, iartemiev approved these changes
LGTM! 🌮

2021-11-10 17:27 UTC, svidgen reviewed
Not blocking. But a few things to consider.

2021-11-10 17:27 UTC, svidgen commented on packages/datastore/src/util.ts
> +export class SubscriptionBuffer {
At a glance, this looks like it successfully extracts your limits race into something testable. That's a win in my book!

That said, this didn't end up being a _buffer_, really. If we care about naming, I think we need another one for this class. If I'm thinking about how we might re-use this elsewhere, I think sticking with some "racing" or "time limiting" terminology is more appropriate. IMO, it's more of a `TimeLimitForPromise` or `PromiseTimeLimit` &mdash; _or something like that_.

2021-11-10 17:27 UTC, svidgen commented on packages/datastore/src/util.ts
> +	public resolveBasePromise(): void {
There's no other resolve-oriented method on this. We could probably shorten this to `resolve`.

2021-11-10 17:27 UTC, svidgen commented on packages/datastore/src/util.ts
> +				resolve('TIMER');
If invoking code is expected to use this, I'd strongly suggest using an exported `const` or `enum`.

2021-11-10 17:27 UTC, svidgen commented on packages/datastore/src/util.ts
> +		this.limitPromise.resolve('LIMIT');
Ditto `const`/`enum` comment.

2021-11-10 19:56 UTC, nickarocho commented on packages/datastore/src/util.ts
> +export class SubscriptionBuffer {
Renamed to `DeferredCallbackResolver` via @iartemiev 's input.

2021-11-11 15:18 UTC, svidgen approved these changes

2021-11-11 17:36 UTC, merged

2021-11-17 11:16 UTC, OskarD commented
My generated models stopped working after upgrading to this version in aws-amplify.

When I tried to query the model, I got this error: `DataStore - The model is not an instance of a PersistentModelConstructor`

I also got this error everywhere in my application:
```
Call Stack
DataStore.<anonymous>
file:///Users/oskar/code/minna/minna-webapp/node_modules/aws-amplify/node_modules/@aws-amplify/datastore/lib/datastore/datastore.js (589:86)
step
file:///Users/oskar/code/minna/minna-webapp/node_modules/aws-amplify/node_modules/@aws-amplify/datastore/lib/datastore/datastore.js (44:23)
Object.next
file:///Users/oskar/code/minna/minna-webapp/node_modules/aws-amplify/node_modules/@aws-amplify/datastore/lib/datastore/datastore.js (25:53)
fulfilled
file:///Users/oskar/code/minna/minna-webapp/node_modules/aws-amplify/node_modules/@aws-amplify/datastore/lib/datastore/datastore.js (16:58)
```

Downgrading to `aws-amplify@4.3.5` and `@aws-amplify/datastore@352` fixed this problem

2021-11-17 13:54 UTC, iartemiev commented
@OskarD if you have **both** `aws-amplify` and `@aws-amplify/datastore` installed, that's likely what is causing the issue. Installing `aws-amplify` includes all of the packages already, so if you also install them individually, that can cause unexpected behavior. Please uninstall `@aws-amplify/datastore` and do a fresh install of your dependencies
```
npm uninstall @aws-amplify/datastore
rm -rf node_modules package-lock.json
npm install
```
If you're still getting the error after that, please open a new GitHub issue, so that we can track it and work on a fix.

2021-11-17 15:44 UTC, OskarD commented
Thanks, it seems to be working.

I have just followed AWS guides, how do I know which `@aws-amplify/X` to require and which are included? For instance, `@aws-amplify/ui-components` and `@aws-amplify/ui-react` both need to be required in order to use their exports, right? Or is there a better way to do it?