feat(in-app-messaging): refactor useInAppMessageStyle to useMessageProps
aws-amplify/amplify-js pull request #9155
Opened 2021-11-03 20:57 UTC by calebpollman

#### Description of changes

Refactor In-App Messaging util hooks and simplify usage in UI components, and clean up style merging. 

> This PR looks larger than it is, it mostly just restructures and abstracts existing code

**hook updates**
- refactor `useInAppMessageStyle` to `useMessageProps`
- add explicit style generation utils for usage in `useMessageProps`
- expose button related booleans via `useMessageProps`
- move calls to `useOnMessageDisplay` to `useMessageProps`
- replace `useInAppMessageImage` with `useMessageImage`, move usage to `useMessageProps`
- update non-banner message base image dimension
- abstract `getImageDimensions` util from `useInAppMessageImage`

**component updates**
- align component structure and styling interfaces between `BannerMessage` and `FullScreenMessage`
- update default UI component styling from static stylesheets to `getStyles` functions

#### Issue #, if available

NA

#### Description of how you validated changes
Manually tested in sample app

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-04 06:14 UTC, cshfang requested changes
Think there was a bug that needs to be addressed. Otherwise, even though I think it's become a bit of a puzzle with all the hooks to trace, it lgtm overall.

2021-11-04 06:14 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> +	const flattenedOverrideStyles = StyleSheet.flatten(baseOverrideContainerStyle);
Should flattening `baseOverrideContainerStyle` turn it plural?

2021-11-04 06:14 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/constants.ts
>  export const BLACK = '#000';
Nit: Consider "grouping" these with a `COLOR_` prefix

2021-11-04 06:14 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/FullScreenMessage.tsx
> +						{renderSecondaryButton && (
Think this might be a copy/paste bug
```suggestion
						{renderPrimaryButton && (
```

2021-11-04 06:14 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/FullScreenMessage.tsx
> +				{renderButtons && (
Nit: Fwiw, I actually feel like `hasButtons`, `hasPrimaryButton` was marginally more self-expressive as to "why" it should be rendered

2021-11-04 19:32 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/constants.ts
>  export const BLACK = '#000';
Sure, had been considering it

2021-11-04 20:42 UTC, nickarocho reviewed
A few nit/naming comments & clarification questions, nothing really blocking.

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
> +	const imageFetching = hasImage && !hasSetDimensions;
Nit: could there be a better name for this? The tense of an active verb feels a bit awkward and it's not super clear what hangs on this condition at first glance.

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
> +			prefetchNetworkImage(src).then((loadingState) => {
Should `loadingState` be of Type `ImageLoadingState`?

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +			return 'loaded';
Nit: it might be worthwhile to put these values (`'loaded'`, `'failed'`, etc.) into a default utility object so we don't need to hard-code the string value so often. I doubt these values will change so might not be worth the lift, but just saw these values referenced multiple times which triggered a smell.

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +	const isLandscape = imageWidth > imageHeight;
Might be overkill, but this looks like it could be its own mini util function like `getAspectRatio` which returns a value of `square`, `portrait` or `landscape`. Then you could use a `switch` statement evaluating each case instead of the multiple `if`'s below. Not a blocker, just an observation.

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/useMessageProps.ts
> +	const renderMessage = !imageFetching;
Related to my previous comment, this is a good example of `imageFetching` being a confusing name, especially when used as `!imageFetching`.

2021-11-04 20:42 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/utils.ts
> +const LINE_HEIGHT_MULTIPLIER = 1.5;
Newb question: is there a `config` object that RN users have access to modify constants like this? Wondering if this should live some place where this can be adjusted if desired.

2021-11-04 21:14 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/styles.ts
> +			flexDirection: 'row',
React Native flex direction defaults to `column`

2021-11-04 21:18 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
> +			prefetchNetworkImage(src).then((loadingState) => {
It's inferred as the return type of `prefetchNetworkImage`

2021-11-04 21:21 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +			return 'loaded';
TS will auto suggest the values of `ImageLoadingState` which imo will keep things in line

2021-11-04 21:23 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +	const isLandscape = imageWidth > imageHeight;
Chose not use a switch statement to avoid having an awkward `default`  case, but can update of you feel strongly

2021-11-04 21:26 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/utils.ts
> +const LINE_HEIGHT_MULTIPLIER = 1.5;
Good question, there is not a `config` object. In the future if we really want to make this configurable we would probably be deriving the `lineHeight` from a theme, which would still most likely be multiplying the theme `fontSize` by `1.5`

2021-11-04 22:06 UTC, nickarocho approved these changes
LGTM! 👌🏼

2021-11-04 22:06 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/styles.ts
> +			flexDirection: 'row',
Got it! makes sense actually being mobile-first

2021-11-04 22:06 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +	const isLandscape = imageWidth > imageHeight;
I'm impartial to the switch, was just wondering if you think we could use this functionality elsewhere - in which case it might be good as a tiny util function. I think it's fine as is :)

2021-11-04 22:06 UTC, nickarocho commented on packages/aws-amplify-react-native/src/InAppMessaging/components/utils.ts
> +const LINE_HEIGHT_MULTIPLIER = 1.5;
Yeah that would be ideal but definitely out of scope of this PR. Will keep in mind for the future.

2021-11-04 22:10 UTC, cshfang approved these changes
Minor comment but lgtm

2021-11-04 22:10 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/useMessageProps.ts
> +	useEffect(() => {
I think un-nesting this from another hook was a good call 👍

2021-11-04 22:10 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
>  	const renderImage = hasImage && hasSetDimensions;
Nit: Consider changing this to `shouldRenderImage` or `hasPrefetchedImage` or something since `render___` kind of reads like a function name

2021-11-04 22:18 UTC, cshfang approved these changes

2021-11-04 22:42 UTC, reesscot approved these changes
LGTM

2021-11-04 22:42 UTC, reesscot commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/BannerMessage.tsx
> +		[position]
should positionStyle also be in the array, or does it not change?

2021-11-04 22:42 UTC, reesscot commented on packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/FullScreenMessage.tsx
> +		useMessageProps(props, getStyles);
Nice and clean 💯

2021-11-04 22:53 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/BannerMessage.tsx
> +		[position]
Valid question, `positionStyle` is declared outside the scope of the component so it can be omitted from the dependency array

2021-11-05 00:04 UTC, elorzafe approved these changes
LGTM @calebpollman 🌮 

Just a couple of questions

2021-11-05 00:08 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts
> +export const getImageDimensions = (
It will, this was a product decision. Ideally the user would follow the image guidelines in the preview console

2021-11-05 00:09 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/useMessageProps.ts
> +	const shouldRenderMessage = !isImageFetching;
If the image fetching fails `isImageFetching` will resolve to `false` and unblock the message rendering 😄

2021-11-05 00:43 UTC, merged