Improve list of Cognito authentication error messages and provide additional typing information
aws-amplify/amplify-js pull request #9167
Opened 2021-11-05 16:08 UTC by joelzwarrington

#### Description of changes

Updating the AuthErrorString enum to include errors which I've found that are not documented, and providing better descriptions of the enum values so that as a developer I can decode which errors to implement

Closes #9104

#### Description of how you validated changes

I got the error messages by manually performing Cognito authentication flows and catching errors, so this isn't an exhaustive list but an improvement to what I've found.

#### Checklist

- [ ] Gather list of error messages provided by Cognito during various authentication flows 

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2021-11-05 16:27 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_IS_ALREADY_CONFIRMED = 'User is already confirmed.'
I have seen both of these errors, I don't know where I saw them but added them both here for now

2021-11-05 17:01 UTC, joelzwarrington commented
@elorzafe I've only added a few of the messages I've found but wanted to get opinions on the changes so far

2021-11-11 09:59 UTC, joelzwarrington commented
@sammartinez / @elorzafe any chance I could get feedback on these changes or the approach I've taken here?

2021-11-11 16:01 UTC, sammartinez commented
> @sammartinez / @elorzafe any chance I could get feedback on these changes or the approach I've taken here?

Apologizes on getting back now on this! Let's see if we can get you some feedback on this :) Thanks for contributing!

2021-11-11 16:56 UTC, sammartinez requested changes
Some callouts here, please look to update thanks!

2021-11-11 16:56 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
Lets look to update the string to the following
```suggestion
	USER_DOES_NOT_EXIST = 'Username and/or password is incorrect.',
```

2021-11-11 16:56 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	INVALID_EMAIL_CONFIRMATION_CODE = 'Invalid code provided, please request a code again.',
```suggestion
	INVALID_EMAIL_CONFIRMATION_CODE = 'Invalid code provided, please request a new code and try again.',
```

2021-11-11 16:56 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	INVALID_MFA_CODE = 'Invalid code received for user',
```suggestion
	INVALID_MFA_CODE = 'Invalid code received for user.',
```

2021-11-11 16:56 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User cannot be confirmed. Current status is CONFIRMED',
```suggestion
	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User cannot be confirmed. Current status is Confirmed',
```

2021-11-11 16:56 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	 * @see `AuthErrorStrings.USER_DOES_NOT_EXIST` will occur if username does not exist
```suggestion
	 * @see `AuthErrorStrings.USER_DOES_NOT_EXIST` will occur if username and/or password is incorrect
```

2021-11-11 17:22 UTC, sammartinez commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User cannot be confirmed. Current status is CONFIRMED',
Actually, this could be the following

```suggestion
	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User is already confirmed.',
```

2021-11-15 19:22 UTC, joelzwarrington commented
@sammartinez I'm not sure the updates you're suggesting make sense to me. These are error messages provided directly from Cognito, and ones I've faced myself. This ENUM isn't made to be user facing and is intended to provide a way to map to translations.

So one would use this like:

```javascript
import { AuthErrorStrings } from "@aws-amplify/auth";
// ... other code here
catch(error) {
  const message = error?.message;

  switch(message) {
    case AuthErrorStrings.USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED: {
       return "This is my own translation for the error user cannot be confirmed, or if I had i18n I could use it here";
    }
  }
  return "Unknown error hit, call support!";
}
```

2021-11-17 23:20 UTC, sammartinez commented
> @sammartinez I'm not sure the updates you're suggesting make sense to me. These are error messages provided directly from Cognito, and ones I've faced myself. This ENUM isn't made to be user facing and is intended to provide a way to map to translations.
> 
> So one would use this like:
> 
> ```js
> import { AuthErrorStrings } from "@aws-amplify/auth";
> // ... other code here
> catch(error) {
>   const message = error?.message;
> 
>   switch(message) {
>     case AuthErrorStrings.USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED: {
>        return "This is my own translation for the error user cannot be confirmed, or if I had i18n I could use it here";
>     }
>   }
>   return "Unknown error hit, call support!";
> }
> ```

Fair callout, while the ENUMs would not be adjusted, I wanted to make sure we had best practices in mind related to threats. So making these strings somewhat more generic to not cause someone looking to DDos if they find `User doesnt exist`

2021-11-19 16:57 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	INVALID_MFA_CODE = 'Invalid code received for user',
Marking as resolved.

I don't think this should be updated based on this comment: https://github.com/aws-amplify/amplify-js/pull/9167#issuecomment-969239965

Let me know if you think differently!

2021-11-19 16:57 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	INVALID_EMAIL_CONFIRMATION_CODE = 'Invalid code provided, please request a code again.',
Marking as resolved.

I don't think this should be updated based on this comment: #9167 (comment)

Let me know if you think differently!

2021-11-19 16:57 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User cannot be confirmed. Current status is CONFIRMED',
Marking as resolved.

I don't think this should be updated based on this comment: #9167 (comment)

Let me know if you think differently!

2021-11-19 16:57 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
Marking as resolved.

I don't think this should be updated based on this comment: #9167 (comment)

Let me know if you think differently!

2021-11-24 00:25 UTC, joelzwarrington commented
@siegerts can I please get feedback/review on this PR or the general direction to solve the root problem?

2021-11-24 18:07 UTC, sammartinez commented
> @siegerts can I please get feedback/review on this PR or the general direction to solve the root problem?

Hey @joelzwarrington, since my above callout sir, we are really looking to make the adjustments that I called out prior for us merging it. We want to make sure we are following best practices for our security posture, hence the reason for the updates to the strings I called out. If you are able to make those adjustments, we can move forward with merging this pull request in.

2021-11-25 16:27 UTC, joelzwarrington commented
> > @siegerts can I please get feedback/review on this PR or the general direction to solve the root problem?
> 
> Hey @joelzwarrington, since my above callout sir, we are really looking to make the adjustments that I called out prior for us merging it. We want to make sure we are following best practices for our security posture, hence the reason for the updates to the strings I called out. If you are able to make those adjustments, we can move forward with merging this pull request in.

@sammartinez, I'm still a bit confused how these would be security concerns, it'd be up to the developer implementing Cognito to provide their own error messages if not using the built in UI provided.

Am I missing something? Does jumping on a call to discuss make sense, I'm available if needed

2021-11-29 19:04 UTC, sammartinez commented
> > > @siegerts can I please get feedback/review on this PR or the general direction to solve the root problem?
> > 
> > 
> > Hey @joelzwarrington, since my above callout sir, we are really looking to make the adjustments that I called out prior for us merging it. We want to make sure we are following best practices for our security posture, hence the reason for the updates to the strings I called out. If you are able to make those adjustments, we can move forward with merging this pull request in.
> 
> @sammartinez, I'm still a bit confused how these would be security concerns, it'd be up to the developer implementing Cognito to provide their own error messages if not using the built in UI provided.
> 
> Am I missing something? Does jumping on a call to discuss make sense, I'm available if needed

Hey @joelzwarrington, apologizes, wasn't around for the holiday week. More than happy to hop on a call with you. Are you on our [Discord](https://discord.com/invite/amplify)?

2021-11-29 21:28 UTC, elorzafe reviewed
Thanks for this @joelzwarrington !

I have a question, why `The user attempts to confirm their email a second time, when it's already confirmed` is duplicated.

In order to use these error messages it will be required to make some changes on `Auth.ts` and `Errors.ts` are you open to those as well?

Thanks again!

2021-11-29 21:32 UTC, joelzwarrington commented
> Hey @joelzwarrington, apologizes, wasn't around for the holiday week. More than happy to hop on a call with you. Are you on our [Discord](https://discord.com/invite/amplify)?

@sammartinez I have not joined the discord and will look into that, and maybe look to send you a message on their once I have some time to chat.



> Thanks for this @joelzwarrington !
> 
> I have a question, why `The user attempts to confirm their email a second time, when it's already confirmed` is duplicated.
> 
> In order to use these error messages it will be required to make some changes on `Auth.ts` and `Errors.ts` are you open to those as well?
> 
> Thanks again!

Thanks @elorzafe, can validate to remove the duplicated error, I can look into `Auth.ts` and `Errors.ts` but how I intend to use them wouldn't need these changes. Since I'm importing them like this:

```typescript
import { AuthErrorStrings } from "@aws-amplify/auth";
```

As I'm not using the built-in Amplify UI and building from scratch.

2021-12-03 20:20 UTC, evcodes commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
this could be vulnerable to a [user enumeration attack](https://www.rapid7.com/blog/post/2017/06/15/about-user-enumeration/)

2021-12-06 16:19 UTC, evcodes commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
This error message leaves Amplify Auth vulnerable to an enumeration attack and I am in agreement with @sammartinez. This error message is leaking information to malicious users who may want to enumerate all possible active emails. 

The error message should be 'idempotent' such that a bad actor would not be able to distinguish between a non-existent account and incorrect username/password combination.

2021-12-06 16:23 UTC, evcodes commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
```suggestion
	USER_DOES_NOT_EXIST = 'Username and/or password is incorrect.',
```

2021-12-07 18:06 UTC, evcodes commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_CANNOT_BE_CONFIRMED_IS_ALREADY_CONFIRMED = 'User cannot be confirmed. Current status is CONFIRMED',
Is this redundant? Lines 68-73 seem to be doing the same thing...

```suggestion

```

2021-12-07 19:26 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
@evcodes i'm still in disagreement, this is the exact error provided by Cognito, and is something that should instead be fixed upstream in Cognito. These errors are simply a mapping of the EXACT error provided by Cognito so that they can be translated.

2021-12-07 19:26 UTC, joelzwarrington commented on packages/auth/src/common/AuthErrorStrings.ts
> +	USER_DOES_NOT_EXIST = 'User does not exist.',
![image](https://user-images.githubusercontent.com/80279872/145093333-11d0c584-a03e-49bb-b141-a7be7c89a028.png)

2021-12-09 23:23 UTC, joelzwarrington commented
I'm gonna close this PR as I don't believe the intention is getting across - I'm going to use these enums in my own project for purposes of translations and if there are any questions, feel free to mention me with @

2021-12-09 23:23 UTC, closed without merging

2021-12-09 23:26 UTC, sammartinez commented
@joelzwarrington Apologizes on the confusion, did you ever get setup via Discord? Can look to hop on a call and discuss there

2022-02-23 10:11 UTC, tesladodger commented
Hi @joelzwarrington, were you able to expand this list, or find a full list of Cognito error messages?
I'm also trying to translate them.

2022-02-23 21:06 UTC, joelzwarrington commented
hey @tesladodger, I haven't expanded this list _yet_, but seeing as you're the second person to ask, I might look into building that out!

2022-02-23 21:47 UTC, tesladodger commented
@joelzwarrington I have gathered few myself, so I can help with that.
Would be nice if Cognito provided a more robust solution, though. If the messages change a bit there go my translations...

2022-10-19 10:49 UTC, PhillipFraThailand commented
If it helps anyone, the error: `UserMigration failed with error Bad password.` can happen when you are signed-in, but calls the signIn method again, with wrong credentials.