feat(amplify-js): add CD support
aws-amplify/amplify-js pull request #9171
Opened 2021-11-05 21:28 UTC by david-mcafee

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-05 21:33 UTC, david-mcafee commented
Will add unit tests prior to merging this PR

2021-11-09 13:06 UTC, iartemiev commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	'^https://\\w{26}.appsync-api.\\w{2}(?:(?:-\\w{2,})+)-\\d.amazonaws.com/graphql$';
This pattern is not precise as defined. I can insert any character in place of the periods (`.`) and still get it to match. We should escape it -> `\.`. This is [called out](https://lgtm.com/projects/g/aws-amplify/amplify-js/rev/pr-8560610adab5295d45c45daa006d5278cf7389ec) by LGTM as well.

For example, the following value will return a successful match, even though it's clearly incorrect (`+` instead of `.`):
`https://xxxxxxxxxxxxxxxxxxxxxxxxxx+appsync-api+us-east-2+amazonawsscom/graphql`

Overall, I think we should use a regular expression literal here (see suggested change), instead of a string pattern. Alternatively, we can construct a RegExp object by passing it the string pattern.

```suggestion
	/^https:\/\/\w{26}\.appsync-api\.\w{2}(?:(?:-\w{2,})+)-\d\.amazonaws.com\/graphql/
```

2021-11-09 13:32 UTC, iartemiev requested changes

2021-11-09 17:14 UTC, david-mcafee commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	'^https://\\w{26}.appsync-api.\\w{2}(?:(?:-\\w{2,})+)-\\d.amazonaws.com/graphql$';
Thanks Ivan, this is a great catch :)

2021-11-09 17:19 UTC, david-mcafee commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	isCustomDomain(url: string): boolean {
Agree with you on this. Updated!

2021-11-09 18:33 UTC, iartemiev approved these changes
LGTM! 🎉

2021-11-09 21:38 UTC, david-mcafee commented
Will remove formatting of `Credentials.ts`

2021-11-11 00:27 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +					let discoverableEndpoint: string = appSyncGraphqlEndpoint
We don't have to do the replace in case `isCustomDomain`. If a customer have a custom domain that has `appsync-api` on it it will change unnecessarily.

2021-11-11 15:23 UTC, iartemiev commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +					let discoverableEndpoint: string = appSyncGraphqlEndpoint
Good catch

2021-11-11 17:14 UTC, sammartinez commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +const standardDomainPattern = /^https:\/\/\w{26}\.appsync\-api\.\w{2}(?:(?:\-\w{2,})+)\-\d\.amazonaws.com\/graphql$/i;
Does this work in al browsers we support?

2021-11-11 17:18 UTC, david-mcafee commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +					let discoverableEndpoint: string = appSyncGraphqlEndpoint
Will update this, great catch!!

2021-11-11 17:41 UTC, elorzafe approved these changes
LGTM! good work @david-mcafee 🌮 🏅

2021-11-11 17:53 UTC, iartemiev commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +const standardDomainPattern = /^https:\/\/\w{26}\.appsync\-api\.\w{2}(?:(?:\-\w{2,})+)\-\d\.amazonaws.com\/graphql$/i;
No reason why it wouldn't. Legacy browser support is spotty for lookaheads and lookbehinds, but this pattern is using neither of those

2021-11-11 17:58 UTC, iartemiev commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +const standardDomainPattern = /^https:\/\/\w{26}\.appsync\-api\.\w{2}(?:(?:\-\w{2,})+)\-\d\.amazonaws.com\/graphql$/i;
No reason why it wouldn't. Legacy browser support is spotty for lookaheads and lookbehinds, but this pattern is using neither of those

2021-11-11 19:47 UTC, merged