fix(@aws-amplify/api): Improve API.graphql return type
aws-amplify/amplify-js pull request #9197
Opened 2021-11-11 02:06 UTC by jamesaucode

#### Description of changes
- Improve the return type signature of `API.graphql`
- Migrated JSDoc to using proper Typescript types

Example:
```ts
const res = await API.graphql({ query: 'query' }); // GraphQLResult<any>
const res2 = await API.graphql<MyType>({ query: 'query' }); // GraphQLResult<MyType>
const res3 = API.graphql({ query: 'query', subscription: true }); // Observable<GraphQLResult<any>>
const res4 = API.graphql<MyType>({ query: 'query', subscription: true }); // Observable<GraphQLResult<MyType>>
```
#### Issue #, if available
#4257
#6369 

#### Description of how you validated changes

#### Checklist
- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-11 17:33 UTC, svidgen commented
I realize this is still in draft, but I saw this on the list and I didn't want to forget to add Ivan and Manuel to the reviewers list. :)

2021-12-29 22:47 UTC, jiahao-c commented
Hi @jamesaucode , looking forward to this being merged and released:) Would really improve the developer experience of amplify api.

2022-01-21 18:28 UTC, ashika01 commented on packages/api/__tests__/API-test.ts
> +		expect(await api.graphql({ query: 'query' })).toBe('grapqhqlResponse');
why is this changed? also shouldn't null work too here? Else it would be breaking right?

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +	get(apiName: string, path: string, init: Record<string, any>): Promise<any> {
Would just an index signature be enough in this case than a `Record`?

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +	post(apiName: string, path: string, init: Record<string, any>): Promise<any> {
same as above

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +	put(apiName: string, path: string, init: Record<string, any>): Promise<any> {
same as above

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +		init: Record<string, any>
same

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +	del(apiName: string, path: string, init: Record<string, any>): Promise<any> {
same

2022-01-21 18:28 UTC, ashika01 commented on packages/api/src/API.ts
> +	isCancel(error: any): boolean {
Curious, whats stopping us from using `Error` object?

2022-01-21 18:38 UTC, ashika01 commented on packages/api/src/API.ts
> +	head(apiName: string, path: string, init: Record<string, any>): Promise<any> {
same

2022-01-21 20:18 UTC, ashika01 commented on packages/api/src/API.ts
> +	): Promise<GraphQLResult<T>> | Observable<GraphQLResult<T>> {
hmm.. I would like someone from datastore to step in here. So you are implying if its GQL Query then the output will have to be a Promise with GQL Result right? Or am i missing something?

2022-01-27 17:32 UTC, jamesaucode commented on packages/api/src/API.ts
> +	): Promise<GraphQLResult<T>> | Observable<GraphQLResult<T>> {
Yea basically, a GQL Query gives a Promise, a GQL Subscription gives an Observable. I had a discussion with @iartemiev and @manueliglesias , they can probably chime in here.

2022-01-27 17:38 UTC, jamesaucode commented on packages/api/__tests__/API-test.ts
> +		expect(await api.graphql({ query: 'query' })).toBe('grapqhqlResponse');
It shouldn't have been allowed in the first place if we look at the function signature: https://github.com/aws-amplify/amplify-js/blob/d9dfff3eef7e5909f76fdea6054f8c02eb7ac8a2/packages/api/src/API.ts#L183-L196

We don't do type checks in our unit test so the tests were not failing, but ideally it should align with the actual implementation.

2022-01-27 18:02 UTC, jamesaucode commented on packages/api/src/API.ts
> +	isCancel(error: any): boolean {
This is essentially `axios.isCancel()` and it takes `any`.

2022-01-27 23:51 UTC, ashika01 commented on packages/api/__tests__/API-test.ts
> +		expect(await api.graphql({ query: 'query' })).toBe('grapqhqlResponse');
oh interesting... I see. then shouldn't sending in null have caused some sort of error?

2022-02-03 18:45 UTC, nfcsportal commented
olk;o;o

2022-02-11 00:37 UTC, ashika01 commented on packages/api/__tests__/API-test.ts
> +		expect(await api.graphql({ query: 'query' })).toBe('grapqhqlResponse');
Discussed offline - I would like for us to start doing these null checks for defensive code. James did point out we dont do this in other place and we have TS check and docs in place. Since it is a nit I m good 👍

2022-02-11 00:38 UTC, ashika01 approved these changes

2022-02-23 18:16 UTC, iartemiev requested changes
Requested a minor change to retain full backward compatibility. Otherwise, PR LGTM. Thanks, James!

2022-02-23 18:16 UTC, iartemiev commented on packages/api/src/API.ts
> +		: Observable<GraphQLResult<T>>;
I think we should default the return type to the same one we have now for backward compatibility when type when `T` is neither `GraphQLQuery<T>` nor `GraphQLSubscription<T>`. 

```suggestion
	): T extends GraphQLQuery<T>
		? Promise<GraphQLResult<T>>
		: T extends GraphQLSubscription <T>
    ? Observable<GraphQLResult<T>>
    : Promise<GraphQLResult> | Observable<object>;
```

2022-02-23 19:21 UTC, iartemiev approved these changes
LGTM 🎉

2022-02-23 19:53 UTC, manueliglesias approved these changes
LGTM 👍

2022-02-24 18:24 UTC, merged

2022-04-25 18:08 UTC, ashika01 commented
it should be in `aws-amplify/@latest`? do u need a specific version when this got rolled out?

2022-04-25 22:41 UTC, naingaungphyo commented
@ashika01 I installed the latest version and it works well. Sorry for late feedback.

2022-09-14 06:25 UTC, jdanielsyeah commented
I can't get this to work. I'm using `"aws-amplify": "^4.3.28",`

```js
import { GraphQLSubscription } from "@aws-amplify/api/lib/types"; // I've attempted to type this manually, since VS Code/intellisense didn't pick it up.
// import API and other code omitted for brevity

const subscription = API.graphql<GraphQLSubscription<Card>>(
      graphqlOperation(subscriptions.onUpdateCard)
    ).subscribe({ // Property 'subscribe' does not exist on type 'Promise<GraphQLResult<any>> | Observable<object>'.
  Property 'subscribe' does not exist on type 'Promise<GraphQLResult<any>>'.ts(2339)
      next: ({ provider, value }) => console.log({ provider, value }),
      error: (error) => console.warn(error),
    });
```

Can someone please show us how this is supposed to work?

2022-09-26 02:39 UTC, TimothyBritt commented
Hello, I spent the better part of an afternoon scratching my head around this issue, and I have to agree — the issue is both frustrating and confusing. However, I have found a workaround that is not throwing type errors locally, but is far from ideal:

```typescript
import { Observable } from 'zen-observable-ts';
import { Amplify, Auth, API, graphqlOperation } from 'aws-amplify';
import { GraphQLSubscription } from '@aws-amplify/api/lib/types';
import * as APIt from './API'; // API types generated by amplify codegen

function App() {
//...
     useEffect(() => {
          const subscription = API.graphql<GraphQLSubscription<APIt.Channel>>(
              graphqlOperation(subscriptions.subscribeToChannel)
          ) as Observable<unknown>;
  
          subscription.subscribe({
              next: ({ provider, value }) => {
                  setReceived(value.data.subscribeToChannel.data);
              },
              error: (error) => console.warn(error),
          });
      }, [channel]);
//...
}
```

Casting the result of `API.graphql(graphQlOperation(...))` to `Observable<unknown>` allows the passing of the `{provider, value}` object to the `next` function on the subscription (Which, consequently is of type `Observable<T>` from `zen-observable`).

A better way to extend this workaround would be to figure out exactly what the expected type is that is passed to `Observable<T>` and replace `Observable<unknown>` with that type.