fix(@aws-amplify/storage): throw error if all upload parts complete but upload cannot be finished
aws-amplify/amplify-js pull request #9317
Opened 2021-12-06 09:56 UTC by katiegoines

#### Description of changes

Added error thrown when multi-part upload cannot be finalized. 

#### Issue #, if available

Issue #8781 

#### Description of how you validated changes
Tested in sample app for multi-part upload (both resumable and non-resumable) 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-06 22:38 UTC, jamesaucode requested changes
Left a few comments, let me know if you any questions 😄

2021-12-06 22:38 UTC, jamesaucode commented on packages/storage/__tests__/providers/AWSS3ProviderManagedUpload-unit-test.ts
> +		expect(Promise.reject(new Error('error'))).rejects.toThrow('error');
Why did we remove this block of code ? Also I think if you reject with an error with the message 'error' the assertion here is always true.

2021-12-06 22:38 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
> +					await this.checkIfUploadCancelled(uploadId);
Do we still need to have these calls to `this.checkIfUploadCancelled`? We can probably just move the logic of that function into the `catch` block below.

2021-12-06 22:38 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
> +			throw error.message;
```suggestion
			throw error;
```

I think we should throw the error as is. correct me if im wrong but I believe there will be no stack trace if you throw a string

2022-02-03 14:03 UTC, Legionses commented
@katiegoines @jamesaucode Hello, guys! Can u complete this fix please?  Seems like error in Storage.put of multipart file is a big issue tat needed to be fixed.

2022-02-09 15:10 UTC, katiegoines commented
@jamesaucode - Having trouble with the `cleanup`. Once the upload is aborted, there is no longer an upload to find with ListParts, which is at odds with the `'error case: upload a string as body that splits in two parts but second part fails'` test. Your guidance would be greatly appreciated. Thank you!

2022-02-09 22:55 UTC, jamesaucode requested changes
Thanks for the PR 😃  just a few more changes

2022-02-09 22:55 UTC, jamesaucode commented on packages/storage/__tests__/providers/AWSS3ProviderManagedUpload-unit-test.ts
> +		}
For this part, we don't need to change this to a `try/catch` block, we want to assert that the error thrown is an `Error` with `expect(...).rejects.toThrowError(...)`

2022-02-09 22:55 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
> +			// if any error is thrown, call cleanup
I believe with your new implementation, `this.cancel` is no longer needed. It used to act as a signal for the main `this.upload` function to do a cleanup, now instead we can just have the `catch` block do the cleanup.

2022-02-09 22:55 UTC, jamesaucode commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
> +				'Error happened while uploading a part. Cancelling the multipart upload',
I think we should remove the `this.cancelUpload()` function call here, and also throw an error.

2022-02-09 23:05 UTC, jamesaucode commented
> @jamesaucode - Having trouble with the `cleanup`. Once the upload is aborted, there is no longer an upload to find with ListParts, which is at odds with the `'error case: upload a string as body that splits in two parts but second part fails'` test. Your guidance would be greatly appreciated. Thank you!



> @jamesaucode - Having trouble with the `cleanup`. Once the upload is aborted, there is no longer an upload to find with ListParts, which is at odds with the `'error case: upload a string as body that splits in two parts but second part fails'` test. Your guidance would be greatly appreciated. Thank you!

I think the problem is 
1. We should throw an error in `.uploadParts` as well
2. In the test file, change line 309 so `UploadPartsCommand` resolves instead of rejecting with an error.
Happy to sync with you offline if you need more information.

2022-05-12 23:29 UTC, jamesaucode approved these changes
LGTM! 🎉

2022-05-16 17:52 UTC, stocaaro commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
>  	private cancel = false;
Looks like this variable isn't used anymore, right?

2022-05-16 18:00 UTC, stocaaro approved these changes

2022-05-16 18:01 UTC, katiegoines commented on packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
>  	private cancel = false;
Correct. Thank you for catching!

2022-05-16 18:10 UTC, merged