feat(@aws-amplify/auth): Delete user API exposed
aws-amplify/amplify-js pull request #9428
Opened 2022-01-04 19:48 UTC by evcodes

#### Description of changes

#### Description of how you validated changes
This PR is in draft however, I will be writing unit and e2e tests for this feature. I will manually test within react native as well.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [in progress] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [in progress] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-04 20:20 UTC, elorzafe requested changes
Thanks @evcodes !

I would check `deleteUser` for HostedUI use case and I would add `dispatchAuthEvent` as well.

2022-01-04 20:20 UTC, elorzafe commented on packages/core/src/I18n/I18n.ts
> +		if (val != null) {
I would make this into a separate PR

2022-01-04 20:20 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +									logger.debug(result);
I am not sure about the implications when delete a user after sign in with HostedUI, can you check that behavior?

I think you will ned to this after `user.signOut()`
```javascript
dispatchAuthEvent('signOut', this.user, `A user has been signed out`);
this.user = null;
```
similar to what happens [here](https://github.com/aws-amplify/amplify-js/blob/c09eec49d9169d05186c97ec1b38b198afe70cd8/packages/auth/src/Auth.ts#L1731)

2022-01-04 20:44 UTC, evcodes commented on packages/core/src/I18n/I18n.ts
> +		if (val != null) {
agh I thought that I removed all the work from a separate branch

2022-01-04 21:42 UTC, hkjpotato commented on packages/auth/src/Auth.ts
> +									logger.debug(result);
The signout flow could be a bit confusing considering different entry points/flows: some ideas here just for reference:
1. In a hosted UI signout, it will have a callback to redirect to "signout url" https://github.com/aws-amplify/amplify-js/blob/c09eec49d9169d05186c97ec1b38b198afe70cd8/packages/auth/src/Auth.ts#L1692
2. there are another concern in signout flow: remove local storage items https://github.com/aws-amplify/amplify-js/blob/c09eec49d9169d05186c97ec1b38b198afe70cd8/packages/auth/src/Auth.ts#L129
3. maybe we can consider to call the higher function, which already encapsulate all these logics. https://github.com/aws-amplify/amplify-js/blob/c09eec49d9169d05186c97ec1b38b198afe70cd8/packages/auth/src/Auth.ts#L1731
4. or as @elorafe suggested, functions can be hook up by "event". Potentially this can help us decouple the nested logics, and keep their single responsibilities. However it might requires more refactor so not necessary something we need to do now.

2022-01-05 17:08 UTC, jamesaucode reviewed
just some nitpicks 😃

2022-01-05 18:40 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +					rej('No current user');
+1

2022-01-05 18:40 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +									logger.debug(result);
+1

2022-01-05 18:51 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +									user.signOut();
So when u try this out in an app, does it even allow you to call `signOut`, if the user is deleted?

i think to avoid confusion here, would it be better to explicitly clear any cache and session in here ?

2022-01-13 19:23 UTC, evcodes commented on packages/auth/src/Auth.ts
> +									user.signOut();
funny enough the user.signOut() does a lot of work behind the scenes which I am not sure if we would want to include that explicitly:

```
clearCachedUser() {
		this.clearCachedTokens();
		this.clearCachedUserData();
	}
```

2022-01-20 21:49 UTC, ashika01 commented on packages/auth/__tests__/auth-unit-test.ts
> +				jasmine.any(Function),
i know this is not an introduced change. But we should try to move away frm using jasmine and make these pure jest tests

2022-01-20 22:00 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +									user.signOut();
Sorry I kinda wasn't clear. So if u check our Auth signout - we do `cleanCachedItems` to clear cached creds. Dont we have to do that too if we are signing a customer out? Did we decide not to do that?

2022-01-20 22:03 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +									user.signOut();
Also, `user.deleteUser` already does this `clearCachedUser` clean out.

https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1106

So what ever reminder cleanup we want to do we can do it here explicitly than calling signout i think. What are we trying to achieve to do with this signOut?

2022-01-20 23:14 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +		// const that = this;
nit: needs to be removed?

2022-01-20 23:16 UTC, ashika01 commented
It seems like a hub event for deleteUser is missed here, There is only one for sign out.

2022-01-21 00:16 UTC, ashika01 commented on packages/auth/__tests__/auth-unit-test.ts
> +			expect(await auth.deleteUser()).toBe('SUCCESS');
could u also check for if the session is cleared out?

2022-01-21 01:49 UTC, elorzafe reviewed
Thanks for the update, can you check the error messages from `user.getSession`?
and revert the change from I18n please

2022-01-21 01:49 UTC, elorzafe commented on packages/core/src/I18n/I18n.ts
> +		if (typeof lang_dict === 'undefined') {
I would revert this change from the PR

2022-01-21 01:49 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +							rej(new Error('User session does not exist'));
I would change this error, in case the client is offline is a different problem. Can you check the err message and map it to the correct one.

2022-01-21 21:10 UTC, evcodes commented on packages/auth/__tests__/auth-unit-test.ts
> +				jasmine.any(Function),
This can be slated as an operational excellence item for the future as I have no context to what Jasmine is...

2022-01-24 08:01 UTC, evcodes commented on packages/auth/src/Auth.ts
> +									user.signOut();
I just tested without the user.signOut call and it works the same so I am going to remove it for now. Thank you Ashika!

2022-01-27 01:34 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +							rej(new Error('User session does not exist'));
talked offline

2022-01-27 06:44 UTC, ashika01 commented on packages/auth/__tests__/auth-unit-test.ts
> +			// expect(await auth.deleteUser()).toThrowError();
this needs to be changed.

2022-01-27 07:15 UTC, ashika01 commented
Fully ran integ test report here - https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/10026/workflows/dc0959e9-6573-43c0-aaf1-9a0d1aec2d71

2022-01-27 07:23 UTC, ashika01 approved these changes

2022-01-27 17:37 UTC, elorzafe requested changes
A couple minor changes, however the promise not awaited and the dispachEvent is a blocker

Overall looks very good

2022-01-27 17:37 UTC, elorzafe commented on packages/auth/__tests__/auth-unit-test.ts
> +			});
This expect is probably not validated by jest because is inside of the callback. Also is testing the mock and not the actual code. I would remove this.

2022-01-27 17:37 UTC, elorzafe commented on packages/auth/src/Auth.ts
> +									`A user has been signed out`
This should be inside of `else` statement otherwise it can be triggered in case `deleteUser` fails.

2022-01-27 17:45 UTC, evcodes commented on packages/auth/src/Auth.ts
> +		});
so should there be an `await` before the` new Promise(...`?

2022-01-27 17:56 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +		});
I don't think this new Promise is being used anywhere. It's probably better if we just remove the whole `new Promise`, and throw an Error if it fails. Similar to how it's done here in `currentAuthenticatedUser`
https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1373-L1378

2022-01-27 18:03 UTC, hkjpotato commented on packages/auth/src/Auth.ts
> +		});
agree with James, a promise is not required here, just normal try-catch.

2022-01-27 18:20 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +	public async deleteUser(): Promise<Error | string | void> {
Do we need to specify the `Promise<Error>` in our return type? It seems inconsistent with our other API and might be harder for our customers to use.

2022-01-27 18:26 UTC, jamesaucode commented on packages/auth/src/Auth.ts
> +	public async deleteUser(): Promise<Error | string | void> {
Pulled this locally, it seems like just `Promise<string>` will be sufficient instead of a union of `Error | string | void`

2022-01-27 18:29 UTC, ashika01 commented on packages/auth/src/Auth.ts
> +	public async deleteUser(): Promise<Error | string | void> {
hmm.. lets chat on this one. I thought void is unnecessary too
but eddy brought a point around oAuthredirect

2022-01-27 18:52 UTC, jamesaucode approved these changes
lgtm! 🎉

2022-01-27 19:03 UTC, elorzafe approved these changes
Great work!! lets ship it 🌮

2022-01-27 19:31 UTC, merged