Fix "EventEmitter.removeListener: Method has been deprecated" warning…
aws-amplify/amplify-js pull request #9450
Opened 2022-01-07 13:02 UTC by retyui

#### Description of changes

I use

- `"react-native": "0.66.x",`
- `@aws-amplify/auth": "^3.4.34",`

And on every start a see this annoying warning 

```bash
 WARN  EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
```

Then I check that implementation and find out that subscription impossible for function because
```ts
let handler;

export default async callback =>{
  	if (handler) { // this code make not possible to unsubscribe after first call
		return; 
	}
        // ....
        Linking.removeEventListener('url', handler);
        subscription?.remove?.();
}

So I decided to remove never reached unsubscription calls

#### Description of how you validated changes

covered with tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-07 13:06 UTC, retyui commented
**Other notes:**

When you check history https://github.com/facebook/react-native/commits/main/Libraries/Linking/Linking.js

![image](https://user-images.githubusercontent.com/4661784/148548026-59731018-ed07-466a-9b2b-32cb9a8f70a5.png)


you will noticed that `removeListener` was removed but then restored (for backward compatibility) 

![image](https://user-images.githubusercontent.com/4661784/148547971-710fce78-a936-43db-82c0-1d913df1447b.png)

so the code above will be `true` always for all **react-native** versions that currently released (`0.67.x - 0.60.x`)

2022-01-07 19:12 UTC, calebpollman requested changes
Thanks for submitting the PR and really appreciate the unit tests 🤩  Left some feedback on the changes.

Regarding the deprecated warning for `Linking.removeListener` when using React Native `v0.66.x` , have you considered leveraging `YellowBox.ignoreWarnings`?  e.g.
```
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Warning: ...']);
```

2022-01-07 19:12 UTC, calebpollman commented on packages/auth/src/urlListener.native.ts
> -	}
Removing `subscription` **should** be fine, but this conditional block is required in order to prevent React Native versions prior to 0.65 (see [v0.64-stable](https://github.com/facebook/react-native/blob/0.64-stable/Libraries/Linking/Linking.js#L47)) from crashing

2022-01-09 20:04 UTC, retyui commented on packages/auth/__tests__/urlListener.native-test.ts
> +	const delay = (ms: number) => new Promise(ok => setTimeout(ok, ms));
it is not possible to manipulate an ordering of promise chain using `useFakeTimers`!

2022-01-09 20:20 UTC, retyui commented on packages/auth/src/urlListener.native.ts
> -	}
- **First of all** `Linking.addEventListenerI()` will be always return  `EmitterSubscription` object  regardless of RN version

see below [source code 0.63.x](https://unpkg.com/browse/react-native@0.63.0/Libraries/vendor/emitter/EventEmitter.js) with flow types

![image](https://user-images.githubusercontent.com/4661784/148698886-db14d57d-a448-4310-a6b7-c303713fd915.png)

---

- **And second thing**, that I tried to explain that unsubscribe will **NEVER** be invoked 

Let try to debug what written currently

```js
let handler;

export default async callback => {
	if (handler) { // 1
		return;
	}

	handler = handler || ((args) => { /* code */ }); // 2

	Linking.removeEventListener('url', handler); // 3
	Linking.addEventListener('url', handler); // 4
       //...
};
``` 

**First invoke:**
- `1` mark, will be `false`, because `handler` no initialized yet
- `2` mark, will assign `handler` variable 
- `3` tried to unsubscribe, but it no make canes (as it was not subscribed before) 
- `4` will be successfully subscribed!

**Second invoke:**
- `1` mark, now if block is **TRUE** and immediately exit from function (as handler was initialized on first call on `2` mark)
- add now never mind what version of react-native 0.64 or 0.66! It subscribe once AND never reach unsubscribe line!

2022-01-09 20:25 UTC, retyui commented
> Thanks for submitting the PR and really appreciate the unit tests star_struck Left some feedback on the changes.
> 
> Regarding the deprecated warning for when using React Native , have you considered leveraging ? e.g.`Linking.removeListener``v0.66.x``YellowBox.ignoreWarnings`
> 
> ```
> import { YellowBox } from 'react-native';
> YellowBox.ignoreWarnings(['Warning: ...']);
> ```

It is nonsense! when you create fresh project and install latest versions of amplify to see Deprecation warnings!

2022-01-09 20:32 UTC, retyui commented
p.s. seems current build process has a memory leak

![image](https://user-images.githubusercontent.com/4661784/148699695-2da1d953-c3bc-4793-a117-3da8af7e3c13.png)

2022-01-11 08:27 UTC, retyui commented
@calebpollman did you have time to review this PR ?

2022-02-20 17:20 UTC, closed without merging

2022-02-20 17:22 UTC, retyui commented
Close as I patch this module localy (https://github.com/ds300/patch-package)