refactor(amplify-js/scripts): replace npm-exec alias with npx and remove unnecessary step 2 in the contribution guide
aws-amplify/amplify-js pull request #9579
Opened 2022-02-11 20:22 UTC by Samaritan1011001

#### Description of changes

Minor code refactoring to remove unwanted aliasing and replace it with `npx` and also remove unnecessary step in the contribution guide since `wml` is installed as part of the `devDependency` for the project. 

#### Issue #, if available

#### Description of how you validated changes
Validated for correctness of work with different packages. 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-11 22:06 UTC, calebpollman requested changes
Just had some minor feedback/questions. Thanks for the updates!

2022-02-11 22:06 UTC, calebpollman commented on CONTRIBUTING.md
>  1. Finish the build steps mentioned in the section: `Setting up for local development`
Should step one be to make sure the contributor has setup the RN dev env? https://reactnative.dev/docs/environment-setup

2022-02-15 01:59 UTC, Samaritan1011001 commented on CONTRIBUTING.md
>  watchman watch node_modules/wml/src
It can be but this step might not even be necessary for some users which is why Chris suggested we take it out. We decided to include it since not running it could have a very confusing user experience (`wml` start simply does nothing). This step is also under debugging section.

2022-02-15 02:19 UTC, Samaritan1011001 commented on CONTRIBUTING.md
> +- If the WML command does not do anything after adding the links, watch it's src file using watchman. Run the below from the root of this repository:
Agreed and changed ✔️

2022-02-15 02:21 UTC, Samaritan1011001 commented on CONTRIBUTING.md
>  1. Finish the build steps mentioned in the section: `Setting up for local development`
Well, these steps are entirely related to the `amplify-js` repository side of things. User will have to only get the path to their RN app which is used with the script command in step 4.

2022-02-15 15:58 UTC, calebpollman commented on CONTRIBUTING.md
>  watchman watch node_modules/wml/src
I'm a bit confused, are we removing it? It appears that we have just changed the step number? If it is not required then that should be explicit?

2022-02-15 17:17 UTC, chintannp commented on CONTRIBUTING.md
>  watchman watch node_modules/wml/src
I do face this issue many times I have to manually add wml src folder to watchman. If there is no harm in running it then I think we should let the script handle and execute it.

2022-02-15 21:51 UTC, Samaritan1011001 commented on CONTRIBUTING.md
>  watchman watch node_modules/wml/src
I moved this command into the script which makes it a simple two step process to get started with development.

2022-02-15 21:52 UTC, Samaritan1011001 commented on CONTRIBUTING.md
>  1. Finish the build steps mentioned in the section: `Setting up for local development`
That's a great observation! I added a note to point contributors to the steps for configuring and creating a RN app.

2022-02-15 22:04 UTC, calebpollman approved these changes
LGTM, thanks @Samaritan1011001

2022-02-15 23:50 UTC, cshfang requested changes

2022-02-15 23:50 UTC, cshfang commented on CONTRIBUTING.md
> +1. Finish the build steps mentioned in the section: `Setting up for local development` to set up your devlopment `amplify-js` repository.
Typo
```suggestion
1. Finish the build steps mentioned in the section: `Setting up for local development` to set up your local `amplify-js` repository for development.
```

2022-02-15 23:50 UTC, cshfang commented on CONTRIBUTING.md
> +   > Note: To setup a sample React-Native app -- configure your [development](https://reactnative.dev/docs/environment-setup) environment and [create](https://reactnative.dev/docs/environment-setup#c
Suggest wrapping `development environment] and [create an app] as the links.
```suggestion
   > Note: To set up a sample React-Native app -- configure your [development environment](https://reactnative.dev/docs/environment-setup) and [create an app](https://reactnative.dev/docs/environment-setup#creating-a-new-application). Note the path to the app as it is required in the next step.
```

2022-02-15 23:50 UTC, cshfang commented on CONTRIBUTING.md
> +2. Run the below command in the root of the amplify-js local repository with a package name (auth for example):
```suggestion
2. Run the below command in the root of your local `amplify-js` repository with a package name (auth for example):
```

2022-02-15 23:50 UTC, cshfang commented on CONTRIBUTING.md
> +- If the WML command does not do anything after adding the links, watch its src file using watchman. Run the below from the root of this repository:
Nice catch with the "its" 💯

2022-02-15 23:50 UTC, cshfang commented on scripts/setup-dev-rn.js
> +const WATCHMAN_WATCH_SRC = `watchman watch node_modules/wml/src`;
Is it possible they do not have `watchman` installed globally? I don't see it as a installation step for `wml` so if this installing `watchman` globally is a required step for this we will need to call it out.

2022-02-16 02:51 UTC, Samaritan1011001 commented on scripts/setup-dev-rn.js
> +const WATCHMAN_WATCH_SRC = `watchman watch node_modules/wml/src`;
You are right, I added a note in step 2 about this. However, that makes for a lot of notes. Let me know if you have better ides to restructure the guide.

2022-02-16 17:17 UTC, calebpollman commented on scripts/setup-dev-rn.js
> +const WATCHMAN_WATCH_SRC = `watchman watch node_modules/wml/src`;
If the user has set up the React Native dev environment then they will have installed `watchman` globally. We could throw an error here with a descriptive message if it is not installed though

2022-02-16 17:24 UTC, calebpollman commented on CONTRIBUTING.md
> +   > Make sure to have [watchman](https://facebook.github.io/watchman/docs/install.html) installed before running the below command
Think this is excessive as if the user has setup the React Native dev environment they will have already done this

2022-02-16 18:53 UTC, cshfang commented on CONTRIBUTING.md
> +   > Make sure to have [watchman](https://facebook.github.io/watchman/docs/install.html) installed before running the below command
Minor flow suggestion
```suggestion
   > Make sure to have [watchman](https://facebook.github.io/watchman/docs/install.html) installed before running the command below
```

2022-02-16 18:53 UTC, cshfang commented on CONTRIBUTING.md
> +   > Make sure to have [watchman](https://facebook.github.io/watchman/docs/install.html) installed before running the below command
Per RN docs it is technically not required to have watchman installed - although it comes highly recommended. Imo it's probably ok to have this for the 0.1% of people that might run into this.

2022-02-17 02:49 UTC, Samaritan1011001 commented on CONTRIBUTING.md
> +   > Make sure to have [watchman](https://facebook.github.io/watchman/docs/install.html) installed before running the below command
I agree, if users setup the RN app without watchman for some reason, this note will help make sure it's available.

2022-02-17 02:53 UTC, Samaritan1011001 commented on scripts/setup-dev-rn.js
> +const WATCHMAN_WATCH_SRC = `watchman watch node_modules/wml/src`;
I am not seeing an easy way to catch that error in the script because all the `wml` commands are sent to the `osascript` which runs them one after the other. I tried the script without `watchman` and it showed a clear error message that watchman isn't installed.

<img width="251" alt="Screen Shot 2022-02-16 at 6 52 20 PM" src="https://user-images.githubusercontent.com/10944487/154395555-4dd19036-5a5e-4188-bc0d-fe4c704bfaf3.png">

2022-03-07 23:44 UTC, cshfang approved these changes

2022-03-09 23:51 UTC, merged