Added ExpoSQLiteAdapter and Code Sharing for common files
aws-amplify/amplify-js pull request #9581
Opened 2022-02-11 23:03 UTC by chintannp

#### Description of changes
This PR adds ExpoSQLiteAdapter inside `datastore-storage-adapter` package. Additionally, it includes updates to the SQLiteAdapter as few files have been moved under `common` directory for code sharing purpose.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-12 01:08 UTC, calebpollman requested changes
Thanks for doing this @chintannp, definitely a good start. Left some feedback, feel free to reach out to me if you have any questions. Btw, while reviewing I noticed that we do not have `@types/react-native-sqlite-storage` which could help us improve some of the typing.

2022-02-14 21:47 UTC, calebpollman commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await tempdb._db.close();
Missed the accessing of the nested `_db` here. Please disregard the above suggestion, it would get really weird/ugly.

I am curious though, do we need to assign `this.db` to `tempdb` in order to access `_db`? Could we just reduce these lines to `(this.db as any)_db.close()`?

2022-02-14 21:49 UTC, cshfang requested changes

2022-02-14 21:49 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		await new Promise((resolve, reject) => {
I believe you should be returning this `Promise` instead
```suggestion
		return new Promise((resolve, reject) => {
```

2022-02-14 21:49 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await tempdb._db.close();
Fwiw, we are already doing a somewhat unsafe cast regardless we may as well just opt for readability and keep the `any`. (I think the proposed casting would have to tack on the `_db` property too, making it even more unclear)

I agree we shouldn't need a tempdb though:
```suggestion
			await (this.db as any)._db.close();
```

2022-02-14 21:49 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		}
Doesn't `executeStatements` accept an array of statements? Can we not just build an array of statements and call `executeStatements` once to keep it to a single transaction?

2022-02-14 22:22 UTC, cshfang commented
Overall actually lgtm! There are some questions and maybe gaps we need to address first but this PR is definitely coming along. I have a couple general thought about the Promise patterns being added. I see these pattern being used throughout:
```js
public async foo(): Promise<any> {
  const resultSet = await new Promise((resolve, reject) => {
    resolve(res);
  })
  // build a result and then return it
  const result = resultSet.rows._array;
  return result;
}

public async bar(): Promise<any> {
  let result = [];
  await new Promise((resolve, reject) => {
    // push things into result then resolve the promise
    resolve();
  })
  return result;
}
```
But instead of wrapping a promise inside an async function just await it, we could/should refactor to just return these promises directly:
```js
public async foo(): Promise<any> { // even the async keyword is technically optional, but it does still serve as a good hint that this function returns a promise to be run asynchronously
  return new Promise((resolve, reject) => {
    // build a result and then resolve it
    const result = res.rows._array;
    resolve(result);
  })
}

public async bar(): Promise<any> {
  let result = [];
  return new Promise((resolve, reject) => {
    // push things into result then resolve the promise
    resolve(result);
  })
}
```

Another thing that I think @calebpollman touched on is the error callbacks returning `true`. I *think* where there are not multiple statements to execute - we shouldn't need to add the `return` at all on the error callbacks. Where there is a desire to break out of a loop where multiple statements are being executed - I'm not sure `true` is the right thing to return either. Imo - just breaking with a `return;` should be sufficient.

2022-02-15 19:10 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				this.db.readTransaction(tx => {
We could name it `transaction` but the default argument name is `tx` across different package documentations including `react-native-sqlite-storage `.

2022-02-15 20:43 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		return result[0] || undefined;
using `item()` instead of `_array` could make it more clearer. `item()` returns null if a row does not exists.

2022-02-15 20:46 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +							return true;
error callback in `executeSql` has a defined return type of `boolean`. The return type is mentioned in the library but I do not see it anywhere in the docs. Not returning a boolean highlights an error in IDE.

2022-02-15 20:53 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		params: any[]
Yes. That would be better. I'll update that.

2022-02-16 17:53 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await tempdb._db.close();
I don't think the intersection would work. It executes the close() method defined in the intersection rather than the one defined in `SQLite.WebSQLDatabase `. I think we could achieve this without using temporary variable like this : 
`await (<any>this.db)._db.close();`

2022-02-16 17:58 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		if (this.db) {
Actually, for `ExpoSQLiteAdapter`, `closeDB()` will never be called. `SQLiteAdapter` calls the `closeDB()` before deleting the database in `clear()` method. In `ExpoSQLiteAdapter`, we are not deleting the database instead we drop all the tables. Thus, there is no need to close the database as it won't be deleted.

2022-02-16 18:07 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +*/
Using both regular JS functions and callback functions is not the best standard. I will update all the functions to use arrow functions.

2022-02-16 18:08 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		// only open database once.
Yes. We should be doing a similar check in `SQLiteDatabase`. I'll add the check.

2022-02-16 18:09 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					(tx, results) => {
Yes. I'll replace it.

2022-02-16 18:09 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					`SELECT name FROM sqlite_master where type='table'`,
I'll update that. Thanks Caleb

2022-02-16 18:36 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		return result || [];
This would be a better approach for re-using existing methods. I'll reuse this method.

2022-02-16 18:40 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					() => resolve(),
The return type is void. Passing `null` will be future proof as you suggested. I'll update it.

2022-02-16 18:40 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						function (_tx, res) {
I'll replace all callback functions to use arrow syntax

2022-02-16 18:50 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						() => {},
Thanks Caleb. Using `null` will use less space. I'll update that.

2022-02-16 18:55 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		return await this.executeStatements(statements);
Good catch, there is no reason to keep the function in the call stack as `createSchema()` itself is `async`. I'll remove the await.

2022-02-16 19:12 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		}
Yes. I will map the `tableNames` array and map it into an array of Drop statements.

2022-02-16 19:41 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		await new Promise((resolve, reject) => {
Yes. That could be another way of handling it and would be more consistent. I will make necessary changes. Thanks for the suggestion caleb.

2022-02-16 19:51 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +							results.push(res.rows._array[0]);
Good catch caleb and chris. I will use `item` here and use a conditional push.

2022-02-16 19:52 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +							() => {},
Will update that.

2022-02-16 20:02 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						resolve(results.rows._array);
Yes.The conditional check would be more error proof. I will add the check here.

2022-02-16 20:05 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		return tableNames;
Yes. I'll update it.

2022-02-16 20:11 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			resultSet.rows._array;
I'll use optional chaining and use `item(0)` instead of accessing it through `_array`

2022-02-16 20:12 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				let tempresults;
will update it to use camelCasing.

2022-02-16 20:19 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						tempresults = res.rows._array;
It would be simpler than assigning it to a temp variable. But the function name `selectAndDelete` suggests that select statement would be executed prior to delete statements.

2022-02-16 20:20 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +import * as SQLite from 'expo-sqlite';
That would be better. I'll update it.

2022-02-16 20:23 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await tempdb._db.close();
I'll use this instead of a temp variable.

2022-02-16 20:30 UTC, chintannp commented on packages/datastore-storage-adapter/src/common/types.ts
> +	batchQuery(queryStatements: Set<ParameterizedStatement>): Promise<any[]>;
That's a great idea. Will update that.

2022-02-16 20:32 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		results = await new Promise((resolve, reject) => {
Thanks. I'll update it.

2022-02-16 20:35 UTC, chintannp commented on packages/datastore-storage-adapter/src/common/types.ts
> +import { ParameterizedStatement } from './SQLiteUtils';
Yes. I'll move it into `types.ts`.

2022-02-16 20:37 UTC, chintannp commented on packages/datastore-storage-adapter/src/common/types.ts
> +export function getSQLiteType(
Good suggestion, I'll move that.

2022-02-21 19:51 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				resolve(null);
Doesn't this resolve happens pretty much right away if we're not waiting for any success callbacks at all?

2022-02-21 19:51 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				resolve(tempResults);
Same question here... wouldn't this resolve the promise without actually waiting for the callback to happen?

2022-02-21 19:51 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		const getTablesCommand =
I would suggest moving this up just out of this class and using screaming snake case convention e.g. `GET_ALL_TABLES_STATEMENT`

2022-02-21 19:51 UTC, cshfang commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +		// only open database once.
Doesn't the `clear` function close the db? I seem to recall that the expected use case is for someone to call `clear` and `init` again - wouldn't this break that use case? Do we need to null out `this.db` when closing a db??

2022-02-21 19:51 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await (this.db as any)._db.close();
Just thought of this but.. once closed - how would the db be reopened? Do we need to null out `this.db` here?

2022-02-24 17:01 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				resolve(null);
Yes, It probably would happen right away. But we still need to `resolve` the promise that we created.

2022-02-28 17:19 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		await new Promise((resolve, reject) => {
Yes. I will update that.

2022-02-28 17:20 UTC, chintannp commented on packages/datastore-storage-adapter/package.json
>  		"expo-sqlite": "~10.1.0"
Thanks. will update it.

2022-02-28 17:20 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		const results: any[] = await this.getAll(statement, params);
Yes `T[]` makes more sense than `any[]`

2022-02-28 17:21 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		return results.length > 0 ? results[0] : undefined;
Thanks Chris, it will reduce our duplication of code. I will update that.

2022-02-28 17:22 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						return true;
I will add those comments for better understanding. 👍

2022-02-28 17:23 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +	public async batchQuery<T = any>(
Since, the output of the `execSql` can be based on the query passed, it could be harder for us to confine further I believe.

2022-02-28 17:24 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		const resultSet: T[] = await new Promise((resolve, reject) => {
Yes. It could be returned directly.

2022-02-28 17:29 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +		// only open database once.
I had a conversation with Ivan. The most common customer use case for this is when multiple end users share a device. Customers will call DataStore.clear on sign out to delete that user’s data from the device. Then when a user signs in, they’ll call DataStore.start() to re-initialize the schema and local db. So basically, we will need to null out db using `this.db = undefined;`. After that when `Datastore.start()` is called, the db will be re-opened when `init()` is called by the `CommonSQLiteAdapter`.

2022-03-02 17:34 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				resolve(tempResults);
Yes. I have updated the code to await the results before resolving the promise. Thanks Chris.

2022-03-02 17:41 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						tempresults = res.rows._array;
This is no longer valid, as we are not using `tempresults`. We are now storing the response from`Promise` and returning it.

2022-03-02 17:45 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +							return true;
As per this [SO](https://stackoverflow.com/a/67561516) answer, it is required to return a boolean value to indicate if the error was handled. Returning `true` means the error was handled and the transaction does not need to be rolled back. I have added comment at the top of the file for better understanding.

2022-03-02 22:42 UTC, cshfang requested changes
I think this is looking much improved. Still have some feedback and questions but we're getting there!

2022-03-02 22:42 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		await deleteAsync(documentDirectory + 'SQLite/' + DB_NAME);
What happens if this fails? Shouldn't we handle the error somehow?

2022-03-02 22:42 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					const results = [];
Instead of doing this, you should be able to resolve the mapped promises with the result of their sql execution. Then the result of the `Promise.all` should already be the array you want. E.g.
```js
const result = await Promise.all([1, 2, 3].map(item => new Promise((resolve, reject) => {
  resolve(item + 1)
})))
console.log(result) // [2, 3, 4]
```

2022-03-02 22:42 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				this.db.transaction(async tx => {
This was previously all part of a single transaction - shouldn't we keep it that way? I think you should be able to build a single array of save *and* delete statements and use a single `Promise.all`. E.g.
```js
[...saveStatements, ...(deleteStatements ?? [])].map(
```
Alternative to the nullish coalesce, you could also give deleteStatements a default value of `[]`

2022-03-02 22:42 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					if (saveStatements) {
Is this necessary? Isn't this required per the function signature?

2022-03-02 22:42 UTC, cshfang commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		deleteParameterizedStatement: ParameterizedStatement
Nit: Imo, it would be better to align these with `saveStatements` or `deleteStatements`:
```suggestion
		queryStatement: ParameterizedStatement,
		deleteStatement: ParameterizedStatement
```
Same goes for the `selectAndDelete` in the `SQLiteDatabase.ts`

2022-03-03 16:57 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +				this.db.transaction(async tx => {
There are multiple benefits of keeping it in a separate transaction. First one is that to prevent table locks that will be placed by the `saveStatements`. Additionally, in case of large number of queries keeping small transactions can be more performant. I will update the spread operators to give `deleteStatements ` and `saveStatements ` a default value of `[]`.

2022-03-03 17:01 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					if (saveStatements) {
I'll remove the if statements and give `saveStatements` a default value of `[]`

2022-03-03 17:04 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		deleteParameterizedStatement: ParameterizedStatement
`queryStatement` and `deleteStatement` would interfere and be confusing when destructuring `queryParameterizedStatement` and `deleteParameterizedStatement` in the later step. eg.

```
		const [queryStatement, queryParams] = queryParameterizedStatement;
		const [deleteStatement, deleteParams] = deleteParameterizedStatement;

```

2022-03-03 17:05 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +					(_tx, res) => {
Thanks, I'll update this.

2022-03-03 17:05 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +				(_tx, res) => {
Thanks, I'll update this.

2022-03-03 17:05 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +		this.db.transaction(tx => {
Thanks, I'll update this. We should await.

2022-03-03 17:08 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		await deleteAsync(documentDirectory + 'SQLite/' + DB_NAME);
I'll add a try and catch block to re initialize the db if it was closed and `this.db` was set to `undefined`. Additionally, I'll log the warning in console.  This should notify that the Datastore local db was not cleared and should also be able continue performing the other functions.

2022-03-03 17:09 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					const results = [];
Thanks Chris. Didn't notice `Promise.all` resolve to an array of resolved promises. I'll update that.

2022-03-08 19:25 UTC, calebpollman requested changes
Good work so far, think this really coming along. It would be great if we could find a way to reduce the amount of boilerplate code we are adding for the transaction handling (e.g. the result and error handling callbacks), maybe could look at adding a util function(s) that abstracts away the boilerplate?

2022-03-09 20:46 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		deleteParameterizedStatement: ParameterizedStatement
I think it is much clearer for future reader if we use `deleteParameterizedStatements` instead of just `deleteStatements` because it makes it clearer that the each individual item inside `deleteParameterizedStatements` is of type `ParameterizedStatement`. However, your concern regarding lengthening the names of the contents of `Set` is valid. I think we can rename the arguments of `batchSave` to use `saveParameterizedStatements` and `deleteParameterizedStatements`. However, as we are directly de-structuring the items inside `saveParameterizedStatements` and `deleteParameterizedStatements`, we do not need to declare `const deleteParameterizedStatement`. So, that it looks like below (simplified for demonstration).

```
this.db.transaction(async tx => {
	[...(saveParameterizedStatements ?? [])].map(([saveStatement, params]) => {
		tx.executeSql(saveStatement, params);
	});
});

```

2022-03-09 20:50 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +const DB_DISPLAYNAME = 'AWS Amplify DataStore SQLite Database';
Thanks. I'll update that.

2022-03-09 20:50 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			await deleteAsync(documentDirectory + 'SQLite/' + DB_NAME);
Cool, I'll update it to use template literal.

2022-03-09 20:52 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					() => resolve(null),
Good catch, I'll remove the `null` from `resolve()`

2022-03-09 20:55 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						[...(saveStatements ?? [])].map(
The type of `saveStatements` is `Set<ParameterizedStatement>`. `map` is only available on arrays, so the spread operator will convert the `Set` into an `Array` of elements.

2022-03-09 20:55 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						[...(deleteStatements ?? [])].map(
The type of deleteStatements is Set<ParameterizedStatement>. map is only available on arrays, so the spread operator will convert the Set into an Array of elements.

2022-03-09 20:57 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +I purposely used arrow functions () => {} in this class as expo-sqlite library is not promisified.
ok. I'll remove the comment.

2022-03-09 20:58 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +										(_, result) => {
Thanks Caleb, I'll remove the unused params from all the places in the file.

2022-03-09 21:37 UTC, calebpollman commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		deleteParameterizedStatement: ParameterizedStatement
Okay, i think you are aligning with me? What I am getting is that in the current form, there no consistent naming pattern

2022-03-09 21:44 UTC, calebpollman commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					() => resolve(null),
Passing `null` is correct, we just don't need to return the output of `resolve` 

```suggestion
					() => {
             resolve(null),
           },
```

2022-03-09 21:52 UTC, calebpollman commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						[...(saveStatements ?? [])].map(
Ideally since `saveStatements` is a required parameter, this should not be a concern. But if you are doing this to ensure that a value of `null` passed as `saveStatements` won't crash, imo it would be cleaner to set a default value for `saveStatements`  of an empty array. Would also suggest doing that for `deleteStatements` (and anywhere else we are spreading a single array to create a new array)

2022-03-10 15:57 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		deleteParameterizedStatement: ParameterizedStatement
Agreed Caleb, there were some inconsistent naming of the function arguments. I'll rename the function arguments to follow more consistent naming pattern. Thanks for pointing this out.

2022-03-10 15:59 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +											resolve(res.rows._array[0]);
`CommonSQLiteAdapter` expects `undefined` if no result was found. Using `_array[0]` returns `undefined` where as `item(0)` returns null if no result was found.

2022-03-10 16:00 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			this.db.readTransaction(tx => {
Yes, I will replace `tx` with `transaction`. It will be a bit longer but definitely easier for future readers to understand.

2022-03-10 17:06 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						resolve(res?.rows?._array || []);
`res.rows._array` would never resolve to falsy as per the documentation. Based on its return type `any[]`, it should return an empty array if no result was found.

2022-03-10 17:07 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +					(_, res) => {
We can use `result` for more clarity. I'll update that.

2022-03-10 17:45 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						[...(saveStatements ?? [])].map(
I have updated it to use set a default Value. This removes the additional check for `null` value. However, we will still need spread operator to convert the `saveStatements:Set` into `saveStatements:[]` so that we can call `map` on the `array`.

2022-03-17 03:15 UTC, manueliglesias reviewed
This looks great! The discussions and comments were very useful.

The question I have is: since there doesn't seem to be an ExpoAdapter exported from the package entry point, how do expo customers use it? E.g. for the other adapter (#8809) we say:


```typescript
import { DataStore } from 'aws-amplify';
import { SQLiteAdapter } from '@aws-amplify/datastore-storage-adapter';

DataStore.configure({
  storageAdapter: SQLiteAdapter
});
```

2022-03-17 16:40 UTC, chintannp commented
@manueliglesias , Good question. `SQLiteAdapter` and `ExpoSQLiteAdapter` both have different dependencies. So, if we export both the adapters from a single entrypoint file eg. `index.js`, the customers will need to install the dependencies for both the adapters regardless of which adapters will be used. Hence, I have created a new separate entrypoint for `ExpoSQLiteAdapter` and `SQLiteAdapter`.  This will also be helpful in the future as we add more adapters to this package. So, with the new changes the import statements will look like below.

```
// SQLiteAdapter 
import { SQLiteAdapter } from '@aws-amplify/datastore-storage-adapter/SQLiteAdapter';

// or 
// Default index.js is not changed and it still exports SQLiteAdapter to avoid any breaking changes
import { SQLiteAdapter } from '@aws-amplify/datastore-storage-adapter';

```

```
// ExpoSQLiteAdapter
import { ExpoSQLiteAdapter } from '@aws-amplify/datastore-storage-adapter/ExpoSQLiteAdapter';
```

2022-03-17 17:19 UTC, calebpollman commented
@chintannp I'm not entirely sold on the import/export pattern of the adapters in this PR. My concern is that there is no mechanism to ensure that we align the import syntax of `SQLiteAdapter` and `ExpoSQLiteAdapter` in the future, and this syntax becomes a one-off point of confusion for Amplify engineers who will not have context to the original decision making here. Also think it is important to mention that having different import syntaxes in the immediate term is a confusing DX for our users, and will have a cascading impact on the complexity of the documentation for the feature.

@manueliglesias @elorzafe Would really like to get your opinions on this. While aligning the way we export the two adapters  by changing the current import syntax for the `SQLiteAdapter` to allow for a common export pattern is a breaking change, as _datastore-storage-adapter_ is not an Amplify category would it be possible to bump the major version for releasing this feature as it would not impact the rest of `aws-amplify` (unless I am missing something)?

2022-03-17 17:23 UTC, calebpollman commented on packages/datastore-storage-adapter/src/index.ts
> +export { default as SQLiteAdapter } from './SQLiteAdapter/SQLiteAdapter';
Curious why we need the cast here?

2022-03-23 01:15 UTC, elorzafe reviewed
A few questions, we can chat more offline

I think is very close

Thanks @chintannp

2022-03-23 01:15 UTC, elorzafe commented on packages/datastore-storage-adapter/src/common/CommonSQLiteAdapter.ts
> +	// TODO: use FKs in relations and have `ON DELETE CASCADE` set
This will be added on a later PR?

2022-03-23 01:15 UTC, elorzafe commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +	public async selectAndDelete<T = any>(
Why `any`?

2022-03-23 01:15 UTC, elorzafe commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +	public async batchQuery<T = any>(
why `any`?

2022-03-23 01:15 UTC, elorzafe commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +			this.db = await SQLite.openDatabase({
What happen with the version?

2022-03-29 19:15 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			this.db = openDatabase(DB_NAME, DB_VERSION, DB_DISPLAY_NAME, DB_SIZE);
@elorzafe , Thanks for pointing this out. I have removed `version`, `size` and `description` args as they don't do anything and are optional as per expo docs [here](https://docs.expo.dev/versions/latest/sdk/sqlite/#sqliteopendatabasename-version-description-size-callback).  The version, description and size arguments are ignored, but are accepted by the function for compatibility with the WebSQL specification.

2022-03-29 19:17 UTC, chintannp commented on packages/datastore-storage-adapter/src/common/CommonSQLiteAdapter.ts
> +	// TODO: use FKs in relations and have `ON DELETE CASCADE` set
I don't have any visibility on that task. The comments were added by @iartemiev when the `SQLiteAdapter` was released. I'll reach out to him and get more information on that.

2022-03-29 19:19 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +	public async selectAndDelete<T = any>(
The return type of [SQLResultSetRowList](https://docs.expo.dev/versions/latest/sdk/sqlite/#sqlresultsetrowlist) is `any`. Hence, we cannot bind the result items to any particular types.

2022-03-29 19:19 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +	public async batchQuery<T = any>(
The return type of [SQLResultSetRowList](https://docs.expo.dev/versions/latest/sdk/sqlite/#sqlresultsetrowlist) is any. Hence, we cannot bind the result items to any particular types.

2022-03-29 19:20 UTC, chintannp commented on packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
> +			this.db = await SQLite.openDatabase({
@elorzafe , Thanks for pointing this out. I have removed version, size and description args as they don't do anything and are optional as per expo docs [here](https://docs.expo.dev/versions/latest/sdk/sqlite/#sqliteopendatabasename-version-description-size-callback). The version, description and size arguments are ignored, but are accepted by the function for compatibility with the WebSQL specification.

2022-04-01 14:49 UTC, iartemiev commented on packages/datastore-storage-adapter/src/common/CommonSQLiteAdapter.ts
> +	// TODO: use FKs in relations and have `ON DELETE CASCADE` set
I don't think we have to address this in this PR. The RN SQLiteAdapter still doesn't cascade either. At the time I wrote the comment, we were going to change cascading behavior across the board, so I held off on implementing it here. Now it's looking like the behavior won't change until the next major release. 

We can add a follow up task for adding cascading to both the RN and Expo SQLite adapters in a separate PR.

2022-04-14 17:27 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +						resolve(result.rows._array || []);
yes. as per the docs they are guaranteed to be defined.

2022-04-14 17:29 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +			this.init();
It should only re-init when the clear fails.

2022-04-19 16:43 UTC, chintannp commented on packages/datastore-storage-adapter/package.json
> +    "@types/react-native-sqlite-storage" : "5.0.1"
Thanks. Will update it.

2022-04-25 19:11 UTC, cshfang approved these changes
Lgtm

2022-04-26 15:53 UTC, calebpollman commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		if (this.db) {
@chintannp Bumping this question

2022-04-26 17:13 UTC, chintannp commented on packages/datastore-storage-adapter/src/ExpoSQLiteAdapter/ExpoSQLiteDatabase.ts
> +		if (this.db) {
I don't see of a need / added benefit of informing the caller. The most likely scenario for condition to be false is when the db is already closed or it hasn't been opened. As we handle the `db` variable inside the `ExpoSQLiteDatabase` there isn't much the caller will be able to do as well in that particular scenario.

2022-04-26 17:18 UTC, calebpollman approved these changes
LGTM 🚢

2022-05-06 17:38 UTC, merged

2022-05-12 13:53 UTC, danrivett commented
As an Expo user myself, I just wanted to say I've been waiting for this for quite a while, and so am very excited to see this has been implemented. Great work team, we're looking forward to trying it out once it's released. 🚀

2022-05-12 15:35 UTC, abdallahshaban557 commented
@danrivett - that is great to hear! We are excited to ship this out soon!

2022-05-12 20:42 UTC, Ashish-Nanda commented
Thanks @danrivett. You can try it out right now on the `@unstable` tag and let us know if you have any feedback.

We'll be releasing it soon.

2022-05-12 21:12 UTC, chintannp commented
@danrivett. Excited to hear feedback from you. Please use below steps to use the ExpoSQLiteAdapter.

1. Install the @aws-amplify/datastore-storage-adapter unstable version and additional dependencies using below command. 

`expo install @aws-amplify/datastore-storage-adapter@unstable expo-sqlite expo-file-system`

2. Configure Datastore to use ExpoSQLiteAdapter as the default adapter for storage.

```
import { ExpoSQLiteAdapter } from '@aws-amplify/datastore-storage-adapter/ExpoSQLiteAdapter';

DataStore.configure({
  storageAdapter: ExpoSQLiteAdapter
});

```

2022-05-12 23:59 UTC, danrivett commented
Thanks for the info @chintannp that's really helpful.

I'll pass that onto my developers to take a look. They are currently working on a separate AppSync/DataStore issue (see aws-amplify/amplify-js#9901), and then have an Expo 45 upgrade scheduled to complete, but testing the `ExpoSQLiteAdapter` has been scheduled after that as we only found out about it today.

So likely in a couple of weeks' time they'll start working on it, and I'll pass on any feedback I receive either here, or a separate issue if it seems to warrant it.

Thanks all.

2022-05-20 12:14 UTC, Temaska commented
Just wanted to try this adapter but import doesn't work at all. In a sample project:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/2772345/169525842-d0eff74e-db9a-4ffb-8811-8740445fe8d6.png">
datastore-storage-adapter version is 1.3.0

2022-05-20 18:38 UTC, abdallahshaban557 commented
@Temaska - we are currently investigating this! Thank you for the feedback!

2022-05-20 19:27 UTC, chintannp commented
@Temaska ,
            Thank you so much for reporting the issue! I have reported this as an issue [here](https://github.com/aws-amplify/amplify-js/issues/9923) and will continue to actively work on this. We appreciate your feedback.

2022-05-24 18:27 UTC, chintannp commented
@Temaska ,
                    If you have typescript strict mode enabled. Can you try after disabling it ?

2022-06-17 15:28 UTC, chintannp commented
@Temaska Thank you for your feedback. We have fixed the problem and you can now use the `ExpoSQLiteAdapter` with strict mode enabled. You can install the latest version of `@aws-amplify/datastore-storage-adapter` and it should solve the error highlighting issue with the strict mode enabled.

Currently, the type for `ExpoSQLiteAdapter` will still be undefined. As there are no arguments that need to be passed to the `ExpoSQLiteAdapter`, it does not affect the functionality/usability of the adapter at all. We will continue to work to provide type support for `ExpoSQLiteAdapter` in the future.

2023-01-17 04:57 UTC, jpslav commented
I was seeing the same `undefined` issue that @temaska was -- the problem, I believe, is that the Amplify docs do a named import when in fact the `ExpoSQLiteAdapter` is a default export.  I made a [PR to update the docs](https://github.com/aws-amplify/docs/pull/5020).