feat: update DataStore observe to return all fields in local update snapshot (#9556)
aws-amplify/amplify-js pull request #9617
Opened 2022-02-19 00:34 UTC by david-mcafee

feat: update DataStore observe to return all fields in local update snapshot (#9556)

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-21 09:32 UTC, david-mcafee commented on packages/datastore/src/types.ts
> +	originalElement?: T;
This is the only update to this file - the rest is Prettier.

2022-02-21 16:09 UTC, cshfang commented on packages/datastore/src/datastore/datastore.ts
> +							element: { ...originalElement, ...element },
Is it ever possible for an update to contain only changes to some nested fields?

2022-02-21 19:40 UTC, iartemiev requested changes
Looks good! Just a minor req'd change

2022-02-21 19:40 UTC, iartemiev commented on packages/datastore/src/datastore/datastore.ts
> +							element: { ...originalElement, ...element },
I believe it's safe to just set `element: originalElement` here without combining the two. `originalElement` should be a strict superset of `element`.

2022-02-22 20:46 UTC, svidgen reviewed
Can we add testing for this?

2022-02-22 21:12 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +							element: { ...originalElement, ...element },
My bad, I completely forgot that `originalElement` is indeed the updated element. Will rename.

2022-02-22 21:57 UTC, cshfang approved these changes
Small nit and a small question that I think was answered offline. Just wanted to make sure we double check it real quick but otherwise lgtm!

2022-02-22 21:57 UTC, cshfang commented on packages/datastore/src/datastore/datastore.ts
> +						const updated = {
Super nit as this is obviously a micro-optimization but I think you could just return this directly here to save a tick without really losing code clarity.

2022-02-22 21:57 UTC, cshfang commented on packages/datastore/src/storage/storage.ts
> +				savedElement,
Just making sure we do a quick sanity check: Does this property being added to the stream affect any consumers of the stream that might not expect it?

2022-02-23 00:00 UTC, david-mcafee commented
> Can we add testing for this?

@svidgen - sure!

2022-02-24 19:17 UTC, manueliglesias approved these changes
LGTM 👍

2022-03-24 18:31 UTC, david-mcafee commented
> > LGTM 👍
> 
> Edit: I need to re-review this as it might be having unintended effects in the fields sent to the mutation input

@manueliglesias this shouldn't affect that, as the updates are only being returned to the customer, but the mutation event sent to AppSync will only send updated fields

2022-03-24 18:36 UTC, manueliglesias commented
> > > LGTM 👍
> > 
> > 
> > Edit: I need to re-review this as it might be having unintended effects in the fields sent to the mutation input
> 
> @manueliglesias this shouldn't affect that, as the updates are only being returned to the customer, but the mutation event sent to AppSync will only send updated fields

Awesome! Thank you for confirming @david-mcafee  😄

2022-03-24 19:22 UTC, manueliglesias requested changes
It works great! The only thing I'd like to see changed is creating two types instead of adding an optional field to the existing type. That way we don't leak that implementation detail.

2022-03-24 19:22 UTC, manueliglesias commented on packages/datastore/src/types.ts
> +	savedElement?: T;
I think we should split the types for internal notifications and customer facing notifications.

e.g.

```typescript
export type SubscriptionMessage<T extends PersistentModel> = Omit<InternalSubscriptionMessage<T>, 'savedElement'>;

export type InternalSubscriptionMessage<T extends PersistentModel> = {
	opType: OpType;
	element: T;
	model: PersistentModelConstructor<T>;
	condition: PredicatesGroup<T> | null;
	savedElement: T;
};
```

2022-03-25 22:31 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +						const updated = {
Agree!

2022-03-25 22:41 UTC, david-mcafee commented on packages/datastore/src/storage/storage.ts
> +				savedElement,
Definitely worth mentioning! However, it does not - I've tested this change pretty extensively, and stepped through both the storage and sync engine, and have observed nothing problematic about adding this here. Also, in the next revision I'll be splitting the types between internal and customer facing notifications (see Manuel's comment below), which should provide some type safety around the notifications.

2022-03-25 22:41 UTC, david-mcafee commented on packages/datastore/src/types.ts
> +	savedElement?: T;
Discussed offline, will be using `Pick` instead of `Omit`

2022-03-28 17:56 UTC, cshfang approved these changes
This lgtm. Thanks for working on this

2022-03-28 17:56 UTC, cshfang commented on packages/datastore/__tests__/DataStore.ts
> +			unsubscribeConnectivity: () => {},
Nit: Doesn't seem like this is the case but if tests ever did need to update the mocks for these implementations, it seems more idiomatic to use `jest.fn()`.

2022-03-28 18:12 UTC, manueliglesias approved these changes
LGTM!! 👍

2022-03-28 20:14 UTC, iartemiev approved these changes
LGTM 👍🏻

2022-03-28 22:57 UTC, david-mcafee commented
Confirmed with @svidgen offline that it's alright to merge this.

2022-03-29 01:04 UTC, merged