feat(in-app-messaging): Add modal UI component
aws-amplify/amplify-js pull request #9712
Opened 2022-03-17 01:11 UTC by Samaritan1011001

#### Description of changes

Adds the modal support to in-app-messaging. Similar to a Full Screen message with a slightly different layout. 
A function in `utils.ts` is modified to fit the needed design for modal. 
Tests have been modified and added to validated the changes.

#### Issue #, if available

#### Description of how you validated changes
Different test cases as mentioned below were manually validated in addition to the unit tests for Modal. 
- Only text of normal length
- Text (Header and Body) with max length
- Modal message with image
- Image + text
- Text + buttons
- Only a single button with action to open a url link
- Image + text + 2 buttons
- Image + long text + 2 buttons

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-17 17:09 UTC, calebpollman commented
@Samaritan1011001 Thanks for opening this! Can you please add screenshots similar to the [In-App Messaging `FullScreenMessage` PR](https://github.com/aws-amplify/amplify-js/pull/9130)?

2022-03-17 18:55 UTC, calebpollman reviewed
@Samaritan1011001 Looks like a great start! Left some minor feedback

2022-03-17 22:41 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			flex: 0.7,
Not needed, updated the styling in the latest push.

2022-03-17 23:08 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/__tests__/utils.spec.ts
> +			layout: 'CAROUSEL',
This test is for non-banner components in which the returned `componentWrapper` from `getContainerAndWrapperStyle` is an `array` whereas for banner components is a [single element](https://github.com/aws-amplify/amplify-js/blob/in-app-messaging/staging/packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts#L85). 

Since modal is added to the components that require [banner like styling](https://github.com/Samaritan1011001/amplify-js-1/blob/in-app-messaging/modalUI/packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts#L83) this test will fail with the `MODAL` layout and so changed it to a non-banner, non-modal component. Either `FULL_SCREEN` or `CAROUSEL` should work.

Line 318 was a mistake and I changed it back to `MODAL`

2022-03-17 23:29 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> +	if (layout === 'TOP_BANNER' || layout === 'MIDDLE_BANNER' || layout === 'BOTTOM_BANNER' || layout === 'MODAL') {
Yeah, makes sense. extracted it. Let me know if that's what we had in mind.

2022-03-21 19:13 UTC, calebpollman requested changes
Left mostly styling related comments. Thanks for addressing the feedback!

2022-03-21 19:13 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			marginVertical: SPACING_LARGE,
Wonder if we should remove this property so the top of the close button and the top of the image line up. Also, why do we need a `flex` property here?

2022-03-21 19:13 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			alignSelf: 'flex-end',
Why do we need this property?

2022-03-22 20:22 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			marginVertical: SPACING_LARGE,
Yeah, removed `marginVertical` 
Flex is needed to center the image while keeping the x mark at the end of the row.

2022-03-22 20:25 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			alignSelf: 'flex-end',
Not needed. Added when trying to get the image and x mark aligned. Thanks for catching it.

2022-03-22 20:26 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			paddingLeft: SPACING_MEDIUM,
Not really necessary. This came from the full message styling so I kept it. Removed it now.

2022-03-23 15:33 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/styles.ts
> +			alignSelf: 'flex-end',
Can we remove it? 🙂

2022-03-23 15:36 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/ModalMessage.tsx
> +				<View style={[styles.contentContainer]}>
Do we need `styles.contentContainer` to be wrapped in an array?

2022-03-24 21:17 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/ModalMessage.tsx
> +				<View style={[styles.contentContainer]}>
Not needed again. Came in when experimenting with portrait landscape. Removed it

2022-03-28 16:37 UTC, calebpollman requested changes

2022-03-28 16:37 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/__tests__/__snapshots__/BannerMessage.spec.tsx.snap
> +<<<<<<< HEAD
Can you please fix the merge conflicts in this file and push up a revision?

2022-03-30 02:00 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/__tests__/__snapshots__/BannerMessage.spec.tsx.snap
> +<<<<<<< HEAD
@calebpollman I think I removed those in the recent commits.

2022-05-03 00:09 UTC, Samaritan1011001 commented
Hey @calebpollman, made the changes we discussed and the image is centered within the red box as shown below for reference. Let me know if that's what we had in mind.

<img width="300" alt="Screen Shot 2022-03-31 at 2 09 04 PM" src="https://user-images.githubusercontent.com/10944487/166345127-8be50016-7847-45dc-87a7-093b07ac4e0a.png">

2022-05-06 17:52 UTC, calebpollman approved these changes
Thanks for working through all the styling issues @Samaritan1011001 🚢

2022-05-09 21:54 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/__tests__/Modal.spec.tsx
> +/*
Test name should match the module/component being tested. I think this should be `ModalMessage.spec.tsx`

2022-05-09 21:54 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/__tests__/Modal.spec.tsx
> +}));
Nit: I *think* you should be able to just let it jest automock this
```suggestion
jest.mock('../../hooks/useMessageImage');
```

2022-05-09 22:12 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {props} - layout props
right, it's just string 👍

2022-05-09 22:33 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {props} - layout props
Can we update the jsdoc param to `layout` and update the expected type on line 81 to `InAppMessageLayout`?

2022-05-09 22:46 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/__tests__/utils.spec.ts
> +		expect(isBannerOrModalLayout('MODAL')).toEqual(true);
Nit: Still would suggest adding an expect for banner to be true given we are testing a function named `isBannerOrModalLayout`

2022-05-09 22:46 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {string} - layout style
I think @calebpollman was saying we should use the layout type instead of just an arbitrary string

2022-05-09 23:14 UTC, Samaritan1011001 commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {string} - layout style
Yeah, there is `InAppMessageLayout` so made changes to use that instead. Thanks for pointing this out!

2022-05-09 23:17 UTC, calebpollman commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {InAppMessageLayout} - layout style
Nit:
```suggestion
 @param {layout} - message layout value
```

2022-05-09 23:38 UTC, cshfang approved these changes
Lgtm thanks!

2022-05-09 23:38 UTC, cshfang commented on packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
> + * @param {layout} - message layout value
Nit: I think the type here should be `InAppMessageLayout` too right?

2022-05-10 00:17 UTC, merged