fix: PubSub - Resolve ts strict errors in the AWSAppSyncRealTimeProvider
aws-amplify/amplify-js pull request #9731
Opened 2022-03-24 23:18 UTC by stocaaro

#### Description of changes
Using a [`tsconfig.json` set to strict](https://github.com/stocaaro/ts-starter/blob/main/tsconfig.json) as a guide, resolve all errors found in `pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts`.

Change includes a deprecation annotation for a constant that should have been included in the prior change.

#### Description of how you validated changes
`yarn test` is passing without issues

Manual testing exercising features in:
- React app with IoT integration
- React app with DataStore syncing over AppSync

#### Checklist
- [x] PR description included
- [x] `yarn test` passes
- [x] Tests apps manually test

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-25 23:58 UTC, jamesaucode reviewed
Looks good overall, just have a few questions 😄

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	startAckTimeoutId?: NodeJS.Timer;
It feels wrong to have a nodejs type here for a (mostly) client-side library, I would probably use `ReturnType<typeof setTimeout>` instead and let Typescript infer it.

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	private keepAliveTimeoutId?: NodeJS.Timer;
Same as above

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			startAckTimeoutId: undefined,
is there a reason why this changes from `null` to `undefined` ?

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			if (err instanceof Error) {
Looks like we are doing this to satisfy the `strict` ts config but are we certain that `err` is always going to be an instance of Error? Im worried there might be cases where the error is not an instance of error and its going to be ignored.

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +		const headerHandler: { [key: string]: any } = {
Nit: This look similar to the union from the last PR so we can probably use that too. So something like `{ [key in GraphQLAuthTypes]: any }` (not sure if thats the exact name)

2022-03-25 23:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +				Credentials.shear(credentials);
is the extra `Credentials.shear` call needed here?

2022-03-28 22:47 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			startAckTimeoutId: undefined,
In the `ObserveQuery` type definition that this fits into, the `startAckTimeoutId` value is optional, which typescript permits to be undefined and `null` is an incompatible type. Opted to keep the shape and make the usage conform, however I could have resolved this by allowing null in the type, like the following:
```
startAckTimeoutId: ReturnType<typeof setTimeout> | null;
```
instead of
```
startAckTimeoutId?: ReturnType<typeof setTimeout>;
```
I don't have strong opinions, do you have a preference?

2022-03-28 22:47 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	startAckTimeoutId?: NodeJS.Timer;
Good call. Doing it.

2022-03-28 22:52 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			if (err instanceof Error) {
Good call. I've gone through a couple iterations in thinking about this.
```
const message = (err as Error)?.message ?? '';
```
would accomplish the same thing as the current code, but again, if semantically we're worried about it not being an Error at times, treating like an error and being paranoid that Error might not have the required message field is odd.
```
const message = (err as {message?: string})?.message ?? '';
```
This is probably closer to reality given the concern.  Thoughts / suggestions?

2022-03-29 00:07 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +				Credentials.shear(credentials);
At the time, it felt better than embedding an `as` clarification with these fields to make ts happy. Something about letting the core library carry the ambiguity as opposed to embedding an auth specific hack here.

I'll update it with the `as` version and see how the feedback goes.

2022-03-29 00:07 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +		const headerHandler: { [key: string]: any } = {
Good call. Have tweaked it to make this work.

2022-03-29 22:28 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			startAckTimeoutId: undefined,
I see, I think there's a minor difference between the 2. One means the key is not optional, but the value could potentially be null, the other one means the key is optional but if it exist the value has to be `ReturnType<typeof setTimeout>`.
It looks like this is just an optional key so I think using `undefined` here is correct.

2022-03-29 22:28 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			const message = (err as { message?: string })?.message ?? '';
I think this works fine, but it might be a bit harder to read with everything in line. Another idea I have is to define a type guard, something like this
```ts
// it seems like all we care is if the thrown object has a message key
function isError(error: unknown): error is { message: string } {
    return (error as { message?: string}).message !== undefined;
}
// or you can just check if its an instanceof Error
function isError(error: unknown): error is Error {
  return error instanceof Error;
}
```
Then we can do something like
```ts
const message = isError(err) ? err.message : '';
```

What do you think?

2022-04-05 16:53 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			const message = (err as { message?: string })?.message ?? '';
It's possible, but not likely that `instanceof` would cause a functionality change where an object with `message` would have worked before, but now because it doesn't match up completely with the shape of Error it no longer works.

I agree that my use of `as` is ugly and it occurs to me that a better translation of the replaced line is just using `[]` access. With TS Strict, using deconstructing assignments is unhappy unless ts knows the shape of the object being deconstructed, where it is happy as a clam accessing members directly (though those members come through as `any`, which shouldn't be a problem with primitives like `message`.

I like the clarity that comes from wrapping this behavior in a private method, but without a refactor to decompose the realtime provider into clearer chunks I think isolating smaller bits of code for clarity makes this file harder to navigate and reason around.

2022-04-06 03:43 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			const message = (err as { message?: string })?.message ?? '';
Yea make sense, I personally prefer using typeguard but I don't have a strong opinion here, I think using `[]` looks clean enough in this case. :+1:

2022-04-06 04:23 UTC, jamesaucode reviewed
One more comment otherwise LGTM :smiley:

2022-04-06 05:42 UTC, elorzafe requested changes
Thanks @stocaaro 

I just have one minor issue to fix on that `err['message']`

2022-04-06 05:42 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +				}).catch<any>(err => {
Why is this needed?

2022-04-06 05:42 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			const message = err['message']?.message ?? '';
isnt `err.message.message` that statement?

2022-04-06 05:42 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +	private async _waitForSubscriptionToBeConnected(subscriptionId: string) {
Maybe this could be refactor to receive `subscriptionObserver` instead of `subscriptionId`

2022-04-06 05:42 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			tempSocket.onclose = null;
Is this a TS thing?

2022-04-06 05:42 UTC, elorzafe commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			};
I think we have a CredentialsInterface on Core package

2022-04-06 15:51 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +			const message = (err as { message?: string })?.message ?? '';
I think I generally agree, but a typeguard makes me nervous in this case as I could imagine an object with a message that doesn't fully match the error type interface making a mess of that. Maybe I'm being over-paranoid or misunderstanding something about how that fits together. Probably a thing I should play around with some more.

2022-04-06 17:38 UTC, stocaaro commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +		if (!authenticationType || !headerHandler[authenticationType]) {
Going back and forth on this one. On one hand not providing an authenticationType is different than providing an auth type that doesn't map to one of our auth functions. Typing the input would make providing an incorrect auth function name, its optional, so it could be undefined and in the current implementation, I believe this is the only corner case you can get to in TS without overriding a string to tell ts that its one of the valid inputs.

Right now, we would log either:
```
Authentication type undefined not supported
```
or
```
Authentication type invalid_option not supported
```
Which seems clear enough to me. As a user with missing or incorrect auth type information, what logged output would you prefer to see to guide you to fixing your problem?

While working through this, I was bothered that the function type on our function map had `any` for the values, so I have narrowed that to specify what we know about them.

2022-04-06 19:39 UTC, elorzafe approved these changes
LGTM! Thanks @stocaaro 🌮

2022-04-06 22:58 UTC, jamesaucode commented on packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
> +		if (!authenticationType || !headerHandler[authenticationType]) {
Now that I look at it again I think `Authentication type undefined not supported` is clear enough to me. Another option which will make the code a bit more verbose will be to have a separate `if` to handle the case where `authenticationType` is undefined, logging something like `authenticationType must be defined`.

2022-04-06 22:58 UTC, jamesaucode commented
Dont think the `authenticationType` thing is blocking, LGTM 🎉 !

2022-04-06 22:58 UTC, jamesaucode approved these changes

2022-04-06 23:00 UTC, merged