New err handler
aws-amplify/amplify-js pull request #9775
Opened 2022-04-06 15:54 UTC by ArkamJ

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-08 20:18 UTC, dpilch requested changes

2022-04-08 20:18 UTC, dpilch commented on packages/datastore/src/types.ts
> +		errorHandler?: (error: SyncError<any>) => void; // default : logger.warn
Is it possible to use `PersistentModel` here to avoid the use of `any`.

2022-04-08 20:18 UTC, dpilch commented on packages/datastore/src/types.ts
> +	| 'save()'
nit: consistent use of parentheses after process name. Either remove or add to all.

2022-04-08 20:18 UTC, dpilch commented on packages/datastore/src/sync/utils.ts
> +	switch (operation) {
Could simplify this with `toLowerCase`.

2022-04-08 20:18 UTC, dpilch commented on packages/datastore/src/sync/processors/sync.ts
> +								for (const err of error.errors) {
Consider changing this to `Promise.all` or `Promise.allSettled` to allow the async to run in parallel rather than in sequence.

```js
await Promise.all(error.error.map(async (err) => { ...

```

2022-05-12 14:56 UTC, svidgen commented
This was used as the basis for another PR, which has been merged.

2022-05-12 14:56 UTC, closed without merging