feat: rework error handler
aws-amplify/amplify-js pull request #9861
Opened 2022-05-02 19:53 UTC by dpilch

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-02 20:20 UTC, svidgen requested changes

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +								} as ErrorMap;
In my local, I had started moving these maps out of the loops and up to the top of the file with the intent on making these blocks shorter, quicker reads down the road. Thoughts?

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +											await this.errorHandler({
```suggestion
											await this.errorHandler({
												recoverySuggestion: "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues",
```

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/mutation.ts
>  									await this.errorHandler({
```suggestion
											await this.errorHandler({
												recoverySuggestion: "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues",
```

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +															await this.errorHandler({
```suggestion
											await this.errorHandler({
												recoverySuggestion: "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues",
```

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +														} as ErrorMap;
For each file, might be easier to read down the line to move these error maps out of the block into the top of the file(s) and/or a utils.

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +														try {
This is partly what was I deliberating on earlier. I think we need to move this out near the top of the `error` callback. Let's log everything we can that comes back from appsync to start with here. We can cut back if we find we're being too verbose.

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/processors/sync.ts
> +								} as ErrorMap;
Ditto. Probably move up/out.

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/sync/utils.ts
> +export function mapErrorToType(errorMap: ErrorMap, error: Error): ErrorType {
```suggestion
/**
 * Categorizes an error with a broad error type, intended to make
 * customer error handling code simpler.
 * @param errorMap Error names and a list of patterns that indicate them (each pattern as a regex or function)
 * @param error The underying error to categorize.
 */
export function mapErrorToType(errorMap: ErrorMap, error: Error): ErrorType {
```

2022-05-02 20:20 UTC, svidgen commented on packages/datastore/src/types.ts
> +	errorInfo?: string;
```suggestion
	errorInfo?: string;
	recoverySuggestion?: string;
```

2022-05-02 21:09 UTC, svidgen requested changes

2022-05-02 21:09 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +													});
Doh!

```
@aws-amplify/datastore: ERROR: src/sync/processors/subscription.ts:467:15 - Expected property shorthand in object literal ('{message}').
@aws-amplify/datastore: ERROR: src/sync/processors/subscription.ts:469:15 - Expected property shorthand in object literal ('{operation}').
```

```suggestion
													await this.errorHandler({
														recoverySuggestion:
															'Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues',
														localModel: null,
														message,
														model: modelDefinition.name,
														operation,
														errorType: mapErrorToType(
															errorMap,
															subscriptionError
														),
														process: ProcessName.subscribe,
														remoteModel: null,
														cause: subscriptionError,
													});
```

2022-05-02 22:47 UTC, svidgen approved these changes
Looking at all 3 error type maps together, I think we still have more error classification work to do. But, I think this is sufficient to improve visibility into errors that are currently just *silent*.

2022-05-02 22:47 UTC, svidgen commented on packages/datastore/src/sync/processors/mutation.ts
> +
As-is, I think this PR gives Studio will have better errors to collect. But, we should make sure we have a TODO to expand this mapping and the similar mapping on the other sync engine processes. I think the missing auth directive errors should surface here too, for example.

Looking at this regex, I probably should have provided a sample in a comment of what this is supposed to match. I can circle back on that tomorrow if desired.

2022-05-03 00:26 UTC, nickarocho approved these changes
LGTM 🤙🏼 just left a clarifying question

2022-05-03 00:26 UTC, nickarocho commented on packages/datastore/src/sync/processors/subscription.ts
> +													await this.errorHandler({
If the `errorHandler` is optional in the constructor, is it possible a call to `this.errorHandler` could result in an exception?

2022-05-03 14:05 UTC, svidgen commented on packages/datastore/src/sync/processors/subscription.ts
> +													await this.errorHandler({
Yep. And, it is intended to be supplied by the user, so every time `errorHandler` is called, it should be done in a try-catch.

2022-05-03 14:20 UTC, dpilch commented on packages/datastore/src/sync/processors/subscription.ts
> +													await this.errorHandler({
I'm thinking we change `errorHandler` to required since it is always passed via SyncEngine.

2022-05-03 16:12 UTC, iartemiev approved these changes
LGTM 👍🏻

2022-05-03 16:13 UTC, merged