fix(@aws-amplify/datastore): adds missing fields to items sent through observe/observeQuery
aws-amplify/amplify-js pull request #9973
Opened 2022-06-08 19:45 UTC by svidgen

#### Description of changes

`observe` and `observeQuery` were returning results that didn't contain all necessary fields and did not load related records the same way `query` does.

TODO:
- [ ] Confirm that `observe` should *also* be updated along with `observeQuery` as this PR does
- [x] test with belongsTo
- [ ] test with hasOne

#### Issue #, if available

#9682

#### Description of how you validated changes

Added failing tests. Made the tests pass.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-08 22:15 UTC, undefobj commented on packages/datastore/src/datastore/datastore.ts
> +					// We need to explicitly remove those items from the existing snapshot.
The details in these comments behind the reasoning why we need such changes is excellent. Keep it up!

2022-06-10 04:06 UTC, david-mcafee approved these changes
Left a few questions. Thanks!

2022-06-10 04:06 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +								const freshElement = await this.query(
Can we make sure we're not sending ALL fields to AppSync with this change? For instance, when I implemented the `map` above, I sent `element` and not `savedElement` when the `savedElement` was not present to ensure we weren't sending all fields (including those that have not been updated) to AppSync.

2022-06-10 20:33 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> +								const freshElement = await this.query(
OK. I've added a test for this [in `commonAdapterTest.ts`](https://github.com/aws-amplify/amplify-js/pull/9973/files#diff-de9d5dae30ad1e8fd1b9539e2f4cfdd40c71894df2fbb38c779a409f3d8a4908R346-R369). It was a minor PITA to sort out how to construct a test for this. But, now that I have a reasonable pattern for the test, if there are other specific scenarios you have in mind to cover, we should definitely get them covered. I didn't see any other tests that would give me the confidence to address this questions otherwise.

2022-06-10 20:43 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> -					.map(
Not *all* changes; your other PR ported over the initial set of missing observe/observeQuery. That's highly valuable!

2022-06-10 22:31 UTC, david-mcafee requested changes

2022-06-10 22:31 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> -					.map(
I just tested this with [a sample app](https://github.com/david-mcafee/ds-observe-testing) (now realizing it may be worth adding an E2E test for this), and your changes result in the first snapshot missing all of the fields (something that the PR I referenced above fixed). Example output of the first snapshot:

```
{
    "items": [
      {
        "name": "name",
        "id": "94dded73-b955-417d-8704-f961b1b5a336"
      }
    ],
    "isSynced": true
  },
```

Expected output for the first snapshot:

```
{
    "items": [
      {
        "id": "94dded73-b955-417d-8704-f961b1b5a336",
        "name": "name",
        "description": null,
        "createdAt": "2022-06-10T22:28:00.671Z",
        "updatedAt": "2022-06-10T22:28:00.671Z",
        "_version": 1,
        "_lastChangedAt": 1654900080693,
        "_deleted": null
      }
    ],
    "isSynced": true
  },
```

2022-06-10 22:34 UTC, svidgen commented on packages/datastore/src/datastore/datastore.ts
> -					.map(
Thanks for testing this!

2022-06-10 22:35 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> -					.map(
I just tested your changes, and it looks like on update, the first snapshot still preserves all fields.

2022-06-10 22:38 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +								const freshElement = await this.query(
I tested your changes locally, and it appears that the outgoing request is only sending updated fields 👍🏻

2022-06-10 22:40 UTC, david-mcafee approved these changes
Tested locally and everything looks good! Only one minor nit (a typo)

2022-06-10 22:40 UTC, david-mcafee commented on packages/datastore/src/datastore/datastore.ts
> +							// as lnog as we're not dealing with a DELETE, we need to fetch a fresh
nit: typo

2022-06-13 19:05 UTC, manueliglesias approved these changes
LGTM as we will work on a subsequent PR on making the tests not rely on timeouts and pauses/

2022-06-13 21:00 UTC, merged